// Settings -> "Also run when Prune is closed" (Task Scheduler), the Dashboard's last-automatic-clean
// line and "Start Prune when I sign in to Windows", all 40 languages:
// { en: { backgroundV3: { ... } }, af: { ... }, ... }. Merged into the catalog by ../catalog.js; every
// key lives under backgroundV3. Generated by an out-of-tree script that writes every value with
// JSON.stringify (or as a template literal for the few that take values), so quotes and non-ASCII
// text are safe. Words for Quarantine, Startup, tray and freed/moved follow each language's existing
// catalog terms. No string here counts anything, so none needs a plural form.
export default {
  en: {
    backgroundV3: {
      task: {
        title: "Also run when Prune is closed",
        description: "Adds a task to Windows Task Scheduler, for your account only, so this schedule runs even when Prune isn't open. It needs no administrator rights and stores no password.",
        detail: "The task runs Prune's command line (prune-cli clean --preset recommended): only the rules Prune ticks by default, never the ones that lose data, and always with your exclusions, protected paths and Quarantine setting. Turning this off, or uninstalling Prune, deletes the task.",
        nextRun: (a) => `Next automatic run: ${a}`,
        needsClean: "Set what the schedule does to cleaning first. The task only cleans.",
        unsupported: "Available in the installed Prune app on Windows. This copy can't set it.",
        cliMissing: "prune-cli.cmd is missing from Prune's folder, so the task can't be set up. Reinstall Prune to restore it.",
        outOfSync: "The task in Windows doesn't match the schedule above yet. Turn this off and on again to update it.",
        taskFailed: (a) => `Windows reported error ${a} the last time the task started.`,
        saveFailed: (a) => `Couldn't change this setting: ${a}`,
        loadFailed: (a) => `Couldn't read the task's state: ${a}`
      },
      last: {
        clean: (a, b, c) => `Last automatic clean: ${a} — moved ${b}, freed ${c}`,
        errors: (a, b, c) => `Last automatic clean: ${a} — some rules failed; moved ${b}, freed ${c}`
      }
    }
  },
  af: {
    backgroundV3: {
      task: {
        title: "Voer ook uit wanneer Prune toe is",
        description: "Voeg ’n taak by Windows Taakskeduleerder, net vir jou rekening, sodat hierdie skedule loop selfs wanneer Prune nie oop is nie. Dit het geen administrateurregte nodig nie en stoor geen wagwoord nie.",
        detail: "Die taak voer Prune se opdragreël uit (prune-cli clean --preset recommended): net die reëls wat Prune by verstek aanmerk, nooit dié wat data verloor nie, en altyd met jou uitsluitings, beskermde paaie en Karantyn-instelling. As jy dit afskakel, of Prune deïnstalleer, word die taak uitgevee.",
        nextRun: (a) => `Volgende outomatiese loop: ${a}`,
        needsClean: "Stel eers die skedule om skoon te maak. Die taak maak net skoon.",
        unsupported: "Beskikbaar in die geïnstalleerde Prune-toepassing op Windows. Hierdie kopie kan dit nie stel nie.",
        cliMissing: "prune-cli.cmd ontbreek in Prune se gids, so die taak kan nie opgestel word nie. Herinstalleer Prune om dit te herstel.",
        outOfSync: "Die taak in Windows stem nog nie met die skedule hierbo ooreen nie. Skakel dit af en weer aan om dit by te werk.",
        taskFailed: (a) => `Windows het fout ${a} gerapporteer toe die taak laas begin het.`,
        saveFailed: (a) => `Kon nie hierdie instelling verander nie: ${a}`,
        loadFailed: (a) => `Kon nie die taak se toestand lees nie: ${a}`
      },
      last: {
        clean: (a, b, c) => `Laaste outomatiese skoonmaak: ${a} — ${b} geskuif, ${c} vrygemaak`,
        errors: (a, b, c) => `Laaste outomatiese skoonmaak: ${a} — sommige reëls het misluk; ${b} geskuif, ${c} vrygemaak`
      }
    }
  },
  ar: {
    backgroundV3: {
      task: {
        title: "التشغيل أيضًا عند إغلاق Prune",
        description: "يضيف مهمة إلى مجدول المهام في Windows لحسابك فقط، ليعمل هذا الجدول حتى عندما لا يكون Prune مفتوحًا. لا يحتاج إلى صلاحيات المسؤول ولا يخزّن أي كلمة مرور.",
        detail: "تشغّل المهمة سطر أوامر Prune (prune-cli clean --preset recommended): القواعد التي يحددها Prune افتراضيًا فقط، ولا تشمل أبدًا ما يفقد البيانات، وبمراعاة الاستثناءات والمسارات المحمية وإعداد الحجر الصحي دائمًا. إيقاف هذا الخيار أو إزالة Prune يحذف المهمة.",
        nextRun: (a) => `التشغيل التلقائي التالي: ${a}`,
        needsClean: "اضبط أولًا ما يفعله الجدول على التنظيف. المهمة تنظّف فقط.",
        unsupported: "متاح في تطبيق Prune المثبّت على Windows. لا يمكن ضبطه من هذه النسخة.",
        cliMissing: "الملف prune-cli.cmd مفقود من مجلد Prune، لذا لا يمكن إعداد المهمة. أعد تثبيت Prune لاستعادته.",
        outOfSync: "المهمة في Windows لا تطابق الجدول أعلاه بعد. أوقف هذا الخيار ثم شغّله لتحديثها.",
        taskFailed: (a) => `أبلغ Windows عن الخطأ ${a} عند آخر بدء للمهمة.`,
        saveFailed: (a) => `تعذّر تغيير هذا الإعداد: ${a}`,
        loadFailed: (a) => `تعذّرت قراءة حالة المهمة: ${a}`
      },
      last: {
        clean: (a, b, c) => `آخر تنظيف تلقائي: ${a} — تم نقل ${b}، وتحرير ${c}`,
        errors: (a, b, c) => `آخر تنظيف تلقائي: ${a} — فشلت بعض القواعد؛ تم نقل ${b}، وتحرير ${c}`
      }
    }
  },
  ca: {
    backgroundV3: {
      task: {
        title: "Executa també quan Prune és tancat",
        description: "Afegeix una tasca al Programador de tasques de Windows, només per al teu compte, perquè aquesta programació s'executi encara que Prune no sigui obert. No necessita drets d'administrador i no desa cap contrasenya.",
        detail: "La tasca executa la línia d'ordres de Prune (prune-cli clean --preset recommended): només les regles que Prune marca per defecte, mai les que fan perdre dades, i sempre amb les teves exclusions, camins protegits i la configuració de la Quarantena. Si ho desactives, o desinstal·les Prune, s'elimina la tasca.",
        nextRun: (a) => `Propera execució automàtica: ${a}`,
        needsClean: "Primer configura la programació perquè netegi. La tasca només neteja.",
        unsupported: "Disponible a l'aplicació Prune instal·lada a Windows. Aquesta còpia no ho pot configurar.",
        cliMissing: "Falta prune-cli.cmd a la carpeta de Prune, així que no es pot crear la tasca. Reinstal·la Prune per restaurar-lo.",
        outOfSync: "La tasca de Windows encara no coincideix amb la programació de dalt. Desactiva i torna a activar això per actualitzar-la.",
        taskFailed: (a) => `Windows va informar de l'error ${a} l'última vegada que va començar la tasca.`,
        saveFailed: (a) => `No s'ha pogut canviar aquesta opció: ${a}`,
        loadFailed: (a) => `No s'ha pogut llegir l'estat de la tasca: ${a}`
      },
      last: {
        clean: (a, b, c) => `Última neteja automàtica: ${a} — ${b} moguts, ${c} alliberats`,
        errors: (a, b, c) => `Última neteja automàtica: ${a} — algunes regles han fallat; ${b} moguts, ${c} alliberats`
      }
    }
  },
  cs: {
    backgroundV3: {
      task: {
        title: "Spouštět také při zavřeném Prune",
        description: "Přidá úlohu do Plánovače úloh Windows, jen pro váš účet, aby se tento plán spouštěl i když Prune není otevřený. Nepotřebuje práva správce a neukládá žádné heslo.",
        detail: "Úloha spouští příkazový řádek Prune (prune-cli clean --preset recommended): jen pravidla, která Prune ve výchozím stavu zaškrtává, nikdy ta, která ztrácejí data, a vždy s vašimi výjimkami, chráněnými cestami a nastavením karantény. Vypnutím této volby nebo odinstalováním Prune se úloha odstraní.",
        nextRun: (a) => `Příští automatické spuštění: ${a}`,
        needsClean: "Nejdřív nastavte, aby plán čistil. Úloha jen čistí.",
        unsupported: "K dispozici v nainstalované aplikaci Prune ve Windows. Tato kopie to nastavit nemůže.",
        cliMissing: "Ve složce Prune chybí prune-cli.cmd, takže úlohu nelze vytvořit. Obnovíte ji přeinstalováním Prune.",
        outOfSync: "Úloha ve Windows zatím neodpovídá plánu výše. Vypněte a znovu zapněte tuto volbu, aby se aktualizovala.",
        taskFailed: (a) => `Windows při posledním spuštění úlohy nahlásil chybu ${a}.`,
        saveFailed: (a) => `Toto nastavení se nepodařilo změnit: ${a}`,
        loadFailed: (a) => `Stav úlohy se nepodařilo přečíst: ${a}`
      },
      last: {
        clean: (a, b, c) => `Poslední automatické čištění: ${a} — přesunuto ${b}, uvolněno ${c}`,
        errors: (a, b, c) => `Poslední automatické čištění: ${a} — některá pravidla selhala; přesunuto ${b}, uvolněno ${c}`
      }
    }
  },
  cy: {
    backgroundV3: {
      task: {
        title: "Rhedeg hefyd pan fo Prune ar gau",
        description: "Yn ychwanegu tasg at Drefnydd Tasgau Windows, ar gyfer eich cyfrif chi yn unig, fel bod yr amserlen hon yn rhedeg hyd yn oed pan nad yw Prune ar agor. Nid oes angen hawliau gweinyddwr arni ac nid yw'n storio cyfrinair.",
        detail: "Mae'r dasg yn rhedeg llinell orchymyn Prune (prune-cli clean --preset recommended): dim ond y rheolau y mae Prune yn eu ticio yn ddiofyn, byth y rhai sy'n colli data, a bob amser gyda'ch eithriadau, llwybrau gwarchodedig a'ch gosodiad Cwarantin. Mae ei ddiffodd, neu ddadosod Prune, yn dileu'r dasg.",
        nextRun: (a) => `Rhediad awtomatig nesaf: ${a}`,
        needsClean: "Gosodwch yr amserlen i lanhau yn gyntaf. Dim ond glanhau mae'r dasg.",
        unsupported: "Ar gael yn yr ap Prune sydd wedi'i osod ar Windows. Ni all y copi hwn ei osod.",
        cliMissing: "Mae prune-cli.cmd ar goll o ffolder Prune, felly ni ellir sefydlu'r dasg. Ailosodwch Prune i'w adfer.",
        outOfSync: "Nid yw'r dasg yn Windows yn cyfateb i'r amserlen uchod eto. Diffoddwch a throwch hwn ymlaen eto i'w diweddaru.",
        taskFailed: (a) => `Adroddodd Windows wall ${a} y tro diwethaf i’r dasg ddechrau.`,
        saveFailed: (a) => `Methwyd newid y gosodiad hwn: ${a}`,
        loadFailed: (a) => `Methwyd darllen cyflwr y dasg: ${a}`
      },
      last: {
        clean: (a, b, c) => `Glanhau awtomatig diwethaf: ${a} — symudwyd ${b}, rhyddhawyd ${c}`,
        errors: (a, b, c) => `Glanhau awtomatig diwethaf: ${a} — methodd rhai rheolau; symudwyd ${b}, rhyddhawyd ${c}`
      }
    }
  },
  da: {
    backgroundV3: {
      task: {
        title: "Kør også når Prune er lukket",
        description: "Tilføjer en opgave i Windows Opgavestyring, kun for din konto, så denne tidsplan kører, selv når Prune ikke er åben. Den kræver ingen administratorrettigheder og gemmer ingen adgangskode.",
        detail: "Opgaven kører Prunes kommandolinje (prune-cli clean --preset recommended): kun de regler, Prune markerer som standard, aldrig dem, der mister data, og altid med dine undtagelser, beskyttede stier og din karantæneindstilling. Slår du dette fra, eller afinstallerer Prune, slettes opgaven.",
        nextRun: (a) => `Næste automatiske kørsel: ${a}`,
        needsClean: "Indstil først tidsplanen til at rense. Opgaven renser kun.",
        unsupported: "Tilgængelig i den installerede Prune-app på Windows. Denne kopi kan ikke indstille det.",
        cliMissing: "prune-cli.cmd mangler i Prunes mappe, så opgaven kan ikke oprettes. Geninstaller Prune for at gendanne den.",
        outOfSync: "Opgaven i Windows svarer endnu ikke til tidsplanen ovenfor. Slå dette fra og til igen for at opdatere den.",
        taskFailed: (a) => `Windows rapporterede fejl ${a}, da opgaven sidst startede.`,
        saveFailed: (a) => `Kunne ikke ændre denne indstilling: ${a}`,
        loadFailed: (a) => `Kunne ikke læse opgavens tilstand: ${a}`
      },
      last: {
        clean: (a, b, c) => `Seneste automatiske rensning: ${a} — flyttede ${b}, frigjorde ${c}`,
        errors: (a, b, c) => `Seneste automatiske rensning: ${a} — nogle regler mislykkedes; flyttede ${b}, frigjorde ${c}`
      }
    }
  },
  de: {
    backgroundV3: {
      task: {
        title: "Auch ausführen, wenn Prune geschlossen ist",
        description: "Fügt der Windows-Aufgabenplanung eine Aufgabe hinzu, nur für dein Konto, damit dieser Zeitplan auch läuft, wenn Prune nicht geöffnet ist. Sie braucht keine Administratorrechte und speichert kein Kennwort.",
        detail: "Die Aufgabe führt die Befehlszeile von Prune aus (prune-cli clean --preset recommended): nur die Regeln, die Prune standardmäßig ankreuzt, nie die, die Daten verlieren, und immer mit deinen Ausnahmen, geschützten Pfaden und der Quarantäne-Einstellung. Schaltest du das aus oder deinstallierst Prune, wird die Aufgabe gelöscht.",
        nextRun: (a) => `Nächster automatischer Lauf: ${a}`,
        needsClean: "Stelle zuerst ein, dass der Zeitplan bereinigt. Die Aufgabe bereinigt nur.",
        unsupported: "Verfügbar in der installierten Prune-App unter Windows. Diese Kopie kann es nicht einrichten.",
        cliMissing: "prune-cli.cmd fehlt im Prune-Ordner, daher lässt sich die Aufgabe nicht einrichten. Installiere Prune neu, um sie wiederherzustellen.",
        outOfSync: "Die Aufgabe in Windows entspricht noch nicht dem Zeitplan oben. Schalte dies aus und wieder ein, um sie zu aktualisieren.",
        taskFailed: (a) => `Windows meldete beim letzten Start der Aufgabe den Fehler ${a}.`,
        saveFailed: (a) => `Diese Einstellung konnte nicht geändert werden: ${a}`,
        loadFailed: (a) => `Der Zustand der Aufgabe konnte nicht gelesen werden: ${a}`
      },
      last: {
        clean: (a, b, c) => `Letzte automatische Bereinigung: ${a} — ${b} verschoben, ${c} freigegeben`,
        errors: (a, b, c) => `Letzte automatische Bereinigung: ${a} — einige Regeln sind fehlgeschlagen; ${b} verschoben, ${c} freigegeben`
      }
    }
  },
  el: {
    backgroundV3: {
      task: {
        title: "Εκτέλεση και όταν το Prune είναι κλειστό",
        description: "Προσθέτει μια εργασία στον Χρονοπρογραμματιστή εργασιών των Windows, μόνο για τον λογαριασμό σας, ώστε αυτός ο προγραμματισμός να εκτελείται ακόμη κι όταν το Prune δεν είναι ανοιχτό. Δεν απαιτεί δικαιώματα διαχειριστή και δεν αποθηκεύει κωδικό πρόσβασης.",
        detail: "Η εργασία εκτελεί τη γραμμή εντολών του Prune (prune-cli clean --preset recommended): μόνο τους κανόνες που το Prune επιλέγει από προεπιλογή, ποτέ εκείνους που χάνουν δεδομένα, και πάντα με τις εξαιρέσεις, τις προστατευμένες διαδρομές και τη ρύθμιση Καραντίνας σας. Αν το απενεργοποιήσετε ή απεγκαταστήσετε το Prune, η εργασία διαγράφεται.",
        nextRun: (a) => `Επόμενη αυτόματη εκτέλεση: ${a}`,
        needsClean: "Ορίστε πρώτα ο προγραμματισμός να κάνει καθαρισμό. Η εργασία κάνει μόνο καθαρισμό.",
        unsupported: "Διαθέσιμο στην εγκατεστημένη εφαρμογή Prune στα Windows. Αυτό το αντίγραφο δεν μπορεί να το ρυθμίσει.",
        cliMissing: "Το prune-cli.cmd λείπει από τον φάκελο του Prune, οπότε δεν μπορεί να οριστεί η εργασία. Επανεγκαταστήστε το Prune για να το επαναφέρετε.",
        outOfSync: "Η εργασία στα Windows δεν ταιριάζει ακόμη με τον παραπάνω προγραμματισμό. Απενεργοποιήστε και ενεργοποιήστε ξανά αυτή την επιλογή για να ενημερωθεί.",
        taskFailed: (a) => `Τα Windows ανέφεραν το σφάλμα ${a} την τελευταία φορά που ξεκίνησε η εργασία.`,
        saveFailed: (a) => `Δεν ήταν δυνατή η αλλαγή αυτής της ρύθμισης: ${a}`,
        loadFailed: (a) => `Δεν ήταν δυνατή η ανάγνωση της κατάστασης της εργασίας: ${a}`
      },
      last: {
        clean: (a, b, c) => `Τελευταίος αυτόματος καθαρισμός: ${a} — μετακινήθηκαν ${b}, ελευθερώθηκαν ${c}`,
        errors: (a, b, c) => `Τελευταίος αυτόματος καθαρισμός: ${a} — κάποιοι κανόνες απέτυχαν· μετακινήθηκαν ${b}, ελευθερώθηκαν ${c}`
      }
    }
  },
  es: {
    backgroundV3: {
      task: {
        title: "Ejecutar también cuando Prune está cerrado",
        description: "Añade una tarea al Programador de tareas de Windows, solo para tu cuenta, para que esta programación se ejecute aunque Prune no esté abierto. No necesita derechos de administrador y no guarda ninguna contraseña.",
        detail: "La tarea ejecuta la línea de comandos de Prune (prune-cli clean --preset recommended): solo las reglas que Prune marca por defecto, nunca las que pierden datos, y siempre con tus exclusiones, rutas protegidas y el ajuste de Cuarentena. Si lo desactivas, o desinstalas Prune, la tarea se elimina.",
        nextRun: (a) => `Próxima ejecución automática: ${a}`,
        needsClean: "Primero configura la programación para que limpie. La tarea solo limpia.",
        unsupported: "Disponible en la aplicación Prune instalada en Windows. Esta copia no puede configurarlo.",
        cliMissing: "Falta prune-cli.cmd en la carpeta de Prune, así que no se puede crear la tarea. Reinstala Prune para restaurarlo.",
        outOfSync: "La tarea de Windows aún no coincide con la programación de arriba. Desactiva y vuelve a activar esto para actualizarla.",
        taskFailed: (a) => `Windows informó del error ${a} la última vez que se inició la tarea.`,
        saveFailed: (a) => `No se pudo cambiar este ajuste: ${a}`,
        loadFailed: (a) => `No se pudo leer el estado de la tarea: ${a}`
      },
      last: {
        clean: (a, b, c) => `Última limpieza automática: ${a} — ${b} movidos, ${c} liberados`,
        errors: (a, b, c) => `Última limpieza automática: ${a} — algunas reglas fallaron; ${b} movidos, ${c} liberados`
      }
    }
  },
  et: {
    backgroundV3: {
      task: {
        title: "Käivita ka siis, kui Prune on suletud",
        description: "Lisab Windowsi tööde ajastajasse ülesande ainult sinu kontole, et see ajakava töötaks ka siis, kui Prune pole avatud. See ei vaja administraatoriõigusi ega salvesta parooli.",
        detail: "Ülesanne käivitab Prune’i käsurea (prune-cli clean --preset recommended): ainult reeglid, mille Prune vaikimisi märgib, mitte kunagi need, mis andmeid kaotavad, ning alati sinu erandite, kaitstud asukohtade ja karantiini seadega. Selle väljalülitamine või Prune’i desinstallimine kustutab ülesande.",
        nextRun: (a) => `Järgmine automaatne käivitus: ${a}`,
        needsClean: "Määra kõigepealt, et ajakava puhastab. Ülesanne ainult puhastab.",
        unsupported: "Saadaval Windowsi paigaldatud Prune’i rakenduses. See koopia ei saa seda seadistada.",
        cliMissing: "Prune’i kaustast puudub prune-cli.cmd, seega ei saa ülesannet luua. Taasta see Prune’i uuesti paigaldades.",
        outOfSync: "Windowsi ülesanne ei vasta veel ülaltoodud ajakavale. Värskendamiseks lülita see välja ja uuesti sisse.",
        taskFailed: (a) => `Windows teatas ülesande viimasel käivitamisel veast ${a}.`,
        saveFailed: (a) => `Seda seadet ei õnnestunud muuta: ${a}`,
        loadFailed: (a) => `Ülesande olekut ei õnnestunud lugeda: ${a}`
      },
      last: {
        clean: (a, b, c) => `Viimane automaatne puhastus: ${a} — teisaldati ${b}, vabastati ${c}`,
        errors: (a, b, c) => `Viimane automaatne puhastus: ${a} — mõned reeglid ebaõnnestusid; teisaldati ${b}, vabastati ${c}`
      }
    }
  },
  fi: {
    backgroundV3: {
      task: {
        title: "Suorita myös kun Prune on suljettu",
        description: "Lisää Windowsin Tehtävien ajoitukseen tehtävän vain sinun tilillesi, jotta tämä aikataulu suoritetaan, vaikka Prune ei ole auki. Se ei tarvitse järjestelmänvalvojan oikeuksia eikä tallenna salasanaa.",
        detail: "Tehtävä ajaa Prunen komentorivin (prune-cli clean --preset recommended): vain säännöt, jotka Prune valitsee oletuksena, ei koskaan niitä, jotka menettävät tietoa, ja aina sinun poikkeuksiesi, suojattujen polkujesi ja karanteeniasetuksesi mukaan. Kun kytket tämän pois tai poistat Prunen, tehtävä poistetaan.",
        nextRun: (a) => `Seuraava automaattinen suoritus: ${a}`,
        needsClean: "Aseta ensin aikataulu siivoamaan. Tehtävä vain siivoaa.",
        unsupported: "Käytettävissä Windowsiin asennetussa Prune-sovelluksessa. Tämä kopio ei voi asettaa sitä.",
        cliMissing: "prune-cli.cmd puuttuu Prunen kansiosta, joten tehtävää ei voi luoda. Palauta se asentamalla Prune uudelleen.",
        outOfSync: "Windowsin tehtävä ei vielä vastaa yllä olevaa aikataulua. Päivitä se kytkemällä tämä pois ja takaisin päälle.",
        taskFailed: (a) => `Windows ilmoitti virheen ${a}, kun tehtävä viimeksi käynnistyi.`,
        saveFailed: (a) => `Asetuksen muuttaminen ei onnistunut: ${a}`,
        loadFailed: (a) => `Tehtävän tilan lukeminen ei onnistunut: ${a}`
      },
      last: {
        clean: (a, b, c) => `Viimeisin automaattinen siivous: ${a} — siirrettiin ${b}, vapautettiin ${c}`,
        errors: (a, b, c) => `Viimeisin automaattinen siivous: ${a} — jotkin säännöt epäonnistuivat; siirrettiin ${b}, vapautettiin ${c}`
      }
    }
  },
  fr: {
    backgroundV3: {
      task: {
        title: "Exécuter aussi quand Prune est fermé",
        description: "Ajoute une tâche au Planificateur de tâches de Windows, pour votre compte uniquement, afin que ce planning s'exécute même quand Prune n'est pas ouvert. Elle n'exige aucun droit d'administrateur et ne stocke aucun mot de passe.",
        detail: "La tâche lance la ligne de commande de Prune (prune-cli clean --preset recommended) : uniquement les règles que Prune coche par défaut, jamais celles qui font perdre des données, et toujours avec vos exclusions, vos chemins protégés et votre réglage de Quarantaine. Désactiver cette option, ou désinstaller Prune, supprime la tâche.",
        nextRun: (a) => `Prochaine exécution automatique : ${a}`,
        needsClean: "Réglez d'abord le planning sur le nettoyage. La tâche ne fait que nettoyer.",
        unsupported: "Disponible dans l'application Prune installée sous Windows. Cette copie ne peut pas le régler.",
        cliMissing: "prune-cli.cmd est absent du dossier de Prune, la tâche ne peut donc pas être créée. Réinstallez Prune pour le restaurer.",
        outOfSync: "La tâche dans Windows ne correspond pas encore au planning ci-dessus. Désactivez puis réactivez cette option pour la mettre à jour.",
        taskFailed: (a) => `Windows a signalé l'erreur ${a} lors du dernier démarrage de la tâche.`,
        saveFailed: (a) => `Impossible de modifier ce réglage : ${a}`,
        loadFailed: (a) => `Impossible de lire l'état de la tâche : ${a}`
      },
      last: {
        clean: (a, b, c) => `Dernier nettoyage automatique : ${a} — ${b} déplacés, ${c} libérés`,
        errors: (a, b, c) => `Dernier nettoyage automatique : ${a} — certaines règles ont échoué ; ${b} déplacés, ${c} libérés`
      }
    }
  },
  he: {
    backgroundV3: {
      task: {
        title: "הרץ גם כש-Prune סגור",
        description: "מוסיף משימה למתזמן המשימות של Windows, עבור החשבון שלך בלבד, כך שהלוח הזמנים הזה ירוץ גם כש-Prune אינו פתוח. אין צורך בהרשאות מנהל והסיסמה אינה נשמרת.",
        detail: "המשימה מריצה את שורת הפקודה של Prune‏ (prune-cli clean --preset recommended): רק את הכללים ש-Prune מסמן כברירת מחדל, לעולם לא את אלה שמאבדים נתונים, ותמיד עם החריגים, הנתיבים המוגנים והגדרת ההסגר שלך. כיבוי האפשרות או הסרת Prune מוחקים את המשימה.",
        nextRun: (a) => `ההרצה האוטומטית הבאה: ${a}`,
        needsClean: "הגדר קודם שהלוח הזמנים מנקה. המשימה רק מנקה.",
        unsupported: "זמין באפליקציית Prune המותקנת ב-Windows. עותק זה אינו יכול להגדיר זאת.",
        cliMissing: "prune-cli.cmd חסר בתיקיית Prune, ולכן אי אפשר להגדיר את המשימה. התקן את Prune מחדש כדי לשחזר אותו.",
        outOfSync: "המשימה ב-Windows עדיין אינה תואמת ללוח הזמנים שלמעלה. כבה והפעל מחדש כדי לעדכן אותה.",
        taskFailed: (a) => `Windows דיווח על שגיאה ${a} בהפעלה האחרונה של המשימה.`,
        saveFailed: (a) => `לא ניתן היה לשנות הגדרה זו: ${a}`,
        loadFailed: (a) => `לא ניתן היה לקרוא את מצב המשימה: ${a}`
      },
      last: {
        clean: (a, b, c) => `הניקוי האוטומטי האחרון: ${a} — הועברו ${b}, פונו ${c}`,
        errors: (a, b, c) => `הניקוי האוטומטי האחרון: ${a} — חלק מהכללים נכשלו; הועברו ${b}, פונו ${c}`
      }
    }
  },
  hu: {
    backgroundV3: {
      task: {
        title: "Futtatás akkor is, ha a Prune be van zárva",
        description: "Feladatot ad a Windows Feladatütemezőhöz, csak a saját fiókodhoz, így ez az ütemezés akkor is lefut, ha a Prune nincs megnyitva. Nem kér rendszergazdai jogot, és jelszót sem tárol.",
        detail: "A feladat a Prune parancssorát futtatja (prune-cli clean --preset recommended): csak a Prune alapból bejelölt szabályait, soha azokat, amelyek adatot veszítenek, és mindig a kivételeiddel, védett útvonalaiddal és a Karantén beállításoddal. Ha kikapcsolod, vagy eltávolítod a Prune-t, a feladat törlődik.",
        nextRun: (a) => `Következő automatikus futás: ${a}`,
        needsClean: "Először állítsd az ütemezést tisztításra. A feladat csak tisztít.",
        unsupported: "A Windowsra telepített Prune alkalmazásban érhető el. Ez a példány nem tudja beállítani.",
        cliMissing: "A prune-cli.cmd hiányzik a Prune mappájából, ezért a feladat nem hozható létre. Telepítsd újra a Prune-t a visszaállításához.",
        outOfSync: "A Windowsban lévő feladat még nem egyezik a fenti ütemezéssel. Kapcsold ki, majd be újra a frissítéshez.",
        taskFailed: (a) => `A Windows a feladat legutóbbi indításakor a(z) ${a} hibát jelentette.`,
        saveFailed: (a) => `Nem sikerült módosítani ezt a beállítást: ${a}`,
        loadFailed: (a) => `Nem sikerült beolvasni a feladat állapotát: ${a}`
      },
      last: {
        clean: (a, b, c) => `Legutóbbi automatikus tisztítás: ${a} — áthelyezve ${b}, felszabadítva ${c}`,
        errors: (a, b, c) => `Legutóbbi automatikus tisztítás: ${a} — egyes szabályok sikertelenek voltak; áthelyezve ${b}, felszabadítva ${c}`
      }
    }
  },
  id: {
    backgroundV3: {
      task: {
        title: "Jalankan juga saat Prune ditutup",
        description: "Menambahkan tugas ke Penjadwal Tugas Windows, hanya untuk akun Anda, agar jadwal ini berjalan walau Prune tidak terbuka. Tidak memerlukan hak administrator dan tidak menyimpan kata sandi.",
        detail: "Tugas ini menjalankan baris perintah Prune (prune-cli clean --preset recommended): hanya aturan yang dicentang Prune secara bawaan, tidak pernah yang menghilangkan data, dan selalu dengan pengecualian, jalur terlindungi, serta pengaturan Karantina Anda. Mematikannya, atau mencopot Prune, menghapus tugas.",
        nextRun: (a) => `Eksekusi otomatis berikutnya: ${a}`,
        needsClean: "Atur dulu jadwal agar membersihkan. Tugas ini hanya membersihkan.",
        unsupported: "Tersedia di aplikasi Prune yang terpasang di Windows. Salinan ini tidak bisa mengaturnya.",
        cliMissing: "prune-cli.cmd tidak ada di folder Prune, sehingga tugas tidak bisa dibuat. Pasang ulang Prune untuk memulihkannya.",
        outOfSync: "Tugas di Windows belum sesuai dengan jadwal di atas. Matikan lalu nyalakan lagi untuk memperbaruinya.",
        taskFailed: (a) => `Windows melaporkan kesalahan ${a} saat tugas terakhir dimulai.`,
        saveFailed: (a) => `Tidak dapat mengubah pengaturan ini: ${a}`,
        loadFailed: (a) => `Tidak dapat membaca status tugas: ${a}`
      },
      last: {
        clean: (a, b, c) => `Pembersihan otomatis terakhir: ${a} — ${b} dipindahkan, ${c} dibebaskan`,
        errors: (a, b, c) => `Pembersihan otomatis terakhir: ${a} — beberapa aturan gagal; ${b} dipindahkan, ${c} dibebaskan`
      }
    }
  },
  is: {
    backgroundV3: {
      task: {
        title: "Keyra líka þegar Prune er lokað",
        description: "Bætir verkefni við Windows verkefnaáætlun, aðeins fyrir þinn aðgang, svo þessi áætlun keyri jafnvel þegar Prune er ekki opið. Þarf ekki stjórnandaréttindi og vistar ekkert lykilorð.",
        detail: "Verkefnið keyrir skipanalínu Prune (prune-cli clean --preset recommended): aðeins reglurnar sem Prune velur sjálfgefið, aldrei þær sem tapa gögnum, og alltaf með undantekningum þínum, vernduðum slóðum og stillingu sóttkvíar. Ef þú slekkur á þessu eða fjarlægir Prune er verkefnið eytt.",
        nextRun: (a) => `Næsta sjálfvirka keyrsla: ${a}`,
        needsClean: "Stilltu fyrst áætlunina á hreinsun. Verkefnið hreinsar aðeins.",
        unsupported: "Í boði í uppsettu Prune-forriti á Windows. Þetta eintak getur ekki stillt það.",
        cliMissing: "prune-cli.cmd vantar í möppu Prune, svo ekki er hægt að setja verkefnið upp. Settu Prune upp aftur til að endurheimta það.",
        outOfSync: "Verkefnið í Windows passar ekki enn við áætlunina hér að ofan. Slökktu og kveiktu aftur á þessu til að uppfæra það.",
        taskFailed: (a) => `Windows tilkynnti villu ${a} þegar verkefnið var síðast ræst.`,
        saveFailed: (a) => `Ekki tókst að breyta þessari stillingu: ${a}`,
        loadFailed: (a) => `Ekki tókst að lesa stöðu verkefnisins: ${a}`
      },
      last: {
        clean: (a, b, c) => `Síðasta sjálfvirka hreinsun: ${a} — fært ${b}, losað ${c}`,
        errors: (a, b, c) => `Síðasta sjálfvirka hreinsun: ${a} — sumar reglur mistókust; fært ${b}, losað ${c}`
      }
    }
  },
  it: {
    backgroundV3: {
      task: {
        title: "Esegui anche quando Prune è chiuso",
        description: "Aggiunge un'attività all'Utilità di pianificazione di Windows, solo per il tuo account, così questa pianificazione viene eseguita anche quando Prune non è aperto. Non richiede diritti di amministratore e non memorizza alcuna password.",
        detail: "L'attività esegue la riga di comando di Prune (prune-cli clean --preset recommended): solo le regole che Prune seleziona per impostazione predefinita, mai quelle che perdono dati, e sempre con le tue esclusioni, i percorsi protetti e l'impostazione della Quarantena. Disattivandola, o disinstallando Prune, l'attività viene eliminata.",
        nextRun: (a) => `Prossima esecuzione automatica: ${a}`,
        needsClean: "Imposta prima la pianificazione sulla pulizia. L'attività si limita a pulire.",
        unsupported: "Disponibile nell'app Prune installata su Windows. Questa copia non può impostarlo.",
        cliMissing: "prune-cli.cmd manca nella cartella di Prune, quindi l'attività non può essere creata. Reinstalla Prune per ripristinarlo.",
        outOfSync: "L'attività in Windows non corrisponde ancora alla pianificazione qui sopra. Disattiva e riattiva questa opzione per aggiornarla.",
        taskFailed: (a) => `Windows ha segnalato l'errore ${a} all'ultimo avvio dell'attività.`,
        saveFailed: (a) => `Impossibile modificare questa impostazione: ${a}`,
        loadFailed: (a) => `Impossibile leggere lo stato dell'attività: ${a}`
      },
      last: {
        clean: (a, b, c) => `Ultima pulizia automatica: ${a} — spostati ${b}, liberati ${c}`,
        errors: (a, b, c) => `Ultima pulizia automatica: ${a} — alcune regole non sono riuscite; spostati ${b}, liberati ${c}`
      }
    }
  },
  ja: {
    backgroundV3: {
      task: {
        title: "Prune を閉じていても実行する",
        description: "あなたのアカウント専用のタスクを Windows タスク スケジューラに追加し、Prune が開いていなくてもこのスケジュールで実行します。管理者権限は不要で、パスワードも保存しません。",
        detail: "タスクは Prune のコマンドライン (prune-cli clean --preset recommended) を実行します。対象は Prune が既定でオンにするルールだけで、データを失うルールは含まれず、常に除外設定、保護されたパス、隔離の設定が適用されます。これをオフにするか Prune をアンインストールすると、タスクは削除されます。",
        nextRun: (a) => `次回の自動実行: ${a}`,
        needsClean: "まずスケジュールの動作をクリーンアップにしてください。タスクはクリーンアップのみ行います。",
        unsupported: "Windows にインストールした Prune アプリで利用できます。このコピーでは設定できません。",
        cliMissing: "Prune のフォルダーに prune-cli.cmd がないため、タスクを設定できません。Prune を再インストールして復元してください。",
        outOfSync: "Windows のタスクはまだ上のスケジュールと一致していません。オフにしてからもう一度オンにすると更新されます。",
        taskFailed: (a) => `タスクの前回の開始時に Windows がエラー ${a} を報告しました。`,
        saveFailed: (a) => `この設定を変更できませんでした: ${a}`,
        loadFailed: (a) => `タスクの状態を読み取れませんでした: ${a}`
      },
      last: {
        clean: (a, b, c) => `前回の自動クリーンアップ: ${a} — ${b} を移動、${c} を解放`,
        errors: (a, b, c) => `前回の自動クリーンアップ: ${a} — 一部のルールが失敗しました。${b} を移動、${c} を解放`
      }
    }
  },
  ko: {
    backgroundV3: {
      task: {
        title: "Prune이 닫혀 있어도 실행",
        description: "내 계정 전용으로 Windows 작업 스케줄러에 작업을 추가하여 Prune이 열려 있지 않아도 이 일정대로 실행합니다. 관리자 권한이 필요 없으며 암호를 저장하지 않습니다.",
        detail: "이 작업은 Prune의 명령줄(prune-cli clean --preset recommended)을 실행합니다. Prune이 기본으로 선택하는 규칙만 사용하고 데이터를 잃는 규칙은 절대 포함하지 않으며, 항상 제외 항목, 보호된 경로, 격리 설정을 따릅니다. 이 옵션을 끄거나 Prune을 제거하면 작업이 삭제됩니다.",
        nextRun: (a) => `다음 자동 실행: ${a}`,
        needsClean: "먼저 일정이 정리를 수행하도록 설정하세요. 이 작업은 정리만 합니다.",
        unsupported: "Windows에 설치된 Prune 앱에서 사용할 수 있습니다. 이 사본에서는 설정할 수 없습니다.",
        cliMissing: "Prune 폴더에 prune-cli.cmd가 없어 작업을 설정할 수 없습니다. Prune을 다시 설치하여 복원하세요.",
        outOfSync: "Windows의 작업이 아직 위의 일정과 일치하지 않습니다. 껐다가 다시 켜서 업데이트하세요.",
        taskFailed: (a) => `작업이 마지막으로 시작될 때 Windows가 오류 ${a}을(를) 보고했습니다.`,
        saveFailed: (a) => `이 설정을 변경할 수 없습니다: ${a}`,
        loadFailed: (a) => `작업 상태를 읽을 수 없습니다: ${a}`
      },
      last: {
        clean: (a, b, c) => `마지막 자동 정리: ${a} — ${b} 이동, ${c} 확보`,
        errors: (a, b, c) => `마지막 자동 정리: ${a} — 일부 규칙 실패, ${b} 이동, ${c} 확보`
      }
    }
  },
  lt: {
    backgroundV3: {
      task: {
        title: "Vykdyti ir kai Prune uždarytas",
        description: "Prideda užduotį prie „Windows“ užduočių planuoklio, tik jūsų paskyrai, kad šis tvarkaraštis veiktų, net kai „Prune“ neatidarytas. Nereikia administratoriaus teisių ir neišsaugomas joks slaptažodis.",
        detail: "Užduotis paleidžia „Prune“ komandų eilutę (prune-cli clean --preset recommended): tik taisykles, kurias „Prune“ pažymi pagal numatytuosius nustatymus, niekada tų, dėl kurių prarandami duomenys, ir visada su jūsų išimtimis, apsaugotais keliais bei karantino nustatymu. Išjungus tai arba pašalinus „Prune“, užduotis ištrinama.",
        nextRun: (a) => `Kitas automatinis vykdymas: ${a}`,
        needsClean: "Pirmiausia nustatykite, kad tvarkaraštis valytų. Užduotis tik valo.",
        unsupported: "Pasiekiama įdiegtoje „Prune“ programoje sistemoje „Windows“. Ši kopija negali to nustatyti.",
        cliMissing: "Trūksta prune-cli.cmd „Prune“ aplanke, todėl užduoties nustatyti negalima. Iš naujo įdiekite „Prune“, kad jį atkurtumėte.",
        outOfSync: "Užduotis „Windows“ dar neatitinka aukščiau esančio tvarkaraščio. Išjunkite ir vėl įjunkite, kad ją atnaujintumėte.",
        taskFailed: (a) => `„Windows“ pranešė apie klaidą ${a}, kai užduotis buvo paleista paskutinį kartą.`,
        saveFailed: (a) => `Nepavyko pakeisti šio nustatymo: ${a}`,
        loadFailed: (a) => `Nepavyko nuskaityti užduoties būsenos: ${a}`
      },
      last: {
        clean: (a, b, c) => `Paskutinis automatinis valymas: ${a} — perkelta ${b}, atlaisvinta ${c}`,
        errors: (a, b, c) => `Paskutinis automatinis valymas: ${a} — kai kurios taisyklės nepavyko; perkelta ${b}, atlaisvinta ${c}`
      }
    }
  },
  ms: {
    backgroundV3: {
      task: {
        title: "Jalankan juga apabila Prune ditutup",
        description: "Menambah tugas pada Penjadual Tugas Windows, untuk akaun anda sahaja, supaya jadual ini berjalan walaupun Prune tidak dibuka. Tidak memerlukan hak pentadbir dan tidak menyimpan kata laluan.",
        detail: "Tugas ini menjalankan baris arahan Prune (prune-cli clean --preset recommended): hanya peraturan yang ditanda oleh Prune secara lalai, tidak pernah yang menyebabkan kehilangan data, dan sentiasa dengan pengecualian, laluan dilindungi serta tetapan Kuarantin anda. Mematikannya, atau menyahpasang Prune, memadam tugas.",
        nextRun: (a) => `Larian automatik seterusnya: ${a}`,
        needsClean: "Tetapkan dahulu jadual untuk membersihkan. Tugas ini hanya membersihkan.",
        unsupported: "Tersedia dalam aplikasi Prune yang dipasang pada Windows. Salinan ini tidak boleh menetapkannya.",
        cliMissing: "prune-cli.cmd tiada dalam folder Prune, jadi tugas tidak dapat disediakan. Pasang semula Prune untuk memulihkannya.",
        outOfSync: "Tugas dalam Windows belum sepadan dengan jadual di atas. Matikan dan hidupkan semula untuk mengemas kininya.",
        taskFailed: (a) => `Windows melaporkan ralat ${a} apabila tugas dimulakan kali terakhir.`,
        saveFailed: (a) => `Tidak dapat menukar tetapan ini: ${a}`,
        loadFailed: (a) => `Tidak dapat membaca keadaan tugas: ${a}`
      },
      last: {
        clean: (a, b, c) => `Pembersihan automatik terakhir: ${a} — ${b} dialihkan, ${c} dibebaskan`,
        errors: (a, b, c) => `Pembersihan automatik terakhir: ${a} — sesetengah peraturan gagal; ${b} dialihkan, ${c} dibebaskan`
      }
    }
  },
  nb: {
    backgroundV3: {
      task: {
        title: "Kjør også når Prune er lukket",
        description: "Legger til en oppgave i Windows Oppgaveplanlegger, bare for kontoen din, slik at denne tidsplanen kjører selv når Prune ikke er åpen. Den trenger ikke administratorrettigheter og lagrer ikke noe passord.",
        detail: "Oppgaven kjører Prunes kommandolinje (prune-cli clean --preset recommended): bare reglene Prune huker av som standard, aldri de som mister data, og alltid med unntakene dine, beskyttede stier og karanteneinnstillingen din. Slår du dette av, eller avinstallerer Prune, slettes oppgaven.",
        nextRun: (a) => `Neste automatiske kjøring: ${a}`,
        needsClean: "Sett først tidsplanen til å rense. Oppgaven renser bare.",
        unsupported: "Tilgjengelig i den installerte Prune-appen på Windows. Denne kopien kan ikke angi det.",
        cliMissing: "prune-cli.cmd mangler i Prunes mappe, så oppgaven kan ikke settes opp. Installer Prune på nytt for å gjenopprette den.",
        outOfSync: "Oppgaven i Windows samsvarer ikke med tidsplanen ovenfor ennå. Slå dette av og på igjen for å oppdatere den.",
        taskFailed: (a) => `Windows rapporterte feil ${a} forrige gang oppgaven startet.`,
        saveFailed: (a) => `Kunne ikke endre denne innstillingen: ${a}`,
        loadFailed: (a) => `Kunne ikke lese oppgavens tilstand: ${a}`
      },
      last: {
        clean: (a, b, c) => `Siste automatiske rensing: ${a} — flyttet ${b}, frigjorde ${c}`,
        errors: (a, b, c) => `Siste automatiske rensing: ${a} — noen regler mislyktes; flyttet ${b}, frigjorde ${c}`
      }
    }
  },
  nl: {
    backgroundV3: {
      task: {
        title: "Ook uitvoeren als Prune gesloten is",
        description: "Voegt een taak toe aan de Windows-taakplanner, alleen voor jouw account, zodat dit schema ook draait als Prune niet open is. Er zijn geen beheerdersrechten voor nodig en er wordt geen wachtwoord opgeslagen.",
        detail: "De taak voert de opdrachtregel van Prune uit (prune-cli clean --preset recommended): alleen de regels die Prune standaard aanvinkt, nooit die waarbij gegevens verloren gaan, en altijd met jouw uitzonderingen, beschermde paden en Quarantaine-instelling. Zet je dit uit, of verwijder je Prune, dan wordt de taak verwijderd.",
        nextRun: (a) => `Volgende automatische uitvoering: ${a}`,
        needsClean: "Stel het schema eerst in op opschonen. De taak ruimt alleen op.",
        unsupported: "Beschikbaar in de geïnstalleerde Prune-app op Windows. Deze kopie kan het niet instellen.",
        cliMissing: "prune-cli.cmd ontbreekt in de map van Prune, dus de taak kan niet worden ingesteld. Installeer Prune opnieuw om het te herstellen.",
        outOfSync: "De taak in Windows komt nog niet overeen met het schema hierboven. Zet dit uit en weer aan om de taak bij te werken.",
        taskFailed: (a) => `Windows meldde fout ${a} toen de taak voor het laatst startte.`,
        saveFailed: (a) => `Deze instelling kon niet worden gewijzigd: ${a}`,
        loadFailed: (a) => `De status van de taak kon niet worden gelezen: ${a}`
      },
      last: {
        clean: (a, b, c) => `Laatste automatische opschoning: ${a} — ${b} verplaatst, ${c} vrijgemaakt`,
        errors: (a, b, c) => `Laatste automatische opschoning: ${a} — sommige regels zijn mislukt; ${b} verplaatst, ${c} vrijgemaakt`
      }
    }
  },
  pl: {
    backgroundV3: {
      task: {
        title: "Uruchamiaj także, gdy Prune jest zamknięty",
        description: "Dodaje zadanie do Harmonogramu zadań systemu Windows, tylko dla Twojego konta, aby ten harmonogram działał nawet wtedy, gdy Prune nie jest otwarty. Nie wymaga uprawnień administratora i nie zapisuje hasła.",
        detail: "Zadanie uruchamia wiersz poleceń Prune (prune-cli clean --preset recommended): tylko reguły, które Prune domyślnie zaznacza, nigdy te powodujące utratę danych, i zawsze z Twoimi wyjątkami, chronionymi ścieżkami oraz ustawieniem kwarantanny. Wyłączenie tej opcji lub odinstalowanie Prune usuwa zadanie.",
        nextRun: (a) => `Następne automatyczne uruchomienie: ${a}`,
        needsClean: "Najpierw ustaw harmonogram na czyszczenie. Zadanie tylko czyści.",
        unsupported: "Dostępne w zainstalowanej aplikacji Prune w systemie Windows. Ta kopia nie może tego ustawić.",
        cliMissing: "Brakuje prune-cli.cmd w folderze Prune, więc nie można utworzyć zadania. Zainstaluj Prune ponownie, aby go przywrócić.",
        outOfSync: "Zadanie w systemie Windows nie zgadza się jeszcze z harmonogramem powyżej. Wyłącz i ponownie włącz tę opcję, aby je zaktualizować.",
        taskFailed: (a) => `System Windows zgłosił błąd ${a} przy ostatnim uruchomieniu zadania.`,
        saveFailed: (a) => `Nie udało się zmienić tego ustawienia: ${a}`,
        loadFailed: (a) => `Nie udało się odczytać stanu zadania: ${a}`
      },
      last: {
        clean: (a, b, c) => `Ostatnie automatyczne czyszczenie: ${a} — przeniesiono ${b}, zwolniono ${c}`,
        errors: (a, b, c) => `Ostatnie automatyczne czyszczenie: ${a} — niektóre reguły nie powiodły się; przeniesiono ${b}, zwolniono ${c}`
      }
    }
  },
  ps: {
    backgroundV3: {
      task: {
        title: "کله چې Prune بند وي هم چلول",
        description: "د Windows د کارونو مهالویش کوونکي ته یوه دنده زیاتوي، یوازې ستاسو د حساب لپاره، ترڅو دا مهالویش حتی هغه وخت چلیږي چې Prune پرانیستی نه وي. د مدیر اجازې ته اړتیا نشته او رمز نه ساتي.",
        detail: "دا دنده د Prune قوماندې کرښه چلوي (prune-cli clean --preset recommended): یوازې هغه قاعدې چې Prune په ډیفالټ ټاکي، هیڅکله هغه نه چې معلومات له لاسه ورکوي، او تل ستاسو له استثناوو، ساتل شویو لارو او د قرنطین له تنظیم سره. که دا بند کړئ، یا Prune ناانسټال کړئ، دنده ړنګیږي.",
        nextRun: (a) => `راتلونکی اتومات چلول: ${a}`,
        needsClean: "لومړی مهالویش پاکولو ته وټاکئ. دنده یوازې پاکوي.",
        unsupported: "په Windows کې په نصب شوي Prune اپ کې شتون لري. دا کاپي یې نشي ټاکلی.",
        cliMissing: "prune-cli.cmd د Prune په فولډر کې نشته، نو دنده نشي جوړیدلی. د بیا راګرځولو لپاره Prune بیا نصب کړئ.",
        outOfSync: "په Windows کې دنده لا تر اوسه پورتني مهالویش سره نه سمون خوري. د تازه کولو لپاره دا بند او بیا چالان کړئ.",
        taskFailed: (a) => `Windows د دندې د وروستي پیل پر مهال ${a} تېروتنه راپور کړه.`,
        saveFailed: (a) => `دا تنظیم بدل نشو: ${a}`,
        loadFailed: (a) => `د دندې حالت ولوستل نشو: ${a}`
      },
      last: {
        clean: (a, b, c) => `وروستی اتومات پاکول: ${a} — ${b} ولیږدول شول، ${c} خلاص شو`,
        errors: (a, b, c) => `وروستی اتومات پاکول: ${a} — ځینې قاعدې ناکامې شوې؛ ${b} ولیږدول شول، ${c} خلاص شو`
      }
    }
  },
  "pt-BR": {
    backgroundV3: {
      task: {
        title: "Executar também quando o Prune está fechado",
        description: "Adiciona uma tarefa ao Agendador de Tarefas do Windows, só para a sua conta, para que este agendamento rode mesmo com o Prune fechado. Não precisa de direitos de administrador e não guarda nenhuma senha.",
        detail: "A tarefa executa a linha de comando do Prune (prune-cli clean --preset recommended): só as regras que o Prune marca por padrão, nunca as que perdem dados, e sempre com suas exclusões, caminhos protegidos e a configuração de Quarentena. Se você desativar isto, ou desinstalar o Prune, a tarefa é excluída.",
        nextRun: (a) => `Próxima execução automática: ${a}`,
        needsClean: "Primeiro defina o agendamento para limpar. A tarefa só limpa.",
        unsupported: "Disponível no aplicativo Prune instalado no Windows. Esta cópia não consegue definir isso.",
        cliMissing: "O prune-cli.cmd não está na pasta do Prune, então a tarefa não pode ser criada. Reinstale o Prune para restaurá-lo.",
        outOfSync: "A tarefa no Windows ainda não corresponde ao agendamento acima. Desative e ative de novo para atualizá-la.",
        taskFailed: (a) => `O Windows informou o erro ${a} na última vez que a tarefa foi iniciada.`,
        saveFailed: (a) => `Não foi possível alterar esta configuração: ${a}`,
        loadFailed: (a) => `Não foi possível ler o estado da tarefa: ${a}`
      },
      last: {
        clean: (a, b, c) => `Última limpeza automática: ${a} — ${b} movidos, ${c} liberados`,
        errors: (a, b, c) => `Última limpeza automática: ${a} — algumas regras falharam; ${b} movidos, ${c} liberados`
      }
    }
  },
  pt: {
    backgroundV3: {
      task: {
        title: "Executar também quando o Prune está fechado",
        description: "Adiciona uma tarefa ao Agendador de Tarefas do Windows, só para a sua conta, para que esta agenda corra mesmo com o Prune fechado. Não precisa de direitos de administrador e não guarda nenhuma palavra-passe.",
        detail: "A tarefa executa a linha de comandos do Prune (prune-cli clean --preset recommended): só as regras que o Prune marca por predefinição, nunca as que perdem dados, e sempre com as suas exclusões, caminhos protegidos e a definição de Quarentena. Se desativar isto, ou desinstalar o Prune, a tarefa é eliminada.",
        nextRun: (a) => `Próxima execução automática: ${a}`,
        needsClean: "Primeiro defina a agenda para limpar. A tarefa só limpa.",
        unsupported: "Disponível na aplicação Prune instalada no Windows. Esta cópia não consegue defini-lo.",
        cliMissing: "O prune-cli.cmd não está na pasta do Prune, por isso a tarefa não pode ser criada. Reinstale o Prune para o restaurar.",
        outOfSync: "A tarefa no Windows ainda não corresponde à agenda acima. Desative e volte a ativar para a atualizar.",
        taskFailed: (a) => `O Windows indicou o erro ${a} na última vez que a tarefa foi iniciada.`,
        saveFailed: (a) => `Não foi possível alterar esta definição: ${a}`,
        loadFailed: (a) => `Não foi possível ler o estado da tarefa: ${a}`
      },
      last: {
        clean: (a, b, c) => `Última limpeza automática: ${a} — ${b} movidos, ${c} libertados`,
        errors: (a, b, c) => `Última limpeza automática: ${a} — algumas regras falharam; ${b} movidos, ${c} libertados`
      }
    }
  },
  ro: {
    backgroundV3: {
      task: {
        title: "Rulează și când Prune este închis",
        description: "Adaugă o sarcină în Task Scheduler din Windows, doar pentru contul tău, astfel încât acest program să ruleze chiar și când Prune nu este deschis. Nu necesită drepturi de administrator și nu stochează nicio parolă.",
        detail: "Sarcina rulează linia de comandă Prune (prune-cli clean --preset recommended): doar regulile pe care Prune le bifează implicit, niciodată cele care pierd date, și mereu cu excluderile, căile protejate și setarea Carantinei tale. Dacă dezactivezi opțiunea sau dezinstalezi Prune, sarcina este ștearsă.",
        nextRun: (a) => `Următoarea rulare automată: ${a}`,
        needsClean: "Setează mai întâi programul să curețe. Sarcina doar curăță.",
        unsupported: "Disponibil în aplicația Prune instalată în Windows. Această copie nu îl poate seta.",
        cliMissing: "Lipsește prune-cli.cmd din folderul Prune, deci sarcina nu poate fi creată. Reinstalează Prune pentru a-l restaura.",
        outOfSync: "Sarcina din Windows nu se potrivește încă cu programul de mai sus. Dezactivează și reactivează opțiunea pentru a o actualiza.",
        taskFailed: (a) => `Windows a raportat eroarea ${a} la ultima pornire a sarcinii.`,
        saveFailed: (a) => `Nu s-a putut schimba această setare: ${a}`,
        loadFailed: (a) => `Nu s-a putut citi starea sarcinii: ${a}`
      },
      last: {
        clean: (a, b, c) => `Ultima curățare automată: ${a} — ${b} mutați, ${c} eliberați`,
        errors: (a, b, c) => `Ultima curățare automată: ${a} — unele reguli au eșuat; ${b} mutați, ${c} eliberați`
      }
    }
  },
  ru: {
    backgroundV3: {
      task: {
        title: "Запускать и при закрытом Prune",
        description: "Добавляет задачу в Планировщик заданий Windows только для вашей учётной записи, чтобы это расписание работало, даже когда Prune не открыт. Права администратора не нужны, пароль не сохраняется.",
        detail: "Задача запускает командную строку Prune (prune-cli clean --preset recommended): только правила, которые Prune отмечает по умолчанию, никогда те, что приводят к потере данных, и всегда с вашими исключениями, защищёнными путями и настройкой карантина. Если отключить это или удалить Prune, задача будет удалена.",
        nextRun: (a) => `Следующий автоматический запуск: ${a}`,
        needsClean: "Сначала задайте для расписания очистку. Задача только очищает.",
        unsupported: "Доступно в установленном приложении Prune в Windows. Эта копия не может это настроить.",
        cliMissing: "В папке Prune нет файла prune-cli.cmd, поэтому задачу нельзя создать. Переустановите Prune, чтобы восстановить его.",
        outOfSync: "Задача в Windows пока не соответствует расписанию выше. Выключите и снова включите этот параметр, чтобы обновить её.",
        taskFailed: (a) => `Windows сообщила об ошибке ${a} при последнем запуске задачи.`,
        saveFailed: (a) => `Не удалось изменить этот параметр: ${a}`,
        loadFailed: (a) => `Не удалось прочитать состояние задачи: ${a}`
      },
      last: {
        clean: (a, b, c) => `Последняя автоматическая очистка: ${a} — перемещено ${b}, освобождено ${c}`,
        errors: (a, b, c) => `Последняя автоматическая очистка: ${a} — некоторые правила завершились ошибкой; перемещено ${b}, освобождено ${c}`
      }
    }
  },
  sk: {
    backgroundV3: {
      task: {
        title: "Spúšťať aj pri zatvorenom Prune",
        description: "Pridá úlohu do Plánovača úloh systému Windows, len pre váš účet, aby sa tento plán spúšťal aj vtedy, keď Prune nie je otvorený. Nepotrebuje práva správcu a neukladá žiadne heslo.",
        detail: "Úloha spúšťa príkazový riadok Prune (prune-cli clean --preset recommended): iba pravidlá, ktoré Prune predvolene zaškrtáva, nikdy tie, ktoré spôsobujú stratu údajov, a vždy s vašimi výnimkami, chránenými cestami a nastavením karantény. Vypnutím tejto možnosti alebo odinštalovaním Prune sa úloha odstráni.",
        nextRun: (a) => `Ďalšie automatické spustenie: ${a}`,
        needsClean: "Najprv nastavte, aby plán čistil. Úloha iba čistí.",
        unsupported: "Dostupné v nainštalovanej aplikácii Prune v systéme Windows. Táto kópia to nemôže nastaviť.",
        cliMissing: "V priečinku Prune chýba prune-cli.cmd, preto sa úloha nedá vytvoriť. Obnovíte ho preinštalovaním Prune.",
        outOfSync: "Úloha v systéme Windows zatiaľ nezodpovedá plánu vyššie. Vypnite a znova zapnite túto možnosť, aby sa aktualizovala.",
        taskFailed: (a) => `Windows pri poslednom spustení úlohy nahlásil chybu ${a}.`,
        saveFailed: (a) => `Toto nastavenie sa nepodarilo zmeniť: ${a}`,
        loadFailed: (a) => `Stav úlohy sa nepodarilo prečítať: ${a}`
      },
      last: {
        clean: (a, b, c) => `Posledné automatické čistenie: ${a} — presunuté ${b}, uvoľnené ${c}`,
        errors: (a, b, c) => `Posledné automatické čistenie: ${a} — niektoré pravidlá zlyhali; presunuté ${b}, uvoľnené ${c}`
      }
    }
  },
  sq: {
    backgroundV3: {
      task: {
        title: "Ekzekuto edhe kur Prune është mbyllur",
        description: "Shton një detyrë te Planifikuesi i detyrave i Windows, vetëm për llogarinë tënde, që ky orar të ekzekutohet edhe kur Prune nuk është i hapur. Nuk kërkon të drejta administratori dhe nuk ruan fjalëkalim.",
        detail: "Detyra ekzekuton rreshtin e komandës të Prune (prune-cli clean --preset recommended): vetëm rregullat që Prune i shënon si parazgjedhje, kurrë ato që humbasin të dhëna, dhe gjithmonë me përjashtimet, shtigjet e mbrojtura dhe cilësimin tënd të Karantinës. Nëse e çaktivizon, ose çinstalon Prune, detyra fshihet.",
        nextRun: (a) => `Ekzekutimi i ardhshëm automatik: ${a}`,
        needsClean: "Fillimisht cakto që orari të pastrojë. Detyra vetëm pastron.",
        unsupported: "Në dispozicion në aplikacionin Prune të instaluar në Windows. Ky kopje nuk mund ta caktojë.",
        cliMissing: "Mungon prune-cli.cmd në dosjen e Prune, ndaj detyra nuk mund të krijohet. Instalo sërish Prune për ta rikthyer.",
        outOfSync: "Detyra në Windows ende nuk përputhet me orarin më sipër. Çaktivizoje dhe aktivizoje sërish për ta përditësuar.",
        taskFailed: (a) => `Windows raportoi gabimin ${a} herën e fundit që nisi detyra.`,
        saveFailed: (a) => `Ky cilësim nuk u ndryshua: ${a}`,
        loadFailed: (a) => `Gjendja e detyrës nuk u lexua: ${a}`
      },
      last: {
        clean: (a, b, c) => `Pastrimi i fundit automatik: ${a} — u zhvendosën ${b}, u liruan ${c}`,
        errors: (a, b, c) => `Pastrimi i fundit automatik: ${a} — disa rregulla dështuan; u zhvendosën ${b}, u liruan ${c}`
      }
    }
  },
  sr: {
    backgroundV3: {
      task: {
        title: "Покрени и када је Prune затворен",
        description: "Додаје задатак у Windows планер задатака, само за ваш налог, да би се овај распоред извршавао чак и када Prune није отворен. Не захтева администраторска права и не чува лозинку.",
        detail: "Задатак покреће командну линију програма Prune (prune-cli clean --preset recommended): само правила која Prune подразумевано означава, никада она која губе податке, и увек са вашим изузецима, заштићеним путањама и подешавањем карантина. Искључивањем ове опције или деинсталирањем Prune задатак се брише.",
        nextRun: (a) => `Следеће аутоматско покретање: ${a}`,
        needsClean: "Прво подесите да распоред чисти. Задатак само чисти.",
        unsupported: "Доступно у инсталираној апликацији Prune на систему Windows. Ова копија то не може да подеси.",
        cliMissing: "Недостаје prune-cli.cmd у фасцикли програма Prune, па се задатак не може подесити. Поново инсталирајте Prune да бисте га вратили.",
        outOfSync: "Задатак у систему Windows још не одговара распореду изнад. Искључите и поново укључите ово да бисте га ажурирали.",
        taskFailed: (a) => `Windows је пријавио грешку ${a} када је задатак последњи пут покренут.`,
        saveFailed: (a) => `Није могуће променити ово подешавање: ${a}`,
        loadFailed: (a) => `Није могуће прочитати стање задатка: ${a}`
      },
      last: {
        clean: (a, b, c) => `Последње аутоматско чишћење: ${a} — премештено ${b}, ослобођено ${c}`,
        errors: (a, b, c) => `Последње аутоматско чишћење: ${a} — нека правила нису успела; премештено ${b}, ослобођено ${c}`
      }
    }
  },
  sv: {
    backgroundV3: {
      task: {
        title: "Kör även när Prune är stängt",
        description: "Lägger till en uppgift i Windows Schemaläggaren, bara för ditt konto, så att det här schemat körs även när Prune inte är öppet. Den kräver inga administratörsrättigheter och sparar inget lösenord.",
        detail: "Uppgiften kör Prunes kommandorad (prune-cli clean --preset recommended): bara de regler som Prune bockar i som standard, aldrig de som förlorar data, och alltid med dina undantag, skyddade sökvägar och karantäninställning. Stänger du av detta, eller avinstallerar Prune, tas uppgiften bort.",
        nextRun: (a) => `Nästa automatiska körning: ${a}`,
        needsClean: "Ställ först in schemat på att rensa. Uppgiften rensar bara.",
        unsupported: "Finns i den installerade Prune-appen i Windows. Den här kopian kan inte ställa in det.",
        cliMissing: "prune-cli.cmd saknas i Prunes mapp, så uppgiften kan inte skapas. Installera om Prune för att återställa den.",
        outOfSync: "Uppgiften i Windows stämmer ännu inte med schemat ovan. Stäng av och slå på detta igen för att uppdatera den.",
        taskFailed: (a) => `Windows rapporterade fel ${a} när uppgiften senast startade.`,
        saveFailed: (a) => `Det gick inte att ändra den här inställningen: ${a}`,
        loadFailed: (a) => `Det gick inte att läsa uppgiftens tillstånd: ${a}`
      },
      last: {
        clean: (a, b, c) => `Senaste automatiska rensning: ${a} — flyttade ${b}, frigjorde ${c}`,
        errors: (a, b, c) => `Senaste automatiska rensning: ${a} — vissa regler misslyckades; flyttade ${b}, frigjorde ${c}`
      }
    }
  },
  th: {
    backgroundV3: {
      task: {
        title: "ทำงานแม้ปิด Prune อยู่",
        description: "เพิ่มงานใน Windows Task Scheduler เฉพาะบัญชีของคุณ เพื่อให้ตารางเวลานี้ทำงานได้แม้ Prune ไม่ได้เปิดอยู่ ไม่ต้องใช้สิทธิ์ผู้ดูแลระบบและไม่เก็บรหัสผ่าน",
        detail: "งานนี้เรียกใช้บรรทัดคำสั่งของ Prune (prune-cli clean --preset recommended) เฉพาะกฎที่ Prune เลือกไว้ตามค่าเริ่มต้น ไม่รวมกฎที่ทำให้ข้อมูลสูญหาย และเป็นไปตามข้อยกเว้น เส้นทางที่ป้องกัน และการตั้งค่ากักกันของคุณเสมอ การปิดตัวเลือกนี้หรือถอนการติดตั้ง Prune จะลบงานนี้",
        nextRun: (a) => `การทำงานอัตโนมัติครั้งถัดไป: ${a}`,
        needsClean: "ตั้งให้ตารางเวลาทำการล้างข้อมูลก่อน งานนี้ล้างข้อมูลเท่านั้น",
        unsupported: "ใช้ได้ในแอป Prune ที่ติดตั้งบน Windows สำเนานี้ไม่สามารถตั้งค่าได้",
        cliMissing: "ไม่พบ prune-cli.cmd ในโฟลเดอร์ของ Prune จึงตั้งค่างานไม่ได้ ติดตั้ง Prune ใหม่เพื่อกู้คืน",
        outOfSync: "งานใน Windows ยังไม่ตรงกับตารางเวลาด้านบน ปิดแล้วเปิดตัวเลือกนี้ใหม่เพื่ออัปเดต",
        taskFailed: (a) => `Windows รายงานข้อผิดพลาด ${a} เมื่อเริ่มงานครั้งล่าสุด`,
        saveFailed: (a) => `เปลี่ยนการตั้งค่านี้ไม่ได้: ${a}`,
        loadFailed: (a) => `อ่านสถานะของงานไม่ได้: ${a}`
      },
      last: {
        clean: (a, b, c) => `การล้างข้อมูลอัตโนมัติครั้งล่าสุด: ${a} — ย้ายแล้ว ${b} เพิ่มพื้นที่ว่าง ${c}`,
        errors: (a, b, c) => `การล้างข้อมูลอัตโนมัติครั้งล่าสุด: ${a} — บางกฎล้มเหลว ย้ายแล้ว ${b} เพิ่มพื้นที่ว่าง ${c}`
      }
    }
  },
  tr: {
    backgroundV3: {
      task: {
        title: "Prune kapalıyken de çalıştır",
        description: "Windows Görev Zamanlayıcı’ya yalnızca hesabınıza ait bir görev ekler; böylece bu zamanlama Prune açık olmasa bile çalışır. Yönetici hakları gerekmez ve parola saklanmaz.",
        detail: "Görev, Prune’un komut satırını çalıştırır (prune-cli clean --preset recommended): yalnızca Prune’un varsayılan olarak işaretlediği kuralları, veri kaybettirenleri asla, ve her zaman dışlamalarınız, korunan yollarınız ve Karantina ayarınızla. Bunu kapatmak veya Prune’u kaldırmak görevi siler.",
        nextRun: (a) => `Sonraki otomatik çalıştırma: ${a}`,
        needsClean: "Önce zamanlamanın temizlik yapmasını ayarlayın. Görev yalnızca temizler.",
        unsupported: "Windows’ta yüklü Prune uygulamasında kullanılabilir. Bu kopya bunu ayarlayamaz.",
        cliMissing: "Prune klasöründe prune-cli.cmd eksik, bu yüzden görev kurulamaz. Geri yüklemek için Prune’u yeniden yükleyin.",
        outOfSync: "Windows’taki görev henüz yukarıdaki zamanlamayla eşleşmiyor. Güncellemek için bunu kapatıp yeniden açın.",
        taskFailed: (a) => `Windows, görev son başladığında ${a} hatasını bildirdi.`,
        saveFailed: (a) => `Bu ayar değiştirilemedi: ${a}`,
        loadFailed: (a) => `Görevin durumu okunamadı: ${a}`
      },
      last: {
        clean: (a, b, c) => `Son otomatik temizlik: ${a} — ${b} taşındı, ${c} boşaltıldı`,
        errors: (a, b, c) => `Son otomatik temizlik: ${a} — bazı kurallar başarısız oldu; ${b} taşındı, ${c} boşaltıldı`
      }
    }
  },
  uk: {
    backgroundV3: {
      task: {
        title: "Запускати й коли Prune закрито",
        description: "Додає завдання до Планувальника завдань Windows лише для вашого облікового запису, щоб цей розклад працював, навіть коли Prune не відкрито. Права адміністратора не потрібні, пароль не зберігається.",
        detail: "Завдання запускає командний рядок Prune (prune-cli clean --preset recommended): лише правила, які Prune позначає за замовчуванням, ніколи ті, що призводять до втрати даних, і завжди з вашими винятками, захищеними шляхами та налаштуванням карантину. Якщо вимкнути це або видалити Prune, завдання буде видалено.",
        nextRun: (a) => `Наступний автоматичний запуск: ${a}`,
        needsClean: "Спочатку задайте для розкладу очищення. Завдання лише очищає.",
        unsupported: "Доступно в установленому застосунку Prune у Windows. Ця копія не може цього налаштувати.",
        cliMissing: "У папці Prune немає prune-cli.cmd, тому завдання не можна створити. Перевстановіть Prune, щоб його відновити.",
        outOfSync: "Завдання у Windows ще не відповідає розкладу вище. Вимкніть і знову ввімкніть цей параметр, щоб оновити його.",
        taskFailed: (a) => `Windows повідомила про помилку ${a} під час останнього запуску завдання.`,
        saveFailed: (a) => `Не вдалося змінити цей параметр: ${a}`,
        loadFailed: (a) => `Не вдалося прочитати стан завдання: ${a}`
      },
      last: {
        clean: (a, b, c) => `Останнє автоматичне очищення: ${a} — переміщено ${b}, звільнено ${c}`,
        errors: (a, b, c) => `Останнє автоматичне очищення: ${a} — деякі правила завершилися помилкою; переміщено ${b}, звільнено ${c}`
      }
    }
  },
  vi: {
    backgroundV3: {
      task: {
        title: "Chạy cả khi Prune đã đóng",
        description: "Thêm một tác vụ vào Windows Task Scheduler, chỉ cho tài khoản của bạn, để lịch này chạy ngay cả khi Prune không mở. Không cần quyền quản trị và không lưu mật khẩu.",
        detail: "Tác vụ chạy dòng lệnh của Prune (prune-cli clean --preset recommended): chỉ các quy tắc Prune chọn mặc định, không bao giờ là những quy tắc làm mất dữ liệu, và luôn tuân theo các mục loại trừ, đường dẫn được bảo vệ và thiết lập Khu cách ly của bạn. Tắt tùy chọn này, hoặc gỡ cài đặt Prune, sẽ xóa tác vụ.",
        nextRun: (a) => `Lần chạy tự động tiếp theo: ${a}`,
        needsClean: "Hãy đặt lịch thành dọn dẹp trước. Tác vụ chỉ dọn dẹp.",
        unsupported: "Có trong ứng dụng Prune đã cài đặt trên Windows. Bản sao này không thể đặt được.",
        cliMissing: "Thiếu prune-cli.cmd trong thư mục của Prune nên không thể thiết lập tác vụ. Hãy cài đặt lại Prune để khôi phục.",
        outOfSync: "Tác vụ trong Windows chưa khớp với lịch ở trên. Hãy tắt rồi bật lại tùy chọn này để cập nhật.",
        taskFailed: (a) => `Windows báo lỗi ${a} ở lần tác vụ khởi động gần nhất.`,
        saveFailed: (a) => `Không thể thay đổi thiết lập này: ${a}`,
        loadFailed: (a) => `Không thể đọc trạng thái của tác vụ: ${a}`
      },
      last: {
        clean: (a, b, c) => `Lần dọn dẹp tự động gần nhất: ${a} — đã chuyển ${b}, đã giải phóng ${c}`,
        errors: (a, b, c) => `Lần dọn dẹp tự động gần nhất: ${a} — một số quy tắc thất bại; đã chuyển ${b}, đã giải phóng ${c}`
      }
    }
  },
  "zh-CN": {
    backgroundV3: {
      task: {
        title: "即使 Prune 已关闭也运行",
        description: "仅为你的账户在 Windows 任务计划程序中添加一个任务，这样即使 Prune 没有打开，此计划也会运行。不需要管理员权限，也不会保存密码。",
        detail: "该任务运行 Prune 的命令行（prune-cli clean --preset recommended）：只包含 Prune 默认勾选的规则，绝不包含会丢失数据的规则，并始终遵守你的排除项、受保护路径和隔离区设置。关闭此选项或卸载 Prune 都会删除该任务。",
        nextRun: (a) => `下次自动运行：${a}`,
        needsClean: "请先将计划的操作设为清理。该任务只执行清理。",
        unsupported: "在 Windows 上已安装的 Prune 应用中可用。此副本无法设置。",
        cliMissing: "Prune 文件夹中缺少 prune-cli.cmd，因此无法设置该任务。请重新安装 Prune 以恢复。",
        outOfSync: "Windows 中的任务尚未与上方的计划一致。关闭后再打开此选项即可更新。",
        taskFailed: (a) => `上次启动该任务时，Windows 报告了错误 ${a}。`,
        saveFailed: (a) => `无法更改此设置：${a}`,
        loadFailed: (a) => `无法读取任务状态：${a}`
      },
      last: {
        clean: (a, b, c) => `上次自动清理：${a} — 已移动 ${b}，已释放 ${c}`,
        errors: (a, b, c) => `上次自动清理：${a} — 部分规则失败；已移动 ${b}，已释放 ${c}`
      }
    }
  },
  "zh-TW": {
    backgroundV3: {
      task: {
        title: "即使 Prune 已關閉也執行",
        description: "僅為你的帳戶在 Windows 工作排程器中新增一個工作，這樣即使 Prune 沒有開啟，此排程也會執行。不需要系統管理員權限，也不會儲存密碼。",
        detail: "該工作會執行 Prune 的命令列（prune-cli clean --preset recommended）：只包含 Prune 預設勾選的規則，絕不包含會遺失資料的規則，並一律遵守你的排除項目、受保護路徑與隔離區設定。關閉此選項或解除安裝 Prune 都會刪除該工作。",
        nextRun: (a) => `下次自動執行：${a}`,
        needsClean: "請先將排程的動作設為清理。該工作只會執行清理。",
        unsupported: "在 Windows 上已安裝的 Prune 應用程式中可用。此副本無法設定。",
        cliMissing: "Prune 資料夾中缺少 prune-cli.cmd，因此無法設定該工作。請重新安裝 Prune 以還原。",
        outOfSync: "Windows 中的工作尚未與上方的排程一致。關閉後再開啟此選項即可更新。",
        taskFailed: (a) => `上次啟動該工作時，Windows 回報了錯誤 ${a}。`,
        saveFailed: (a) => `無法變更此設定：${a}`,
        loadFailed: (a) => `無法讀取工作狀態：${a}`
      },
      last: {
        clean: (a, b, c) => `上次自動清理：${a} — 已移動 ${b}，已釋放 ${c}`,
        errors: (a, b, c) => `上次自動清理：${a} — 部分規則失敗；已移動 ${b}，已釋放 ${c}`
      }
    }
  }
};
