// Dashboard quality-of-life features, all 40 languages: { en: { dashboardQolV3: { ... } }, af: { ... }, ... }.
// Clean recommended, the lifetime freed total, the low-disk warning and Undo after a Quarantine move.
// Merged into the catalog by ../catalog.js. Generated by an out-of-tree script that writes every value
// with JSON.stringify (or an escaped template literal for a function), so quotes and non-ASCII text are
// safe. Counts are written as "Label: count" so no language needs a plural form. Terminology follows
// each language's own Dashboard, Deep Clean and Quarantine strings.
export default {
  en: {
    dashboardQolV3: {
      clean: {
        title: "Clean recommended",
        intro: "Cleans only what Prune marks as recommended, never anything that loses data. You see the total and where it goes before anything is removed.",
        measureFirst: "Nothing has been measured yet. Prune measures first, then asks before it cleans.",
        measure: "Measure and review",
        found: (a) => `Can be cleaned: ${a}`,
        nothing: "Nothing recommended needs cleaning right now.",
        review: "Review and clean",
        confirmQuarantine: (a) => `Move ${a} to Quarantine?`,
        confirmRecycle: (a) => `Move ${a} to the Recycle Bin?`,
        confirmDelete: (a) => `Delete ${a} now? This can't be undone.`,
        progress: (a, b) => `Cleaning… ${a} of ${b}`,
        done: "Done"
      },
      stats: {
        freed: (a, b) => `Prune has freed ${a} since ${b}.`,
        freedNoDate: (a) => `Prune has freed ${a}.`,
        note: "Files moved to Quarantine count once you empty it."
      }
    }
  },
  af: {
    dashboardQolV3: {
      clean: {
        title: "Maak aanbevole items skoon",
        intro: "Maak net skoon wat Prune as aanbeveel merk, nooit iets wat data verloor nie. Jy sien die totaal en waarheen dit gaan voordat iets verwyder word.",
        measureFirst: "Niks is nog gemeet nie. Prune meet eers en vra dan voordat dit skoonmaak.",
        measure: "Meet en hersien",
        found: (a) => `Kan skoongemaak word: ${a}`,
        nothing: "Niks aanbevole hoef nou skoongemaak te word nie.",
        review: "Hersien en maak skoon",
        confirmQuarantine: (a) => `Skuif ${a} na Karantyn?`,
        confirmRecycle: (a) => `Skuif ${a} na die Asblik?`,
        confirmDelete: (a) => `Verwyder ${a} nou? Dit kan nie ongedaan gemaak word nie.`,
        progress: (a, b) => `Maak skoon… ${a} van ${b}`,
        done: "Klaar"
      },
      stats: {
        freed: (a, b) => `Prune het sedert ${b} ${a} vrygemaak.`,
        freedNoDate: (a) => `Prune het ${a} vrygemaak.`,
        note: "Lêers wat na Karantyn geskuif is, tel eers sodra jy dit leegmaak."
      }
    }
  },
  ar: {
    dashboardQolV3: {
      clean: {
        title: "تنظيف الموصى به",
        intro: "ينظّف Prune فقط ما يضعه علامة موصى به، ولا يشمل أي شيء يفقدك بياناتك. سترى الإجمالي ووجهته قبل إزالة أي شيء.",
        measureFirst: "لم يُقَس أي شيء بعد. يقيس Prune أولًا، ثم يسألك قبل أن ينظّف.",
        measure: "قياس ومراجعة",
        found: (a) => `يمكن تنظيفه: ${a}`,
        nothing: "لا يحتاج أي عنصر موصى به إلى التنظيف الآن.",
        review: "مراجعة وتنظيف",
        confirmQuarantine: (a) => `هل تريد نقل ${a} إلى الحجر الصحي؟`,
        confirmRecycle: (a) => `هل تريد نقل ${a} إلى سلة المحذوفات؟`,
        confirmDelete: (a) => `هل تريد حذف ${a} الآن؟ لا يمكن التراجع عن ذلك.`,
        progress: (a, b) => `جارٍ التنظيف… ${a} من ${b}`,
        done: "تم"
      },
      stats: {
        freed: (a, b) => `حرّر Prune ما مقداره ${a} منذ ${b}.`,
        freedNoDate: (a) => `حرّر Prune ما مقداره ${a}.`,
        note: "لا تُحتسب الملفات المنقولة إلى الحجر الصحي إلا بعد إفراغه."
      }
    }
  },
  ca: {
    dashboardQolV3: {
      clean: {
        title: "Neteja el recomanat",
        intro: "Neteja només el que Prune marca com a recomanat, mai res que faci perdre dades. Veus el total i la destinació abans que s'elimini res.",
        measureFirst: "Encara no s'ha mesurat res. Prune mesura primer i després et pregunta abans de netejar.",
        measure: "Mesura i revisa",
        found: (a) => `Es pot netejar: ${a}`,
        nothing: "Ara mateix no cal netejar res del que és recomanat.",
        review: "Revisa i neteja",
        confirmQuarantine: (a) => `Vols moure ${a} a la Quarantena?`,
        confirmRecycle: (a) => `Vols moure ${a} a la Paperera?`,
        confirmDelete: (a) => `Vols eliminar ${a} ara? Això no es pot desfer.`,
        progress: (a, b) => `Netejant… ${a} de ${b}`,
        done: "Fet"
      },
      stats: {
        freed: (a, b) => `Prune ha alliberat ${a} des del ${b}.`,
        freedNoDate: (a) => `Prune ha alliberat ${a}.`,
        note: "Els fitxers moguts a la Quarantena només es compten quan la buides."
      }
    }
  },
  cs: {
    dashboardQolV3: {
      clean: {
        title: "Vyčistit doporučené",
        intro: "Čistí jen to, co Prune označuje jako doporučené, nikdy nic, při čem by se ztratila data. Celkovou velikost i cíl uvidíte dřív, než se cokoli odstraní.",
        measureFirst: "Zatím nic nebylo změřeno. Prune nejdřív změří a před čištěním se zeptá.",
        measure: "Změřit a zkontrolovat",
        found: (a) => `Lze vyčistit: ${a}`,
        nothing: "Nic z doporučeného teď není potřeba čistit.",
        review: "Zkontrolovat a vyčistit",
        confirmQuarantine: (a) => `Přesunout ${a} do karantény?`,
        confirmRecycle: (a) => `Přesunout ${a} do koše?`,
        confirmDelete: (a) => `Smazat ${a} hned? Nelze to vrátit zpět.`,
        progress: (a, b) => `Čištění… ${a} z ${b}`,
        done: "Hotovo"
      },
      stats: {
        freed: (a, b) => `Prune od ${b} uvolnil ${a}.`,
        freedNoDate: (a) => `Prune uvolnil ${a}.`,
        note: "Soubory přesunuté do karantény se započítají, až karanténu vyprázdníte."
      }
    }
  },
  cy: {
    dashboardQolV3: {
      clean: {
        title: "Glanhau'r hyn a argymhellir",
        intro: "Dim ond yr hyn y mae Prune yn ei farcio fel un a argymhellir y mae'n ei lanhau, byth unrhyw beth sy'n colli data. Fe welwch y cyfanswm a ble mae'n mynd cyn i unrhyw beth gael ei dynnu.",
        measureFirst: "Nid oes dim wedi'i fesur eto. Mae Prune yn mesur yn gyntaf, yna'n gofyn cyn glanhau.",
        measure: "Mesur ac adolygu",
        found: (a) => `Gellir ei lanhau: ${a}`,
        nothing: "Nid oes angen glanhau dim a argymhellir ar hyn o bryd.",
        review: "Adolygu a glanhau",
        confirmQuarantine: (a) => `Symud ${a} i'r Cwarantin?`,
        confirmRecycle: (a) => `Symud ${a} i'r Bin Ailgylchu?`,
        confirmDelete: (a) => `Dileu ${a} nawr? Ni ellir dadwneud hyn.`,
        progress: (a, b) => `Yn glanhau… ${a} o ${b}`,
        done: "Wedi gorffen"
      },
      stats: {
        freed: (a, b) => `Mae Prune wedi rhyddhau ${a} ers ${b}.`,
        freedNoDate: (a) => `Mae Prune wedi rhyddhau ${a}.`,
        note: "Mae ffeiliau a symudir i'r Cwarantin yn cyfrif unwaith y byddwch yn ei wacáu."
      }
    }
  },
  da: {
    dashboardQolV3: {
      clean: {
        title: "Rens det anbefalede",
        intro: "Renser kun det, Prune markerer som anbefalet, og aldrig noget, der mister data. Du ser samlet størrelse og destination, før noget fjernes.",
        measureFirst: "Intet er målt endnu. Prune måler først og spørger, før det renser.",
        measure: "Mål og gennemgå",
        found: (a) => `Kan renses: ${a}`,
        nothing: "Intet anbefalet skal renses lige nu.",
        review: "Gennemgå og rens",
        confirmQuarantine: (a) => `Flyt ${a} til karantæne?`,
        confirmRecycle: (a) => `Flyt ${a} til Papirkurven?`,
        confirmDelete: (a) => `Slet ${a} nu? Det kan ikke fortrydes.`,
        progress: (a, b) => `Renser… ${a} af ${b}`,
        done: "Færdig"
      },
      stats: {
        freed: (a, b) => `Prune har frigjort ${a} siden ${b}.`,
        freedNoDate: (a) => `Prune har frigjort ${a}.`,
        note: "Filer, der er flyttet til karantæne, tæller først, når du tømmer den."
      }
    }
  },
  de: {
    dashboardQolV3: {
      clean: {
        title: "Empfohlenes bereinigen",
        intro: "Bereinigt nur, was Prune als empfohlen markiert, nie etwas, bei dem Daten verloren gehen. Sie sehen die Gesamtgröße und das Ziel, bevor etwas entfernt wird.",
        measureFirst: "Noch nichts wurde gemessen. Prune misst zuerst und fragt dann nach, bevor es bereinigt.",
        measure: "Messen und prüfen",
        found: (a) => `Kann bereinigt werden: ${a}`,
        nothing: "Derzeit muss nichts Empfohlenes bereinigt werden.",
        review: "Prüfen und bereinigen",
        confirmQuarantine: (a) => `${a} in die Quarantäne verschieben?`,
        confirmRecycle: (a) => `${a} in den Papierkorb verschieben?`,
        confirmDelete: (a) => `${a} sofort löschen? Das lässt sich nicht rückgängig machen.`,
        progress: (a, b) => `Bereinigung läuft… ${a} von ${b}`,
        done: "Fertig"
      },
      stats: {
        freed: (a, b) => `Prune hat seit ${b} ${a} freigegeben.`,
        freedNoDate: (a) => `Prune hat ${a} freigegeben.`,
        note: "In die Quarantäne verschobene Dateien zählen erst, wenn du sie leerst."
      }
    }
  },
  el: {
    dashboardQolV3: {
      clean: {
        title: "Καθαρισμός προτεινόμενων",
        intro: "Καθαρίζει μόνο όσα το Prune επισημαίνει ως προτεινόμενα, ποτέ κάτι που χάνει δεδομένα. Βλέπετε το σύνολο και τον προορισμό πριν αφαιρεθεί οτιδήποτε.",
        measureFirst: "Δεν έχει μετρηθεί ακόμη τίποτα. Το Prune μετρά πρώτα και ρωτά πριν καθαρίσει.",
        measure: "Μέτρηση και έλεγχος",
        found: (a) => `Μπορεί να καθαριστεί: ${a}`,
        nothing: "Προς το παρόν δεν χρειάζεται να καθαριστεί κάτι προτεινόμενο.",
        review: "Έλεγχος και καθαρισμός",
        confirmQuarantine: (a) => `Μετακίνηση ${a} σε καραντίνα;`,
        confirmRecycle: (a) => `Μετακίνηση ${a} στον Κάδο Ανακύκλωσης;`,
        confirmDelete: (a) => `Διαγραφή ${a} τώρα; Η ενέργεια δεν αναιρείται.`,
        progress: (a, b) => `Καθαρισμός… ${a} από ${b}`,
        done: "Τέλος"
      },
      stats: {
        freed: (a, b) => `Το Prune έχει ελευθερώσει ${a} από τις ${b}.`,
        freedNoDate: (a) => `Το Prune έχει ελευθερώσει ${a}.`,
        note: "Τα αρχεία που μετακινούνται στην Καραντίνα προσμετρώνται μόλις την αδειάσετε."
      }
    }
  },
  es: {
    dashboardQolV3: {
      clean: {
        title: "Limpiar lo recomendado",
        intro: "Limpia solo lo que Prune marca como recomendado, nunca nada que pierda datos. Ves el total y el destino antes de que se elimine nada.",
        measureFirst: "Todavía no se ha medido nada. Prune mide primero y te pregunta antes de limpiar.",
        measure: "Medir y revisar",
        found: (a) => `Se puede limpiar: ${a}`,
        nothing: "Ahora mismo no hace falta limpiar nada de lo recomendado.",
        review: "Revisar y limpiar",
        confirmQuarantine: (a) => `¿Mover ${a} a cuarentena?`,
        confirmRecycle: (a) => `¿Mover ${a} a la Papelera de reciclaje?`,
        confirmDelete: (a) => `¿Eliminar ${a} ahora? No se puede deshacer.`,
        progress: (a, b) => `Limpiando… ${a} de ${b}`,
        done: "Listo"
      },
      stats: {
        freed: (a, b) => `Prune ha liberado ${a} desde el ${b}.`,
        freedNoDate: (a) => `Prune ha liberado ${a}.`,
        note: "Los archivos movidos a Cuarentena cuentan cuando la vacías."
      }
    }
  },
  et: {
    dashboardQolV3: {
      clean: {
        title: "Puhasta soovitatud",
        intro: "Puhastab ainult seda, mida Prune soovitatuks märgib, mitte kunagi midagi, mis andmeid kaotab. Näed kogusuurust ja sihtkohta enne, kui midagi eemaldatakse.",
        measureFirst: "Midagi pole veel mõõdetud. Prune mõõdab kõigepealt ja küsib enne puhastamist.",
        measure: "Mõõda ja vaata üle",
        found: (a) => `Saab puhastada: ${a}`,
        nothing: "Praegu ei vaja soovitatud üksused puhastamist.",
        review: "Vaata üle ja puhasta",
        confirmQuarantine: (a) => `Teisaldada ${a} karantiini?`,
        confirmRecycle: (a) => `Teisaldada ${a} prügikasti?`,
        confirmDelete: (a) => `Kustutada ${a} kohe? Seda ei saa tagasi võtta.`,
        progress: (a, b) => `Puhastamine… ${a} / ${b}`,
        done: "Valmis"
      },
      stats: {
        freed: (a, b) => `Prune on alates ${b} vabastanud ${a}.`,
        freedNoDate: (a) => `Prune on vabastanud ${a}.`,
        note: "Karantiini teisaldatud failid lähevad arvesse alles siis, kui karantiini tühjendad."
      }
    }
  },
  fi: {
    dashboardQolV3: {
      clean: {
        title: "Puhdista suositellut",
        intro: "Puhdistaa vain sen, minkä Prune merkitsee suositelluksi, ei koskaan mitään, mikä menettää tietoja. Näet kokonaismäärän ja kohteen ennen kuin mitään poistetaan.",
        measureFirst: "Mitään ei ole vielä mitattu. Prune mittaa ensin ja kysyy ennen puhdistusta.",
        measure: "Mittaa ja tarkista",
        found: (a) => `Voidaan puhdistaa: ${a}`,
        nothing: "Mitään suositeltua ei tarvitse puhdistaa juuri nyt.",
        review: "Tarkista ja puhdista",
        confirmQuarantine: (a) => `Siirretäänkö ${a} karanteeniin?`,
        confirmRecycle: (a) => `Siirretäänkö ${a} roskakoriin?`,
        confirmDelete: (a) => `Poistetaanko ${a} nyt? Tätä ei voi peruuttaa.`,
        progress: (a, b) => `Puhdistetaan… ${a} / ${b}`,
        done: "Valmis"
      },
      stats: {
        freed: (a, b) => `Prune on vapauttanut ${a} päivästä ${b} lähtien.`,
        freedNoDate: (a) => `Prune on vapauttanut ${a}.`,
        note: "Karanteeniin siirretyt tiedostot lasketaan vasta, kun tyhjennät karanteenin."
      }
    }
  },
  fr: {
    dashboardQolV3: {
      clean: {
        title: "Nettoyer le recommandé",
        intro: "Nettoie uniquement ce que Prune marque comme recommandé, jamais rien qui fasse perdre des données. Vous voyez le total et la destination avant que quoi que ce soit soit supprimé.",
        measureFirst: "Rien n'a encore été mesuré. Prune mesure d'abord, puis demande avant de nettoyer.",
        measure: "Mesurer et vérifier",
        found: (a) => `Peut être nettoyé : ${a}`,
        nothing: "Rien de recommandé n'a besoin d'être nettoyé pour le moment.",
        review: "Vérifier et nettoyer",
        confirmQuarantine: (a) => `Déplacer ${a} vers la quarantaine ?`,
        confirmRecycle: (a) => `Déplacer ${a} vers la Corbeille ?`,
        confirmDelete: (a) => `Supprimer ${a} maintenant ? C'est irréversible.`,
        progress: (a, b) => `Nettoyage… ${a} sur ${b}`,
        done: "Terminé"
      },
      stats: {
        freed: (a, b) => `Prune a libéré ${a} depuis le ${b}.`,
        freedNoDate: (a) => `Prune a libéré ${a}.`,
        note: "Les fichiers déplacés vers la Quarantaine ne comptent qu'une fois celle-ci vidée."
      }
    }
  },
  he: {
    dashboardQolV3: {
      clean: {
        title: "נקה את המומלץ",
        intro: "מנקה רק את מה ש-Prune מסמן כמומלץ, ואף פעם לא משהו שגורם לאובדן נתונים. תראה את הסכום ואת היעד לפני שמשהו יוסר.",
        measureFirst: "עדיין לא נמדד דבר. Prune מודד קודם ושואל לפני הניקוי.",
        measure: "מדוד ובדוק",
        found: (a) => `אפשר לנקות: ${a}`,
        nothing: "כרגע אין צורך לנקות דבר מהמומלץ.",
        review: "בדוק ונקה",
        confirmQuarantine: (a) => `להעביר ${a} להסגר?`,
        confirmRecycle: (a) => `להעביר ${a} לסל המיחזור?`,
        confirmDelete: (a) => `למחוק ${a} עכשיו? אי אפשר לבטל את הפעולה.`,
        progress: (a, b) => `מנקה… ${a} מתוך ${b}`,
        done: "סיום"
      },
      stats: {
        freed: (a, b) => `Prune שחרר ${a} מאז ${b}.`,
        freedNoDate: (a) => `Prune שחרר ${a}.`,
        note: "קבצים שהועברו להסגר נספרים רק לאחר שתרוקן אותו."
      }
    }
  },
  hu: {
    dashboardQolV3: {
      clean: {
        title: "Ajánlottak tisztítása",
        intro: "Csak azt tisztítja, amit a Prune ajánlottként jelöl, soha nem olyat, ami adatvesztéssel jár. Mielőtt bármi törlődne, látod az összeget és a célt.",
        measureFirst: "Még semmi sincs megmérve. A Prune először mér, majd tisztítás előtt rákérdez.",
        measure: "Mérés és áttekintés",
        found: (a) => `Tisztítható: ${a}`,
        nothing: "Jelenleg semmi ajánlottat nem kell tisztítani.",
        review: "Áttekintés és tisztítás",
        confirmQuarantine: (a) => `Áthelyezed a(z) ${a} mennyiséget a karanténba?`,
        confirmRecycle: (a) => `Áthelyezed a(z) ${a} mennyiséget a Lomtárba?`,
        confirmDelete: (a) => `Törlöd most a(z) ${a} mennyiséget? Ez nem vonható vissza.`,
        progress: (a, b) => `Tisztítás… ${a} / ${b}`,
        done: "Kész"
      },
      stats: {
        freed: (a, b) => `A Prune ${b} óta ${a} szabadított fel.`,
        freedNoDate: (a) => `A Prune ${a} szabadított fel.`,
        note: "A karanténba helyezett fájlok csak a karantén kiürítése után számítanak bele."
      }
    }
  },
  id: {
    dashboardQolV3: {
      clean: {
        title: "Bersihkan yang direkomendasikan",
        intro: "Hanya membersihkan yang ditandai Prune sebagai direkomendasikan, tidak pernah yang menghilangkan data. Anda melihat total dan tujuannya sebelum apa pun dihapus.",
        measureFirst: "Belum ada yang diukur. Prune mengukur terlebih dahulu, lalu bertanya sebelum membersihkan.",
        measure: "Ukur dan tinjau",
        found: (a) => `Dapat dibersihkan: ${a}`,
        nothing: "Saat ini tidak ada yang direkomendasikan yang perlu dibersihkan.",
        review: "Tinjau dan bersihkan",
        confirmQuarantine: (a) => `Pindahkan ${a} ke Karantina?`,
        confirmRecycle: (a) => `Pindahkan ${a} ke Recycle Bin?`,
        confirmDelete: (a) => `Hapus ${a} sekarang? Tindakan ini tidak bisa dibatalkan.`,
        progress: (a, b) => `Membersihkan… ${a} dari ${b}`,
        done: "Selesai"
      },
      stats: {
        freed: (a, b) => `Prune telah membebaskan ${a} sejak ${b}.`,
        freedNoDate: (a) => `Prune telah membebaskan ${a}.`,
        note: "File yang dipindahkan ke Karantina baru dihitung setelah Anda mengosongkannya."
      }
    }
  },
  is: {
    dashboardQolV3: {
      clean: {
        title: "Hreinsa það sem mælt er með",
        intro: "Hreinsar aðeins það sem Prune merkir sem ráðlagt, aldrei neitt sem glatar gögnum. Þú sérð heildarstærð og áfangastað áður en nokkuð er fjarlægt.",
        measureFirst: "Ekkert hefur verið mælt enn. Prune mælir fyrst og spyr áður en það hreinsar.",
        measure: "Mæla og yfirfara",
        found: (a) => `Hægt að hreinsa: ${a}`,
        nothing: "Ekkert af því sem mælt er með þarf hreinsun núna.",
        review: "Yfirfara og hreinsa",
        confirmQuarantine: (a) => `Flytja ${a} í sóttkví?`,
        confirmRecycle: (a) => `Flytja ${a} í ruslafötuna?`,
        confirmDelete: (a) => `Eyða ${a} núna? Ekki er hægt að afturkalla þetta.`,
        progress: (a, b) => `Hreinsa… ${a} af ${b}`,
        done: "Lokið"
      },
      stats: {
        freed: (a, b) => `Prune hefur losað ${a} frá ${b}.`,
        freedNoDate: (a) => `Prune hefur losað ${a}.`,
        note: "Skrár sem fluttar eru í sóttkví teljast með þegar þú tæmir hana."
      }
    }
  },
  it: {
    dashboardQolV3: {
      clean: {
        title: "Pulisci i consigliati",
        intro: "Pulisce solo ciò che Prune contrassegna come consigliato, mai nulla che faccia perdere dati. Vedi il totale e la destinazione prima che venga rimosso qualcosa.",
        measureFirst: "Non è stato ancora misurato nulla. Prune misura prima e chiede conferma prima di pulire.",
        measure: "Misura e controlla",
        found: (a) => `Si può pulire: ${a}`,
        nothing: "Al momento non c'è nulla di consigliato da pulire.",
        review: "Controlla e pulisci",
        confirmQuarantine: (a) => `Spostare ${a} in quarantena?`,
        confirmRecycle: (a) => `Spostare ${a} nel Cestino?`,
        confirmDelete: (a) => `Eliminare subito ${a}? Non si può annullare.`,
        progress: (a, b) => `Pulizia in corso… ${a} di ${b}`,
        done: "Fatto"
      },
      stats: {
        freed: (a, b) => `Prune ha liberato ${a} dal ${b}.`,
        freedNoDate: (a) => `Prune ha liberato ${a}.`,
        note: "I file spostati in Quarantena vengono conteggiati quando la svuoti."
      }
    }
  },
  ja: {
    dashboardQolV3: {
      clean: {
        title: "推奨項目をクリーン",
        intro: "Prune が推奨としている項目だけをクリーンし、データを失う項目は含めません。何かを削除する前に、合計サイズと移動先が表示されます。",
        measureFirst: "まだ何も測定していません。Prune はまず測定し、クリーンの前に確認します。",
        measure: "測定して確認",
        found: (a) => `クリーン可能: ${a}`,
        nothing: "今すぐクリーンが必要な推奨項目はありません。",
        review: "確認してクリーン",
        confirmQuarantine: (a) => `${a} を隔離に移動しますか?`,
        confirmRecycle: (a) => `${a} をごみ箱に移動しますか?`,
        confirmDelete: (a) => `${a} を今すぐ削除しますか? 元に戻せません。`,
        progress: (a, b) => `クリーン中… ${a} / ${b}`,
        done: "完了"
      },
      stats: {
        freed: (a, b) => `Prune は ${b} 以降、${a} を解放しました。`,
        freedNoDate: (a) => `Prune は ${a} を解放しました。`,
        note: "隔離に移動したファイルは、隔離を空にした時点で加算されます。"
      }
    }
  },
  ko: {
    dashboardQolV3: {
      clean: {
        title: "권장 항목 정리",
        intro: "Prune이 권장으로 표시한 항목만 정리하며, 데이터를 잃게 되는 항목은 절대 포함하지 않습니다. 무엇이든 제거하기 전에 총 용량과 이동 위치를 확인할 수 있습니다.",
        measureFirst: "아직 측정된 것이 없습니다. Prune은 먼저 측정한 다음 정리하기 전에 확인합니다.",
        measure: "측정하고 검토",
        found: (a) => `정리 가능: ${a}`,
        nothing: "지금 정리가 필요한 권장 항목이 없습니다.",
        review: "검토하고 정리",
        confirmQuarantine: (a) => `${a}을(를) 격리로 이동하시겠습니까?`,
        confirmRecycle: (a) => `${a}을(를) 휴지통으로 이동하시겠습니까?`,
        confirmDelete: (a) => `${a}을(를) 지금 삭제하시겠습니까? 되돌릴 수 없습니다.`,
        progress: (a, b) => `정리 중… ${a}/${b}`,
        done: "완료"
      },
      stats: {
        freed: (a, b) => `Prune은 ${b} 이후 ${a}을(를) 확보했습니다.`,
        freedNoDate: (a) => `Prune은 ${a}을(를) 확보했습니다.`,
        note: "격리로 이동한 파일은 격리를 비운 뒤에 합산됩니다."
      }
    }
  },
  lt: {
    dashboardQolV3: {
      clean: {
        title: "Valyti rekomenduojamus",
        intro: "Valo tik tai, ką Prune pažymi kaip rekomenduojamą, niekada nieko, kas prarastų duomenis. Prieš ką nors pašalinant matysite bendrą dydį ir paskirtį.",
        measureFirst: "Dar niekas nematuota. Prune pirmiausia išmatuoja, o prieš valydama paklausia.",
        measure: "Išmatuoti ir peržiūrėti",
        found: (a) => `Galima išvalyti: ${a}`,
        nothing: "Šiuo metu nieko rekomenduojamo valyti nereikia.",
        review: "Peržiūrėti ir valyti",
        confirmQuarantine: (a) => `Perkelti ${a} į karantiną?`,
        confirmRecycle: (a) => `Perkelti ${a} į šiukšlinę?`,
        confirmDelete: (a) => `Ištrinti ${a} dabar? To atšaukti nebus galima.`,
        progress: (a, b) => `Valoma… ${a} iš ${b}`,
        done: "Atlikta"
      },
      stats: {
        freed: (a, b) => `Nuo ${b} Prune atlaisvino ${a}.`,
        freedNoDate: (a) => `Prune atlaisvino ${a}.`,
        note: "Į karantiną perkelti failai įskaičiuojami, kai ištuštinate karantiną."
      }
    }
  },
  ms: {
    dashboardQolV3: {
      clean: {
        title: "Bersihkan yang disyorkan",
        intro: "Hanya membersihkan apa yang ditandakan Prune sebagai disyorkan, tidak pernah yang menyebabkan kehilangan data. Anda melihat jumlah dan destinasinya sebelum apa-apa dialih keluar.",
        measureFirst: "Belum ada yang diukur. Prune mengukur dahulu, kemudian bertanya sebelum membersihkan.",
        measure: "Ukur dan semak",
        found: (a) => `Boleh dibersihkan: ${a}`,
        nothing: "Tiada yang disyorkan perlu dibersihkan sekarang.",
        review: "Semak dan bersihkan",
        confirmQuarantine: (a) => `Alih ${a} ke Kuarantin?`,
        confirmRecycle: (a) => `Alih ${a} ke Tong Kitar Semula?`,
        confirmDelete: (a) => `Padam ${a} sekarang? Ini tidak boleh dibuat asal.`,
        progress: (a, b) => `Membersihkan… ${a} daripada ${b}`,
        done: "Selesai"
      },
      stats: {
        freed: (a, b) => `Prune telah membebaskan ${a} sejak ${b}.`,
        freedNoDate: (a) => `Prune telah membebaskan ${a}.`,
        note: "Fail yang dialihkan ke Kuarantin hanya dikira apabila anda mengosongkannya."
      }
    }
  },
  nb: {
    dashboardQolV3: {
      clean: {
        title: "Rens det anbefalte",
        intro: "Renser bare det Prune merker som anbefalt, aldri noe som mister data. Du ser totalen og hvor det havner før noe fjernes.",
        measureFirst: "Ingenting er målt ennå. Prune måler først og spør før det renser.",
        measure: "Mål og gå gjennom",
        found: (a) => `Kan renses: ${a}`,
        nothing: "Ingenting anbefalt trenger rensing akkurat nå.",
        review: "Gå gjennom og rens",
        confirmQuarantine: (a) => `Flytte ${a} til karantene?`,
        confirmRecycle: (a) => `Flytte ${a} til papirkurven?`,
        confirmDelete: (a) => `Slette ${a} nå? Dette kan ikke angres.`,
        progress: (a, b) => `Renser… ${a} av ${b}`,
        done: "Ferdig"
      },
      stats: {
        freed: (a, b) => `Prune har frigjort ${a} siden ${b}.`,
        freedNoDate: (a) => `Prune har frigjort ${a}.`,
        note: "Filer som er flyttet til karantene, teller først når du tømmer den."
      }
    }
  },
  nl: {
    dashboardQolV3: {
      clean: {
        title: "Aanbevolen opschonen",
        intro: "Ruimt alleen op wat Prune als aanbevolen markeert, nooit iets waarbij gegevens verloren gaan. U ziet het totaal en de bestemming voordat er iets wordt verwijderd.",
        measureFirst: "Er is nog niets gemeten. Prune meet eerst en vraagt daarna bevestiging voordat het opschoont.",
        measure: "Meten en controleren",
        found: (a) => `Kan worden opgeschoond: ${a}`,
        nothing: "Er hoeft op dit moment niets aanbevolen te worden opgeschoond.",
        review: "Controleren en opschonen",
        confirmQuarantine: (a) => `${a} naar Quarantaine verplaatsen?`,
        confirmRecycle: (a) => `${a} naar de Prullenbak verplaatsen?`,
        confirmDelete: (a) => `${a} nu verwijderen? Dit kan niet ongedaan worden gemaakt.`,
        progress: (a, b) => `Opschonen… ${a} van ${b}`,
        done: "Klaar"
      },
      stats: {
        freed: (a, b) => `Prune heeft sinds ${b} ${a} vrijgemaakt.`,
        freedNoDate: (a) => `Prune heeft ${a} vrijgemaakt.`,
        note: "Bestanden die naar Quarantaine zijn verplaatst, tellen pas mee zodra je die leegmaakt."
      }
    }
  },
  pl: {
    dashboardQolV3: {
      clean: {
        title: "Wyczyść zalecane",
        intro: "Czyści tylko to, co Prune oznacza jako zalecane, nigdy niczego, co powoduje utratę danych. Przed usunięciem czegokolwiek zobaczysz łączny rozmiar i miejsce docelowe.",
        measureFirst: "Nic jeszcze nie zostało zmierzone. Prune najpierw mierzy, a przed czyszczeniem pyta.",
        measure: "Zmierz i sprawdź",
        found: (a) => `Można wyczyścić: ${a}`,
        nothing: "Obecnie nic zalecanego nie wymaga czyszczenia.",
        review: "Sprawdź i wyczyść",
        confirmQuarantine: (a) => `Przenieść ${a} do kwarantanny?`,
        confirmRecycle: (a) => `Przenieść ${a} do Kosza?`,
        confirmDelete: (a) => `Usunąć ${a} teraz? Nie można tego cofnąć.`,
        progress: (a, b) => `Czyszczenie… ${a} z ${b}`,
        done: "Gotowe"
      },
      stats: {
        freed: (a, b) => `Prune zwolnił ${a} od ${b}.`,
        freedNoDate: (a) => `Prune zwolnił ${a}.`,
        note: "Pliki przeniesione do kwarantanny są wliczane dopiero po jej opróżnieniu."
      }
    }
  },
  ps: {
    dashboardQolV3: {
      clean: {
        title: "سپارښتل شوي پاک کړئ",
        intro: "یوازې هغه څه پاکوي چې Prune یې د سپارښتل شوي په توګه نښه کوي، هیڅکله هغه څه نه چې معلومات له لاسه ورکوي. مخکې له دې چې څه لرې شي، مجموعه او منزل وینئ.",
        measureFirst: "تر اوسه هیڅ نه دي اندازه شوي. Prune لومړی اندازه کوي، بیا د پاکولو مخکې پوښتنه کوي.",
        measure: "اندازه کړئ او وګورئ",
        found: (a) => `پاکیدلی شي: ${a}`,
        nothing: "همدا اوس هیڅ سپارښتل شوی د پاکولو اړتیا نه لري.",
        review: "وګورئ او پاک کړئ",
        confirmQuarantine: (a) => `${a} قرنطین ته ولیږدول شي؟`,
        confirmRecycle: (a) => `${a} ردي بکس ته ولیږدول شي؟`,
        confirmDelete: (a) => `${a} همدا اوس ړنګ شي؟ دا بیرته نشي راتلی.`,
        progress: (a, b) => `پاکول کیږي… ${a} له ${b} څخه`,
        done: "بشپړ شو"
      },
      stats: {
        freed: (a, b) => `Prune له ${b} راهیسې ${a} خلاص کړل.`,
        freedNoDate: (a) => `Prune ${a} خلاص کړل.`,
        note: "هغه فایلونه چې قرنطین ته لیږدول کیږي، یوازې هغه وخت شمیرل کیږي چې قرنطین خالي کړئ."
      }
    }
  },
  "pt-BR": {
    dashboardQolV3: {
      clean: {
        title: "Limpar o recomendado",
        intro: "Limpa apenas o que o Prune marca como recomendado, nunca algo que perca dados. Você vê o total e o destino antes de qualquer coisa ser removida.",
        measureFirst: "Nada foi medido ainda. O Prune mede primeiro e pergunta antes de limpar.",
        measure: "Medir e revisar",
        found: (a) => `Pode ser limpo: ${a}`,
        nothing: "Nada recomendado precisa ser limpo agora.",
        review: "Revisar e limpar",
        confirmQuarantine: (a) => `Mover ${a} para a Quarentena?`,
        confirmRecycle: (a) => `Mover ${a} para a Lixeira?`,
        confirmDelete: (a) => `Excluir ${a} agora? Isso não pode ser desfeito.`,
        progress: (a, b) => `Limpando… ${a} de ${b}`,
        done: "Concluído"
      },
      stats: {
        freed: (a, b) => `O Prune liberou ${a} desde ${b}.`,
        freedNoDate: (a) => `O Prune liberou ${a}.`,
        note: "Os arquivos movidos para a Quarentena só contam quando você a esvazia."
      }
    }
  },
  pt: {
    dashboardQolV3: {
      clean: {
        title: "Limpar o recomendado",
        intro: "Limpa apenas o que o Prune marca como recomendado, nunca algo que perca dados. Vê o total e o destino antes de qualquer coisa ser removida.",
        measureFirst: "Ainda nada foi medido. O Prune mede primeiro e pergunta antes de limpar.",
        measure: "Medir e rever",
        found: (a) => `Pode ser limpo: ${a}`,
        nothing: "Nada recomendado precisa de ser limpo neste momento.",
        review: "Rever e limpar",
        confirmQuarantine: (a) => `Mover ${a} para a Quarentena?`,
        confirmRecycle: (a) => `Enviar ${a} para a Reciclagem?`,
        confirmDelete: (a) => `Eliminar ${a} agora? Isto não pode ser desfeito.`,
        progress: (a, b) => `A limpar… ${a} de ${b}`,
        done: "Concluído"
      },
      stats: {
        freed: (a, b) => `O Prune libertou ${a} desde ${b}.`,
        freedNoDate: (a) => `O Prune libertou ${a}.`,
        note: "Os ficheiros movidos para a Quarentena só contam quando a esvaziar."
      }
    }
  },
  ro: {
    dashboardQolV3: {
      clean: {
        title: "Curăță ce este recomandat",
        intro: "Curăță doar ce marchează Prune ca recomandat, niciodată ceva care pierde date. Vezi totalul și destinația înainte de a fi eliminat ceva.",
        measureFirst: "Încă nu s-a măsurat nimic. Prune măsoară mai întâi, apoi întreabă înainte să curețe.",
        measure: "Măsoară și verifică",
        found: (a) => `Se poate curăța: ${a}`,
        nothing: "Momentan nu trebuie curățat nimic din ce este recomandat.",
        review: "Verifică și curăță",
        confirmQuarantine: (a) => `Muți ${a} în carantină?`,
        confirmRecycle: (a) => `Muți ${a} în Coșul de reciclare?`,
        confirmDelete: (a) => `Ștergi ${a} acum? Nu se poate anula.`,
        progress: (a, b) => `Se curăță… ${a} din ${b}`,
        done: "Gata"
      },
      stats: {
        freed: (a, b) => `Prune a eliberat ${a} din ${b}.`,
        freedNoDate: (a) => `Prune a eliberat ${a}.`,
        note: "Fișierele mutate în Carantină se numără abia după ce golești Carantina."
      }
    }
  },
  ru: {
    dashboardQolV3: {
      clean: {
        title: "Очистить рекомендованное",
        intro: "Очищает только то, что Prune помечает как рекомендованное, и никогда ничего, что приводит к потере данных. Перед удалением вы увидите общий размер и место назначения.",
        measureFirst: "Пока ничего не измерено. Prune сначала измеряет, а перед очисткой спрашивает.",
        measure: "Измерить и проверить",
        found: (a) => `Можно очистить: ${a}`,
        nothing: "Сейчас ничего из рекомендованного очищать не нужно.",
        review: "Проверить и очистить",
        confirmQuarantine: (a) => `Переместить ${a} в карантин?`,
        confirmRecycle: (a) => `Переместить ${a} в Корзину?`,
        confirmDelete: (a) => `Удалить ${a} сейчас? Отменить это нельзя.`,
        progress: (a, b) => `Очистка… ${a} из ${b}`,
        done: "Готово"
      },
      stats: {
        freed: (a, b) => `Prune освободил ${a} с ${b}.`,
        freedNoDate: (a) => `Prune освободил ${a}.`,
        note: "Файлы, перемещённые в карантин, учитываются, когда вы очистите карантин."
      }
    }
  },
  sk: {
    dashboardQolV3: {
      clean: {
        title: "Vyčistiť odporúčané",
        intro: "Čistí iba to, čo Prune označuje ako odporúčané, nikdy nič, pri čom by sa stratili údaje. Celkovú veľkosť a cieľ uvidíte skôr, než sa čokoľvek odstráni.",
        measureFirst: "Zatiaľ nič nebolo zmerané. Prune najprv zmeria a pred čistením sa opýta.",
        measure: "Zmerať a skontrolovať",
        found: (a) => `Možno vyčistiť: ${a}`,
        nothing: "Nič z odporúčaného teraz netreba čistiť.",
        review: "Skontrolovať a vyčistiť",
        confirmQuarantine: (a) => `Presunúť ${a} do karantény?`,
        confirmRecycle: (a) => `Presunúť ${a} do koša?`,
        confirmDelete: (a) => `Odstrániť ${a} hneď? Nemožno to vrátiť.`,
        progress: (a, b) => `Čistenie… ${a} z ${b}`,
        done: "Hotovo"
      },
      stats: {
        freed: (a, b) => `Prune od ${b} uvoľnil ${a}.`,
        freedNoDate: (a) => `Prune uvoľnil ${a}.`,
        note: "Súbory presunuté do karantény sa započítajú, až keď karanténu vyprázdnite."
      }
    }
  },
  sq: {
    dashboardQolV3: {
      clean: {
        title: "Pastro të rekomanduarat",
        intro: "Pastron vetëm atë që Prune e shënon si të rekomanduar, kurrë diçka që humb të dhëna. E shihni totalin dhe destinacionin përpara se të hiqet gjë.",
        measureFirst: "Ende nuk është matur asgjë. Prune mat së pari, pastaj pyet përpara se të pastrojë.",
        measure: "Mat dhe rishiko",
        found: (a) => `Mund të pastrohet: ${a}`,
        nothing: "Tani për tani asgjë e rekomanduar nuk ka nevojë për pastrim.",
        review: "Rishiko dhe pastro",
        confirmQuarantine: (a) => `Të zhvendoset ${a} në Karantinë?`,
        confirmRecycle: (a) => `Të zhvendoset ${a} në Koshin e Riciklimit?`,
        confirmDelete: (a) => `Të fshihet ${a} tani? Kjo nuk mund të zhbëhet.`,
        progress: (a, b) => `Po pastrohet… ${a} nga ${b}`,
        done: "U krye"
      },
      stats: {
        freed: (a, b) => `Prune ka liruar ${a} që nga ${b}.`,
        freedNoDate: (a) => `Prune ka liruar ${a}.`,
        note: "Skedarët e zhvendosur në Karantinë llogariten sapo ta zbrazni."
      }
    }
  },
  sr: {
    dashboardQolV3: {
      clean: {
        title: "Очисти препоручено",
        intro: "Чисти само оно што Prune означава као препоручено, никада ништа што губи податке. Пре него што се било шта уклони, видите укупну величину и одредиште.",
        measureFirst: "Још ништа није измерено. Prune прво мери, а пре чишћења пита.",
        measure: "Измери и прегледај",
        found: (a) => `Може се очистити: ${a}`,
        nothing: "Тренутно ништа препоручено не треба чистити.",
        review: "Прегледај и очисти",
        confirmQuarantine: (a) => `Преместити ${a} у карантин?`,
        confirmRecycle: (a) => `Преместити ${a} у корпу за отпатке?`,
        confirmDelete: (a) => `Обрисати ${a} одмах? Ово не може да се опозове.`,
        progress: (a, b) => `Чишћење… ${a} од ${b}`,
        done: "Готово"
      },
      stats: {
        freed: (a, b) => `Prune је ослободио ${a} од ${b}.`,
        freedNoDate: (a) => `Prune је ослободио ${a}.`,
        note: "Датотеке премештене у карантин рачунају се када испразните карантин."
      }
    }
  },
  sv: {
    dashboardQolV3: {
      clean: {
        title: "Rensa det rekommenderade",
        intro: "Rensar bara det Prune markerar som rekommenderat, aldrig något som förlorar data. Du ser totalen och vart det går innan något tas bort.",
        measureFirst: "Inget har mätts ännu. Prune mäter först och frågar innan det rensar.",
        measure: "Mät och granska",
        found: (a) => `Kan rensas: ${a}`,
        nothing: "Inget rekommenderat behöver rensas just nu.",
        review: "Granska och rensa",
        confirmQuarantine: (a) => `Flytta ${a} till karantän?`,
        confirmRecycle: (a) => `Flytta ${a} till papperskorgen?`,
        confirmDelete: (a) => `Radera ${a} nu? Det kan inte ångras.`,
        progress: (a, b) => `Rensar… ${a} av ${b}`,
        done: "Klart"
      },
      stats: {
        freed: (a, b) => `Prune har frigjort ${a} sedan ${b}.`,
        freedNoDate: (a) => `Prune har frigjort ${a}.`,
        note: "Filer som flyttats till karantän räknas först när du tömmer den."
      }
    }
  },
  th: {
    dashboardQolV3: {
      clean: {
        title: "ล้างรายการที่แนะนำ",
        intro: "ล้างเฉพาะสิ่งที่ Prune ทำเครื่องหมายว่าแนะนำ และไม่รวมสิ่งที่ทำให้ข้อมูลสูญหาย คุณจะเห็นขนาดรวมและปลายทางก่อนที่จะลบสิ่งใด",
        measureFirst: "ยังไม่มีการวัดขนาด Prune จะวัดก่อน แล้วถามก่อนล้าง",
        measure: "วัดและตรวจสอบ",
        found: (a) => `ล้างได้: ${a}`,
        nothing: "ขณะนี้ไม่มีรายการที่แนะนำที่ต้องล้าง",
        review: "ตรวจสอบและล้าง",
        confirmQuarantine: (a) => `ย้าย ${a} ไปยังกักกันหรือไม่`,
        confirmRecycle: (a) => `ย้าย ${a} ไปยังถังรีไซเคิลหรือไม่`,
        confirmDelete: (a) => `ลบ ${a} ทันทีหรือไม่ ย้อนกลับไม่ได้`,
        progress: (a, b) => `กำลังล้าง… ${a} จาก ${b}`,
        done: "เสร็จสิ้น"
      },
      stats: {
        freed: (a, b) => `Prune เพิ่มพื้นที่ว่างแล้ว ${a} ตั้งแต่ ${b}`,
        freedNoDate: (a) => `Prune เพิ่มพื้นที่ว่างแล้ว ${a}`,
        note: "ไฟล์ที่ย้ายไปยังกักกันจะนับเมื่อคุณล้างกักกัน"
      }
    }
  },
  tr: {
    dashboardQolV3: {
      clean: {
        title: "Önerilenleri temizle",
        intro: "Yalnızca Prune'un önerilen olarak işaretlediklerini temizler, veri kaybettiren hiçbir şeyi asla. Bir şey kaldırılmadan önce toplamı ve hedefi görürsünüz.",
        measureFirst: "Henüz hiçbir şey ölçülmedi. Prune önce ölçer, sonra temizlemeden önce sorar.",
        measure: "Ölç ve gözden geçir",
        found: (a) => `Temizlenebilir: ${a}`,
        nothing: "Şu anda önerilenlerden temizlenmesi gereken bir şey yok.",
        review: "Gözden geçir ve temizle",
        confirmQuarantine: (a) => `${a} karantinaya taşınsın mı?`,
        confirmRecycle: (a) => `${a} Geri Dönüşüm Kutusuna taşınsın mı?`,
        confirmDelete: (a) => `${a} şimdi silinsin mi? Bu işlem geri alınamaz.`,
        progress: (a, b) => `Temizleniyor… ${a} / ${b}`,
        done: "Bitti"
      },
      stats: {
        freed: (a, b) => `Prune ${b} tarihinden bu yana ${a} boşalttı.`,
        freedNoDate: (a) => `Prune ${a} boşalttı.`,
        note: "Karantinaya taşınan dosyalar, Karantinayı boşalttığınızda sayılır."
      }
    }
  },
  uk: {
    dashboardQolV3: {
      clean: {
        title: "Очистити рекомендоване",
        intro: "Очищає лише те, що Prune позначає як рекомендоване, і ніколи нічого, що призводить до втрати даних. Перед видаленням ви побачите загальний розмір і місце призначення.",
        measureFirst: "Поки що нічого не виміряно. Prune спочатку вимірює, а перед очищенням питає.",
        measure: "Виміряти й перевірити",
        found: (a) => `Можна очистити: ${a}`,
        nothing: "Зараз нічого з рекомендованого очищати не потрібно.",
        review: "Перевірити й очистити",
        confirmQuarantine: (a) => `Перемістити ${a} у карантин?`,
        confirmRecycle: (a) => `Перемістити ${a} у Кошик?`,
        confirmDelete: (a) => `Видалити ${a} зараз? Скасувати це не можна.`,
        progress: (a, b) => `Очищення… ${a} із ${b}`,
        done: "Готово"
      },
      stats: {
        freed: (a, b) => `Prune звільнив ${a} з ${b}.`,
        freedNoDate: (a) => `Prune звільнив ${a}.`,
        note: "Файли, переміщені в карантин, враховуються, коли ви очистите карантин."
      }
    }
  },
  vi: {
    dashboardQolV3: {
      clean: {
        title: "Dọn dẹp mục khuyến nghị",
        intro: "Chỉ dọn những gì Prune đánh dấu là khuyến nghị, không bao giờ dọn thứ gì làm mất dữ liệu. Bạn thấy tổng dung lượng và nơi đến trước khi có gì bị gỡ bỏ.",
        measureFirst: "Chưa đo gì cả. Prune đo trước, rồi hỏi bạn trước khi dọn.",
        measure: "Đo và xem lại",
        found: (a) => `Có thể dọn: ${a}`,
        nothing: "Hiện không có mục khuyến nghị nào cần dọn.",
        review: "Xem lại và dọn dẹp",
        confirmQuarantine: (a) => `Chuyển ${a} vào khu cách ly?`,
        confirmRecycle: (a) => `Chuyển ${a} vào Thùng rác?`,
        confirmDelete: (a) => `Xóa ${a} ngay bây giờ? Không thể hoàn tác.`,
        progress: (a, b) => `Đang dọn dẹp… ${a} trên ${b}`,
        done: "Xong"
      },
      stats: {
        freed: (a, b) => `Prune đã giải phóng ${a} kể từ ${b}.`,
        freedNoDate: (a) => `Prune đã giải phóng ${a}.`,
        note: "Các tệp được chuyển vào khu cách ly chỉ được tính khi bạn làm trống khu cách ly."
      }
    }
  },
  "zh-CN": {
    dashboardQolV3: {
      clean: {
        title: "清理推荐项",
        intro: "仅清理 Prune 标记为推荐的项目，绝不包含会丢失数据的项目。在移除任何内容之前，您会看到总大小和去向。",
        measureFirst: "尚未测量任何内容。Prune 会先测量，再在清理前询问您。",
        measure: "测量并查看",
        found: (a) => `可清理：${a}`,
        nothing: "目前没有需要清理的推荐项。",
        review: "查看并清理",
        confirmQuarantine: (a) => `要将 ${a} 移至隔离区吗？`,
        confirmRecycle: (a) => `要将 ${a} 移至回收站吗？`,
        confirmDelete: (a) => `要立即删除 ${a} 吗？此操作无法撤销。`,
        progress: (a, b) => `正在清理… ${a}/${b}`,
        done: "完成"
      },
      stats: {
        freed: (a, b) => `自 ${b} 起，Prune 已释放 ${a}。`,
        freedNoDate: (a) => `Prune 已释放 ${a}。`,
        note: "移至隔离区的文件在清空隔离区后才会计入。"
      }
    }
  },
  "zh-TW": {
    dashboardQolV3: {
      clean: {
        title: "清理建議項目",
        intro: "僅清理 Prune 標示為建議的項目，絕不包含會遺失資料的項目。在移除任何內容之前，您會看到總大小和去向。",
        measureFirst: "尚未測量任何內容。Prune 會先測量，再於清理前詢問您。",
        measure: "測量並檢視",
        found: (a) => `可清理：${a}`,
        nothing: "目前沒有需要清理的建議項目。",
        review: "檢視並清理",
        confirmQuarantine: (a) => `要將 ${a} 移至隔離區嗎？`,
        confirmRecycle: (a) => `要將 ${a} 移至資源回收筒嗎？`,
        confirmDelete: (a) => `要立即刪除 ${a} 嗎？此動作無法復原。`,
        progress: (a, b) => `正在清理… ${a}/${b}`,
        done: "完成"
      },
      stats: {
        freed: (a, b) => `自 ${b} 起，Prune 已釋放 ${a}。`,
        freedNoDate: (a) => `Prune 已釋放 ${a}。`,
        note: "移至隔離區的檔案在清空隔離區後才會計入。"
      }
    }
  }
};
