// Disk Map quality-of-life, all 40 languages: { en: { diskMapQolV3: { ... } }, af: { ... }, ... }.
// Remembering the last scan of each drive, the "last scan" banner, "what grew since the last scan",
// and the Settings switch with its offer to delete the automatic scans. Merged into the catalog by
// ../catalog.js. Generated by an out-of-tree script that writes every value with JSON.stringify (or an
// escaped template literal for a function), so quotes and non-ASCII text are safe. Counts are written as
// "Label: count" so no language needs a plural form. Terminology follows each language's own Disk Map,
// saved scans and compare strings (diskMap.js) and its Quarantine strings.
export default {
  en: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Last scan of ${a}`,
        scanned: (a) => `Scanned ${a}`,
        note: "This is how the drive looked then, not now. Moving files to Quarantine is off until you scan again."
      },
      growth: {
        title: "What grew since the last scan",
        comparedWith: (a) => `Compared with the scan from ${a}`,
        newFolder: "New",
        nothing: "No folder grew by 1 MB or more.",
        partial: "One of the two scans was partial, so these changes may be incomplete.",
        differentSize: "The drive changed size between the two scans, so compare with care.",
        differentMethod: "One scan was a fast scan and the other walked the folders, so small differences may come from the method.",
        foldedNote: "Compares folder totals. Small files grouped as smaller items count in their folder's total but are not compared one by one."
      },
      setting: {
        title: "Remember the last Disk Map scan of each drive",
        description: "Saves the latest two Disk Map scans of every drive on this PC, so the Disk Map opens on the last one at once and can show what grew. Each is a compressed folder tree with the biggest files and takes a few MB, up to about 25 MB on a drive with a million folders. It stays on this PC. Turn it off to stop saving.",
        usage: (a, b) => `Automatic scans saved: ${a} (${b})`,
        deleteQuestion: "Delete the automatic scans that are already saved?",
        deleteNow: "Delete them",
        keep: "Keep them",
        deleted: "Automatic scans deleted.",
        deleteFailed: (a) => `Couldn't delete them: ${a}`
      },
      auto: {
        label: (a) => `Automatic scan of ${a}`,
        badge: "Automatic"
      }
    }
  },
  af: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Laaste skandering van ${a}`,
        scanned: (a) => `Geskandeer ${a}`,
        note: "Dit is hoe die skyf toe gelyk het, nie nou nie. Skuif van lêers na Karantyn is af totdat jy weer skandeer."
      },
      growth: {
        title: "Wat gegroei het sedert die laaste skandering",
        comparedWith: (a) => `Vergelyk met die skandering van ${a}`,
        newFolder: "Nuut",
        nothing: "Geen vouer het met 1 MB of meer gegroei nie.",
        partial: "Een van die twee skanderings was gedeeltelik, so hierdie veranderinge kan onvolledig wees.",
        differentSize: "Die skyf se grootte het tussen die twee skanderings verander, so vergelyk versigtig.",
        differentMethod: "Een skandering was 'n vinnige skandering en die ander het deur die vouers geloop, so klein verskille kan van die metode kom.",
        foldedNote: "Vergelyk vouertotale. Klein lêers wat as kleiner items gegroepeer is, tel in hul vouer se totaal maar word nie een vir een vergelyk nie."
      },
      setting: {
        title: "Onthou die laaste Skyfkaart-skandering van elke skyf",
        description: "Stoor die laaste twee Skyfkaart-skanderings van elke skyf op hierdie rekenaar, sodat die Skyfkaart dadelik op die laaste een oopmaak en kan wys wat gegroei het. Elkeen is 'n saamgeperste vouerboom met die grootste lêers en neem 'n paar MB in beslag, tot ongeveer 25 MB op 'n skyf met 'n miljoen vouers. Dit bly op hierdie rekenaar. Skakel af om op te hou stoor.",
        usage: (a, b) => `Outomatiese skanderings gestoor: ${a} (${b})`,
        deleteQuestion: "Verwyder die outomatiese skanderings wat reeds gestoor is?",
        deleteNow: "Verwyder hulle",
        keep: "Behou hulle",
        deleted: "Outomatiese skanderings verwyder.",
        deleteFailed: (a) => `Kon hulle nie verwyder nie: ${a}`
      },
      auto: {
        label: (a) => `Outomatiese skandering van ${a}`,
        badge: "Outomaties"
      }
    }
  },
  ar: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `آخر فحص للقرص ${a}`,
        scanned: (a) => `تم الفحص ${a}`,
        note: "هذا هو شكل القرص وقتها، وليس الآن. نقل الملفات إلى الحجر الصحي متوقف إلى أن تفحص مرة أخرى."
      },
      growth: {
        title: "ما الذي نما منذ آخر فحص",
        comparedWith: (a) => `مقارنة بالفحص الذي تم ${a}`,
        newFolder: "جديد",
        nothing: "لم ينمُ أي مجلد بمقدار 1 MB أو أكثر.",
        partial: "كان أحد الفحصين جزئيًا، لذا قد تكون هذه التغييرات غير كاملة.",
        differentSize: "تغيّر حجم القرص بين الفحصين، لذا قارن بحذر.",
        differentMethod: "كان أحد الفحصين فحصًا سريعًا والآخر مرّ عبر المجلدات، لذا قد تنتج الفروق الصغيرة عن الطريقة.",
        foldedNote: "تتم مقارنة إجماليات المجلدات. الملفات الصغيرة المجمّعة كعناصر أصغر تُحتسب ضمن إجمالي مجلدها لكنها لا تُقارن واحدًا واحدًا."
      },
      setting: {
        title: "تذكّر آخر فحص لخريطة القرص لكل محرك",
        description: "يحفظ آخر فحصين لخريطة القرص لكل محرك على هذا الكمبيوتر، فتفتح خريطة القرص على آخر فحص فورًا ويمكنها إظهار ما نما. كل فحص شجرة مجلدات مضغوطة مع أكبر الملفات ويشغل بضعة MB، وحتى نحو 25 MB على محرك فيه مليون مجلد. يبقى على هذا الكمبيوتر. أوقف الخيار لإيقاف الحفظ.",
        usage: (a, b) => `عمليات الفحص التلقائية المحفوظة: ${a} (${b})`,
        deleteQuestion: "حذف عمليات الفحص التلقائية المحفوظة بالفعل؟",
        deleteNow: "احذفها",
        keep: "أبقها",
        deleted: "تم حذف عمليات الفحص التلقائية.",
        deleteFailed: (a) => `تعذّر حذفها: ${a}`
      },
      auto: {
        label: (a) => `فحص تلقائي للقرص ${a}`,
        badge: "تلقائي"
      }
    }
  },
  ca: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Últim escaneig de ${a}`,
        scanned: (a) => `Escanejat ${a}`,
        note: "Així era la unitat llavors, no ara. Moure fitxers a la quarantena està desactivat fins que torneu a escanejar."
      },
      growth: {
        title: "Què ha crescut des de l’últim escaneig",
        comparedWith: (a) => `En comparació amb l’escaneig de ${a}`,
        newFolder: "Nova",
        nothing: "Cap carpeta ha crescut 1 MB o més.",
        partial: "Un dels dos escaneigs era parcial, així que aquests canvis poden estar incomplets.",
        differentSize: "La mida de la unitat ha canviat entre els dos escaneigs, així que compareu amb cura.",
        differentMethod: "Un escaneig va ser ràpid i l’altre va recórrer les carpetes, així que les diferències petites poden venir del mètode.",
        foldedNote: "Compara els totals de les carpetes. Els fitxers petits agrupats com a elements més petits compten en el total de la seva carpeta, però no es comparen un per un."
      },
      setting: {
        title: "Recorda l’últim escaneig del mapa del disc de cada unitat",
        description: "Desa els dos últims escanejos del mapa del disc de cada unitat d’aquest PC, de manera que el mapa del disc s’obre a l’instant amb l’últim i pot mostrar què ha crescut. Cadascun és un arbre de carpetes comprimit amb els fitxers més grans i ocupa uns quants MB, fins a uns 25 MB en una unitat amb un milió de carpetes. Es queda en aquest PC. Desactiveu-ho per deixar de desar.",
        usage: (a, b) => `Escanejos automàtics desats: ${a} (${b})`,
        deleteQuestion: "Voleu suprimir els escanejos automàtics que ja estan desats?",
        deleteNow: "Suprimeix-los",
        keep: "Conserva’ls",
        deleted: "S’han suprimit els escanejos automàtics.",
        deleteFailed: (a) => `No s’han pogut suprimir: ${a}`
      },
      auto: {
        label: (a) => `Escaneig automàtic de ${a}`,
        badge: "Automàtic"
      }
    }
  },
  cs: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Poslední skenování disku ${a}`,
        scanned: (a) => `Naskenováno ${a}`,
        note: "Tak disk vypadal tehdy, ne teď. Přesun souborů do karantény je vypnutý, dokud neprovedete nové skenování."
      },
      growth: {
        title: "Co od posledního skenování přibylo",
        comparedWith: (a) => `Porovnáno se skenováním z ${a}`,
        newFolder: "Nová",
        nothing: "Žádná složka nenarostla o 1 MB nebo více.",
        partial: "Jedno ze dvou skenování bylo částečné, takže tyto změny mohou být neúplné.",
        differentSize: "Velikost disku se mezi skenováními změnila, porovnávejte proto opatrně.",
        differentMethod: "Jedno skenování bylo rychlé a druhé procházelo složky, takže drobné rozdíly mohou plynout z metody.",
        foldedNote: "Porovnává součty složek. Malé soubory seskupené jako menší položky se počítají do součtu své složky, ale neporovnávají se jednotlivě."
      },
      setting: {
        title: "Pamatovat si poslední skenování Mapy disku u každého disku",
        description: "Ukládá poslední dvě skenování Mapy disku každého disku v tomto počítači, takže se Mapa disku okamžitě otevře na tom posledním a umí ukázat, co přibylo. Každé je komprimovaný strom složek s největšími soubory a zabere několik MB, na disku s milionem složek asi 25 MB. Zůstává v tomto počítači. Vypnutím ukládání zastavíte.",
        usage: (a, b) => `Uložená automatická skenování: ${a} (${b})`,
        deleteQuestion: "Odstranit automatická skenování, která už jsou uložená?",
        deleteNow: "Odstranit je",
        keep: "Ponechat je",
        deleted: "Automatická skenování byla odstraněna.",
        deleteFailed: (a) => `Nepodařilo se je odstranit: ${a}`
      },
      auto: {
        label: (a) => `Automatické skenování disku ${a}`,
        badge: "Automatické"
      }
    }
  },
  cy: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Sgan diwethaf ${a}`,
        scanned: (a) => `Sganiwyd ${a}`,
        note: "Dyma sut oedd y gyriant bryd hynny, nid nawr. Mae symud ffeiliau i Gwarantin wedi’i ddiffodd nes i chi sganio eto."
      },
      growth: {
        title: "Beth sydd wedi tyfu ers y sgan diwethaf",
        comparedWith: (a) => `O’i gymharu â’r sgan o ${a}`,
        newFolder: "Newydd",
        nothing: "Ni thyfodd unrhyw ffolder 1 MB neu fwy.",
        partial: "Roedd un o’r ddau sgan yn rhannol, felly gall y newidiadau hyn fod yn anghyflawn.",
        differentSize: "Newidiodd maint y gyriant rhwng y ddau sgan, felly cymharwch yn ofalus.",
        differentMethod: "Sgan cyflym oedd un sgan ac aeth y llall drwy’r ffolderi, felly gall gwahaniaethau bach ddod o’r dull.",
        foldedNote: "Yn cymharu cyfansymiau ffolderi. Mae ffeiliau bach wedi’u grwpio fel eitemau llai yn cyfrif yng nghyfanswm eu ffolder ond nid ydynt yn cael eu cymharu fesul un."
      },
      setting: {
        title: "Cofio sgan Map Disg diwethaf pob gyriant",
        description: "Yn cadw dau sgan Map Disg diweddaraf pob gyriant ar y cyfrifiadur hwn, fel bod Map Disg yn agor ar yr un diwethaf ar unwaith ac yn gallu dangos beth sydd wedi tyfu. Mae pob un yn goeden ffolderi gywasgedig gyda’r ffeiliau mwyaf ac yn cymryd ychydig o MB, hyd at tua 25 MB ar yriant gyda miliwn o ffolderi. Mae’n aros ar y cyfrifiadur hwn. Diffoddwch i roi’r gorau i gadw.",
        usage: (a, b) => `Sganiau awtomatig wedi’u cadw: ${a} (${b})`,
        deleteQuestion: "Dileu’r sganiau awtomatig sydd eisoes wedi’u cadw?",
        deleteNow: "Dileu nhw",
        keep: "Eu cadw",
        deleted: "Dilëwyd y sganiau awtomatig.",
        deleteFailed: (a) => `Methwyd â’u dileu: ${a}`
      },
      auto: {
        label: (a) => `Sgan awtomatig o ${a}`,
        badge: "Awtomatig"
      }
    }
  },
  da: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Seneste scanning af ${a}`,
        scanned: (a) => `Scannet ${a}`,
        note: "Sådan så drevet ud dengang, ikke nu. Flytning af filer til Karantæne er slået fra, indtil du scanner igen."
      },
      growth: {
        title: "Hvad er vokset siden sidste scanning",
        comparedWith: (a) => `Sammenlignet med scanningen fra ${a}`,
        newFolder: "Ny",
        nothing: "Ingen mappe er vokset med 1 MB eller mere.",
        partial: "Én af de to scanninger var delvis, så disse ændringer kan være ufuldstændige.",
        differentSize: "Drevets størrelse ændrede sig mellem de to scanninger, så sammenlign med forsigtighed.",
        differentMethod: "Den ene scanning var en hurtig scanning, og den anden gennemgik mapperne, så små forskelle kan skyldes metoden.",
        foldedNote: "Sammenligner mappetotaler. Små filer, der er grupperet som mindre elementer, tæller med i mappens total, men sammenlignes ikke enkeltvis."
      },
      setting: {
        title: "Husk den seneste Diskkort-scanning af hvert drev",
        description: "Gemmer de to seneste Diskkort-scanninger af hvert drev på denne pc, så Diskkort åbner på den seneste med det samme og kan vise, hvad der er vokset. Hver er et komprimeret mappetræ med de største filer og fylder nogle få MB, op til cirka 25 MB på et drev med en million mapper. Det bliver på denne pc. Slå fra for at holde op med at gemme.",
        usage: (a, b) => `Automatiske scanninger gemt: ${a} (${b})`,
        deleteQuestion: "Slet de automatiske scanninger, der allerede er gemt?",
        deleteNow: "Slet dem",
        keep: "Behold dem",
        deleted: "De automatiske scanninger er slettet.",
        deleteFailed: (a) => `Kunne ikke slette dem: ${a}`
      },
      auto: {
        label: (a) => `Automatisk scanning af ${a}`,
        badge: "Automatisk"
      }
    }
  },
  de: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Letzter Scan von ${a}`,
        scanned: (a) => `Gescannt ${a}`,
        note: "So sah das Laufwerk damals aus, nicht jetzt. Das Verschieben von Dateien in die Quarantäne ist aus, bis Sie erneut scannen."
      },
      growth: {
        title: "Was seit dem letzten Scan gewachsen ist",
        comparedWith: (a) => `Verglichen mit dem Scan von ${a}`,
        newFolder: "Neu",
        nothing: "Kein Ordner ist um 1 MB oder mehr gewachsen.",
        partial: "Einer der beiden Scans war unvollständig, daher können diese Änderungen unvollständig sein.",
        differentSize: "Die Größe des Laufwerks hat sich zwischen den beiden Scans geändert, vergleichen Sie also mit Vorsicht.",
        differentMethod: "Ein Scan war ein Schnellscan, der andere hat die Ordner durchlaufen, daher können kleine Unterschiede von der Methode stammen.",
        foldedNote: "Verglichen werden die Ordnersummen. Kleine Dateien, die als kleinere Elemente zusammengefasst sind, zählen zur Summe ihres Ordners, werden aber nicht einzeln verglichen."
      },
      setting: {
        title: "Den letzten Festplattenkarte-Scan jedes Laufwerks merken",
        description: "Speichert die letzten beiden Festplattenkarte-Scans jedes Laufwerks dieses PCs, damit sich die Festplattenkarte sofort mit dem letzten öffnet und zeigen kann, was gewachsen ist. Jeder ist ein komprimierter Ordnerbaum mit den größten Dateien und belegt einige MB, bis zu etwa 25 MB bei einem Laufwerk mit einer Million Ordnern. Er bleibt auf diesem PC. Zum Beenden des Speicherns ausschalten.",
        usage: (a, b) => `Gespeicherte automatische Scans: ${a} (${b})`,
        deleteQuestion: "Die bereits gespeicherten automatischen Scans löschen?",
        deleteNow: "Löschen",
        keep: "Behalten",
        deleted: "Die automatischen Scans wurden gelöscht.",
        deleteFailed: (a) => `Konnte nicht gelöscht werden: ${a}`
      },
      auto: {
        label: (a) => `Automatischer Scan von ${a}`,
        badge: "Automatisch"
      }
    }
  },
  el: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Τελευταία σάρωση του ${a}`,
        scanned: (a) => `Σαρώθηκε ${a}`,
        note: "Έτσι ήταν η μονάδα τότε, όχι τώρα. Η μετακίνηση αρχείων στην Καραντίνα είναι απενεργοποιημένη μέχρι να σαρώσετε ξανά."
      },
      growth: {
        title: "Τι αυξήθηκε από την τελευταία σάρωση",
        comparedWith: (a) => `Σε σύγκριση με τη σάρωση από ${a}`,
        newFolder: "Νέος",
        nothing: "Κανένας φάκελος δεν αυξήθηκε κατά 1 MB ή περισσότερο.",
        partial: "Η μία από τις δύο σαρώσεις ήταν μερική, επομένως οι αλλαγές αυτές μπορεί να είναι ελλιπείς.",
        differentSize: "Το μέγεθος της μονάδας άλλαξε ανάμεσα στις δύο σαρώσεις, επομένως συγκρίνετε με προσοχή.",
        differentMethod: "Η μία σάρωση ήταν γρήγορη και η άλλη διέτρεξε τους φακέλους, επομένως μικρές διαφορές μπορεί να οφείλονται στη μέθοδο.",
        foldedNote: "Συγκρίνονται τα σύνολα των φακέλων. Τα μικρά αρχεία που ομαδοποιούνται ως μικρότερα στοιχεία προσμετρούνται στο σύνολο του φακέλου τους αλλά δεν συγκρίνονται ένα προς ένα."
      },
      setting: {
        title: "Απομνημόνευση της τελευταίας σάρωσης του Χάρτη δίσκου για κάθε μονάδα",
        description: "Αποθηκεύει τις δύο τελευταίες σαρώσεις του Χάρτη δίσκου κάθε μονάδας αυτού του υπολογιστή, ώστε ο Χάρτης δίσκου να ανοίγει αμέσως στην τελευταία και να δείχνει τι αυξήθηκε. Κάθε σάρωση είναι ένα συμπιεσμένο δέντρο φακέλων με τα μεγαλύτερα αρχεία και πιάνει λίγα MB, έως περίπου 25 MB σε μονάδα με ένα εκατομμύριο φακέλους. Μένει σε αυτόν τον υπολογιστή. Απενεργοποιήστε το για να σταματήσει η αποθήκευση.",
        usage: (a, b) => `Αποθηκευμένες αυτόματες σαρώσεις: ${a} (${b})`,
        deleteQuestion: "Να διαγραφούν οι αυτόματες σαρώσεις που έχουν ήδη αποθηκευτεί;",
        deleteNow: "Διαγραφή τους",
        keep: "Διατήρησή τους",
        deleted: "Οι αυτόματες σαρώσεις διαγράφηκαν.",
        deleteFailed: (a) => `Δεν ήταν δυνατή η διαγραφή τους: ${a}`
      },
      auto: {
        label: (a) => `Αυτόματη σάρωση του ${a}`,
        badge: "Αυτόματη"
      }
    }
  },
  es: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Último escaneo de ${a}`,
        scanned: (a) => `Escaneado ${a}`,
        note: "Así era la unidad entonces, no ahora. Mover archivos a la cuarentena está desactivado hasta que vuelvas a escanear."
      },
      growth: {
        title: "Qué ha crecido desde el último escaneo",
        comparedWith: (a) => `En comparación con el escaneo de ${a}`,
        newFolder: "Nueva",
        nothing: "Ninguna carpeta ha crecido 1 MB o más.",
        partial: "Uno de los dos escaneos fue parcial, así que estos cambios pueden estar incompletos.",
        differentSize: "El tamaño de la unidad cambió entre los dos escaneos, así que compara con cuidado.",
        differentMethod: "Un escaneo fue rápido y el otro recorrió las carpetas, así que las diferencias pequeñas pueden deberse al método.",
        foldedNote: "Compara los totales de las carpetas. Los archivos pequeños agrupados como elementos menores cuentan en el total de su carpeta, pero no se comparan uno a uno."
      },
      setting: {
        title: "Recordar el último escaneo del mapa del disco de cada unidad",
        description: "Guarda los dos últimos escaneos del mapa del disco de cada unidad de este PC, para que el mapa del disco se abra al instante con el último y pueda mostrar qué ha crecido. Cada uno es un árbol de carpetas comprimido con los archivos más grandes y ocupa unos pocos MB, hasta unos 25 MB en una unidad con un millón de carpetas. Se queda en este PC. Desactívalo para dejar de guardar.",
        usage: (a, b) => `Escaneos automáticos guardados: ${a} (${b})`,
        deleteQuestion: "¿Eliminar los escaneos automáticos que ya están guardados?",
        deleteNow: "Eliminarlos",
        keep: "Conservarlos",
        deleted: "Se eliminaron los escaneos automáticos.",
        deleteFailed: (a) => `No se pudieron eliminar: ${a}`
      },
      auto: {
        label: (a) => `Escaneo automático de ${a}`,
        badge: "Automático"
      }
    }
  },
  et: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Draivi ${a} viimane skannimine`,
        scanned: (a) => `Skannitud ${a}`,
        note: "Nii draiv tol ajal välja nägi, mitte praegu. Failide teisaldamine karantiini on välja lülitatud, kuni skannite uuesti."
      },
      growth: {
        title: "Mis on pärast viimast skannimist kasvanud",
        comparedWith: (a) => `Võrreldes skannimisega ajast ${a}`,
        newFolder: "Uus",
        nothing: "Ükski kaust ei kasvanud 1 MB või rohkem.",
        partial: "Üks kahest skannimisest oli osaline, seega võivad need muudatused olla puudulikud.",
        differentSize: "Draivi suurus muutus kahe skannimise vahel, seega võrrelge ettevaatlikult.",
        differentMethod: "Üks skannimine oli kiirskannimine ja teine käis kaustad läbi, seega võivad väikesed erinevused tuleneda meetodist.",
        foldedNote: "Võrreldakse kaustade kogusummasid. Väiksemate üksustena rühmitatud väikesed failid lähevad oma kausta kogusummasse, kuid neid ei võrrelda ükshaaval."
      },
      setting: {
        title: "Jäta meelde iga draivi viimane Kettakaardi skannimine",
        description: "Salvestab selle arvuti iga draivi kaks viimast Kettakaardi skannimist, et Kettakaart avaneks kohe viimasel ja saaks näidata, mis on kasvanud. Iga skannimine on tihendatud kaustapuu koos suurimate failidega ja võtab mõne MB, miljoni kausta puhul kuni umbes 25 MB. See jääb sellesse arvutisse. Salvestamise lõpetamiseks lülitage välja.",
        usage: (a, b) => `Salvestatud automaatseid skannimisi: ${a} (${b})`,
        deleteQuestion: "Kas kustutada juba salvestatud automaatsed skannimised?",
        deleteNow: "Kustuta need",
        keep: "Jäta need alles",
        deleted: "Automaatsed skannimised kustutati.",
        deleteFailed: (a) => `Kustutamine ebaõnnestus: ${a}`
      },
      auto: {
        label: (a) => `Draivi ${a} automaatne skannimine`,
        badge: "Automaatne"
      }
    }
  },
  fi: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Aseman ${a} viimeisin skannaus`,
        scanned: (a) => `Skannattu ${a}`,
        note: "Tältä asema näytti silloin, ei nyt. Tiedostojen siirto karanteeniin on pois käytöstä, kunnes skannaat uudelleen."
      },
      growth: {
        title: "Mikä on kasvanut viime skannauksen jälkeen",
        comparedWith: (a) => `Verrattuna skannaukseen ajalta ${a}`,
        newFolder: "Uusi",
        nothing: "Mikään kansio ei kasvanut 1 MB:n tai enemmän.",
        partial: "Toinen kahdesta skannauksesta oli osittainen, joten nämä muutokset voivat olla puutteellisia.",
        differentSize: "Aseman koko muuttui skannausten välillä, joten vertaa varoen.",
        differentMethod: "Toinen skannaus oli pikaskannaus ja toinen kävi kansiot läpi, joten pienet erot voivat johtua menetelmästä.",
        foldedNote: "Vertaa kansioiden kokonaismääriä. Pienemmiksi kohteiksi ryhmitellyt pienet tiedostot lasketaan kansionsa kokonaismäärään, mutta niitä ei verrata yksitellen."
      },
      setting: {
        title: "Muista kunkin aseman viimeisin Levykartta-skannaus",
        description: "Tallentaa tämän tietokoneen jokaisen aseman kaksi viimeisintä Levykartta-skannausta, jolloin Levykartta aukeaa heti viimeisimpään ja voi näyttää, mikä on kasvanut. Kukin on pakattu kansiopuu suurimpine tiedostoineen ja vie muutaman MB, enintään noin 25 MB asemalla, jolla on miljoona kansiota. Se pysyy tässä tietokoneessa. Poista käytöstä lopettaaksesi tallennuksen.",
        usage: (a, b) => `Tallennetut automaattiset skannaukset: ${a} (${b})`,
        deleteQuestion: "Poistetaanko jo tallennetut automaattiset skannaukset?",
        deleteNow: "Poista ne",
        keep: "Säilytä ne",
        deleted: "Automaattiset skannaukset poistettiin.",
        deleteFailed: (a) => `Poistaminen epäonnistui: ${a}`
      },
      auto: {
        label: (a) => `Aseman ${a} automaattinen skannaus`,
        badge: "Automaattinen"
      }
    }
  },
  fr: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Dernière analyse de ${a}`,
        scanned: (a) => `Analysé ${a}`,
        note: "Voici l’état du lecteur à ce moment-là, pas maintenant. Le déplacement de fichiers vers la quarantaine est désactivé tant que vous n’analysez pas à nouveau."
      },
      growth: {
        title: "Ce qui a grossi depuis la dernière analyse",
        comparedWith: (a) => `Comparé à l’analyse du ${a}`,
        newFolder: "Nouveau",
        nothing: "Aucun dossier n’a grossi de 1 MB ou plus.",
        partial: "L’une des deux analyses était partielle ; ces changements peuvent donc être incomplets.",
        differentSize: "La taille du lecteur a changé entre les deux analyses ; comparez donc avec prudence.",
        differentMethod: "L’une des analyses était rapide et l’autre a parcouru les dossiers ; de petites différences peuvent donc venir de la méthode.",
        foldedNote: "Compare les totaux des dossiers. Les petits fichiers regroupés en éléments plus petits comptent dans le total de leur dossier, mais ne sont pas comparés un par un."
      },
      setting: {
        title: "Mémoriser la dernière analyse de la carte du disque de chaque lecteur",
        description: "Enregistre les deux dernières analyses de la carte du disque de chaque lecteur de ce PC, pour que la carte du disque s’ouvre aussitôt sur la dernière et puisse montrer ce qui a grossi. Chacune est une arborescence de dossiers compressée avec les plus gros fichiers et occupe quelques MB, jusqu’à environ 25 MB pour un lecteur d’un million de dossiers. Elle reste sur ce PC. Désactivez l’option pour arrêter l’enregistrement.",
        usage: (a, b) => `Analyses automatiques enregistrées : ${a} (${b})`,
        deleteQuestion: "Supprimer les analyses automatiques déjà enregistrées ?",
        deleteNow: "Les supprimer",
        keep: "Les conserver",
        deleted: "Les analyses automatiques ont été supprimées.",
        deleteFailed: (a) => `Impossible de les supprimer : ${a}`
      },
      auto: {
        label: (a) => `Analyse automatique de ${a}`,
        badge: "Automatique"
      }
    }
  },
  he: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `הסריקה האחרונה של ${a}`,
        scanned: (a) => `נסרק ${a}`,
        note: "כך נראה הכונן אז, לא עכשיו. העברת קבצים להסגר כבויה עד שתסרקו שוב."
      },
      growth: {
        title: "מה גדל מאז הסריקה האחרונה",
        comparedWith: (a) => `בהשוואה לסריקה מ${a}`,
        newFolder: "חדש",
        nothing: "אף תיקייה לא גדלה ב-1 MB או יותר.",
        partial: "אחת משתי הסריקות הייתה חלקית, ולכן ייתכן שהשינויים האלה חלקיים.",
        differentSize: "גודל הכונן השתנה בין שתי הסריקות, ולכן כדאי להשוות בזהירות.",
        differentMethod: "אחת הסריקות הייתה סריקה מהירה והשנייה עברה על התיקיות, ולכן הבדלים קטנים עשויים לנבוע מהשיטה.",
        foldedNote: "משווה סך הכול של תיקיות. קבצים קטנים שמקובצים כפריטים קטנים נספרים בסך התיקייה שלהם אך אינם מושווים אחד אחד."
      },
      setting: {
        title: "לזכור את הסריקה האחרונה של מפת הדיסק לכל כונן",
        description: "שומר את שתי הסריקות האחרונות של מפת הדיסק לכל כונן במחשב הזה, כך שמפת הדיסק נפתחת מיד על האחרונה ויכולה להראות מה גדל. כל סריקה היא עץ תיקיות דחוס עם הקבצים הגדולים ביותר ותופסת כמה MB, עד כ-25 MB בכונן עם מיליון תיקיות. היא נשארת במחשב הזה. כבו כדי להפסיק לשמור.",
        usage: (a, b) => `סריקות אוטומטיות שמורות: ${a} (${b})`,
        deleteQuestion: "למחוק את הסריקות האוטומטיות שכבר נשמרו?",
        deleteNow: "מחק אותן",
        keep: "השאר אותן",
        deleted: "הסריקות האוטומטיות נמחקו.",
        deleteFailed: (a) => `לא ניתן למחוק אותן: ${a}`
      },
      auto: {
        label: (a) => `סריקה אוטומטית של ${a}`,
        badge: "אוטומטית"
      }
    }
  },
  hu: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `A(z) ${a} meghajtó legutóbbi vizsgálata`,
        scanned: (a) => `Vizsgálva: ${a}`,
        note: "Ilyen volt akkor a meghajtó, nem most. A fájlok karanténba helyezése ki van kapcsolva, amíg újra nem vizsgál."
      },
      growth: {
        title: "Mi nőtt a legutóbbi vizsgálat óta",
        comparedWith: (a) => `Összehasonlítva a(z) ${a} vizsgálattal`,
        newFolder: "Új",
        nothing: "Egyetlen mappa sem nőtt 1 MB-tal vagy többel.",
        partial: "A két vizsgálat egyike részleges volt, ezért ezek a változások hiányosak lehetnek.",
        differentSize: "A meghajtó mérete megváltozott a két vizsgálat között, ezért óvatosan hasonlítson.",
        differentMethod: "Az egyik vizsgálat gyors vizsgálat volt, a másik bejárta a mappákat, ezért a kis eltérések a módszerből is adódhatnak.",
        foldedNote: "A mappák összegeit hasonlítja össze. A kisebb elemekként csoportosított kis fájlok beleszámítanak a mappájuk összegébe, de egyenként nincsenek összehasonlítva."
      },
      setting: {
        title: "Az egyes meghajtók legutóbbi Lemeztérkép-vizsgálatának megjegyzése",
        description: "Elmenti a számítógép minden meghajtójának két legutóbbi Lemeztérkép-vizsgálatát, így a Lemeztérkép azonnal a legutóbbin nyílik meg, és meg tudja mutatni, mi nőtt. Mindegyik tömörített mappafa a legnagyobb fájlokkal, és néhány MB-ot foglal, egymillió mappás meghajtón legfeljebb körülbelül 25 MB-ot. A számítógépen marad. Kapcsolja ki a mentés leállításához.",
        usage: (a, b) => `Mentett automatikus vizsgálatok: ${a} (${b})`,
        deleteQuestion: "Törli a már mentett automatikus vizsgálatokat?",
        deleteNow: "Törlésük",
        keep: "Megtartásuk",
        deleted: "Az automatikus vizsgálatok törölve.",
        deleteFailed: (a) => `Nem sikerült törölni őket: ${a}`
      },
      auto: {
        label: (a) => `A(z) ${a} meghajtó automatikus vizsgálata`,
        badge: "Automatikus"
      }
    }
  },
  id: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Pemindaian terakhir ${a}`,
        scanned: (a) => `Dipindai ${a}`,
        note: "Begini kondisi drive saat itu, bukan sekarang. Memindahkan file ke Karantina nonaktif sampai Anda memindai lagi."
      },
      growth: {
        title: "Yang bertambah sejak pemindaian terakhir",
        comparedWith: (a) => `Dibandingkan dengan pemindaian dari ${a}`,
        newFolder: "Baru",
        nothing: "Tidak ada folder yang bertambah 1 MB atau lebih.",
        partial: "Salah satu dari dua pemindaian bersifat sebagian, sehingga perubahan ini mungkin tidak lengkap.",
        differentSize: "Ukuran drive berubah di antara kedua pemindaian, jadi bandingkan dengan hati-hati.",
        differentMethod: "Satu pemindaian adalah pemindaian cepat dan yang lain menelusuri folder, jadi selisih kecil mungkin berasal dari metodenya.",
        foldedNote: "Membandingkan total folder. File kecil yang dikelompokkan sebagai item lebih kecil dihitung dalam total foldernya tetapi tidak dibandingkan satu per satu."
      },
      setting: {
        title: "Ingat pemindaian Peta Disk terakhir untuk setiap drive",
        description: "Menyimpan dua pemindaian Peta Disk terbaru untuk setiap drive di PC ini, sehingga Peta Disk langsung terbuka pada yang terakhir dan dapat menunjukkan apa yang bertambah. Masing-masing adalah pohon folder terkompresi dengan file terbesar dan memakan beberapa MB, hingga sekitar 25 MB pada drive dengan sejuta folder. Tetap berada di PC ini. Matikan untuk berhenti menyimpan.",
        usage: (a, b) => `Pemindaian otomatis tersimpan: ${a} (${b})`,
        deleteQuestion: "Hapus pemindaian otomatis yang sudah tersimpan?",
        deleteNow: "Hapus semuanya",
        keep: "Simpan saja",
        deleted: "Pemindaian otomatis dihapus.",
        deleteFailed: (a) => `Tidak dapat menghapusnya: ${a}`
      },
      auto: {
        label: (a) => `Pemindaian otomatis ${a}`,
        badge: "Otomatis"
      }
    }
  },
  is: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Síðasta skönnun á ${a}`,
        scanned: (a) => `Skannað ${a}`,
        note: "Svona leit drifið út þá, ekki núna. Slökkt er á flutningi skráa í sóttkví þar til þú skannar aftur."
      },
      growth: {
        title: "Hvað hefur stækkað frá síðustu skönnun",
        comparedWith: (a) => `Borið saman við skönnunina frá ${a}`,
        newFolder: "Ný",
        nothing: "Engin mappa stækkaði um 1 MB eða meira.",
        partial: "Önnur skönnunin var að hluta, svo þessar breytingar gætu verið ófullkomnar.",
        differentSize: "Stærð drifsins breyttist milli skannananna, svo berðu saman með varúð.",
        differentMethod: "Önnur skönnunin var hraðskönnun og hin fór í gegnum möppurnar, svo litlir munir geta stafað af aðferðinni.",
        foldedNote: "Ber saman heildartölur mappa. Litlar skrár sem flokkaðar eru sem minni atriði teljast með í heild möppunnar en eru ekki bornar saman ein og ein."
      },
      setting: {
        title: "Muna síðustu Diskakorts-skönnun hvers drifs",
        description: "Vistar tvær síðustu Diskakorts-skannanir hvers drifs í þessari tölvu svo Diskakortið opnist strax á þeirri síðustu og geti sýnt hvað hefur stækkað. Hver er þjöppuð möppuskrá með stærstu skránum og tekur nokkur MB, allt að um 25 MB á drifi með milljón möppum. Hún helst í þessari tölvu. Slökktu til að hætta að vista.",
        usage: (a, b) => `Vistaðar sjálfvirkar skannanir: ${a} (${b})`,
        deleteQuestion: "Eyða sjálfvirku skönnununum sem þegar eru vistaðar?",
        deleteNow: "Eyða þeim",
        keep: "Halda þeim",
        deleted: "Sjálfvirkum skönnunum var eytt.",
        deleteFailed: (a) => `Ekki tókst að eyða þeim: ${a}`
      },
      auto: {
        label: (a) => `Sjálfvirk skönnun á ${a}`,
        badge: "Sjálfvirk"
      }
    }
  },
  it: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Ultima scansione di ${a}`,
        scanned: (a) => `Scansionato ${a}`,
        note: "Così appariva l’unità allora, non adesso. Lo spostamento dei file in quarantena è disattivato finché non esegui una nuova scansione."
      },
      growth: {
        title: "Cosa è cresciuto dall’ultima scansione",
        comparedWith: (a) => `Confronto con la scansione di ${a}`,
        newFolder: "Nuova",
        nothing: "Nessuna cartella è cresciuta di 1 MB o più.",
        partial: "Una delle due scansioni era parziale, quindi queste variazioni potrebbero essere incomplete.",
        differentSize: "La dimensione dell’unità è cambiata tra le due scansioni, quindi confronta con cautela.",
        differentMethod: "Una scansione era rapida e l’altra ha percorso le cartelle, quindi piccole differenze possono dipendere dal metodo.",
        foldedNote: "Confronta i totali delle cartelle. I file piccoli raggruppati come elementi minori contano nel totale della loro cartella ma non vengono confrontati uno per uno."
      },
      setting: {
        title: "Ricorda l’ultima scansione della mappa del disco di ogni unità",
        description: "Salva le ultime due scansioni della mappa del disco di ogni unità di questo PC, così la mappa del disco si apre subito sull’ultima e può mostrare cosa è cresciuto. Ognuna è un albero di cartelle compresso con i file più grandi e occupa qualche MB, fino a circa 25 MB su un’unità con un milione di cartelle. Resta su questo PC. Disattiva per smettere di salvare.",
        usage: (a, b) => `Scansioni automatiche salvate: ${a} (${b})`,
        deleteQuestion: "Eliminare le scansioni automatiche già salvate?",
        deleteNow: "Elimina",
        keep: "Mantieni",
        deleted: "Le scansioni automatiche sono state eliminate.",
        deleteFailed: (a) => `Impossibile eliminarle: ${a}`
      },
      auto: {
        label: (a) => `Scansione automatica di ${a}`,
        badge: "Automatica"
      }
    }
  },
  ja: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `${a} の前回のスキャン`,
        scanned: (a) => `スキャン日時: ${a}`,
        note: "現在ではなく、そのときのドライブの状態です。もう一度スキャンするまで、ファイルの隔離への移動はできません。"
      },
      growth: {
        title: "前回のスキャンから増えたもの",
        comparedWith: (a) => `${a} のスキャンとの比較`,
        newFolder: "新規",
        nothing: "1 MB 以上増えたフォルダーはありません。",
        partial: "2 回のスキャンのうち一方は一部のみのため、この変化は不完全な可能性があります。",
        differentSize: "2 回のスキャンの間にドライブの容量が変わっているため、比較には注意してください。",
        differentMethod: "一方は高速スキャン、もう一方はフォルダーをたどったスキャンのため、小さな差は方法の違いによる可能性があります。",
        foldedNote: "フォルダーの合計を比較します。小さな項目としてまとめられた小さいファイルはフォルダーの合計には含まれますが、1 件ずつは比較されません。"
      },
      setting: {
        title: "各ドライブの前回のディスクマップのスキャンを記憶する",
        description: "この PC の各ドライブについて、直近 2 回のディスクマップのスキャンを保存します。ディスクマップは前回のスキャンをすぐに表示し、何が増えたかを示せます。各スキャンは最大のファイルを含む圧縮されたフォルダーツリーで、数 MB、100 万フォルダーのドライブでも約 25 MB です。この PC の外には出ません。保存をやめるにはオフにします。",
        usage: (a, b) => `保存済みの自動スキャン: ${a} (${b})`,
        deleteQuestion: "保存済みの自動スキャンを削除しますか？",
        deleteNow: "削除する",
        keep: "残す",
        deleted: "自動スキャンを削除しました。",
        deleteFailed: (a) => `削除できませんでした: ${a}`
      },
      auto: {
        label: (a) => `${a} の自動スキャン`,
        badge: "自動"
      }
    }
  },
  ko: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `${a}의 마지막 검사`,
        scanned: (a) => `검사 시각: ${a}`,
        note: "지금이 아니라 그때의 드라이브 모습입니다. 다시 검사하기 전에는 파일을 격리로 옮길 수 없습니다."
      },
      growth: {
        title: "마지막 검사 이후 늘어난 항목",
        comparedWith: (a) => `${a}의 검사와 비교`,
        newFolder: "새 항목",
        nothing: "1 MB 이상 늘어난 폴더가 없습니다.",
        partial: "두 검사 중 하나가 부분 검사여서 이 변화는 불완전할 수 있습니다.",
        differentSize: "두 검사 사이에 드라이브 크기가 바뀌었으므로 주의해서 비교하세요.",
        differentMethod: "한 검사는 빠른 검사였고 다른 검사는 폴더를 살펴본 것이어서, 작은 차이는 방식 때문일 수 있습니다.",
        foldedNote: "폴더 합계를 비교합니다. 더 작은 항목으로 묶인 작은 파일은 해당 폴더의 합계에 포함되지만 하나씩 비교되지는 않습니다."
      },
      setting: {
        title: "각 드라이브의 마지막 디스크 맵 검사 기억",
        description: "이 PC의 각 드라이브에 대해 최근 두 번의 디스크 맵 검사를 저장하여, 디스크 맵이 마지막 검사를 바로 열고 무엇이 늘었는지 보여줄 수 있게 합니다. 각 검사는 가장 큰 파일이 포함된 압축 폴더 트리이며 수 MB를 차지하고, 폴더가 100만 개인 드라이브에서는 약 25 MB입니다. 이 PC 안에만 보관됩니다. 저장을 멈추려면 끄세요.",
        usage: (a, b) => `저장된 자동 검사: ${a} (${b})`,
        deleteQuestion: "이미 저장된 자동 검사를 삭제할까요?",
        deleteNow: "삭제",
        keep: "유지",
        deleted: "자동 검사를 삭제했습니다.",
        deleteFailed: (a) => `삭제하지 못했습니다: ${a}`
      },
      auto: {
        label: (a) => `${a} 자동 검사`,
        badge: "자동"
      }
    }
  },
  lt: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Paskutinis ${a} nuskaitymas`,
        scanned: (a) => `Nuskaityta ${a}`,
        note: "Toks diskas buvo tada, o ne dabar. Failų perkėlimas į karantiną išjungtas, kol nuskaitysite iš naujo."
      },
      growth: {
        title: "Kas padidėjo nuo paskutinio nuskaitymo",
        comparedWith: (a) => `Palyginta su ${a} nuskaitymu`,
        newFolder: "Naujas",
        nothing: "Nė vienas aplankas nepadidėjo 1 MB ar daugiau.",
        partial: "Vienas iš dviejų nuskaitymų buvo dalinis, todėl šie pokyčiai gali būti neišsamūs.",
        differentSize: "Tarp dviejų nuskaitymų disko dydis pasikeitė, todėl lyginkite atsargiai.",
        differentMethod: "Vienas nuskaitymas buvo greitasis, o kitas peržiūrėjo aplankus, todėl nedideli skirtumai gali atsirasti dėl metodo.",
        foldedNote: "Lyginamos aplankų sumos. Maži failai, sugrupuoti kaip smulkesni elementai, įskaičiuojami į savo aplanko sumą, bet nelyginami po vieną."
      },
      setting: {
        title: "Prisiminti paskutinį kiekvieno disko Disko žemėlapio nuskaitymą",
        description: "Įrašo du naujausius kiekvieno šio kompiuterio disko Disko žemėlapio nuskaitymus, kad Disko žemėlapis iškart atsidarytų paskutiniame ir galėtų parodyti, kas padidėjo. Kiekvienas yra suglaudintas aplankų medis su didžiausiais failais ir užima kelis MB, iki maždaug 25 MB diske su milijonu aplankų. Lieka šiame kompiuteryje. Išjunkite, kad nebūtų įrašoma.",
        usage: (a, b) => `Įrašyti automatiniai nuskaitymai: ${a} (${b})`,
        deleteQuestion: "Ištrinti jau įrašytus automatinius nuskaitymus?",
        deleteNow: "Ištrinti juos",
        keep: "Palikti juos",
        deleted: "Automatiniai nuskaitymai ištrinti.",
        deleteFailed: (a) => `Nepavyko jų ištrinti: ${a}`
      },
      auto: {
        label: (a) => `Automatinis ${a} nuskaitymas`,
        badge: "Automatinis"
      }
    }
  },
  ms: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Imbasan terakhir ${a}`,
        scanned: (a) => `Diimbas ${a}`,
        note: "Beginilah keadaan pemacu ketika itu, bukan sekarang. Memindahkan fail ke Kuarantin dimatikan sehingga anda mengimbas semula."
      },
      growth: {
        title: "Apa yang bertambah sejak imbasan terakhir",
        comparedWith: (a) => `Dibandingkan dengan imbasan pada ${a}`,
        newFolder: "Baharu",
        nothing: "Tiada folder yang bertambah 1 MB atau lebih.",
        partial: "Salah satu daripada dua imbasan adalah separa, jadi perubahan ini mungkin tidak lengkap.",
        differentSize: "Saiz pemacu berubah antara kedua-dua imbasan, jadi bandingkan dengan berhati-hati.",
        differentMethod: "Satu imbasan ialah imbasan pantas dan satu lagi menjelajah folder, jadi perbezaan kecil mungkin datang daripada kaedah.",
        foldedNote: "Membandingkan jumlah folder. Fail kecil yang dikumpulkan sebagai item lebih kecil dikira dalam jumlah foldernya tetapi tidak dibandingkan satu demi satu."
      },
      setting: {
        title: "Ingat imbasan Peta Cakera terakhir bagi setiap pemacu",
        description: "Menyimpan dua imbasan Peta Cakera terkini bagi setiap pemacu pada PC ini, supaya Peta Cakera terbuka terus pada yang terakhir dan boleh menunjukkan apa yang bertambah. Setiap satu ialah pokok folder termampat dengan fail terbesar dan mengambil beberapa MB, sehingga kira-kira 25 MB pada pemacu dengan sejuta folder. Ia kekal pada PC ini. Matikan untuk berhenti menyimpan.",
        usage: (a, b) => `Imbasan automatik disimpan: ${a} (${b})`,
        deleteQuestion: "Padam imbasan automatik yang sudah disimpan?",
        deleteNow: "Padamkannya",
        keep: "Kekalkannya",
        deleted: "Imbasan automatik telah dipadam.",
        deleteFailed: (a) => `Tidak dapat memadamkannya: ${a}`
      },
      auto: {
        label: (a) => `Imbasan automatik ${a}`,
        badge: "Automatik"
      }
    }
  },
  nb: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Siste skanning av ${a}`,
        scanned: (a) => `Skannet ${a}`,
        note: "Slik så stasjonen ut da, ikke nå. Flytting av filer til Karantene er slått av til du skanner på nytt."
      },
      growth: {
        title: "Hva som har vokst siden forrige skanning",
        comparedWith: (a) => `Sammenlignet med skanningen fra ${a}`,
        newFolder: "Ny",
        nothing: "Ingen mappe har vokst med 1 MB eller mer.",
        partial: "Én av de to skanningene var delvis, så disse endringene kan være ufullstendige.",
        differentSize: "Stasjonens størrelse endret seg mellom de to skanningene, så sammenlign med forsiktighet.",
        differentMethod: "Den ene skanningen var en hurtigskanning, og den andre gikk gjennom mappene, så små forskjeller kan skyldes metoden.",
        foldedNote: "Sammenligner mappetotaler. Små filer som er gruppert som mindre elementer, teller med i mappens total, men sammenlignes ikke enkeltvis."
      },
      setting: {
        title: "Husk den siste Diskkart-skanningen av hver stasjon",
        description: "Lagrer de to siste Diskkart-skanningene av hver stasjon på denne PC-en, slik at Diskkart åpnes på den siste med én gang og kan vise hva som har vokst. Hver er et komprimert mappetre med de største filene og tar noen få MB, opptil rundt 25 MB på en stasjon med en million mapper. Den blir på denne PC-en. Slå av for å slutte å lagre.",
        usage: (a, b) => `Lagrede automatiske skanninger: ${a} (${b})`,
        deleteQuestion: "Slette de automatiske skanningene som allerede er lagret?",
        deleteNow: "Slett dem",
        keep: "Behold dem",
        deleted: "De automatiske skanningene er slettet.",
        deleteFailed: (a) => `Kunne ikke slette dem: ${a}`
      },
      auto: {
        label: (a) => `Automatisk skanning av ${a}`,
        badge: "Automatisk"
      }
    }
  },
  nl: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Laatste scan van ${a}`,
        scanned: (a) => `Gescand ${a}`,
        note: "Zo zag de schijf er toen uit, niet nu. Bestanden naar Quarantaine verplaatsen staat uit tot u opnieuw scant."
      },
      growth: {
        title: "Wat is er gegroeid sinds de laatste scan",
        comparedWith: (a) => `Vergeleken met de scan van ${a}`,
        newFolder: "Nieuw",
        nothing: "Geen map is 1 MB of meer gegroeid.",
        partial: "Een van de twee scans was onvolledig, dus deze wijzigingen kunnen onvolledig zijn.",
        differentSize: "De grootte van de schijf is tussen de twee scans veranderd, dus vergelijk voorzichtig.",
        differentMethod: "De ene scan was een snelle scan en de andere liep de mappen door, dus kleine verschillen kunnen door de methode komen.",
        foldedNote: "Vergelijkt maptotalen. Kleine bestanden die als kleinere items zijn gegroepeerd, tellen mee in het totaal van hun map, maar worden niet een voor een vergeleken."
      },
      setting: {
        title: "De laatste Schijfkaart-scan van elke schijf onthouden",
        description: "Slaat de laatste twee Schijfkaart-scans van elke schijf op deze pc op, zodat de Schijfkaart meteen opent op de laatste en kan laten zien wat er is gegroeid. Elke scan is een gecomprimeerde mappenboom met de grootste bestanden en neemt een paar MB in beslag, tot ongeveer 25 MB op een schijf met een miljoen mappen. Hij blijft op deze pc. Zet uit om het opslaan te stoppen.",
        usage: (a, b) => `Opgeslagen automatische scans: ${a} (${b})`,
        deleteQuestion: "De automatische scans verwijderen die al zijn opgeslagen?",
        deleteNow: "Verwijderen",
        keep: "Behouden",
        deleted: "De automatische scans zijn verwijderd.",
        deleteFailed: (a) => `Kon ze niet verwijderen: ${a}`
      },
      auto: {
        label: (a) => `Automatische scan van ${a}`,
        badge: "Automatisch"
      }
    }
  },
  pl: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Ostatni skan dysku ${a}`,
        scanned: (a) => `Zeskanowano ${a}`,
        note: "Tak dysk wyglądał wtedy, a nie teraz. Przenoszenie plików do kwarantanny jest wyłączone, dopóki nie wykonasz nowego skanu."
      },
      growth: {
        title: "Co urosło od ostatniego skanu",
        comparedWith: (a) => `W porównaniu ze skanem z ${a}`,
        newFolder: "Nowy",
        nothing: "Żaden folder nie urósł o 1 MB lub więcej.",
        partial: "Jeden z dwóch skanów był częściowy, więc te zmiany mogą być niepełne.",
        differentSize: "Rozmiar dysku zmienił się między skanami, więc porównuj ostrożnie.",
        differentMethod: "Jeden skan był szybki, a drugi przeglądał foldery, więc drobne różnice mogą wynikać z metody.",
        foldedNote: "Porównuje sumy folderów. Małe pliki zgrupowane jako mniejsze elementy wchodzą do sumy swojego folderu, ale nie są porównywane pojedynczo."
      },
      setting: {
        title: "Zapamiętuj ostatni skan Mapy dysku każdego dysku",
        description: "Zapisuje dwa ostatnie skany Mapy dysku każdego dysku na tym komputerze, dzięki czemu Mapa dysku od razu otwiera się na ostatnim i może pokazać, co urosło. Każdy to skompresowane drzewo folderów z największymi plikami i zajmuje kilka MB, do około 25 MB na dysku z milionem folderów. Zostaje na tym komputerze. Wyłącz, aby przestać zapisywać.",
        usage: (a, b) => `Zapisane skany automatyczne: ${a} (${b})`,
        deleteQuestion: "Usunąć skany automatyczne, które są już zapisane?",
        deleteNow: "Usuń je",
        keep: "Zachowaj je",
        deleted: "Skany automatyczne zostały usunięte.",
        deleteFailed: (a) => `Nie udało się ich usunąć: ${a}`
      },
      auto: {
        label: (a) => `Automatyczny skan dysku ${a}`,
        badge: "Automatyczny"
      }
    }
  },
  ps: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `د ${a} وروستی سکین`,
        scanned: (a) => `سکین شو ${a}`,
        note: "ډرایو هغه وخت داسې و، نه اوس. تر هغه چې بیا سکین نه کړئ، فایلونه قرنطین ته لیږدول بند دي."
      },
      growth: {
        title: "د وروستي سکین راهیسې څه لوی شوي",
        comparedWith: (a) => `د ${a} له سکین سره پرتله شوی`,
        newFolder: "نوی",
        nothing: "هیڅ فولډر په 1 MB یا ډیر نه دی لوی شوی.",
        partial: "له دوو سکینونو څخه یو نیمګړی و، نو دا بدلونونه ښايي بشپړ نه وي.",
        differentSize: "د دواړو سکینونو ترمنځ د ډرایو اندازه بدله شوې، نو په احتیاط پرتله کړئ.",
        differentMethod: "یو سکین چټک سکین و او بل یې فولډرونه تیر کړل، نو کوچني توپیرونه ښايي د طریقې له امله وي.",
        foldedNote: "د فولډرونو ټولټال پرتله کوي. کوچني فایلونه چې د کوچنیو توکو په توګه ګروپ شوي د خپل فولډر په ټولټال کې شمېرل کېږي، خو یو په یو نه پرتله کېږي."
      },
      setting: {
        title: "د هر ډرایو د ډیسک نقشې وروستی سکین په یاد ولرئ",
        description: "پر دې کمپیوټر د هر ډرایو د ډیسک نقشې وروستي دوه سکینونه خوندي کوي، ترڅو د ډیسک نقشه سمدلاسه په وروستي سکین پرانیستل شي او وښيي چې څه لوی شوي. هر یو د تر ټولو لویو فایلونو سره یو فشار شوی د فولډرونو ونه ده او څو MB نیسي، په هغه ډرایو کې چې یو میلیون فولډرونه لري تر شاوخوا 25 MB پورې. په همدې کمپیوټر کې پاتې کېږي. د خوندي کولو بندولو لپاره یې بند کړئ.",
        usage: (a, b) => `خوندي شوي اتوماتیک سکینونه: ${a} (${b})`,
        deleteQuestion: "هغه اتوماتیک سکینونه ړنګ کړئ چې دمخه خوندي شوي؟",
        deleteNow: "ړنګ یې کړئ",
        keep: "وساتئ یې",
        deleted: "اتوماتیک سکینونه ړنګ شول.",
        deleteFailed: (a) => `ړنګ یې نه شول: ${a}`
      },
      auto: {
        label: (a) => `د ${a} اتوماتیک سکین`,
        badge: "اتوماتیک"
      }
    }
  },
  "pt-BR": {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Última verificação de ${a}`,
        scanned: (a) => `Verificado ${a}`,
        note: "Era assim que a unidade estava na época, não agora. Mover arquivos para a Quarentena fica desativado até você verificar de novo."
      },
      growth: {
        title: "O que cresceu desde a última verificação",
        comparedWith: (a) => `Comparado com a verificação de ${a}`,
        newFolder: "Nova",
        nothing: "Nenhuma pasta cresceu 1 MB ou mais.",
        partial: "Uma das duas verificações foi parcial, então essas mudanças podem estar incompletas.",
        differentSize: "O tamanho da unidade mudou entre as duas verificações, então compare com cuidado.",
        differentMethod: "Uma verificação foi rápida e a outra percorreu as pastas, então pequenas diferenças podem vir do método.",
        foldedNote: "Compara os totais das pastas. Arquivos pequenos agrupados como itens menores contam no total da pasta, mas não são comparados um a um."
      },
      setting: {
        title: "Lembrar a última verificação do mapa do disco de cada unidade",
        description: "Salva as duas últimas verificações do mapa do disco de cada unidade deste PC, para que o mapa do disco abra na última na hora e possa mostrar o que cresceu. Cada uma é uma árvore de pastas compactada com os maiores arquivos e ocupa alguns MB, até cerca de 25 MB em uma unidade com um milhão de pastas. Fica neste PC. Desative para parar de salvar.",
        usage: (a, b) => `Verificações automáticas salvas: ${a} (${b})`,
        deleteQuestion: "Excluir as verificações automáticas que já estão salvas?",
        deleteNow: "Excluir",
        keep: "Manter",
        deleted: "As verificações automáticas foram excluídas.",
        deleteFailed: (a) => `Não foi possível excluí-las: ${a}`
      },
      auto: {
        label: (a) => `Verificação automática de ${a}`,
        badge: "Automática"
      }
    }
  },
  pt: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Última análise de ${a}`,
        scanned: (a) => `Analisado ${a}`,
        note: "Era assim que a unidade estava na altura, não agora. Mover ficheiros para a Quarentena fica desativado até analisar de novo."
      },
      growth: {
        title: "O que cresceu desde a última análise",
        comparedWith: (a) => `Comparado com a análise de ${a}`,
        newFolder: "Nova",
        nothing: "Nenhuma pasta cresceu 1 MB ou mais.",
        partial: "Uma das duas análises foi parcial, por isso estas alterações podem estar incompletas.",
        differentSize: "O tamanho da unidade mudou entre as duas análises, por isso compare com cuidado.",
        differentMethod: "Uma análise foi rápida e a outra percorreu as pastas, por isso pequenas diferenças podem vir do método.",
        foldedNote: "Compara os totais das pastas. Os ficheiros pequenos agrupados como itens menores contam no total da pasta, mas não são comparados um a um."
      },
      setting: {
        title: "Memorizar a última análise do mapa do disco de cada unidade",
        description: "Guarda as duas últimas análises do mapa do disco de cada unidade deste PC, para que o mapa do disco abra logo na última e possa mostrar o que cresceu. Cada uma é uma árvore de pastas comprimida com os maiores ficheiros e ocupa alguns MB, até cerca de 25 MB numa unidade com um milhão de pastas. Fica neste PC. Desative para deixar de guardar.",
        usage: (a, b) => `Análises automáticas guardadas: ${a} (${b})`,
        deleteQuestion: "Eliminar as análises automáticas que já estão guardadas?",
        deleteNow: "Eliminar",
        keep: "Manter",
        deleted: "As análises automáticas foram eliminadas.",
        deleteFailed: (a) => `Não foi possível eliminá-las: ${a}`
      },
      auto: {
        label: (a) => `Análise automática de ${a}`,
        badge: "Automática"
      }
    }
  },
  ro: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Ultima scanare a ${a}`,
        scanned: (a) => `Scanat ${a}`,
        note: "Așa arăta unitatea atunci, nu acum. Mutarea fișierelor în carantină este dezactivată până scanați din nou."
      },
      growth: {
        title: "Ce a crescut de la ultima scanare",
        comparedWith: (a) => `Comparat cu scanarea din ${a}`,
        newFolder: "Nou",
        nothing: "Niciun folder nu a crescut cu 1 MB sau mai mult.",
        partial: "Una dintre cele două scanări a fost parțială, deci aceste modificări pot fi incomplete.",
        differentSize: "Dimensiunea unității s-a schimbat între cele două scanări, deci comparați cu prudență.",
        differentMethod: "O scanare a fost rapidă, iar cealaltă a parcurs folderele, deci diferențele mici pot proveni din metodă.",
        foldedNote: "Compară totalurile folderelor. Fișierele mici grupate ca elemente mai mici se numără în totalul folderului lor, dar nu sunt comparate unul câte unul."
      },
      setting: {
        title: "Reține ultima scanare a hărții discului pentru fiecare unitate",
        description: "Salvează ultimele două scanări ale hărții discului pentru fiecare unitate a acestui PC, astfel încât harta discului se deschide imediat pe ultima și poate arăta ce a crescut. Fiecare este un arbore de foldere comprimat cu cele mai mari fișiere și ocupă câțiva MB, până la aproximativ 25 MB pe o unitate cu un milion de foldere. Rămâne pe acest PC. Dezactivați pentru a nu mai salva.",
        usage: (a, b) => `Scanări automate salvate: ${a} (${b})`,
        deleteQuestion: "Ștergeți scanările automate deja salvate?",
        deleteNow: "Șterge-le",
        keep: "Păstrează-le",
        deleted: "Scanările automate au fost șterse.",
        deleteFailed: (a) => `Nu au putut fi șterse: ${a}`
      },
      auto: {
        label: (a) => `Scanare automată a ${a}`,
        badge: "Automată"
      }
    }
  },
  ru: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Последнее сканирование диска ${a}`,
        scanned: (a) => `Просканировано: ${a}`,
        note: "Так диск выглядел тогда, а не сейчас. Перемещение файлов в карантин отключено, пока вы не просканируете снова."
      },
      growth: {
        title: "Что выросло с прошлого сканирования",
        comparedWith: (a) => `Сравнение со сканированием от ${a}`,
        newFolder: "Новая",
        nothing: "Ни одна папка не выросла на 1 MB или больше.",
        partial: "Одно из двух сканирований было частичным, поэтому эти изменения могут быть неполными.",
        differentSize: "Размер диска изменился между двумя сканированиями, поэтому сравнивайте с осторожностью.",
        differentMethod: "Одно сканирование было быстрым, а другое обходило папки, поэтому небольшие расхождения могут объясняться методом.",
        foldedNote: "Сравниваются итоги по папкам. Мелкие файлы, сгруппированные как более мелкие элементы, входят в итог своей папки, но по отдельности не сравниваются."
      },
      setting: {
        title: "Запоминать последнее сканирование Карты диска для каждого диска",
        description: "Сохраняет два последних сканирования Карты диска для каждого диска этого компьютера, чтобы Карта диска сразу открывалась на последнем и могла показать, что выросло. Каждое — это сжатое дерево папок с самыми большими файлами, оно занимает несколько MB, до примерно 25 MB на диске с миллионом папок. Данные остаются на этом компьютере. Выключите, чтобы прекратить сохранение.",
        usage: (a, b) => `Сохранено автоматических сканирований: ${a} (${b})`,
        deleteQuestion: "Удалить уже сохранённые автоматические сканирования?",
        deleteNow: "Удалить их",
        keep: "Оставить их",
        deleted: "Автоматические сканирования удалены.",
        deleteFailed: (a) => `Не удалось удалить: ${a}`
      },
      auto: {
        label: (a) => `Автоматическое сканирование диска ${a}`,
        badge: "Автоматическое"
      }
    }
  },
  sk: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Posledné skenovanie disku ${a}`,
        scanned: (a) => `Naskenované ${a}`,
        note: "Takto disk vyzeral vtedy, nie teraz. Presun súborov do karantény je vypnutý, kým znova neskenujete."
      },
      growth: {
        title: "Čo od posledného skenovania pribudlo",
        comparedWith: (a) => `Porovnané so skenovaním z ${a}`,
        newFolder: "Nový",
        nothing: "Žiadny priečinok nenarástol o 1 MB alebo viac.",
        partial: "Jedno z dvoch skenovaní bolo čiastočné, takže tieto zmeny môžu byť neúplné.",
        differentSize: "Veľkosť disku sa medzi skenovaniami zmenila, preto porovnávajte opatrne.",
        differentMethod: "Jedno skenovanie bolo rýchle a druhé prechádzalo priečinky, takže drobné rozdiely môžu plynúť z metódy.",
        foldedNote: "Porovnáva súčty priečinkov. Malé súbory zoskupené ako menšie položky sa započítavajú do súčtu svojho priečinka, ale neporovnávajú sa jednotlivo."
      },
      setting: {
        title: "Pamätať si posledné skenovanie Mapy disku každého disku",
        description: "Ukladá dve posledné skenovania Mapy disku každého disku v tomto počítači, takže sa Mapa disku okamžite otvorí na poslednom a vie ukázať, čo pribudlo. Každé je komprimovaný strom priečinkov s najväčšími súbormi a zaberie niekoľko MB, na disku s miliónom priečinkov asi 25 MB. Zostáva v tomto počítači. Vypnutím ukladanie zastavíte.",
        usage: (a, b) => `Uložené automatické skenovania: ${a} (${b})`,
        deleteQuestion: "Odstrániť automatické skenovania, ktoré sú už uložené?",
        deleteNow: "Odstrániť ich",
        keep: "Ponechať ich",
        deleted: "Automatické skenovania boli odstránené.",
        deleteFailed: (a) => `Nepodarilo sa ich odstrániť: ${a}`
      },
      auto: {
        label: (a) => `Automatické skenovanie disku ${a}`,
        badge: "Automatické"
      }
    }
  },
  sq: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Skanimi i fundit i ${a}`,
        scanned: (a) => `Skanuar ${a}`,
        note: "Ja si dukej disku atëherë, jo tani. Zhvendosja e skedarëve në Karantinë është e çaktivizuar derisa të skanoni sërish."
      },
      growth: {
        title: "Çfarë ka rritur madhësinë që nga skanimi i fundit",
        comparedWith: (a) => `Krahasuar me skanimin e ${a}`,
        newFolder: "E re",
        nothing: "Asnjë dosje nuk u rrit me 1 MB ose më shumë.",
        partial: "Njëri nga dy skanimet ishte i pjesshëm, ndaj këto ndryshime mund të jenë të paplota.",
        differentSize: "Madhësia e diskut ndryshoi mes dy skanimeve, ndaj krahasoni me kujdes.",
        differentMethod: "Njëri skanim ishte i shpejtë dhe tjetri kaloi nëpër dosje, ndaj dallimet e vogla mund të vijnë nga metoda.",
        foldedNote: "Krahason totalet e dosjeve. Skedarët e vegjël të grupuar si artikuj më të vegjël llogariten në totalin e dosjes së tyre, por nuk krahasohen një nga një."
      },
      setting: {
        title: "Mbaj mend skanimin e fundit të Hartës së Diskut për çdo disk",
        description: "Ruan dy skanimet më të fundit të Hartës së Diskut për çdo disk të këtij kompjuteri, që Harta e Diskut të hapet menjëherë te i fundit dhe të tregojë çfarë është rritur. Secili është një pemë dosjesh e kompresuar me skedarët më të mëdhenj dhe zë disa MB, deri në rreth 25 MB në një disk me një milion dosje. Mbetet në këtë kompjuter. Çaktivizojeni për të ndaluar ruajtjen.",
        usage: (a, b) => `Skanime automatike të ruajtura: ${a} (${b})`,
        deleteQuestion: "T’i fshij skanimet automatike që janë ruajtur tashmë?",
        deleteNow: "Fshiji",
        keep: "Mbaji",
        deleted: "Skanimet automatike u fshinë.",
        deleteFailed: (a) => `Nuk u fshinë dot: ${a}`
      },
      auto: {
        label: (a) => `Skanim automatik i ${a}`,
        badge: "Automatik"
      }
    }
  },
  sr: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Последње скенирање диска ${a}`,
        scanned: (a) => `Скенирано ${a}`,
        note: "Овако је диск изгледао тада, а не сада. Премештање датотека у карантин је искључено док поново не скенирате."
      },
      growth: {
        title: "Шта је порасло од последњег скенирања",
        comparedWith: (a) => `У поређењу са скенирањем од ${a}`,
        newFolder: "Нова",
        nothing: "Ниједна фасцикла није порасла за 1 MB или више.",
        partial: "Једно од два скенирања било је делимично, па ове промене могу бити непотпуне.",
        differentSize: "Величина диска се променила између два скенирања, па упоређујте пажљиво.",
        differentMethod: "Једно скенирање било је брзо, а друго је прошло кроз фасцикле, па мале разлике могу потицати од метода.",
        foldedNote: "Пореде се укупне величине фасцикли. Мале датотеке груписане као мање ставке рачунају се у укупну величину своје фасцикле, али се не пореде једна по једна."
      },
      setting: {
        title: "Памти последње скенирање Мапе диска за сваки диск",
        description: "Чува два последња скенирања Мапе диска за сваки диск на овом рачунару, па се Мапа диска одмах отвара на последњем и може да прикаже шта је порасло. Свако је сажето стабло фасцикли са највећим датотекама и заузима неколико MB, до око 25 MB на диску са милион фасцикли. Остаје на овом рачунару. Искључите да бисте престали да чувате.",
        usage: (a, b) => `Сачувана аутоматска скенирања: ${a} (${b})`,
        deleteQuestion: "Обрисати аутоматска скенирања која су већ сачувана?",
        deleteNow: "Обриши их",
        keep: "Задржи их",
        deleted: "Аутоматска скенирања су обрисана.",
        deleteFailed: (a) => `Брисање није успело: ${a}`
      },
      auto: {
        label: (a) => `Аутоматско скенирање диска ${a}`,
        badge: "Аутоматско"
      }
    }
  },
  sv: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Senaste skanningen av ${a}`,
        scanned: (a) => `Skannad ${a}`,
        note: "Så här såg enheten ut då, inte nu. Att flytta filer till Karantän är avstängt tills du skannar igen."
      },
      growth: {
        title: "Vad som har vuxit sedan senaste skanningen",
        comparedWith: (a) => `Jämfört med skanningen från ${a}`,
        newFolder: "Ny",
        nothing: "Ingen mapp har vuxit med 1 MB eller mer.",
        partial: "En av de två skanningarna var ofullständig, så de här ändringarna kan vara ofullständiga.",
        differentSize: "Enhetens storlek ändrades mellan de två skanningarna, så jämför med försiktighet.",
        differentMethod: "Den ena skanningen var en snabbskanning och den andra gick igenom mapparna, så små skillnader kan bero på metoden.",
        foldedNote: "Jämför mapptotaler. Små filer som grupperats som mindre objekt räknas in i mappens total men jämförs inte en och en."
      },
      setting: {
        title: "Kom ihåg den senaste Diskkarta-skanningen för varje enhet",
        description: "Sparar de två senaste Diskkarta-skanningarna för varje enhet på den här datorn, så att Diskkarta öppnas direkt på den senaste och kan visa vad som har vuxit. Varje skanning är ett komprimerat mappträd med de största filerna och tar några MB, upp till cirka 25 MB på en enhet med en miljon mappar. Den stannar på den här datorn. Stäng av för att sluta spara.",
        usage: (a, b) => `Sparade automatiska skanningar: ${a} (${b})`,
        deleteQuestion: "Ta bort de automatiska skanningar som redan är sparade?",
        deleteNow: "Ta bort dem",
        keep: "Behåll dem",
        deleted: "De automatiska skanningarna har tagits bort.",
        deleteFailed: (a) => `Det gick inte att ta bort dem: ${a}`
      },
      auto: {
        label: (a) => `Automatisk skanning av ${a}`,
        badge: "Automatisk"
      }
    }
  },
  th: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `การสแกนล่าสุดของ ${a}`,
        scanned: (a) => `สแกนเมื่อ ${a}`,
        note: "นี่คือสภาพของไดรฟ์ในตอนนั้น ไม่ใช่ตอนนี้ การย้ายไฟล์ไปยังที่กักกันจะปิดอยู่จนกว่าคุณจะสแกนใหม่"
      },
      growth: {
        title: "สิ่งที่เพิ่มขึ้นตั้งแต่การสแกนล่าสุด",
        comparedWith: (a) => `เทียบกับการสแกนเมื่อ ${a}`,
        newFolder: "ใหม่",
        nothing: "ไม่มีโฟลเดอร์ใดเพิ่มขึ้น 1 MB ขึ้นไป",
        partial: "การสแกนหนึ่งในสองครั้งเป็นแบบบางส่วน การเปลี่ยนแปลงเหล่านี้จึงอาจไม่ครบถ้วน",
        differentSize: "ขนาดของไดรฟ์เปลี่ยนไประหว่างการสแกนทั้งสองครั้ง โปรดเปรียบเทียบด้วยความระมัดระวัง",
        differentMethod: "การสแกนหนึ่งเป็นแบบเร็ว อีกครั้งสแกนทีละโฟลเดอร์ ความต่างเล็กน้อยจึงอาจมาจากวิธีสแกน",
        foldedNote: "เปรียบเทียบยอดรวมของโฟลเดอร์ ไฟล์เล็กที่จัดกลุ่มเป็นรายการย่อยจะนับรวมในยอดของโฟลเดอร์ แต่ไม่ได้เปรียบเทียบทีละไฟล์"
      },
      setting: {
        title: "จดจำการสแกนแผนที่ดิสก์ล่าสุดของแต่ละไดรฟ์",
        description: "บันทึกการสแกนแผนที่ดิสก์ล่าสุดสองครั้งของทุกไดรฟ์ในพีซีเครื่องนี้ เพื่อให้แผนที่ดิสก์เปิดที่ครั้งล่าสุดได้ทันทีและแสดงสิ่งที่เพิ่มขึ้นได้ แต่ละครั้งเป็นโครงสร้างโฟลเดอร์ที่บีบอัดพร้อมไฟล์ใหญ่ที่สุด ใช้พื้นที่ไม่กี่ MB และสูงสุดราว 25 MB บนไดรฟ์ที่มีหนึ่งล้านโฟลเดอร์ ข้อมูลอยู่ในพีซีเครื่องนี้เท่านั้น ปิดเพื่อหยุดการบันทึก",
        usage: (a, b) => `การสแกนอัตโนมัติที่บันทึกไว้: ${a} (${b})`,
        deleteQuestion: "ลบการสแกนอัตโนมัติที่บันทึกไว้แล้วหรือไม่",
        deleteNow: "ลบทั้งหมด",
        keep: "เก็บไว้",
        deleted: "ลบการสแกนอัตโนมัติแล้ว",
        deleteFailed: (a) => `ลบไม่สำเร็จ: ${a}`
      },
      auto: {
        label: (a) => `การสแกนอัตโนมัติของ ${a}`,
        badge: "อัตโนมัติ"
      }
    }
  },
  tr: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `${a} sürücüsünün son taraması`,
        scanned: (a) => `Taranma zamanı: ${a}`,
        note: "Sürücü o zaman böyleydi, şimdi değil. Yeniden tarayana kadar dosyaları Karantina'ya taşıma kapalıdır."
      },
      growth: {
        title: "Son taramadan beri büyüyenler",
        comparedWith: (a) => `${a} tarihli tarama ile karşılaştırıldı`,
        newFolder: "Yeni",
        nothing: "Hiçbir klasör 1 MB veya daha fazla büyümedi.",
        partial: "İki taramadan biri kısmiydi, bu nedenle bu değişiklikler eksik olabilir.",
        differentSize: "Sürücü boyutu iki tarama arasında değişti, bu nedenle dikkatli karşılaştırın.",
        differentMethod: "Taramalardan biri hızlı tarama, diğeri klasörleri gezen taramaydı; küçük farklar yöntemden kaynaklanıyor olabilir.",
        foldedNote: "Klasör toplamlarını karşılaştırır. Daha küçük öğeler olarak gruplanan küçük dosyalar klasörünün toplamına dahildir ancak tek tek karşılaştırılmaz."
      },
      setting: {
        title: "Her sürücünün son Disk Haritası taramasını hatırla",
        description: "Bu bilgisayardaki her sürücünün son iki Disk Haritası taramasını kaydeder; böylece Disk Haritası son taramayla hemen açılır ve nelerin büyüdüğünü gösterebilir. Her biri en büyük dosyalarla birlikte sıkıştırılmış bir klasör ağacıdır ve birkaç MB yer kaplar; bir milyon klasörlü bir sürücüde yaklaşık 25 MB'a kadar çıkar. Bu bilgisayarda kalır. Kaydetmeyi durdurmak için kapatın.",
        usage: (a, b) => `Kaydedilen otomatik taramalar: ${a} (${b})`,
        deleteQuestion: "Zaten kaydedilmiş otomatik taramalar silinsin mi?",
        deleteNow: "Sil",
        keep: "Tut",
        deleted: "Otomatik taramalar silindi.",
        deleteFailed: (a) => `Silinemedi: ${a}`
      },
      auto: {
        label: (a) => `${a} otomatik taraması`,
        badge: "Otomatik"
      }
    }
  },
  uk: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Останнє сканування диска ${a}`,
        scanned: (a) => `Скановано: ${a}`,
        note: "Так диск виглядав тоді, а не зараз. Переміщення файлів у карантин вимкнено, доки ви не просканюєте знову."
      },
      growth: {
        title: "Що зросло з минулого сканування",
        comparedWith: (a) => `Порівняно зі скануванням від ${a}`,
        newFolder: "Нова",
        nothing: "Жодна папка не зросла на 1 MB або більше.",
        partial: "Одне з двох сканувань було частковим, тому ці зміни можуть бути неповними.",
        differentSize: "Розмір диска змінився між двома скануваннями, тому порівнюйте обережно.",
        differentMethod: "Одне сканування було швидким, а інше обходило папки, тому невеликі розбіжності можуть бути через метод.",
        foldedNote: "Порівнюються підсумки за папками. Дрібні файли, згруповані як менші елементи, входять до підсумку своєї папки, але окремо не порівнюються."
      },
      setting: {
        title: "Запам’ятовувати останнє сканування Карти диска для кожного диска",
        description: "Зберігає два останні сканування Карти диска для кожного диска цього комп’ютера, щоб Карта диска одразу відкривалася на останньому й могла показати, що зросло. Кожне — це стиснуте дерево папок із найбільшими файлами, воно займає кілька MB, до приблизно 25 MB на диску з мільйоном папок. Дані залишаються на цьому комп’ютері. Вимкніть, щоб припинити збереження.",
        usage: (a, b) => `Збережено автоматичних сканувань: ${a} (${b})`,
        deleteQuestion: "Видалити автоматичні сканування, які вже збережено?",
        deleteNow: "Видалити їх",
        keep: "Залишити їх",
        deleted: "Автоматичні сканування видалено.",
        deleteFailed: (a) => `Не вдалося видалити: ${a}`
      },
      auto: {
        label: (a) => `Автоматичне сканування диска ${a}`,
        badge: "Автоматичне"
      }
    }
  },
  vi: {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `Lần quét gần nhất của ${a}`,
        scanned: (a) => `Đã quét ${a}`,
        note: "Đây là tình trạng ổ đĩa lúc đó, không phải bây giờ. Việc chuyển tệp vào khu cách ly bị tắt cho đến khi bạn quét lại."
      },
      growth: {
        title: "Những gì đã tăng kể từ lần quét trước",
        comparedWith: (a) => `So với lần quét ${a}`,
        newFolder: "Mới",
        nothing: "Không có thư mục nào tăng 1 MB trở lên.",
        partial: "Một trong hai lần quét chỉ là một phần, nên các thay đổi này có thể chưa đầy đủ.",
        differentSize: "Kích thước ổ đĩa đã thay đổi giữa hai lần quét, nên hãy so sánh thận trọng.",
        differentMethod: "Một lần quét là quét nhanh còn lần kia duyệt qua các thư mục, nên chênh lệch nhỏ có thể do phương pháp.",
        foldedNote: "So sánh tổng của các thư mục. Các tệp nhỏ được gộp thành mục nhỏ hơn được tính vào tổng của thư mục chứa chúng nhưng không được so sánh từng tệp một."
      },
      setting: {
        title: "Ghi nhớ lần quét Bản đồ ổ đĩa gần nhất của từng ổ đĩa",
        description: "Lưu hai lần quét Bản đồ ổ đĩa gần nhất của mỗi ổ đĩa trên máy tính này, để Bản đồ ổ đĩa mở ngay trên lần quét cuối và có thể cho biết những gì đã tăng. Mỗi lần quét là một cây thư mục được nén kèm các tệp lớn nhất, chiếm vài MB, tối đa khoảng 25 MB trên ổ đĩa có một triệu thư mục. Dữ liệu chỉ ở trên máy tính này. Tắt để ngừng lưu.",
        usage: (a, b) => `Lần quét tự động đã lưu: ${a} (${b})`,
        deleteQuestion: "Xóa các lần quét tự động đã được lưu?",
        deleteNow: "Xóa chúng",
        keep: "Giữ lại",
        deleted: "Đã xóa các lần quét tự động.",
        deleteFailed: (a) => `Không thể xóa: ${a}`
      },
      auto: {
        label: (a) => `Quét tự động ${a}`,
        badge: "Tự động"
      }
    }
  },
  "zh-CN": {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `${a} 的上次扫描`,
        scanned: (a) => `扫描于 ${a}`,
        note: "这是当时驱动器的样子，不是现在的。在重新扫描之前，无法将文件移到隔离区。"
      },
      growth: {
        title: "自上次扫描以来增长的内容",
        comparedWith: (a) => `与 ${a} 的扫描相比`,
        newFolder: "新增",
        nothing: "没有文件夹增长 1 MB 或更多。",
        partial: "两次扫描中有一次是部分扫描，因此这些变化可能不完整。",
        differentSize: "两次扫描之间驱动器的大小发生了变化，请谨慎比较。",
        differentMethod: "其中一次是快速扫描，另一次是遍历文件夹，因此细小的差异可能来自方式不同。",
        foldedNote: "比较的是文件夹的总计。归并为较小项目的小文件会计入所在文件夹的总计，但不会逐个比较。"
      },
      setting: {
        title: "记住每个驱动器的上次磁盘地图扫描",
        description: "为这台电脑上的每个驱动器保存最近两次磁盘地图扫描，这样磁盘地图会立即打开最近一次，并能显示增长了什么。每次扫描是附带最大文件的压缩文件夹树，占用几 MB，在有一百万个文件夹的驱动器上最多约 25 MB。它只保存在这台电脑上。关闭即可停止保存。",
        usage: (a, b) => `已保存的自动扫描：${a}（${b}）`,
        deleteQuestion: "要删除已保存的自动扫描吗？",
        deleteNow: "删除",
        keep: "保留",
        deleted: "已删除自动扫描。",
        deleteFailed: (a) => `无法删除：${a}`
      },
      auto: {
        label: (a) => `${a} 的自动扫描`,
        badge: "自动"
      }
    }
  },
  "zh-TW": {
    diskMapQolV3: {
      lastScan: {
        title: (a) => `${a} 的上次掃描`,
        scanned: (a) => `掃描於 ${a}`,
        note: "這是當時磁碟機的樣子，不是現在的。在重新掃描之前，無法將檔案移到隔離區。"
      },
      growth: {
        title: "自上次掃描以來增加的內容",
        comparedWith: (a) => `與 ${a} 的掃描相比`,
        newFolder: "新增",
        nothing: "沒有資料夾增加 1 MB 或更多。",
        partial: "兩次掃描中有一次是部分掃描，因此這些變化可能不完整。",
        differentSize: "兩次掃描之間磁碟機的大小發生了變化，請謹慎比較。",
        differentMethod: "其中一次是快速掃描，另一次是走訪資料夾，因此細小的差異可能來自方式不同。",
        foldedNote: "比較的是資料夾的總計。歸併為較小項目的小檔案會計入所在資料夾的總計，但不會逐一比較。"
      },
      setting: {
        title: "記住每個磁碟機的上次磁碟地圖掃描",
        description: "為這台電腦上的每個磁碟機儲存最近兩次磁碟地圖掃描，這樣磁碟地圖會立即開啟最近一次，並能顯示增加了什麼。每次掃描是附帶最大檔案的壓縮資料夾樹，佔用幾 MB，在有一百萬個資料夾的磁碟機上最多約 25 MB。它只會留在這台電腦上。關閉即可停止儲存。",
        usage: (a, b) => `已儲存的自動掃描：${a}（${b}）`,
        deleteQuestion: "要刪除已儲存的自動掃描嗎？",
        deleteNow: "刪除",
        keep: "保留",
        deleted: "已刪除自動掃描。",
        deleteFailed: (a) => `無法刪除：${a}`
      },
      auto: {
        label: (a) => `${a} 的自動掃描`,
        badge: "自動"
      }
    }
  }
};
