// Settings -> General -> "Always run as administrator" (opt-in, off by default), all 40 languages:
// { en: { runAsAdminV3: { ... } }, af: { ... }, ... }. Merged into the catalog by ../catalog.js; every
// key lives under runAsAdminV3. Generated by an out-of-tree script that writes every value with
// JSON.stringify, so quotes and non-ASCII text are safe. The startup-conflict text names the Startup
// screen using each language's own nav.startup label.
export default {
  en: {
    runAsAdminV3: {
      title: "Always run as administrator",
      description: "Starts Prune with administrator rights every time, using Windows' own “Run this program as administrator” setting for this copy of Prune. The fast Disk Map scan, machine-wide leftovers and scheduled tasks then need no extra prompts. You can turn it off here at any time.",
      costsHeading: "What it costs",
      costUac: "Windows asks for your approval every time Prune starts.",
      costDragDrop: "A program running as administrator can't receive files dragged from a normal Explorer window, so dragging files or folders into Prune stops working. Use the file chooser buttons instead.",
      costStartup: "It can't start silently when you sign in, because Windows asks for approval first.",
      costRights: "Everything Prune does runs with full rights, so a mistake can reach protected files.",
      nextStart: "Takes effect the next time Prune starts.",
      running: "Prune is running as administrator now.",
      unsupported: "Available in the installed Prune app. This copy can't set it.",
      startupConflict: "Prune is set to start with Windows, and Windows won't start a program that runs as administrator silently at sign-in: it asks for approval every time, or doesn't start. Turn that off in “Startup” if you'd rather not.",
      saveFailed: (m) => `Couldn't change this setting: ${m}`,
      loadFailed: (m) => `Couldn't read this setting: ${m}`
    }
  },
  af: {
    runAsAdminV3: {
      title: "Voer altyd as administrateur uit",
      description: "Begin Prune elke keer met administrateurregte, deur Windows se eie instelling “Voer hierdie program as administrateur uit” vir hierdie kopie van Prune te gebruik. Die vinnige Skyfkaart-skandering, masjienwye oorblyfsels en geskeduleerde take het dan geen ekstra versoeke nodig nie. Jy kan dit enige tyd hier afskakel.",
      costsHeading: "Wat dit kos",
      costUac: "Windows vra elke keer wat Prune begin om jou goedkeuring.",
      costDragDrop: "’n Program wat as administrateur loop, kan nie lêers ontvang wat uit ’n gewone Verkenner-venster gesleep word nie, so om lêers of vouers na Prune te sleep werk nie meer nie. Gebruik eerder die lêerkieserknoppies.",
      costStartup: "Dit kan nie stilweg begin wanneer jy aanmeld nie, want Windows vra eers om goedkeuring.",
      costRights: "Alles wat Prune doen, loop met volle regte, so ’n fout kan beskermde lêers bereik.",
      nextStart: "Tree in werking die volgende keer wat Prune begin.",
      running: "Prune loop nou as administrateur.",
      unsupported: "Beskikbaar in die geïnstalleerde Prune-toepassing. Hierdie kopie kan dit nie stel nie.",
      startupConflict: "Prune is ingestel om saam met Windows te begin, en Windows begin nie ’n program wat as administrateur loop stilweg by aanmelding nie: dit vra elke keer om goedkeuring, of begin nie. Skakel dit af onder “Opstart” as jy dit liewer nie wil hê nie.",
      saveFailed: (m) => `Kon nie hierdie instelling verander nie: ${m}`,
      loadFailed: (m) => `Kon nie hierdie instelling lees nie: ${m}`
    }
  },
  ar: {
    runAsAdminV3: {
      title: "التشغيل دائمًا كمسؤول",
      description: "يشغّل Prune بصلاحيات المسؤول في كل مرة، باستخدام إعداد Windows نفسه «تشغيل هذا البرنامج كمسؤول» لهذه النسخة من Prune. عندها لا تحتاج مسح خريطة القرص السريع والمخلفات على مستوى الجهاز والمهام المجدولة إلى أي مطالبات إضافية. يمكنك إيقافه هنا في أي وقت.",
      costsHeading: "ما الذي يكلّفه",
      costUac: "يطلب Windows موافقتك في كل مرة يبدأ فيها Prune.",
      costDragDrop: "البرنامج الذي يعمل كمسؤول لا يستطيع استقبال الملفات المسحوبة من نافذة مستكشف ملفات عادية، لذا يتوقف سحب الملفات أو المجلدات إلى Prune عن العمل. استخدم أزرار اختيار الملفات بدلًا من ذلك.",
      costStartup: "لا يمكنه البدء بصمت عند تسجيل الدخول، لأن Windows يطلب الموافقة أولًا.",
      costRights: "كل ما يفعله Prune يعمل بكامل الصلاحيات، لذلك قد يصل أي خطأ إلى ملفات محمية.",
      nextStart: "يسري عند البدء التالي لـ Prune.",
      running: "يعمل Prune الآن كمسؤول.",
      unsupported: "متاح في تطبيق Prune المثبّت. لا يمكن لهذه النسخة ضبطه.",
      startupConflict: "تم ضبط Prune ليبدأ مع Windows، ولا يبدأ Windows برنامجًا يعمل كمسؤول بصمت عند تسجيل الدخول: فهو يطلب الموافقة في كل مرة أو لا يبدأ. أوقف ذلك من «بدء التشغيل» إن كنت لا تريده.",
      saveFailed: (m) => `تعذّر تغيير هذا الإعداد: ${m}`,
      loadFailed: (m) => `تعذّرت قراءة هذا الإعداد: ${m}`
    }
  },
  ca: {
    runAsAdminV3: {
      title: "Executa sempre com a administrador",
      description: "Inicia Prune amb drets d'administrador cada vegada, amb la mateixa opció de Windows «Executa aquest programa com a administrador» per a aquesta còpia de Prune. L'exploració ràpida del Mapa del disc, les restes de tot l'equip i les tasques programades ja no necessiten més avisos. Pots desactivar-ho aquí en qualsevol moment.",
      costsHeading: "Què costa",
      costUac: "Windows et demana l'aprovació cada vegada que s'inicia Prune.",
      costDragDrop: "Un programa que s'executa com a administrador no pot rebre fitxers arrossegats des d'una finestra normal de l'Explorador, de manera que arrossegar fitxers o carpetes a Prune deixa de funcionar. Utilitza els botons de selecció de fitxers.",
      costStartup: "No pot iniciar-se en silenci en iniciar la sessió, perquè Windows demana primer l'aprovació.",
      costRights: "Tot el que fa Prune s'executa amb drets complets, de manera que un error pot arribar a fitxers protegits.",
      nextStart: "Té efecte la propera vegada que s'iniciï Prune.",
      running: "Prune s'està executant com a administrador ara.",
      unsupported: "Disponible a l'aplicació Prune instal·lada. Aquesta còpia no ho pot configurar.",
      startupConflict: "Prune està configurat per iniciar-se amb Windows, i Windows no inicia en silenci un programa que s'executa com a administrador en iniciar la sessió: demana l'aprovació cada vegada o no s'inicia. Desactiva-ho a «Inici» si prefereixes que no sigui així.",
      saveFailed: (m) => `No s'ha pogut canviar aquest ajust: ${m}`,
      loadFailed: (m) => `No s'ha pogut llegir aquest ajust: ${m}`
    }
  },
  cs: {
    runAsAdminV3: {
      title: "Vždy spouštět jako správce",
      description: "Spustí Prune pokaždé s právy správce pomocí vlastního nastavení Windows „Spustit tento program jako správce“ pro tuto kopii Prune. Rychlé prohledání Mapy disku, zbytky v celém počítači a plánované úlohy pak nevyžadují další výzvy. Můžete to tady kdykoli vypnout.",
      costsHeading: "Co to stojí",
      costUac: "Windows se pokaždé při spuštění Prune zeptá na váš souhlas.",
      costDragDrop: "Program spuštěný jako správce nemůže přijímat soubory přetažené z běžného okna Průzkumníka, takže přetahování souborů nebo složek do Prune přestane fungovat. Použijte místo toho tlačítka pro výběr souborů.",
      costStartup: "Nemůže se při přihlášení spustit potichu, protože Windows nejdřív žádá o souhlas.",
      costRights: "Vše, co Prune dělá, běží s plnými právy, takže chyba může zasáhnout chráněné soubory.",
      nextStart: "Projeví se při dalším spuštění Prune.",
      running: "Prune nyní běží jako správce.",
      unsupported: "K dispozici v nainstalované aplikaci Prune. Tato kopie to nastavit nemůže.",
      startupConflict: "Prune je nastaven ke spuštění s Windows a Windows program spuštěný jako správce při přihlášení potichu nespustí: pokaždé požádá o souhlas, nebo se nespustí. Pokud to nechcete, vypněte to v části „Po spuštění“.",
      saveFailed: (m) => `Toto nastavení se nepodařilo změnit: ${m}`,
      loadFailed: (m) => `Toto nastavení se nepodařilo přečíst: ${m}`
    }
  },
  cy: {
    runAsAdminV3: {
      title: "Rhedeg fel gweinyddwr bob amser",
      description: "Yn cychwyn Prune gyda hawliau gweinyddwr bob tro, gan ddefnyddio gosodiad Windows ei hun “Rhedeg y rhaglen hon fel gweinyddwr” ar gyfer y copi hwn o Prune. Does dim angen cadarnhau rhagor wedyn ar gyfer sgan cyflym y Map Disg, gweddillion ar draws y peiriant a thasgau wedi'u hamserlennu. Gallwch ei ddiffodd yma unrhyw bryd.",
      costsHeading: "Beth yw'r gost",
      costUac: "Mae Windows yn gofyn am eich cymeradwyaeth bob tro y bydd Prune yn cychwyn.",
      costDragDrop: "Ni all rhaglen sy'n rhedeg fel gweinyddwr dderbyn ffeiliau a lusgir o ffenestr Explorer arferol, felly mae llusgo ffeiliau neu ffolderi i Prune yn peidio â gweithio. Defnyddiwch y botymau dewis ffeiliau yn lle hynny.",
      costStartup: "Ni all gychwyn yn dawel pan fyddwch yn mewngofnodi, oherwydd mae Windows yn gofyn am gymeradwyaeth yn gyntaf.",
      costRights: "Mae popeth y mae Prune yn ei wneud yn rhedeg gyda hawliau llawn, felly gall camgymeriad gyrraedd ffeiliau gwarchodedig.",
      nextStart: "Daw i rym y tro nesaf y bydd Prune yn cychwyn.",
      running: "Mae Prune yn rhedeg fel gweinyddwr nawr.",
      unsupported: "Ar gael yn yr ap Prune sydd wedi'i osod. Ni all y copi hwn ei osod.",
      startupConflict: "Mae Prune wedi'i osod i gychwyn gyda Windows, ac nid yw Windows yn cychwyn rhaglen sy'n rhedeg fel gweinyddwr yn dawel wrth fewngofnodi: mae'n gofyn am gymeradwyaeth bob tro, neu ddim yn cychwyn. Diffoddwch hynny yn “Cychwyn” os byddai'n well gennych beidio.",
      saveFailed: (m) => `Methwyd newid y gosodiad hwn: ${m}`,
      loadFailed: (m) => `Methwyd darllen y gosodiad hwn: ${m}`
    }
  },
  da: {
    runAsAdminV3: {
      title: "Kør altid som administrator",
      description: "Starter Prune med administratorrettigheder hver gang ved hjælp af Windows' egen indstilling “Kør dette program som administrator” for denne kopi af Prune. Den hurtige Diskkort-scanning, rester på hele computeren og planlagte opgaver kræver så ingen ekstra bekræftelser. Du kan slå det fra her når som helst.",
      costsHeading: "Hvad det koster",
      costUac: "Windows beder om din godkendelse, hver gang Prune starter.",
      costDragDrop: "Et program, der kører som administrator, kan ikke modtage filer, der trækkes fra et almindeligt Stifinder-vindue, så det holder op med at virke at trække filer eller mapper ind i Prune. Brug knapperne til valg af filer i stedet.",
      costStartup: "Det kan ikke starte lydløst, når du logger på, fordi Windows først beder om godkendelse.",
      costRights: "Alt, hvad Prune gør, kører med fulde rettigheder, så en fejl kan nå beskyttede filer.",
      nextStart: "Træder i kraft, næste gang Prune starter.",
      running: "Prune kører som administrator nu.",
      unsupported: "Findes i det installerede Prune-program. Denne kopi kan ikke indstille det.",
      startupConflict: "Prune er sat til at starte sammen med Windows, og Windows starter ikke et program, der kører som administrator, lydløst ved login: det beder om godkendelse hver gang eller starter ikke. Slå det fra under “Opstart”, hvis du hellere vil det.",
      saveFailed: (m) => `Indstillingen kunne ikke ændres: ${m}`,
      loadFailed: (m) => `Indstillingen kunne ikke læses: ${m}`
    }
  },
  de: {
    runAsAdminV3: {
      title: "Immer als Administrator ausführen",
      description: "Startet Prune jedes Mal mit Administratorrechten, über die Windows-Einstellung „Programm als Administrator ausführen“ für diese Kopie von Prune. Der schnelle Datenträgerkarte-Scan, systemweite Überreste und geplante Aufgaben brauchen dann keine zusätzlichen Rückfragen. Sie können das hier jederzeit ausschalten.",
      costsHeading: "Was es kostet",
      costUac: "Windows fragt bei jedem Start von Prune nach Ihrer Zustimmung.",
      costDragDrop: "Ein Programm, das als Administrator läuft, kann keine Dateien aus einem normalen Explorer-Fenster per Ziehen und Ablegen empfangen. Dateien oder Ordner in Prune zu ziehen funktioniert dann nicht mehr. Nutzen Sie stattdessen die Schaltflächen zur Dateiauswahl.",
      costStartup: "Es kann bei der Anmeldung nicht unbemerkt starten, weil Windows zuerst um Zustimmung bittet.",
      costRights: "Alles, was Prune tut, läuft mit vollen Rechten, ein Fehler kann daher geschützte Dateien erreichen.",
      nextStart: "Wird beim nächsten Start von Prune wirksam.",
      running: "Prune läuft gerade als Administrator.",
      unsupported: "In der installierten Prune-App verfügbar. Diese Kopie kann es nicht einstellen.",
      startupConflict: "Prune startet mit Windows, aber Windows startet ein Programm, das als Administrator läuft, bei der Anmeldung nicht unbemerkt: Es fragt jedes Mal nach Zustimmung oder startet nicht. Schalten Sie das unter „Autostart“ aus, wenn Sie das nicht möchten.",
      saveFailed: (m) => `Die Einstellung konnte nicht geändert werden: ${m}`,
      loadFailed: (m) => `Die Einstellung konnte nicht gelesen werden: ${m}`
    }
  },
  el: {
    runAsAdminV3: {
      title: "Να εκτελείται πάντα ως διαχειριστής",
      description: "Ξεκινά το Prune με δικαιώματα διαχειριστή κάθε φορά, χρησιμοποιώντας τη δική του ρύθμιση των Windows «Εκτέλεση αυτού του προγράμματος ως διαχειριστής» για αυτό το αντίγραφο του Prune. Η γρήγορη σάρωση του Χάρτη δίσκου, τα υπολείμματα σε όλο το μηχάνημα και οι προγραμματισμένες εργασίες δεν χρειάζονται τότε πρόσθετες ερωτήσεις. Μπορείτε να το απενεργοποιήσετε εδώ ανά πάσα στιγμή.",
      costsHeading: "Τι κοστίζει",
      costUac: "Τα Windows ζητούν την έγκρισή σας κάθε φορά που ξεκινά το Prune.",
      costDragDrop: "Ένα πρόγραμμα που εκτελείται ως διαχειριστής δεν μπορεί να λάβει αρχεία που σύρονται από ένα κανονικό παράθυρο της Εξερεύνησης, οπότε η μεταφορά αρχείων ή φακέλων στο Prune σταματά να λειτουργεί. Χρησιμοποιήστε τα κουμπιά επιλογής αρχείων.",
      costStartup: "Δεν μπορεί να ξεκινήσει αθόρυβα κατά τη σύνδεση, επειδή τα Windows ζητούν πρώτα έγκριση.",
      costRights: "Ό,τι κάνει το Prune εκτελείται με πλήρη δικαιώματα, οπότε ένα λάθος μπορεί να φτάσει σε προστατευμένα αρχεία.",
      nextStart: "Τίθεται σε ισχύ στην επόμενη εκκίνηση του Prune.",
      running: "Το Prune εκτελείται τώρα ως διαχειριστής.",
      unsupported: "Διαθέσιμο στην εγκατεστημένη εφαρμογή Prune. Αυτό το αντίγραφο δεν μπορεί να το ορίσει.",
      startupConflict: "Το Prune έχει οριστεί να ξεκινά με τα Windows, και τα Windows δεν ξεκινούν αθόρυβα κατά τη σύνδεση ένα πρόγραμμα που εκτελείται ως διαχειριστής: ζητούν έγκριση κάθε φορά ή δεν ξεκινά. Απενεργοποιήστε το στην ενότητα «Εκκίνηση» αν προτιμάτε.",
      saveFailed: (m) => `Δεν ήταν δυνατή η αλλαγή αυτής της ρύθμισης: ${m}`,
      loadFailed: (m) => `Δεν ήταν δυνατή η ανάγνωση αυτής της ρύθμισης: ${m}`
    }
  },
  es: {
    runAsAdminV3: {
      title: "Ejecutar siempre como administrador",
      description: "Inicia Prune con derechos de administrador cada vez, usando el propio ajuste de Windows «Ejecutar este programa como administrador» para esta copia de Prune. El análisis rápido del Mapa del disco, los restos de todo el equipo y las tareas programadas dejan de necesitar avisos adicionales. Puedes desactivarlo aquí en cualquier momento.",
      costsHeading: "Lo que cuesta",
      costUac: "Windows pide tu aprobación cada vez que se inicia Prune.",
      costDragDrop: "Un programa que se ejecuta como administrador no puede recibir archivos arrastrados desde una ventana normal del Explorador, así que arrastrar archivos o carpetas a Prune deja de funcionar. Usa los botones de selección de archivos.",
      costStartup: "No puede iniciarse en silencio al iniciar sesión, porque Windows pide primero la aprobación.",
      costRights: "Todo lo que hace Prune se ejecuta con todos los derechos, así que un error puede alcanzar archivos protegidos.",
      nextStart: "Surte efecto la próxima vez que se inicie Prune.",
      running: "Prune se está ejecutando como administrador ahora.",
      unsupported: "Disponible en la aplicación Prune instalada. Esta copia no puede configurarlo.",
      startupConflict: "Prune está configurado para iniciarse con Windows, y Windows no inicia en silencio un programa que se ejecuta como administrador al iniciar sesión: pide la aprobación cada vez, o no se inicia. Desactívalo en «Inicio» si prefieres que no sea así.",
      saveFailed: (m) => `No se pudo cambiar este ajuste: ${m}`,
      loadFailed: (m) => `No se pudo leer este ajuste: ${m}`
    }
  },
  et: {
    runAsAdminV3: {
      title: "Käivita alati administraatorina",
      description: "Käivitab Pruned iga kord administraatoriõigustega, kasutades selle Pruned koopia jaoks Windowsi enda sätet „Käivita see programm administraatorina“. Kiire kettakaardi skannimine, kogu arvuti jäägid ja ajastatud ülesanded ei vaja siis lisakinnitusi. Saad selle siin igal ajal välja lülitada.",
      costsHeading: "Mis see maksab",
      costUac: "Windows küsib sinu nõusolekut iga kord, kui Prune käivitub.",
      costDragDrop: "Administraatorina töötav programm ei saa vastu võtta faile, mida lohistatakse tavalisest Exploreri aknast, mistõttu failide või kaustade lohistamine Prunesse lakkab töötamast. Kasuta selle asemel failivaliku nuppe.",
      costStartup: "See ei saa sisselogimisel vaikselt käivituda, sest Windows küsib esmalt nõusolekut.",
      costRights: "Kõik, mida Prune teeb, töötab täisõigustega, nii et viga võib jõuda kaitstud failideni.",
      nextStart: "Jõustub Pruned järgmisel käivitamisel.",
      running: "Prune töötab praegu administraatorina.",
      unsupported: "Saadaval installitud Pruned rakenduses. See koopia ei saa seda seadistada.",
      startupConflict: "Prune on seatud koos Windowsiga käivituma ning Windows ei käivita administraatorina töötavat programmi sisselogimisel vaikselt: see küsib nõusolekut iga kord või ei käivitu. Lülita see välja jaotises „Käivitus“, kui eelistad nii.",
      saveFailed: (m) => `Seda sätet ei saanud muuta: ${m}`,
      loadFailed: (m) => `Seda sätet ei saanud lugeda: ${m}`
    }
  },
  fi: {
    runAsAdminV3: {
      title: "Suorita aina järjestelmänvalvojana",
      description: "Käynnistää Prunen joka kerta järjestelmänvalvojan oikeuksilla Windowsin oman asetuksen ”Suorita tämä ohjelma järjestelmänvalvojana” avulla tälle Prunen kopiolle. Nopea levykartan tarkistus, koko koneen jäämät ja ajastetut tehtävät eivät sen jälkeen tarvitse lisäkehotteita. Voit poistaa tämän käytöstä täällä milloin tahansa.",
      costsHeading: "Mitä se maksaa",
      costUac: "Windows kysyy lupaasi joka kerta, kun Prune käynnistyy.",
      costDragDrop: "Järjestelmänvalvojana toimiva ohjelma ei voi vastaanottaa tiedostoja, joita vedetään tavallisesta Resurssienhallinnan ikkunasta, joten tiedostojen tai kansioiden vetäminen Pruneen lakkaa toimimasta. Käytä sen sijaan tiedostonvalintapainikkeita.",
      costStartup: "Se ei voi käynnistyä äänettömästi kirjautuessasi, koska Windows pyytää ensin hyväksyntää.",
      costRights: "Kaikki, mitä Prune tekee, toimii täysin oikeuksin, joten virhe voi osua suojattuihin tiedostoihin.",
      nextStart: "Tulee voimaan, kun Prune käynnistyy seuraavan kerran.",
      running: "Prune toimii nyt järjestelmänvalvojana.",
      unsupported: "Käytettävissä asennetussa Prune-sovelluksessa. Tämä kopio ei voi asettaa sitä.",
      startupConflict: "Prune on asetettu käynnistymään Windowsin mukana, eikä Windows käynnistä järjestelmänvalvojana toimivaa ohjelmaa äänettömästi kirjautuessa: se pyytää hyväksyntää joka kerta tai ohjelma ei käynnisty. Poista se käytöstä kohdassa ”Käynnistys”, jos haluat niin.",
      saveFailed: (m) => `Asetusta ei voitu muuttaa: ${m}`,
      loadFailed: (m) => `Asetusta ei voitu lukea: ${m}`
    }
  },
  fr: {
    runAsAdminV3: {
      title: "Toujours exécuter en tant qu'administrateur",
      description: "Lance Prune avec les droits d'administrateur à chaque fois, grâce au paramètre Windows « Exécuter ce programme en tant qu'administrateur » appliqué à cette copie de Prune. L'analyse rapide de la Carte du disque, les restes à l'échelle de la machine et les tâches planifiées n'ont alors plus besoin de confirmations supplémentaires. Vous pouvez le désactiver ici à tout moment.",
      costsHeading: "Ce que cela coûte",
      costUac: "Windows demande votre accord à chaque démarrage de Prune.",
      costDragDrop: "Un programme exécuté en tant qu'administrateur ne peut pas recevoir de fichiers glissés depuis une fenêtre normale de l'Explorateur : glisser des fichiers ou des dossiers dans Prune ne fonctionne plus. Utilisez plutôt les boutons de sélection de fichiers.",
      costStartup: "Il ne peut pas démarrer discrètement à l'ouverture de session, car Windows demande d'abord une autorisation.",
      costRights: "Tout ce que fait Prune s'exécute avec tous les droits : une erreur peut donc atteindre des fichiers protégés.",
      nextStart: "Prend effet au prochain démarrage de Prune.",
      running: "Prune s'exécute actuellement en tant qu'administrateur.",
      unsupported: "Disponible dans l'application Prune installée. Cette copie ne peut pas le définir.",
      startupConflict: "Prune est réglé pour démarrer avec Windows, et Windows ne lance pas discrètement à l'ouverture de session un programme exécuté en tant qu'administrateur : il demande une autorisation à chaque fois, ou ne démarre pas. Désactivez-le dans « Démarrage » si vous préférez.",
      saveFailed: (m) => `Impossible de modifier ce paramètre : ${m}`,
      loadFailed: (m) => `Impossible de lire ce paramètre : ${m}`
    }
  },
  he: {
    runAsAdminV3: {
      title: "הפעל תמיד כמנהל",
      description: "מפעיל את Prune עם הרשאות מנהל בכל פעם, באמצעות ההגדרה של Windows ‏„הפעל תוכנית זו כמנהל“ עבור עותק זה של Prune. סריקת מפת הדיסק המהירה, שאריות ברחבי המחשב ומשימות מתוזמנות לא יצריכו אז אישורים נוספים. אפשר לכבות זאת כאן בכל עת.",
      costsHeading: "מה המחיר",
      costUac: "Windows מבקש את אישורכם בכל פעם ש-Prune מתחיל לפעול.",
      costDragDrop: "תוכנה שרצה כמנהל אינה יכולה לקבל קבצים שנגררים מחלון רגיל של סייר הקבצים, ולכן גרירת קבצים או תיקיות אל Prune מפסיקה לעבוד. השתמשו בכפתורי בחירת הקבצים במקום.",
      costStartup: "היא לא יכולה להתחיל בשקט בעת הכניסה, כי Windows מבקש קודם אישור.",
      costRights: "כל מה ש-Prune עושה רץ עם הרשאות מלאות, ולכן טעות עלולה להגיע לקבצים מוגנים.",
      nextStart: "ייכנס לתוקף בפעם הבאה ש-Prune יתחיל לפעול.",
      running: "Prune רץ כרגע כמנהל.",
      unsupported: "זמין באפליקציית Prune המותקנת. עותק זה אינו יכול להגדיר זאת.",
      startupConflict: "Prune מוגדר להתחיל עם Windows, ו-Windows אינו מפעיל בשקט בעת הכניסה תוכנה שרצה כמנהל: הוא מבקש אישור בכל פעם, או שהתוכנה לא מתחילה. כבו זאת ב„הפעלה“ אם אתם מעדיפים.",
      saveFailed: (m) => `לא ניתן היה לשנות הגדרה זו: ${m}`,
      loadFailed: (m) => `לא ניתן היה לקרוא הגדרה זו: ${m}`
    }
  },
  hu: {
    runAsAdminV3: {
      title: "Mindig futtatás rendszergazdaként",
      description: "A Prune-t minden alkalommal rendszergazdai jogokkal indítja, a Windows saját „Program futtatása rendszergazdaként” beállításával a Prune ezen példányához. A gyors Lemezkártya-vizsgálat, a gépszintű maradványok és az ütemezett feladatok ezután nem kérnek további jóváhagyást. Itt bármikor kikapcsolhatja.",
      costsHeading: "Mibe kerül",
      costUac: "A Windows minden Prune-indításkor kéri a jóváhagyását.",
      costDragDrop: "A rendszergazdaként futó program nem fogad fájlokat egy normál Fájlkezelő-ablakból húzva, ezért a fájlok vagy mappák Prune-ba húzása nem működik. Használja helyette a fájlválasztó gombokat.",
      costStartup: "Bejelentkezéskor nem indulhat el csendben, mert a Windows előbb jóváhagyást kér.",
      costRights: "Minden, amit a Prune tesz, teljes jogokkal fut, ezért egy hiba védett fájlokat is elérhet.",
      nextStart: "A Prune következő indításakor lép életbe.",
      running: "A Prune most rendszergazdaként fut.",
      unsupported: "A telepített Prune alkalmazásban érhető el. Ez a példány nem tudja beállítani.",
      startupConflict: "A Prune úgy van beállítva, hogy a Windows-szal induljon, a Windows viszont nem indít csendben bejelentkezéskor rendszergazdaként futó programot: minden alkalommal jóváhagyást kér, vagy nem indul el. Kapcsolja ki a(z) „Indítás” részben, ha nem szeretné.",
      saveFailed: (m) => `Nem sikerült módosítani ezt a beállítást: ${m}`,
      loadFailed: (m) => `Nem sikerült beolvasni ezt a beállítást: ${m}`
    }
  },
  id: {
    runAsAdminV3: {
      title: "Selalu jalankan sebagai administrator",
      description: "Memulai Prune dengan hak administrator setiap kali, memakai pengaturan Windows “Jalankan program ini sebagai administrator” untuk salinan Prune ini. Pemindaian cepat Peta Disk, sisa di seluruh komputer, dan tugas terjadwal tidak lagi memerlukan konfirmasi tambahan. Anda dapat mematikannya di sini kapan saja.",
      costsHeading: "Apa biayanya",
      costUac: "Windows meminta persetujuan Anda setiap kali Prune dimulai.",
      costDragDrop: "Program yang berjalan sebagai administrator tidak dapat menerima berkas yang diseret dari jendela File Explorer biasa, sehingga menyeret berkas atau folder ke Prune tidak lagi berfungsi. Gunakan tombol pemilih berkas.",
      costStartup: "Program tidak dapat dimulai secara senyap saat Anda masuk, karena Windows meminta persetujuan terlebih dahulu.",
      costRights: "Semua yang dilakukan Prune berjalan dengan hak penuh, sehingga kesalahan dapat menjangkau berkas yang dilindungi.",
      nextStart: "Berlaku saat Prune dimulai berikutnya.",
      running: "Prune sedang berjalan sebagai administrator.",
      unsupported: "Tersedia di aplikasi Prune yang terpasang. Salinan ini tidak dapat mengaturnya.",
      startupConflict: "Prune diatur untuk mulai bersama Windows, dan Windows tidak memulai program yang berjalan sebagai administrator secara senyap saat masuk: Windows meminta persetujuan setiap kali, atau program tidak dimulai. Matikan di “Startup” jika Anda tidak menginginkannya.",
      saveFailed: (m) => `Tidak dapat mengubah pengaturan ini: ${m}`,
      loadFailed: (m) => `Tidak dapat membaca pengaturan ini: ${m}`
    }
  },
  is: {
    runAsAdminV3: {
      title: "Keyra alltaf sem stjórnandi",
      description: "Ræsir Prune með stjórnandaréttindum í hvert sinn með eigin stillingu Windows „Keyra þetta forrit sem stjórnandi“ fyrir þetta eintak af Prune. Hröð skönnun Diskakorts, leifar á allri tölvunni og áætluð verkefni þurfa þá engar auka staðfestingar. Þú getur slökkt á þessu hér hvenær sem er.",
      costsHeading: "Hvað það kostar",
      costUac: "Windows biður um samþykki þitt í hvert sinn sem Prune ræsist.",
      costDragDrop: "Forrit sem keyrir sem stjórnandi getur ekki tekið við skrám sem dregnar eru úr venjulegum Explorer-glugga, svo að það hættir að virka að draga skrár eða möppur inn í Prune. Notaðu skráavalshnappana í staðinn.",
      costStartup: "Það getur ekki ræst hljóðlaust þegar þú skráir þig inn því að Windows biður fyrst um samþykki.",
      costRights: "Allt sem Prune gerir keyrir með fullum réttindum, svo mistök geta náð til varinna skráa.",
      nextStart: "Tekur gildi næst þegar Prune ræsist.",
      running: "Prune keyrir nú sem stjórnandi.",
      unsupported: "Í boði í uppsettu Prune-forriti. Þetta eintak getur ekki stillt það.",
      startupConflict: "Prune er stillt á að ræsast með Windows og Windows ræsir ekki forrit sem keyrir sem stjórnandi hljóðlaust við innskráningu: það biður um samþykki í hvert sinn eða ræsist ekki. Slökktu á því í „Ræsing“ ef þú vilt það ekki.",
      saveFailed: (m) => `Ekki tókst að breyta þessari stillingu: ${m}`,
      loadFailed: (m) => `Ekki tókst að lesa þessa stillingu: ${m}`
    }
  },
  it: {
    runAsAdminV3: {
      title: "Esegui sempre come amministratore",
      description: "Avvia Prune ogni volta con i privilegi di amministratore, usando l'impostazione di Windows «Esegui questo programma come amministratore» per questa copia di Prune. La scansione rapida della Mappa disco, i residui di tutto il computer e le attività pianificate non richiedono più conferme aggiuntive. Puoi disattivarlo qui in qualsiasi momento.",
      costsHeading: "Cosa costa",
      costUac: "Windows chiede la tua approvazione ogni volta che Prune si avvia.",
      costDragDrop: "Un programma eseguito come amministratore non può ricevere file trascinati da una normale finestra di Esplora file, quindi trascinare file o cartelle in Prune smette di funzionare. Usa invece i pulsanti di selezione dei file.",
      costStartup: "Non può avviarsi in silenzio all'accesso, perché Windows chiede prima l'approvazione.",
      costRights: "Tutto ciò che fa Prune viene eseguito con tutti i privilegi, quindi un errore può raggiungere file protetti.",
      nextStart: "Ha effetto al prossimo avvio di Prune.",
      running: "Prune è in esecuzione come amministratore.",
      unsupported: "Disponibile nell'app Prune installata. Questa copia non può impostarlo.",
      startupConflict: "Prune è impostato per avviarsi con Windows, e Windows non avvia in silenzio all'accesso un programma eseguito come amministratore: chiede l'approvazione ogni volta, oppure non si avvia. Disattivalo in «Avvio» se preferisci.",
      saveFailed: (m) => `Impossibile modificare questa impostazione: ${m}`,
      loadFailed: (m) => `Impossibile leggere questa impostazione: ${m}`
    }
  },
  ja: {
    runAsAdminV3: {
      title: "常に管理者として実行",
      description: "Windows 標準の「このプログラムを管理者として実行する」設定をこの Prune に適用し、毎回管理者権限で起動します。高速なディスクマップのスキャン、PC 全体の残骸、スケジュールされたタスクで追加の確認が不要になります。ここでいつでもオフにできます。",
      costsHeading: "代償",
      costUac: "Prune を起動するたびに、Windows が承認を求めます。",
      costDragDrop: "管理者として実行中のプログラムは、通常のエクスプローラーのウィンドウからドラッグされたファイルを受け取れないため、Prune へのファイルやフォルダーのドラッグが機能しなくなります。代わりにファイル選択ボタンを使ってください。",
      costStartup: "Windows が先に承認を求めるため、サインイン時に無音で起動することはできません。",
      costRights: "Prune の操作はすべてフル権限で実行されるため、操作ミスが保護されたファイルに及ぶ可能性があります。",
      nextStart: "次回 Prune を起動したときから有効になります。",
      running: "Prune は現在、管理者として実行されています。",
      unsupported: "インストール版の Prune アプリで利用できます。このコピーでは設定できません。",
      startupConflict: "Prune は Windows と同時に起動する設定になっていますが、Windows は管理者として実行するプログラムをサインイン時に無音では起動しません。毎回承認を求めるか、起動しません。望まない場合は「スタートアップ」でオフにしてください。",
      saveFailed: (m) => `この設定を変更できませんでした: ${m}`,
      loadFailed: (m) => `この設定を読み取れませんでした: ${m}`
    }
  },
  ko: {
    runAsAdminV3: {
      title: "항상 관리자 권한으로 실행",
      description: "이 Prune 사본에 Windows 자체 설정인 “이 프로그램을 관리자 권한으로 실행”을 적용해 매번 관리자 권한으로 시작합니다. 그러면 빠른 디스크 맵 검사, 컴퓨터 전체의 잔여물, 예약된 작업에 추가 확인이 필요 없습니다. 여기에서 언제든지 끌 수 있습니다.",
      costsHeading: "감수해야 할 점",
      costUac: "Prune이 시작될 때마다 Windows가 승인을 요청합니다.",
      costDragDrop: "관리자 권한으로 실행되는 프로그램은 일반 탐색기 창에서 끌어온 파일을 받을 수 없어서, Prune으로 파일이나 폴더를 끌어다 놓는 기능이 작동하지 않습니다. 대신 파일 선택 버튼을 사용하세요.",
      costStartup: "Windows가 먼저 승인을 요청하므로 로그인할 때 조용히 시작할 수 없습니다.",
      costRights: "Prune이 하는 모든 작업이 전체 권한으로 실행되므로 실수가 보호된 파일에 영향을 줄 수 있습니다.",
      nextStart: "다음에 Prune을 시작할 때부터 적용됩니다.",
      running: "Prune이 지금 관리자 권한으로 실행 중입니다.",
      unsupported: "설치된 Prune 앱에서 사용할 수 있습니다. 이 사본에서는 설정할 수 없습니다.",
      startupConflict: "Prune이 Windows와 함께 시작되도록 설정되어 있지만, Windows는 관리자 권한으로 실행되는 프로그램을 로그인 시 조용히 시작하지 않습니다. 매번 승인을 요청하거나 시작되지 않습니다. 원하지 않으면 “시작 프로그램”에서 끄세요.",
      saveFailed: (m) => `이 설정을 변경할 수 없습니다: ${m}`,
      loadFailed: (m) => `이 설정을 읽을 수 없습니다: ${m}`
    }
  },
  lt: {
    runAsAdminV3: {
      title: "Visada vykdyti kaip administratorių",
      description: "Kaskart paleidžia „Prune“ su administratoriaus teisėmis, naudodama paties „Windows“ nustatymą „Vykdyti šią programą kaip administratorių“ šiai „Prune“ kopijai. Greitam disko žemėlapio nuskaitymui, viso kompiuterio likučiams ir suplanuotoms užduotims tada nereikia papildomų patvirtinimų. Galite tai išjungti čia bet kada.",
      costsHeading: "Kiek tai kainuoja",
      costUac: "„Windows“ prašo jūsų patvirtinimo kaskart, kai paleidžiama „Prune“.",
      costDragDrop: "Kaip administratorius veikianti programa negali gauti failų, vilkomų iš įprasto „Explorer“ lango, todėl failų ar aplankų vilkimas į „Prune“ nustoja veikti. Naudokite failų pasirinkimo mygtukus.",
      costStartup: "Ji negali tyliai pasileisti prisijungus, nes „Windows“ pirmiausia prašo patvirtinimo.",
      costRights: "Viskas, ką daro „Prune“, vykdoma su visomis teisėmis, todėl klaida gali pasiekti apsaugotus failus.",
      nextStart: "Įsigalioja kitą kartą paleidus „Prune“.",
      running: "„Prune“ dabar veikia kaip administratorius.",
      unsupported: "Pasiekiama įdiegtoje „Prune“ programoje. Ši kopija jos nustatyti negali.",
      startupConflict: "„Prune“ nustatyta paleisti kartu su „Windows“, o „Windows“ prisijungiant tyliai nepaleidžia kaip administratorius veikiančios programos: ji kaskart prašo patvirtinimo arba nepasileidžia. Jei nenorite, išjunkite tai skiltyje „Paleistis“.",
      saveFailed: (m) => `Nepavyko pakeisti šio nustatymo: ${m}`,
      loadFailed: (m) => `Nepavyko perskaityti šio nustatymo: ${m}`
    }
  },
  ms: {
    runAsAdminV3: {
      title: "Sentiasa jalankan sebagai pentadbir",
      description: "Memulakan Prune dengan hak pentadbir setiap kali, menggunakan tetapan Windows sendiri “Jalankan program ini sebagai pentadbir” untuk salinan Prune ini. Imbasan pantas Peta Cakera, sisa seluruh komputer dan tugas berjadual tidak memerlukan gesaan tambahan lagi. Anda boleh mematikannya di sini pada bila-bila masa.",
      costsHeading: "Apa kosnya",
      costUac: "Windows meminta kebenaran anda setiap kali Prune bermula.",
      costDragDrop: "Program yang berjalan sebagai pentadbir tidak boleh menerima fail yang diseret dari tetingkap File Explorer biasa, jadi menyeret fail atau folder ke dalam Prune tidak lagi berfungsi. Gunakan butang pemilih fail sebaliknya.",
      costStartup: "Ia tidak boleh bermula secara senyap semasa anda log masuk, kerana Windows meminta kebenaran dahulu.",
      costRights: "Semua yang dilakukan Prune berjalan dengan hak penuh, jadi kesilapan boleh sampai ke fail yang dilindungi.",
      nextStart: "Berkuat kuasa apabila Prune bermula seterusnya.",
      running: "Prune sedang berjalan sebagai pentadbir sekarang.",
      unsupported: "Tersedia dalam aplikasi Prune yang dipasang. Salinan ini tidak dapat menetapkannya.",
      startupConflict: "Prune ditetapkan untuk bermula bersama Windows, dan Windows tidak memulakan program yang berjalan sebagai pentadbir secara senyap semasa log masuk: ia meminta kebenaran setiap kali, atau tidak bermula. Matikannya di “Permulaan” jika anda tidak mahu.",
      saveFailed: (m) => `Tidak dapat mengubah tetapan ini: ${m}`,
      loadFailed: (m) => `Tidak dapat membaca tetapan ini: ${m}`
    }
  },
  nb: {
    runAsAdminV3: {
      title: "Kjør alltid som administrator",
      description: "Starter Prune med administratorrettigheter hver gang, ved hjelp av Windows’ egen innstilling «Kjør dette programmet som administrator» for denne kopien av Prune. Den raske Diskkart-skanningen, rester på hele maskinen og planlagte oppgaver trenger da ingen ekstra bekreftelser. Du kan slå det av her når som helst.",
      costsHeading: "Hva det koster",
      costUac: "Windows ber om godkjenning hver gang Prune starter.",
      costDragDrop: "Et program som kjører som administrator, kan ikke motta filer som dras fra et vanlig Utforsker-vindu, så det slutter å fungere å dra filer eller mapper inn i Prune. Bruk knappene for filvalg i stedet.",
      costStartup: "Det kan ikke starte stille når du logger på, fordi Windows ber om godkjenning først.",
      costRights: "Alt Prune gjør, kjører med fulle rettigheter, så en feil kan nå beskyttede filer.",
      nextStart: "Trer i kraft neste gang Prune starter.",
      running: "Prune kjører som administrator nå.",
      unsupported: "Tilgjengelig i den installerte Prune-appen. Denne kopien kan ikke angi det.",
      startupConflict: "Prune er satt til å starte sammen med Windows, og Windows starter ikke et program som kjører som administrator, stille ved pålogging: det ber om godkjenning hver gang, eller starter ikke. Slå det av under «Oppstart» hvis du heller vil det.",
      saveFailed: (m) => `Kunne ikke endre denne innstillingen: ${m}`,
      loadFailed: (m) => `Kunne ikke lese denne innstillingen: ${m}`
    }
  },
  nl: {
    runAsAdminV3: {
      title: "Altijd als administrator uitvoeren",
      description: "Start Prune telkens met administratorrechten, via de eigen Windows-instelling “Dit programma als administrator uitvoeren” voor deze kopie van Prune. De snelle Schijfkaart-scan, resten op de hele computer en geplande taken hebben dan geen extra bevestigingen nodig. U kunt dit hier op elk moment uitschakelen.",
      costsHeading: "Wat het kost",
      costUac: "Windows vraagt telkens om uw goedkeuring wanneer Prune start.",
      costDragDrop: "Een programma dat als administrator draait, kan geen bestanden ontvangen die uit een gewoon Verkenner-venster worden gesleept, dus bestanden of mappen naar Prune slepen werkt niet meer. Gebruik in plaats daarvan de knoppen voor bestandskeuze.",
      costStartup: "Het kan niet stil starten wanneer u zich aanmeldt, omdat Windows eerst om goedkeuring vraagt.",
      costRights: "Alles wat Prune doet, draait met volledige rechten, dus een fout kan beschermde bestanden bereiken.",
      nextStart: "Gaat in bij de volgende start van Prune.",
      running: "Prune draait nu als administrator.",
      unsupported: "Beschikbaar in de geïnstalleerde Prune-app. Deze kopie kan het niet instellen.",
      startupConflict: "Prune is ingesteld om met Windows te starten, en Windows start een programma dat als administrator draait niet stil bij het aanmelden: het vraagt telkens om goedkeuring of start niet. Schakel dat uit onder “Opstarten” als u dat liever niet wilt.",
      saveFailed: (m) => `Kon deze instelling niet wijzigen: ${m}`,
      loadFailed: (m) => `Kon deze instelling niet lezen: ${m}`
    }
  },
  pl: {
    runAsAdminV3: {
      title: "Zawsze uruchamiaj jako administrator",
      description: "Za każdym razem uruchamia Prune z uprawnieniami administratora, używając ustawienia Windows „Uruchom ten program jako administrator” dla tej kopii Prune. Szybkie skanowanie Mapy dysku, pozostałości w całym komputerze i zaplanowane zadania nie wymagają wtedy dodatkowych potwierdzeń. Możesz to tutaj wyłączyć w dowolnej chwili.",
      costsHeading: "Jaki jest koszt",
      costUac: "Windows prosi o Twoją zgodę przy każdym uruchomieniu Prune.",
      costDragDrop: "Program uruchomiony jako administrator nie może odbierać plików przeciąganych ze zwykłego okna Eksploratora, więc przeciąganie plików lub folderów do Prune przestaje działać. Zamiast tego użyj przycisków wyboru plików.",
      costStartup: "Nie może uruchomić się po cichu przy logowaniu, ponieważ Windows najpierw prosi o zgodę.",
      costRights: "Wszystko, co robi Prune, działa z pełnymi uprawnieniami, więc pomyłka może dotknąć chronionych plików.",
      nextStart: "Zacznie obowiązywać przy następnym uruchomieniu Prune.",
      running: "Prune działa teraz jako administrator.",
      unsupported: "Dostępne w zainstalowanej aplikacji Prune. Ta kopia nie może tego ustawić.",
      startupConflict: "Prune jest ustawiony tak, by uruchamiać się z Windows, a Windows nie uruchamia po cichu przy logowaniu programu działającego jako administrator: prosi o zgodę za każdym razem albo się nie uruchamia. Wyłącz to w sekcji „Autostart”, jeśli wolisz.",
      saveFailed: (m) => `Nie udało się zmienić tego ustawienia: ${m}`,
      loadFailed: (m) => `Nie udało się odczytać tego ustawienia: ${m}`
    }
  },
  ps: {
    runAsAdminV3: {
      title: "تل د مدیر په توګه چلول",
      description: "Prune هر ځل د مدیر له حقونو سره پیلوي، د Windows د خپل تنظیم “دا برنامه د مدیر په توګه چلول” په کارولو سره د Prune د دې کاپي لپاره. بیا د ډیسک نقشې چټک سکین، د ټول کمپیوټر پاتې شوني او مهالویش شوې دندې نور اضافي پوښتنې نه غواړي. تاسو کولای شئ دا دلته هر وخت بند کړئ.",
      costsHeading: "څه لګښت لري",
      costUac: "Windows هر ځل ستاسو تصویب غواړي کله چې Prune پیل شي.",
      costDragDrop: "هغه برنامه چې د مدیر په توګه چلېږي، هغه فایلونه نشي منلای چې له عادي Explorer کړکۍ څخه راکاږل کېږي، نو Prune ته د فایلونو یا پوښۍ راکاږل کار نه کوي. پر ځای یې د فایل انتخاب تڼۍ وکاروئ.",
      costStartup: "دا نشي کولای کله چې ننوځئ په چوپه پیل شي، ځکه چې Windows لومړی تصویب غواړي.",
      costRights: "هر څه چې Prune کوي په بشپړو حقونو چلېږي، نو یوه تېروتنه کېدای شي خوندي فایلونو ته ورسېږي.",
      nextStart: "د Prune په بل پیل کې اغېز کوي.",
      running: "Prune اوس د مدیر په توګه چلېږي.",
      unsupported: "د نصب شوې Prune په اپ کې شته. دا کاپي یې نشي تنظیمولای.",
      startupConflict: "Prune د Windows سره د پیل لپاره ټاکل شوی، او Windows هغه برنامه چې د مدیر په توګه چلېږي د ننوتلو پر مهال په چوپه نه پیلوي: دا هر ځل تصویب غواړي، یا نه پیلېږي. که تاسو نه غواړئ، دا په «پیل» کې بند کړئ.",
      saveFailed: (m) => `دا تنظیم بدل نشو: ${m}`,
      loadFailed: (m) => `دا تنظیم ولوستل نشو: ${m}`
    }
  },
  "pt-BR": {
    runAsAdminV3: {
      title: "Sempre executar como administrador",
      description: "Inicia o Prune com direitos de administrador toda vez, usando a própria configuração do Windows “Executar este programa como administrador” para esta cópia do Prune. A verificação rápida do Mapa do disco, os restos em todo o computador e as tarefas agendadas deixam de precisar de confirmações extras. Você pode desativar isso aqui a qualquer momento.",
      costsHeading: "O que isso custa",
      costUac: "O Windows pede sua aprovação toda vez que o Prune inicia.",
      costDragDrop: "Um programa executado como administrador não pode receber arquivos arrastados de uma janela normal do Explorador de Arquivos, então arrastar arquivos ou pastas para o Prune deixa de funcionar. Use os botões de seleção de arquivos.",
      costStartup: "Ele não pode iniciar silenciosamente quando você entra, porque o Windows pede aprovação antes.",
      costRights: "Tudo o que o Prune faz é executado com todos os direitos, então um erro pode alcançar arquivos protegidos.",
      nextStart: "Entra em vigor na próxima vez que o Prune iniciar.",
      running: "O Prune está sendo executado como administrador agora.",
      unsupported: "Disponível no aplicativo Prune instalado. Esta cópia não pode defini-lo.",
      startupConflict: "O Prune está configurado para iniciar com o Windows, e o Windows não inicia silenciosamente, no logon, um programa executado como administrador: ele pede aprovação toda vez, ou não inicia. Desative isso em “Inicialização” se preferir.",
      saveFailed: (m) => `Não foi possível alterar esta configuração: ${m}`,
      loadFailed: (m) => `Não foi possível ler esta configuração: ${m}`
    }
  },
  pt: {
    runAsAdminV3: {
      title: "Executar sempre como administrador",
      description: "Inicia o Prune com direitos de administrador de cada vez, usando a própria definição do Windows “Executar este programa como administrador” para esta cópia do Prune. A análise rápida do Mapa do disco, os restos em todo o computador e as tarefas agendadas deixam de precisar de confirmações adicionais. Pode desativá-lo aqui a qualquer momento.",
      costsHeading: "O que custa",
      costUac: "O Windows pede a sua aprovação sempre que o Prune inicia.",
      costDragDrop: "Um programa executado como administrador não pode receber ficheiros arrastados de uma janela normal do Explorador de Ficheiros, pelo que arrastar ficheiros ou pastas para o Prune deixa de funcionar. Utilize os botões de seleção de ficheiros.",
      costStartup: "Não pode iniciar silenciosamente quando inicia sessão, porque o Windows pede primeiro aprovação.",
      costRights: "Tudo o que o Prune faz é executado com todos os direitos, pelo que um erro pode atingir ficheiros protegidos.",
      nextStart: "Produz efeito da próxima vez que o Prune iniciar.",
      running: "O Prune está a ser executado como administrador agora.",
      unsupported: "Disponível na aplicação Prune instalada. Esta cópia não o pode definir.",
      startupConflict: "O Prune está definido para iniciar com o Windows, e o Windows não inicia silenciosamente, ao iniciar sessão, um programa executado como administrador: pede aprovação de cada vez, ou não inicia. Desative isso em “Arranque” se preferir.",
      saveFailed: (m) => `Não foi possível alterar esta definição: ${m}`,
      loadFailed: (m) => `Não foi possível ler esta definição: ${m}`
    }
  },
  ro: {
    runAsAdminV3: {
      title: "Rulează întotdeauna ca administrator",
      description: "Pornește Prune de fiecare dată cu drepturi de administrator, folosind setarea proprie a Windows „Execută acest program ca administrator” pentru această copie a Prune. Scanarea rapidă a Hărții discului, resturile de pe tot computerul și sarcinile programate nu mai au nevoie de confirmări suplimentare. Îl poți dezactiva aici oricând.",
      costsHeading: "Ce costă",
      costUac: "Windows îți cere aprobarea de fiecare dată când pornește Prune.",
      costDragDrop: "Un program care rulează ca administrator nu poate primi fișiere trase dintr-o fereastră obișnuită din Explorator, deci tragerea fișierelor sau folderelor în Prune nu mai funcționează. Folosește în schimb butoanele de selectare a fișierelor.",
      costStartup: "Nu poate porni discret la autentificare, pentru că Windows cere mai întâi aprobarea.",
      costRights: "Tot ce face Prune rulează cu drepturi depline, deci o greșeală poate ajunge la fișiere protejate.",
      nextStart: "Are efect la următoarea pornire a Prune.",
      running: "Prune rulează acum ca administrator.",
      unsupported: "Disponibil în aplicația Prune instalată. Această copie nu îl poate seta.",
      startupConflict: "Prune este setat să pornească odată cu Windows, iar Windows nu pornește discret la autentificare un program care rulează ca administrator: cere aprobarea de fiecare dată sau nu pornește. Dezactivează asta din „Pornire” dacă preferi.",
      saveFailed: (m) => `Nu s-a putut schimba această setare: ${m}`,
      loadFailed: (m) => `Nu s-a putut citi această setare: ${m}`
    }
  },
  ru: {
    runAsAdminV3: {
      title: "Всегда запускать от имени администратора",
      description: "Каждый раз запускает Prune с правами администратора, используя собственный параметр Windows «Выполнять эту программу от имени администратора» для этой копии Prune. Быстрое сканирование Карты диска, остатки на всём компьютере и запланированные задачи тогда не требуют дополнительных запросов. Это можно отключить здесь в любой момент.",
      costsHeading: "Чем это обходится",
      costUac: "Windows запрашивает ваше подтверждение при каждом запуске Prune.",
      costDragDrop: "Программа, запущенная от имени администратора, не может принимать файлы, перетаскиваемые из обычного окна Проводника, поэтому перетаскивание файлов и папок в Prune перестаёт работать. Используйте кнопки выбора файлов.",
      costStartup: "Она не может тихо запускаться при входе в систему, потому что Windows сначала запрашивает подтверждение.",
      costRights: "Всё, что делает Prune, выполняется с полными правами, поэтому ошибка может затронуть защищённые файлы.",
      nextStart: "Вступает в силу при следующем запуске Prune.",
      running: "Prune сейчас запущен от имени администратора.",
      unsupported: "Доступно в установленном приложении Prune. Эта копия не может задать этот параметр.",
      startupConflict: "Prune настроен на запуск вместе с Windows, а Windows не запускает тихо при входе программу, работающую от имени администратора: он каждый раз запрашивает подтверждение или программа не запускается. Отключите это в разделе «Автозагрузка», если не хотите этого.",
      saveFailed: (m) => `Не удалось изменить этот параметр: ${m}`,
      loadFailed: (m) => `Не удалось прочитать этот параметр: ${m}`
    }
  },
  sk: {
    runAsAdminV3: {
      title: "Vždy spúšťať ako správca",
      description: "Spustí Prune zakaždým s právami správcu pomocou vlastného nastavenia Windows „Spustiť tento program ako správca“ pre túto kópiu Prune. Rýchle prehľadanie Mapy disku, zvyšky v celom počítači a naplánované úlohy potom nepotrebujú ďalšie výzvy. Môžete to tu kedykoľvek vypnúť.",
      costsHeading: "Čo to stojí",
      costUac: "Windows sa pri každom spustení Prune opýta na váš súhlas.",
      costDragDrop: "Program spustený ako správca nemôže prijímať súbory presunuté z bežného okna Prieskumníka, takže presúvanie súborov alebo priečinkov do Prune prestane fungovať. Použite namiesto toho tlačidlá na výber súborov.",
      costStartup: "Pri prihlásení sa nemôže spustiť potichu, pretože Windows najprv žiada o súhlas.",
      costRights: "Všetko, čo Prune robí, beží s plnými právami, takže chyba môže zasiahnuť chránené súbory.",
      nextStart: "Prejaví sa pri ďalšom spustení Prune.",
      running: "Prune teraz beží ako správca.",
      unsupported: "K dispozícii v nainštalovanej aplikácii Prune. Táto kópia to nastaviť nemôže.",
      startupConflict: "Prune je nastavený na spustenie s Windows a Windows program spustený ako správca pri prihlásení potichu nespustí: pri každom spustení požiada o súhlas, alebo sa nespustí. Ak to nechcete, vypnite to v časti „Po spustení“.",
      saveFailed: (m) => `Toto nastavenie sa nepodarilo zmeniť: ${m}`,
      loadFailed: (m) => `Toto nastavenie sa nepodarilo prečítať: ${m}`
    }
  },
  sq: {
    runAsAdminV3: {
      title: "Ekzekuto gjithmonë si administrator",
      description: "E nis Prune me të drejta administratori çdo herë, duke përdorur cilësimin e vetë Windows «Ekzekuto këtë program si administrator» për këtë kopje të Prune. Skanimi i shpejtë i Hartës së diskut, mbetjet në të gjithë kompjuterin dhe detyrat e planifikuara nuk kërkojnë më pyetje shtesë. Mund ta çaktivizoni këtu në çdo kohë.",
      costsHeading: "Sa kushton",
      costUac: "Windows kërkon miratimin tuaj sa herë që niset Prune.",
      costDragDrop: "Një program që ekzekutohet si administrator nuk mund të marrë skedarë të tërhequr nga një dritare normale e Explorer, ndaj tërheqja e skedarëve ose dosjeve në Prune pushon së punuari. Përdorni në vend të saj butonat e zgjedhjes së skedarëve.",
      costStartup: "Nuk mund të niset në heshtje kur hyni, sepse Windows kërkon fillimisht miratimin.",
      costRights: "Gjithçka që bën Prune ekzekutohet me të drejta të plota, ndaj një gabim mund të arrijë skedarë të mbrojtur.",
      nextStart: "Hyn në fuqi herën tjetër që niset Prune.",
      running: "Prune po ekzekutohet tani si administrator.",
      unsupported: "Në dispozicion në aplikacionin e instaluar Prune. Kjo kopje nuk mund ta caktojë.",
      startupConflict: "Prune është caktuar të niset me Windows, dhe Windows nuk nis në heshtje gjatë hyrjes një program që ekzekutohet si administrator: kërkon miratim çdo herë, ose nuk niset. Çaktivizojeni te «Nisja» nëse e preferoni.",
      saveFailed: (m) => `Ky cilësim nuk mund të ndryshohej: ${m}`,
      loadFailed: (m) => `Ky cilësim nuk mund të lexohej: ${m}`
    }
  },
  sr: {
    runAsAdminV3: {
      title: "Увек покрени као администратор",
      description: "Покреће Prune сваки пут са правима администратора, користећи сам Windows подешавање „Покрени овај програм као администратор“ за ову копију програма Prune. Брзо скенирање Мапе диска, остаци на целом рачунару и заказани задаци тада не траже додатна питања. Можете то овде да искључите у било ком тренутку.",
      costsHeading: "Шта то кошта",
      costUac: "Windows тражи ваше одобрење сваки пут када се Prune покрене.",
      costDragDrop: "Програм који ради као администратор не може да прима датотеке превучене из обичног прозора Експлорера, па превлачење датотека или фасцикли у Prune престаје да ради. Уместо тога користите дугмад за избор датотека.",
      costStartup: "Не може тихо да се покрене при пријављивању, јер Windows прво тражи одобрење.",
      costRights: "Све што Prune ради извршава се са пуним правима, па грешка може да дође до заштићених датотека.",
      nextStart: "Ступа на снагу при следећем покретању програма Prune.",
      running: "Prune сада ради као администратор.",
      unsupported: "Доступно у инсталираној апликацији Prune. Ова копија то не може да подеси.",
      startupConflict: "Prune је подешен да се покреће са Windows-ом, а Windows не покреће тихо при пријављивању програм који ради као администратор: сваки пут тражи одобрење или се не покреће. Искључите то у одељку „Покретање“ ако желите.",
      saveFailed: (m) => `Није могуће променити ово подешавање: ${m}`,
      loadFailed: (m) => `Није могуће прочитати ово подешавање: ${m}`
    }
  },
  sv: {
    runAsAdminV3: {
      title: "Kör alltid som administratör",
      description: "Startar Prune med administratörsrättigheter varje gång, med Windows egen inställning ”Kör det här programmet som administratör” för den här kopian av Prune. Den snabba Diskkarta-skanningen, rester på hela datorn och schemalagda uppgifter behöver då inga extra bekräftelser. Du kan stänga av det här när som helst.",
      costsHeading: "Vad det kostar",
      costUac: "Windows ber om ditt godkännande varje gång Prune startar.",
      costDragDrop: "Ett program som körs som administratör kan inte ta emot filer som dras från ett vanligt Utforskaren-fönster, så att dra filer eller mappar till Prune slutar fungera. Använd knapparna för filval i stället.",
      costStartup: "Det kan inte starta tyst när du loggar in, eftersom Windows först ber om godkännande.",
      costRights: "Allt Prune gör körs med full behörighet, så ett misstag kan nå skyddade filer.",
      nextStart: "Träder i kraft nästa gång Prune startar.",
      running: "Prune körs som administratör just nu.",
      unsupported: "Finns i den installerade Prune-appen. Den här kopian kan inte ställa in det.",
      startupConflict: "Prune är inställt på att starta med Windows, och Windows startar inte ett program som körs som administratör tyst vid inloggning: det ber om godkännande varje gång, eller startar inte. Stäng av det under ”Startprogram” om du hellre vill det.",
      saveFailed: (m) => `Det gick inte att ändra den här inställningen: ${m}`,
      loadFailed: (m) => `Det gick inte att läsa den här inställningen: ${m}`
    }
  },
  th: {
    runAsAdminV3: {
      title: "เรียกใช้ในฐานะผู้ดูแลระบบเสมอ",
      description: "เริ่ม Prune ด้วยสิทธิ์ผู้ดูแลระบบทุกครั้ง โดยใช้การตั้งค่าของ Windows เอง “เรียกใช้โปรแกรมนี้ในฐานะผู้ดูแลระบบ” สำหรับ Prune ชุดนี้ การสแกนแผนที่ดิสก์แบบเร็ว ส่วนที่เหลือทั่วทั้งเครื่อง และงานที่ตั้งเวลาไว้จะไม่ต้องมีการยืนยันเพิ่มเติม คุณปิดได้ที่นี่ทุกเมื่อ",
      costsHeading: "สิ่งที่ต้องแลก",
      costUac: "Windows จะขอการอนุมัติจากคุณทุกครั้งที่ Prune เริ่มทำงาน",
      costDragDrop: "โปรแกรมที่ทำงานในฐานะผู้ดูแลระบบไม่สามารถรับไฟล์ที่ลากมาจากหน้าต่าง File Explorer ปกติได้ การลากไฟล์หรือโฟลเดอร์ลงใน Prune จึงใช้ไม่ได้ ให้ใช้ปุ่มเลือกไฟล์แทน",
      costStartup: "เริ่มทำงานแบบเงียบๆ ตอนลงชื่อเข้าใช้ไม่ได้ เพราะ Windows ต้องขอการอนุมัติก่อน",
      costRights: "ทุกอย่างที่ Prune ทำจะทำงานด้วยสิทธิ์เต็ม ความผิดพลาดจึงอาจกระทบไฟล์ที่ได้รับการป้องกัน",
      nextStart: "มีผลเมื่อ Prune เริ่มทำงานครั้งถัดไป",
      running: "ขณะนี้ Prune ทำงานในฐานะผู้ดูแลระบบ",
      unsupported: "ใช้ได้ในแอป Prune ที่ติดตั้งแล้ว สำเนานี้ตั้งค่าไม่ได้",
      startupConflict: "Prune ถูกตั้งให้เริ่มพร้อมกับ Windows และ Windows จะไม่เริ่มโปรแกรมที่ทำงานในฐานะผู้ดูแลระบบแบบเงียบๆ ตอนลงชื่อเข้าใช้ โดยจะขอการอนุมัติทุกครั้งหรือไม่เริ่มทำงานเลย หากไม่ต้องการ ให้ปิดที่ “เริ่มต้นระบบ”",
      saveFailed: (m) => `เปลี่ยนการตั้งค่านี้ไม่ได้: ${m}`,
      loadFailed: (m) => `อ่านการตั้งค่านี้ไม่ได้: ${m}`
    }
  },
  tr: {
    runAsAdminV3: {
      title: "Her zaman yönetici olarak çalıştır",
      description: "Prune'u bu kopya için Windows'un kendi “Bu programı yönetici olarak çalıştır” ayarını kullanarak her seferinde yönetici haklarıyla başlatır. Hızlı Disk Haritası taraması, makine genelindeki kalıntılar ve zamanlanmış görevler o zaman ek onay istemez. Bunu burada istediğiniz zaman kapatabilirsiniz.",
      costsHeading: "Bedeli nedir",
      costUac: "Windows, Prune her başladığında onayınızı ister.",
      costDragDrop: "Yönetici olarak çalışan bir program, normal bir Dosya Gezgini penceresinden sürüklenen dosyaları alamaz; bu yüzden Prune'a dosya veya klasör sürüklemek çalışmaz. Bunun yerine dosya seçme düğmelerini kullanın.",
      costStartup: "Oturum açtığınızda sessizce başlayamaz, çünkü Windows önce onay ister.",
      costRights: "Prune'un yaptığı her şey tam haklarla çalışır, bu yüzden bir hata korumalı dosyalara ulaşabilir.",
      nextStart: "Prune'un bir sonraki başlatılışında geçerli olur.",
      running: "Prune şu anda yönetici olarak çalışıyor.",
      unsupported: "Yüklü Prune uygulamasında kullanılabilir. Bu kopya bunu ayarlayamaz.",
      startupConflict: "Prune Windows ile başlayacak şekilde ayarlı ve Windows, yönetici olarak çalışan bir programı oturum açılırken sessizce başlatmaz: her seferinde onay ister veya başlamaz. İstemiyorsanız bunu “Başlangıç” bölümünden kapatın.",
      saveFailed: (m) => `Bu ayar değiştirilemedi: ${m}`,
      loadFailed: (m) => `Bu ayar okunamadı: ${m}`
    }
  },
  uk: {
    runAsAdminV3: {
      title: "Завжди запускати від імені адміністратора",
      description: "Щоразу запускає Prune з правами адміністратора, використовуючи власний параметр Windows «Виконувати цю програму від імені адміністратора» для цієї копії Prune. Швидке сканування Карти диска, залишки на всьому комп’ютері та заплановані завдання тоді не потребують додаткових запитів. Це можна вимкнути тут будь-коли.",
      costsHeading: "Чим це обходиться",
      costUac: "Windows запитує ваше підтвердження під час кожного запуску Prune.",
      costDragDrop: "Програма, запущена від імені адміністратора, не може приймати файли, перетягнуті зі звичайного вікна Провідника, тому перетягування файлів і папок у Prune перестає працювати. Натомість використовуйте кнопки вибору файлів.",
      costStartup: "Вона не може тихо запускатися під час входу в систему, бо Windows спершу запитує підтвердження.",
      costRights: "Усе, що робить Prune, виконується з повними правами, тому помилка може зачепити захищені файли.",
      nextStart: "Набирає чинності під час наступного запуску Prune.",
      running: "Prune зараз запущено від імені адміністратора.",
      unsupported: "Доступно в установленому застосунку Prune. Ця копія не може задати цей параметр.",
      startupConflict: "Prune налаштовано на запуск разом із Windows, а Windows не запускає тихо під час входу програму, що працює від імені адміністратора: щоразу запитує підтвердження або програма не запускається. Вимкніть це в розділі «Автозавантаження», якщо не хочете цього.",
      saveFailed: (m) => `Не вдалося змінити цей параметр: ${m}`,
      loadFailed: (m) => `Не вдалося прочитати цей параметр: ${m}`
    }
  },
  vi: {
    runAsAdminV3: {
      title: "Luôn chạy với quyền quản trị viên",
      description: "Khởi động Prune với quyền quản trị viên mỗi lần, dùng chính thiết lập “Chạy chương trình này với tư cách quản trị viên” của Windows cho bản Prune này. Khi đó quét nhanh Bản đồ ổ đĩa, phần còn sót trên toàn máy và tác vụ theo lịch không cần thêm lời nhắc nào. Bạn có thể tắt tại đây bất cứ lúc nào.",
      costsHeading: "Cái giá phải trả",
      costUac: "Windows yêu cầu bạn phê duyệt mỗi lần Prune khởi động.",
      costDragDrop: "Chương trình chạy với quyền quản trị viên không nhận được tệp kéo từ cửa sổ File Explorer thông thường, nên kéo tệp hoặc thư mục vào Prune sẽ không còn hoạt động. Hãy dùng các nút chọn tệp thay thế.",
      costStartup: "Nó không thể khởi động âm thầm khi bạn đăng nhập, vì Windows yêu cầu phê duyệt trước.",
      costRights: "Mọi việc Prune làm đều chạy với đầy đủ quyền, nên một sai sót có thể ảnh hưởng đến tệp được bảo vệ.",
      nextStart: "Có hiệu lực vào lần khởi động Prune tiếp theo.",
      running: "Prune hiện đang chạy với quyền quản trị viên.",
      unsupported: "Có trong ứng dụng Prune đã cài đặt. Bản này không thể thiết lập.",
      startupConflict: "Prune được đặt khởi động cùng Windows, và Windows không khởi động âm thầm chương trình chạy với quyền quản trị viên khi đăng nhập: nó yêu cầu phê duyệt mỗi lần, hoặc không khởi động. Hãy tắt tại “Khởi động” nếu bạn không muốn.",
      saveFailed: (m) => `Không thể đổi thiết lập này: ${m}`,
      loadFailed: (m) => `Không thể đọc thiết lập này: ${m}`
    }
  },
  "zh-CN": {
    runAsAdminV3: {
      title: "始终以管理员身份运行",
      description: "借助 Windows 自带的“以管理员身份运行此程序”设置，让这份 Prune 每次都以管理员权限启动。这样，快速磁盘地图扫描、整台电脑的残留项和计划任务就不再需要额外确认。你可以随时在这里关闭。",
      costsHeading: "代价",
      costUac: "每次启动 Prune 时，Windows 都会请求你的批准。",
      costDragDrop: "以管理员身份运行的程序无法接收从普通资源管理器窗口拖来的文件，因此将文件或文件夹拖入 Prune 将失效。请改用文件选择按钮。",
      costStartup: "它无法在你登录时静默启动，因为 Windows 会先请求批准。",
      costRights: "Prune 所做的一切都以完全权限运行，因此一次失误可能波及受保护的文件。",
      nextStart: "下次启动 Prune 时生效。",
      running: "Prune 当前正以管理员身份运行。",
      unsupported: "在已安装的 Prune 应用中可用。此副本无法设置。",
      startupConflict: "Prune 已设置为随 Windows 启动，而 Windows 不会在登录时静默启动以管理员身份运行的程序：它每次都会请求批准，或者不会启动。如果不想这样，请在“启动项”中关闭。",
      saveFailed: (m) => `无法更改此设置：${m}`,
      loadFailed: (m) => `无法读取此设置：${m}`
    }
  },
  "zh-TW": {
    runAsAdminV3: {
      title: "一律以系統管理員身分執行",
      description: "透過 Windows 內建的「以系統管理員身分執行此程式」設定，讓這份 Prune 每次都以系統管理員權限啟動。如此一來，快速磁碟地圖掃描、整台電腦的殘留項目和排程工作就不需要額外確認。你可以隨時在這裡關閉。",
      costsHeading: "代價",
      costUac: "每次啟動 Prune 時，Windows 都會要求你核准。",
      costDragDrop: "以系統管理員身分執行的程式無法接收從一般檔案總管視窗拖曳過來的檔案，因此將檔案或資料夾拖曳到 Prune 會失效。請改用檔案選取按鈕。",
      costStartup: "它無法在你登入時靜默啟動，因為 Windows 會先要求核准。",
      costRights: "Prune 所做的一切都以完整權限執行，因此一次失誤可能波及受保護的檔案。",
      nextStart: "下次啟動 Prune 時生效。",
      running: "Prune 目前正以系統管理員身分執行。",
      unsupported: "可在已安裝的 Prune 應用程式中使用。此複本無法設定。",
      startupConflict: "Prune 已設為隨 Windows 啟動，而 Windows 不會在登入時靜默啟動以系統管理員身分執行的程式：它每次都會要求核准，或不會啟動。如果不想這樣，請在「啟動項目」中關閉。",
      saveFailed: (m) => `無法變更此設定：${m}`,
      loadFailed: (m) => `無法讀取此設定：${m}`
    }
  }
};
