// New UI text for the uninstaller work (scan modes, confidence tiers, forced uninstall,
// install monitor, Hunter, backups, history), all 40 languages: { en: { ... }, af: { ... }, ... }.
// See the note at the bottom of ../catalog.js. Generated by an out-of-tree script that writes
// every value with JSON.stringify, so quotes and non-ASCII text are safe.
export default {
  en: {
    uninstallerV3: {
      scanMode: {
        label: "Leftover scan",
        safe: "Safe",
        moderate: "Moderate",
        advanced: "Advanced",
        safeHint: "Only this program's own install folder and registry key.",
        moderateHint: "The usual places, matched by name. Recommended.",
        advancedHint: "Searches many more places, several folders deep. Finds more, but more of it needs a careful look. Slower."
      },
      review: {
        services: "Services",
        tier: {
          certain: "Certain",
          likely: "Likely",
          possible: "Possible",
          certainHint: "Inside the program's own folder, or named by its own entries.",
          likelyHint: "Named after the program.",
          possibleHint: "Matched only by the publisher's name or one word of the program's. Not ticked; check each one."
        },
        protectedNote: (n) => `Left out because they belong to Windows or to other installed programs: ${n}.`,
        truncatedNote: "The search stopped early to stay quick, so there may be more."
      },
      tasks: {
        removed: (n) => `Scheduled tasks removed: ${n}. Their definitions are saved under Backups on the Quarantine screen, where they can be restored.`,
        failedHeading: (n) => `Scheduled tasks that could not be removed: ${n}`
      },
      forced: {
        button: "Forced uninstall…",
        title: "Forced uninstall",
        modalTitle: (n) => `Forced uninstall of ${n}`,
        intro: "For software that is not listed, or whose uninstaller is gone. Give its name, choose the folder it was installed in, or both, and Prune searches deeply for what it left behind. You review everything before anything is removed.",
        nameLabel: "Program name",
        namePlaceholder: "Optional if you choose a folder",
        folderLabel: "Install folder",
        folderPlaceholder: "Optional if you enter a name",
        browse: "Browse…",
        continue: "Continue",
        needOne: "Enter a name or choose a folder to continue.",
        pickFailed: (m) => `Couldn't open the folder dialog: ${m}`,
        scanIntro: "Prune will search for files, registry entries and scheduled tasks that match this name and folder. Nothing is removed until you have reviewed it.",
        folderLine: (f) => `Folder: ${f}`
      }
    }
  },
  af: {
    uninstallerV3: {
      scanMode: {
        label: "Oorblyfsel-skandering",
        safe: "Veilig",
        moderate: "Gematig",
        advanced: "Gevorderd",
        safeHint: "Slegs hierdie program se eie installasiegids en registersleutel.",
        moderateHint: "Die gewone plekke, volgens naam gepas. Aanbeveel.",
        advancedHint: "Deursoek baie meer plekke, verskeie vouers diep. Vind meer, maar meer daarvan moet noukeurig nagegaan word. Stadiger."
      },
      review: {
        services: "Dienste",
        tier: {
          certain: "Seker",
          likely: "Waarskynlik",
          possible: "Moontlik",
          certainHint: "In die program se eie gids, of deur sy eie inskrywings genoem.",
          likelyHint: "Na die program vernoem.",
          possibleHint: "Slegs met die uitgewer se naam of een woord van die program se naam gepas. Nie gemerk nie; gaan elkeen na."
        },
        protectedNote: (n) => `Uitgelaat omdat hulle aan Windows of ander geïnstalleerde programme behoort: ${n}.`,
        truncatedNote: "Die soektog het vroeg gestop om vinnig te bly, so daar kan meer wees."
      },
      tasks: {
        removed: (n) => `Geskeduleerde take verwyder: ${n}. Hul definisies is gestoor onder Rugsteun op die Karantyn-skerm, waar hulle herstel kan word.`,
        failedHeading: (n) => `Geskeduleerde take wat nie verwyder kon word nie: ${n}`
      },
      forced: {
        button: "Gedwonge deïnstallering…",
        title: "Gedwonge deïnstallering",
        modalTitle: (n) => `Gedwonge deïnstallering van ${n}`,
        intro: "Vir sagteware wat nie gelys is nie, of waarvan die deïnstalleerder weg is. Gee die naam, kies die gids waarin dit geïnstalleer is, of albei, en Prune soek diep na wat dit agtergelaat het. Jy hersien alles voordat iets verwyder word.",
        nameLabel: "Programnaam",
        namePlaceholder: "Opsioneel as jy 'n gids kies",
        folderLabel: "Installasiegids",
        folderPlaceholder: "Opsioneel as jy 'n naam invoer",
        browse: "Blaai…",
        continue: "Gaan voort",
        needOne: "Voer 'n naam in of kies 'n gids om voort te gaan.",
        pickFailed: (m) => `Kon nie die gidsdialoog open nie: ${m}`,
        scanIntro: "Prune soek na lêers, registerinskrywings en geskeduleerde take wat by hierdie naam en gids pas. Niks word verwyder voordat jy dit hersien het nie.",
        folderLine: (f) => `Gids: ${f}`
      }
    }
  },
  ar: {
    uninstallerV3: {
      scanMode: {
        label: "فحص المخلفات",
        safe: "آمن",
        moderate: "متوسط",
        advanced: "متقدم",
        safeHint: "مجلد التثبيت الخاص بهذا البرنامج ومفتاح السجل الخاص به فقط.",
        moderateHint: "الأماكن المعتادة، بالمطابقة حسب الاسم. موصى به.",
        advancedHint: "يبحث في أماكن أكثر بكثير وعلى عدة مستويات من المجلدات. يجد المزيد، لكن يحتاج الكثير منه إلى مراجعة دقيقة. أبطأ."
      },
      review: {
        services: "الخدمات",
        tier: {
          certain: "مؤكد",
          likely: "مرجّح",
          possible: "محتمل",
          certainHint: "داخل مجلد البرنامج نفسه، أو مذكور في إدخالاته الخاصة.",
          likelyHint: "يحمل اسم البرنامج.",
          possibleHint: "مطابق فقط لاسم الناشر أو لكلمة واحدة من اسم البرنامج. غير محدد؛ راجع كل عنصر."
        },
        protectedNote: (n) => `تم استبعادها لأنها تخص Windows أو برامج مثبتة أخرى: ${n}.`,
        truncatedNote: "توقف البحث مبكرًا للحفاظ على السرعة، لذا قد يوجد المزيد."
      },
      tasks: {
        removed: (n) => `المهام المجدولة المحذوفة: ${n}. تم حفظ تعريفاتها ضمن النسخ الاحتياطية في شاشة الحجر الصحي، حيث يمكن استعادتها.`,
        failedHeading: (n) => `المهام المجدولة التي تعذّرت إزالتها: ${n}`
      },
      forced: {
        button: "إلغاء تثبيت إجباري…",
        title: "إلغاء تثبيت إجباري",
        modalTitle: (n) => `إلغاء تثبيت ${n} إجباريًا`,
        intro: "للبرامج غير المدرجة أو التي فُقد برنامج إلغاء التثبيت الخاص بها. أدخل اسمها أو اختر المجلد الذي ثُبّتت فيه أو كليهما، وسيبحث Prune بعمق عما خلّفته. تراجع كل شيء قبل إزالة أي شيء.",
        nameLabel: "اسم البرنامج",
        namePlaceholder: "اختياري إذا اخترت مجلدًا",
        folderLabel: "مجلد التثبيت",
        folderPlaceholder: "اختياري إذا أدخلت اسمًا",
        browse: "استعراض…",
        continue: "متابعة",
        needOne: "أدخل اسمًا أو اختر مجلدًا للمتابعة.",
        pickFailed: (m) => `تعذّر فتح نافذة المجلد: ${m}`,
        scanIntro: "سيبحث Prune عن الملفات وإدخالات السجل والمهام المجدولة المطابقة لهذا الاسم والمجلد. لن يُزال شيء قبل أن تراجعه.",
        folderLine: (f) => `المجلد: ${f}`
      }
    }
  },
  ca: {
    uninstallerV3: {
      scanMode: {
        label: "Cerca de restes",
        safe: "Segur",
        moderate: "Moderat",
        advanced: "Avançat",
        safeHint: "Només la carpeta d'instal·lació del programa i la seva clau del registre.",
        moderateHint: "Els llocs habituals, per coincidència de nom. Recomanat.",
        advancedHint: "Cerca en molts més llocs, a diversos nivells de carpetes. Troba més coses, però cal revisar-ne més. Més lent."
      },
      review: {
        services: "Serveis",
        tier: {
          certain: "Cert",
          likely: "Probable",
          possible: "Possible",
          certainHint: "Dins la carpeta del programa, o assenyalat per les seves pròpies entrades.",
          likelyHint: "Porta el nom del programa.",
          possibleHint: "Coincideix només amb el nom de l'editor o una paraula del programa. No marcat; revisa'ls un per un."
        },
        protectedNote: (n) => `Exclosos perquè pertanyen a Windows o a altres programes instal·lats: ${n}.`,
        truncatedNote: "La cerca s'ha aturat abans per ser ràpida, així que pot haver-hi més coses."
      },
      tasks: {
        removed: (n) => `Tasques programades eliminades: ${n}. Les seves definicions es desen a Còpies de seguretat, a la pantalla Quarantena, on es poden restaurar.`,
        failedHeading: (n) => `Tasques programades que no s'han pogut eliminar: ${n}`
      },
      forced: {
        button: "Desinstal·lació forçada…",
        title: "Desinstal·lació forçada",
        modalTitle: (n) => `Desinstal·lació forçada de ${n}`,
        intro: "Per a programari que no apareix a la llista o que ha perdut el desinstal·lador. Indica el nom, tria la carpeta on es va instal·lar, o totes dues coses, i Prune cerca en profunditat el que ha deixat. Ho revises tot abans que s'elimini res.",
        nameLabel: "Nom del programa",
        namePlaceholder: "Opcional si tries una carpeta",
        folderLabel: "Carpeta d'instal·lació",
        folderPlaceholder: "Opcional si introdueixes un nom",
        browse: "Explora…",
        continue: "Continua",
        needOne: "Introdueix un nom o tria una carpeta per continuar.",
        pickFailed: (m) => `No s'ha pogut obrir el diàleg de carpetes: ${m}`,
        scanIntro: "Prune cercarà fitxers, entrades del registre i tasques programades que coincideixin amb aquest nom i aquesta carpeta. No s'elimina res fins que ho hagis revisat.",
        folderLine: (f) => `Carpeta: ${f}`
      }
    }
  },
  cs: {
    uninstallerV3: {
      scanMode: {
        label: "Hledání zbytků",
        safe: "Bezpečný",
        moderate: "Střední",
        advanced: "Pokročilý",
        safeHint: "Jen vlastní instalační složka programu a jeho klíč v registru.",
        moderateHint: "Obvyklá místa, hledání podle názvu. Doporučeno.",
        advancedHint: "Prohledá mnohem více míst do několika úrovní složek. Najde víc, ale víc z toho je třeba pečlivě zkontrolovat. Pomalejší."
      },
      review: {
        services: "Služby",
        tier: {
          certain: "Jisté",
          likely: "Pravděpodobné",
          possible: "Možné",
          certainHint: "Uvnitř vlastní složky programu nebo uvedeno v jeho vlastních záznamech.",
          likelyHint: "Pojmenováno podle programu.",
          possibleHint: "Shoda jen podle jména vydavatele nebo jednoho slova z názvu programu. Není zaškrtnuto; zkontrolujte každé zvlášť."
        },
        protectedNote: (n) => `Vynecháno, protože patří Windows nebo jiným nainstalovaným programům: ${n}.`,
        truncatedNote: "Hledání se předčasně zastavilo, aby zůstalo rychlé, takže může být více výsledků."
      },
      tasks: {
        removed: (n) => `Odebrané naplánované úlohy: ${n}. Jejich definice jsou uloženy v části Zálohy na obrazovce Karanténa, odkud je lze obnovit.`,
        failedHeading: (n) => `Naplánované úlohy, které se nepodařilo odebrat: ${n}`
      },
      forced: {
        button: "Vynucené odinstalování…",
        title: "Vynucené odinstalování",
        modalTitle: (n) => `Vynucené odinstalování: ${n}`,
        intro: "Pro software, který není v seznamu nebo jehož odinstalátor zmizel. Zadejte název, vyberte složku, do které byl nainstalován, nebo obojí, a Prune důkladně vyhledá, co po něm zůstalo. Před odebráním vše zkontrolujete.",
        nameLabel: "Název programu",
        namePlaceholder: "Volitelné, pokud vyberete složku",
        folderLabel: "Instalační složka",
        folderPlaceholder: "Volitelné, pokud zadáte název",
        browse: "Procházet…",
        continue: "Pokračovat",
        needOne: "Pro pokračování zadejte název nebo vyberte složku.",
        pickFailed: (m) => `Dialog složky se nepodařilo otevřít: ${m}`,
        scanIntro: "Prune vyhledá soubory, položky registru a naplánované úlohy odpovídající tomuto názvu a složce. Nic se neodebere, dokud to nezkontrolujete.",
        folderLine: (f) => `Složka: ${f}`
      }
    }
  },
  cy: {
    uninstallerV3: {
      scanMode: {
        label: "Sganio am olion",
        safe: "Diogel",
        moderate: "Cymedrol",
        advanced: "Uwch",
        safeHint: "Ffolder gosod y rhaglen ei hun a'i allwedd cofrestrfa yn unig.",
        moderateHint: "Y llefydd arferol, wedi'u paru yn ôl enw. Argymhellir.",
        advancedHint: "Yn chwilio llawer mwy o lefydd, sawl ffolder o ddyfnder. Yn dod o hyd i fwy, ond mae angen edrych yn ofalus ar fwy ohono. Arafach."
      },
      review: {
        services: "Gwasanaethau",
        tier: {
          certain: "Sicr",
          likely: "Tebygol",
          possible: "Posibl",
          certainHint: "Y tu mewn i ffolder y rhaglen ei hun, neu wedi'i enwi gan ei gofnodion ei hun.",
          likelyHint: "Wedi'i enwi ar ôl y rhaglen.",
          possibleHint: "Wedi'i baru dim ond ag enw'r cyhoeddwr neu un gair o enw'r rhaglen. Heb ei dicio; gwiriwch bob un."
        },
        protectedNote: (n) => `Wedi'u gadael allan am eu bod yn perthyn i Windows neu i raglenni eraill a osodwyd: ${n}.`,
        truncatedNote: "Stopiodd y chwiliad yn gynnar i aros yn gyflym, felly efallai bod mwy."
      },
      tasks: {
        removed: (n) => `Tasgau wedi'u hamserlennu a dynnwyd: ${n}. Mae eu diffiniadau wedi'u cadw o dan Copïau wrth gefn ar sgrin Cwarantin, lle gellir eu hadfer.`,
        failedHeading: (n) => `Tasgau wedi'u hamserlennu na ellid eu tynnu: ${n}`
      },
      forced: {
        button: "Dadosod gorfodol…",
        title: "Dadosod gorfodol",
        modalTitle: (n) => `Dadosod gorfodol ${n}`,
        intro: "Ar gyfer meddalwedd nad yw wedi'i restru, neu y mae ei ddadosodwr wedi mynd. Rhowch ei enw, dewiswch y ffolder y'i gosodwyd ynddo, neu'r ddau, a bydd Prune yn chwilio'n ddwfn am yr hyn a adawodd ar ôl. Rydych yn adolygu popeth cyn tynnu dim.",
        nameLabel: "Enw'r rhaglen",
        namePlaceholder: "Dewisol os dewiswch ffolder",
        folderLabel: "Ffolder gosod",
        folderPlaceholder: "Dewisol os rhowch enw",
        browse: "Pori…",
        continue: "Parhau",
        needOne: "Rhowch enw neu dewiswch ffolder i barhau.",
        pickFailed: (m) => `Methu agor y deialog ffolder: ${m}`,
        scanIntro: "Bydd Prune yn chwilio am ffeiliau, cofnodion cofrestrfa a thasgau wedi'u hamserlennu sy'n cyfateb i'r enw a'r ffolder hwn. Ni chaiff dim ei dynnu nes i chi ei adolygu.",
        folderLine: (f) => `Ffolder: ${f}`
      }
    }
  },
  da: {
    uninstallerV3: {
      scanMode: {
        label: "Scanning efter rester",
        safe: "Sikker",
        moderate: "Moderat",
        advanced: "Avanceret",
        safeHint: "Kun programmets egen installationsmappe og registreringsdatabasenøgle.",
        moderateHint: "De sædvanlige steder, fundet via navn. Anbefalet.",
        advancedHint: "Søger mange flere steder, flere mapper dybt. Finder mere, men mere af det kræver et nøje kig. Langsommere."
      },
      review: {
        services: "Tjenester",
        tier: {
          certain: "Vist",
          likely: "Sandsynlige",
          possible: "Muligt",
          certainHint: "Inde i programmets egen mappe eller nævnt af dets egne poster.",
          likelyHint: "Opkaldt efter programmet.",
          possibleHint: "Matchet kun på udgiverens navn eller ét ord af programmets. Ikke afkrydset; tjek hver enkelt."
        },
        protectedNote: (n) => `Udeladt, fordi de tilhører Windows eller andre installerede programmer: ${n}.`,
        truncatedNote: "Søgningen stoppede tidligt for at holde tempoet, så der kan være mere."
      },
      tasks: {
        removed: (n) => `Fjernede planlagte opgaver: ${n}. Deres definitioner er gemt under Sikkerhedskopier på skærmen Karantæne, hvor de kan gendannes.`,
        failedHeading: (n) => `Planlagte opgaver, der ikke kunne fjernes: ${n}`
      },
      forced: {
        button: "Gennemtvungen afinstallation…",
        title: "Gennemtvungen afinstallation",
        modalTitle: (n) => `Gennemtvungen afinstallation af ${n}`,
        intro: "Til software, der ikke er på listen, eller hvis afinstallationsprogram er væk. Angiv navnet, vælg den mappe, det blev installeret i, eller begge dele, så søger Prune grundigt efter det, der er efterladt. Du gennemgår alt, før noget fjernes.",
        nameLabel: "Programnavn",
        namePlaceholder: "Valgfrit, hvis du vælger en mappe",
        folderLabel: "Installationsmappe",
        folderPlaceholder: "Valgfrit, hvis du angiver et navn",
        browse: "Gennemse…",
        continue: "Fortsæt",
        needOne: "Angiv et navn, eller vælg en mappe for at fortsætte.",
        pickFailed: (m) => `Mappedialogen kunne ikke åbnes: ${m}`,
        scanIntro: "Prune søger efter filer, registreringsposter og planlagte opgaver, der matcher dette navn og denne mappe. Intet fjernes, før du har gennemgået det.",
        folderLine: (f) => `Mappe: ${f}`
      }
    }
  },
  de: {
    uninstallerV3: {
      scanMode: {
        label: "Rückstandssuche",
        safe: "Sicher",
        moderate: "Moderat",
        advanced: "Erweitert",
        safeHint: "Nur der eigene Installationsordner des Programms und sein Registrierungsschlüssel.",
        moderateHint: "Die üblichen Orte, per Namensabgleich. Empfohlen.",
        advancedHint: "Durchsucht deutlich mehr Orte, mehrere Ordnerebenen tief. Findet mehr, doch mehr davon muss genau geprüft werden. Langsamer."
      },
      review: {
        services: "Dienste",
        tier: {
          certain: "Eindeutig",
          likely: "Wahrscheinlich",
          possible: "Möglich",
          certainHint: "Im eigenen Ordner des Programms oder von dessen eigenen Einträgen genannt.",
          likelyHint: "Nach dem Programm benannt.",
          possibleHint: "Nur über den Namen des Herausgebers oder ein Wort des Programmnamens gefunden. Nicht angehakt; prüfen Sie jeden Eintrag."
        },
        protectedNote: (n) => `Ausgelassen, weil sie zu Windows oder anderen installierten Programmen gehören: ${n}.`,
        truncatedNote: "Die Suche wurde vorzeitig beendet, um schnell zu bleiben – es kann also mehr geben."
      },
      tasks: {
        removed: (n) => `Entfernte geplante Aufgaben: ${n}. Ihre Definitionen sind unter „Sicherungen“ auf der Seite „Quarantäne“ gespeichert und können dort wiederhergestellt werden.`,
        failedHeading: (n) => `Geplante Aufgaben, die nicht entfernt werden konnten: ${n}`
      },
      forced: {
        button: "Erzwungene Deinstallation…",
        title: "Erzwungene Deinstallation",
        modalTitle: (n) => `Erzwungene Deinstallation von ${n}`,
        intro: "Für Software, die nicht aufgelistet ist oder deren Deinstallationsprogramm fehlt. Geben Sie den Namen an, wählen Sie den Installationsordner oder beides – Prune sucht dann gründlich nach dem, was zurückgeblieben ist. Sie prüfen alles, bevor etwas entfernt wird.",
        nameLabel: "Programmname",
        namePlaceholder: "Optional, wenn Sie einen Ordner wählen",
        folderLabel: "Installationsordner",
        folderPlaceholder: "Optional, wenn Sie einen Namen eingeben",
        browse: "Durchsuchen…",
        continue: "Weiter",
        needOne: "Geben Sie einen Namen ein oder wählen Sie einen Ordner, um fortzufahren.",
        pickFailed: (m) => `Der Ordnerdialog konnte nicht geöffnet werden: ${m}`,
        scanIntro: "Prune sucht nach Dateien, Registrierungseinträgen und geplanten Aufgaben, die zu diesem Namen und Ordner passen. Nichts wird entfernt, bevor Sie es geprüft haben.",
        folderLine: (f) => `Ordner: ${f}`
      }
    }
  },
  el: {
    uninstallerV3: {
      scanMode: {
        label: "Σάρωση καταλοίπων",
        safe: "Ασφαλής",
        moderate: "Μέτρια",
        advanced: "Για προχωρημένους",
        safeHint: "Μόνο ο φάκελος εγκατάστασης του προγράμματος και το κλειδί μητρώου του.",
        moderateHint: "Οι συνηθισμένες τοποθεσίες, με αντιστοίχιση ονόματος. Προτείνεται.",
        advancedHint: "Αναζητά σε πολύ περισσότερες τοποθεσίες, σε πολλά επίπεδα φακέλων. Βρίσκει περισσότερα, αλλά περισσότερα χρειάζονται προσεκτικό έλεγχο. Πιο αργή."
      },
      review: {
        services: "Υπηρεσίες",
        tier: {
          certain: "Βέβαιο",
          likely: "Πιθανό",
          possible: "Ενδεχόμενο",
          certainHint: "Μέσα στον φάκελο του ίδιου του προγράμματος ή αναφέρεται από τις δικές του εγγραφές.",
          likelyHint: "Φέρει το όνομα του προγράμματος.",
          possibleHint: "Αντιστοιχίστηκε μόνο με το όνομα του εκδότη ή μία λέξη του προγράμματος. Δεν είναι επιλεγμένο· ελέγξτε το καθένα."
        },
        protectedNote: (n) => `Παραλείφθηκαν επειδή ανήκουν στα Windows ή σε άλλα εγκατεστημένα προγράμματα: ${n}.`,
        truncatedNote: "Η αναζήτηση σταμάτησε νωρίτερα για να μείνει γρήγορη, οπότε μπορεί να υπάρχουν κι άλλα."
      },
      tasks: {
        removed: (n) => `Προγραμματισμένες εργασίες που αφαιρέθηκαν: ${n}. Οι ορισμοί τους αποθηκεύτηκαν στην ενότητα Αντίγραφα ασφαλείας της οθόνης Καραντίνα, όπου μπορούν να επαναφερθούν.`,
        failedHeading: (n) => `Προγραμματισμένες εργασίες που δεν αφαιρέθηκαν: ${n}`
      },
      forced: {
        button: "Αναγκαστική απεγκατάσταση…",
        title: "Αναγκαστική απεγκατάσταση",
        modalTitle: (n) => `Αναγκαστική απεγκατάσταση του ${n}`,
        intro: "Για λογισμικό που δεν εμφανίζεται στη λίστα ή του οποίου λείπει το πρόγραμμα απεγκατάστασης. Δώστε το όνομα, επιλέξτε τον φάκελο εγκατάστασης ή και τα δύο, και το Prune αναζητά σε βάθος ό,τι άφησε πίσω του. Ελέγχετε τα πάντα πριν αφαιρεθεί οτιδήποτε.",
        nameLabel: "Όνομα προγράμματος",
        namePlaceholder: "Προαιρετικό αν επιλέξετε φάκελο",
        folderLabel: "Φάκελος εγκατάστασης",
        folderPlaceholder: "Προαιρετικό αν δώσετε όνομα",
        browse: "Αναζήτηση…",
        continue: "Συνέχεια",
        needOne: "Δώστε όνομα ή επιλέξτε φάκελο για να συνεχίσετε.",
        pickFailed: (m) => `Δεν ήταν δυνατό το άνοιγμα του διαλόγου φακέλου: ${m}`,
        scanIntro: "Το Prune θα αναζητήσει αρχεία, εγγραφές μητρώου και προγραμματισμένες εργασίες που ταιριάζουν με αυτό το όνομα και φάκελο. Τίποτα δεν αφαιρείται πριν το ελέγξετε.",
        folderLine: (f) => `Φάκελος: ${f}`
      }
    }
  },
  es: {
    uninstallerV3: {
      scanMode: {
        label: "Búsqueda de restos",
        safe: "Seguro",
        moderate: "Moderado",
        advanced: "Avanzado",
        safeHint: "Solo la carpeta de instalación del programa y su clave del registro.",
        moderateHint: "Los lugares habituales, por coincidencia de nombre. Recomendado.",
        advancedHint: "Busca en muchos más lugares, varios niveles de carpetas. Encuentra más, pero hay que revisar más con cuidado. Más lento."
      },
      review: {
        services: "Servicios",
        tier: {
          certain: "Confirmado",
          likely: "Probable",
          possible: "Posible",
          certainHint: "Dentro de la carpeta del propio programa, o indicado por sus propias entradas.",
          likelyHint: "Lleva el nombre del programa.",
          possibleHint: "Coincide solo con el nombre del editor o una palabra del programa. Sin marcar; revisa cada uno."
        },
        protectedNote: (n) => `Omitidos porque pertenecen a Windows o a otros programas instalados: ${n}.`,
        truncatedNote: "La búsqueda se detuvo antes para ser rápida, así que puede haber más."
      },
      tasks: {
        removed: (n) => `Tareas programadas eliminadas: ${n}. Sus definiciones se guardan en Copias de seguridad, en la pantalla Cuarentena, donde se pueden restaurar.`,
        failedHeading: (n) => `Tareas programadas que no se pudieron eliminar: ${n}`
      },
      forced: {
        button: "Desinstalación forzada…",
        title: "Desinstalación forzada",
        modalTitle: (n) => `Desinstalación forzada de ${n}`,
        intro: "Para software que no aparece en la lista o cuyo desinstalador ya no existe. Indica el nombre, elige la carpeta donde se instaló, o ambas cosas, y Prune busca a fondo lo que dejó. Revisas todo antes de que se elimine nada.",
        nameLabel: "Nombre del programa",
        namePlaceholder: "Opcional si eliges una carpeta",
        folderLabel: "Carpeta de instalación",
        folderPlaceholder: "Opcional si escribes un nombre",
        browse: "Examinar…",
        continue: "Continuar",
        needOne: "Escribe un nombre o elige una carpeta para continuar.",
        pickFailed: (m) => `No se pudo abrir el cuadro de carpetas: ${m}`,
        scanIntro: "Prune buscará archivos, entradas del registro y tareas programadas que coincidan con este nombre y carpeta. No se elimina nada hasta que lo hayas revisado.",
        folderLine: (f) => `Carpeta: ${f}`
      }
    }
  },
  et: {
    uninstallerV3: {
      scanMode: {
        label: "Jääkide otsing",
        safe: "Turvaline",
        moderate: "Mõõdukas",
        advanced: "Põhjalik",
        safeHint: "Ainult programmi enda paigalduskaust ja registrivõti.",
        moderateHint: "Tavalised kohad, nime järgi sobitatud. Soovitatav.",
        advancedHint: "Otsib palju rohkem kohti, mitme kaustataseme sügavuselt. Leiab rohkem, kuid suuremat osa tuleb hoolikalt üle vaadata. Aeglasem."
      },
      review: {
        services: "Teenused",
        tier: {
          certain: "Kindel",
          likely: "Tõenäoline",
          possible: "Võimalik",
          certainHint: "Programmi enda kaustas või selle enda kirjetes nimetatud.",
          likelyHint: "Programmi järgi nimetatud.",
          possibleHint: "Sobib ainult väljaandja nime või ühe programminime sõnaga. Märkimata; kontrolli igaüht."
        },
        protectedNote: (n) => `Välja jäetud, sest need kuuluvad Windowsile või teistele installitud programmidele: ${n}.`,
        truncatedNote: "Otsing peatati varakult, et see püsiks kiire, seega võib leide olla rohkem."
      },
      tasks: {
        removed: (n) => `Eemaldatud ajastatud toimingud: ${n}. Nende definitsioonid on salvestatud jaotisse Varukoopiad ekraanil Karantiin, kust neid saab taastada.`,
        failedHeading: (n) => `Ajastatud toimingud, mida ei saanud eemaldada: ${n}`
      },
      forced: {
        button: "Sundeemaldamine…",
        title: "Sundeemaldamine",
        modalTitle: (n) => `${n} sundeemaldamine`,
        intro: "Tarkvara jaoks, mida loendis pole või mille eemaldaja on kadunud. Sisesta nimi, vali kaust, kuhu see paigaldati, või mõlemad, ja Prune otsib põhjalikult, mis järele jäi. Sa vaatad kõik üle enne, kui midagi eemaldatakse.",
        nameLabel: "Programmi nimi",
        namePlaceholder: "Valikuline, kui valid kausta",
        folderLabel: "Paigalduskaust",
        folderPlaceholder: "Valikuline, kui sisestad nime",
        browse: "Sirvi…",
        continue: "Jätka",
        needOne: "Jätkamiseks sisesta nimi või vali kaust.",
        pickFailed: (m) => `Kausta dialoogi ei saanud avada: ${m}`,
        scanIntro: "Prune otsib faile, registrikirjeid ja ajastatud toiminguid, mis sobivad selle nime ja kaustaga. Midagi ei eemaldata enne, kui oled selle üle vaadanud.",
        folderLine: (f) => `Kaust: ${f}`
      }
    }
  },
  fi: {
    uninstallerV3: {
      scanMode: {
        label: "Jäänteiden haku",
        safe: "Turvallinen",
        moderate: "Kohtalainen",
        advanced: "Laaja",
        safeHint: "Vain ohjelman oma asennuskansio ja rekisteriavain.",
        moderateHint: "Tavalliset paikat, nimen perusteella. Suositeltu.",
        advancedHint: "Etsii paljon useammista paikoista, usean kansiotason syvyydeltä. Löytää enemmän, mutta suurempi osa vaatii tarkkaa harkintaa. Hitaampi."
      },
      review: {
        services: "Palvelut",
        tier: {
          certain: "Varma",
          likely: "Todennäköinen",
          possible: "Mahdollinen",
          certainHint: "Ohjelman omassa kansiossa tai sen omien merkintöjen mainitsema.",
          likelyHint: "Nimetty ohjelman mukaan.",
          possibleHint: "Vastaa vain julkaisijan nimeä tai yhtä ohjelman nimen sanaa. Ei valittu; tarkista jokainen."
        },
        protectedNote: (n) => `Jätetty pois, koska ne kuuluvat Windowsille tai muille asennetuille ohjelmille: ${n}.`,
        truncatedNote: "Haku pysähtyi aikaisin nopeuden säilyttämiseksi, joten löytyvää voi olla enemmän."
      },
      tasks: {
        removed: (n) => `Poistetut ajastetut tehtävät: ${n}. Niiden määritykset on tallennettu kohtaan Varmuuskopiot näkymässä Karanteeni, josta ne voi palauttaa.`,
        failedHeading: (n) => `Ajastetut tehtävät, joita ei voitu poistaa: ${n}`
      },
      forced: {
        button: "Pakotettu poisto…",
        title: "Pakotettu poisto",
        modalTitle: (n) => `Pakotettu poisto: ${n}`,
        intro: "Ohjelmille, joita ei ole luettelossa tai joiden poisto-ohjelma on kadonnut. Anna nimi, valitse kansio, johon ohjelma asennettiin, tai molemmat, niin Prune etsii perusteellisesti sen jättämät jäänteet. Tarkistat kaiken ennen kuin mitään poistetaan.",
        nameLabel: "Ohjelman nimi",
        namePlaceholder: "Valinnainen, jos valitset kansion",
        folderLabel: "Asennuskansio",
        folderPlaceholder: "Valinnainen, jos annat nimen",
        browse: "Selaa…",
        continue: "Jatka",
        needOne: "Jatka antamalla nimi tai valitsemalla kansio.",
        pickFailed: (m) => `Kansioikkunaa ei voitu avata: ${m}`,
        scanIntro: "Prune etsii tiedostoja, rekisterimerkintöjä ja ajastettuja tehtäviä, jotka vastaavat tätä nimeä ja kansiota. Mitään ei poisteta ennen kuin olet tarkistanut sen.",
        folderLine: (f) => `Kansio: ${f}`
      }
    }
  },
  fr: {
    uninstallerV3: {
      scanMode: {
        label: "Recherche de résidus",
        safe: "Sûr",
        moderate: "Modéré",
        advanced: "Avancé",
        safeHint: "Uniquement le dossier d'installation du programme et sa clé de registre.",
        moderateHint: "Les emplacements habituels, repérés par le nom. Recommandé.",
        advancedHint: "Explore bien plus d'emplacements, sur plusieurs niveaux de dossiers. Trouve davantage, mais il faut examiner de plus près. Plus lent."
      },
      review: {
        services: "Services",
        tier: {
          certain: "Certain",
          likely: "Probable",
          possible: "Possible",
          certainHint: "Dans le dossier du programme lui-même, ou désigné par ses propres entrées.",
          likelyHint: "Porte le nom du programme.",
          possibleHint: "Trouvé uniquement par le nom de l'éditeur ou un mot du nom du programme. Non coché ; vérifiez chaque élément."
        },
        protectedNote: (n) => `Écartés car ils appartiennent à Windows ou à d'autres programmes installés : ${n}.`,
        truncatedNote: "La recherche s'est arrêtée plus tôt pour rester rapide ; il peut donc y avoir davantage."
      },
      tasks: {
        removed: (n) => `Tâches planifiées supprimées : ${n}. Leurs définitions sont enregistrées dans Sauvegardes, sur l'écran Quarantaine, où elles peuvent être restaurées.`,
        failedHeading: (n) => `Tâches planifiées qui n'ont pas pu être supprimées : ${n}`
      },
      forced: {
        button: "Désinstallation forcée…",
        title: "Désinstallation forcée",
        modalTitle: (n) => `Désinstallation forcée de ${n}`,
        intro: "Pour un logiciel qui n'est pas listé ou dont le désinstalleur a disparu. Indiquez son nom, choisissez le dossier où il a été installé, ou les deux, et Prune cherche en profondeur ce qu'il a laissé. Vous vérifiez tout avant que quoi que ce soit soit supprimé.",
        nameLabel: "Nom du programme",
        namePlaceholder: "Facultatif si vous choisissez un dossier",
        folderLabel: "Dossier d'installation",
        folderPlaceholder: "Facultatif si vous saisissez un nom",
        browse: "Parcourir…",
        continue: "Continuer",
        needOne: "Saisissez un nom ou choisissez un dossier pour continuer.",
        pickFailed: (m) => `Impossible d'ouvrir la boîte de dialogue de dossier : ${m}`,
        scanIntro: "Prune recherchera les fichiers, entrées du registre et tâches planifiées correspondant à ce nom et à ce dossier. Rien n'est supprimé avant que vous l'ayez vérifié.",
        folderLine: (f) => `Dossier : ${f}`
      }
    }
  },
  he: {
    uninstallerV3: {
      scanMode: {
        label: "סריקת שאריות",
        safe: "בטוח",
        moderate: "בינוני",
        advanced: "מתקדם",
        safeHint: "רק תיקיית ההתקנה של התוכנה ומפתח הרישום שלה.",
        moderateHint: "המקומות הרגילים, לפי התאמת שם. מומלץ.",
        advancedHint: "מחפש במקומות רבים יותר, כמה רמות עומק של תיקיות. מוצא יותר, אבל חלק גדול יותר ממנו דורש בדיקה זהירה. איטי יותר."
      },
      review: {
        services: "שירותים",
        tier: {
          certain: "ודאי",
          likely: "סביר",
          possible: "אפשרי",
          certainHint: "בתוך התיקייה של התוכנה עצמה, או מצוין ברשומות שלה.",
          likelyHint: "נושא את שם התוכנה.",
          possibleHint: "הותאם רק לשם המפרסם או למילה אחת משם התוכנה. לא מסומן; בדקו כל פריט."
        },
        protectedNote: (n) => `הושמטו כי הם שייכים ל-Windows או לתוכנות מותקנות אחרות: ${n}.`,
        truncatedNote: "החיפוש נעצר מוקדם כדי להישאר מהיר, לכן ייתכן שיש עוד."
      },
      tasks: {
        removed: (n) => `משימות מתוזמנות שהוסרו: ${n}. ההגדרות שלהן נשמרו תחת גיבויים במסך הסגר, ושם אפשר לשחזר אותן.`,
        failedHeading: (n) => `משימות מתוזמנות שלא ניתן היה להסיר: ${n}`
      },
      forced: {
        button: "הסרה כפויה…",
        title: "הסרה כפויה",
        modalTitle: (n) => `הסרה כפויה של ${n}`,
        intro: "לתוכנות שאינן ברשימה או שתוכנית ההסרה שלהן נעלמה. הזינו שם, בחרו את תיקיית ההתקנה, או שניהם, ו-Prune יחפש לעומק מה שנשאר. תבדקו הכול לפני שמשהו יוסר.",
        nameLabel: "שם התוכנה",
        namePlaceholder: "אופציונלי אם בוחרים תיקייה",
        folderLabel: "תיקיית התקנה",
        folderPlaceholder: "אופציונלי אם מזינים שם",
        browse: "עיון…",
        continue: "המשך",
        needOne: "הזינו שם או בחרו תיקייה כדי להמשיך.",
        pickFailed: (m) => `לא ניתן לפתוח את חלון בחירת התיקייה: ${m}`,
        scanIntro: "Prune יחפש קבצים, רשומות רישום ומשימות מתוזמנות התואמים לשם ולתיקייה האלה. שום דבר לא יוסר לפני שתבדקו אותו.",
        folderLine: (f) => `תיקייה: ${f}`
      }
    }
  },
  hu: {
    uninstallerV3: {
      scanMode: {
        label: "Maradványok keresése",
        safe: "Biztonságos",
        moderate: "Mérsékelt",
        advanced: "Haladó",
        safeHint: "Csak a program saját telepítési mappája és beállításjegyzék-kulcsa.",
        moderateHint: "A szokásos helyek, név alapján egyeztetve. Ajánlott.",
        advancedHint: "Sokkal több helyen keres, több mappaszint mélyen. Többet talál, de többet kell közülük gondosan átnézni. Lassabb."
      },
      review: {
        services: "Szolgáltatások",
        tier: {
          certain: "Biztos",
          likely: "Valószínű",
          possible: "Lehetséges",
          certainHint: "A program saját mappájában, vagy a program saját bejegyzései nevezik meg.",
          likelyHint: "A programról elnevezve.",
          possibleHint: "Csak a kiadó nevével vagy a program nevének egy szavával egyezik. Nincs bejelölve; ellenőrizze mindegyiket."
        },
        protectedNote: (n) => `Kihagyva, mert a Windowshoz vagy más telepített programokhoz tartoznak: ${n}.`,
        truncatedNote: "A keresés korán leállt, hogy gyors maradjon, így lehet, hogy van még találat."
      },
      tasks: {
        removed: (n) => `Eltávolított ütemezett feladatok: ${n}. A definíciójuk a(z) Karantén képernyő Biztonsági mentések részében van mentve, onnan visszaállíthatók.`,
        failedHeading: (n) => `Nem eltávolítható ütemezett feladatok: ${n}`
      },
      forced: {
        button: "Kényszerített eltávolítás…",
        title: "Kényszerített eltávolítás",
        modalTitle: (n) => `${n} kényszerített eltávolítása`,
        intro: "Olyan szoftverhez, amely nincs a listában, vagy amelynek az eltávolítója hiányzik. Adja meg a nevét, válassza ki a telepítési mappát, vagy mindkettőt, és a Prune alaposan átkutatja, mi maradt hátra. Mindent átnézhet, mielőtt bármi eltávolításra kerülne.",
        nameLabel: "A program neve",
        namePlaceholder: "Nem kötelező, ha mappát választ",
        folderLabel: "Telepítési mappa",
        folderPlaceholder: "Nem kötelező, ha nevet ad meg",
        browse: "Tallózás…",
        continue: "Tovább",
        needOne: "A folytatáshoz adjon meg egy nevet, vagy válasszon egy mappát.",
        pickFailed: (m) => `A mappaválasztó nem nyitható meg: ${m}`,
        scanIntro: "A Prune fájlokat, beállításjegyzék-bejegyzéseket és ütemezett feladatokat keres, amelyek egyeznek ezzel a névvel és mappával. Semmi sem törlődik, amíg át nem nézte.",
        folderLine: (f) => `Mappa: ${f}`
      }
    }
  },
  id: {
    uninstallerV3: {
      scanMode: {
        label: "Pemindaian sisa",
        safe: "Aman",
        moderate: "Sedang",
        advanced: "Lanjutan",
        safeHint: "Hanya folder instalasi dan kunci registri milik program itu sendiri.",
        moderateHint: "Lokasi yang umum, dicocokkan berdasarkan nama. Disarankan.",
        advancedHint: "Mencari di lebih banyak lokasi, beberapa tingkat folder ke dalam. Menemukan lebih banyak, tetapi lebih banyak yang perlu diperiksa dengan cermat. Lebih lambat."
      },
      review: {
        services: "Layanan",
        tier: {
          certain: "Pasti",
          likely: "Kemungkinan besar",
          possible: "Mungkin",
          certainHint: "Di dalam folder program itu sendiri, atau disebut oleh entri miliknya.",
          likelyHint: "Dinamai sesuai program.",
          possibleHint: "Hanya cocok dengan nama penerbit atau satu kata dari nama program. Tidak dicentang; periksa satu per satu."
        },
        protectedNote: (n) => `Dilewati karena milik Windows atau program lain yang terpasang: ${n}.`,
        truncatedNote: "Pencarian dihentikan lebih awal agar tetap cepat, jadi mungkin masih ada lagi."
      },
      tasks: {
        removed: (n) => `Tugas terjadwal yang dihapus: ${n}. Definisinya disimpan di Cadangan pada layar Karantina, tempat tugas dapat dipulihkan.`,
        failedHeading: (n) => `Tugas terjadwal yang tidak dapat dihapus: ${n}`
      },
      forced: {
        button: "Uninstal paksa…",
        title: "Uninstal paksa",
        modalTitle: (n) => `Uninstal paksa ${n}`,
        intro: "Untuk perangkat lunak yang tidak terdaftar atau yang pencopotnya hilang. Masukkan namanya, pilih folder tempat program dipasang, atau keduanya, dan Prune akan mencari sisa-sisanya secara mendalam. Anda meninjau semuanya sebelum ada yang dihapus.",
        nameLabel: "Nama program",
        namePlaceholder: "Opsional jika Anda memilih folder",
        folderLabel: "Folder instalasi",
        folderPlaceholder: "Opsional jika Anda memasukkan nama",
        browse: "Telusuri…",
        continue: "Lanjutkan",
        needOne: "Masukkan nama atau pilih folder untuk melanjutkan.",
        pickFailed: (m) => `Tidak dapat membuka dialog folder: ${m}`,
        scanIntro: "Prune akan mencari berkas, entri registri, dan tugas terjadwal yang cocok dengan nama dan folder ini. Tidak ada yang dihapus sebelum Anda meninjaunya.",
        folderLine: (f) => `Folder: ${f}`
      }
    }
  },
  is: {
    uninstallerV3: {
      scanMode: {
        label: "Leit að leifum",
        safe: "Öruggt",
        moderate: "Í meðallagi",
        advanced: "Ítarlegt",
        safeHint: "Aðeins uppsetningarmappa forritsins sjálfs og skrárlykill þess.",
        moderateHint: "Venjulegir staðir, pöruð eftir nafni. Mælt með.",
        advancedHint: "Leitar á mun fleiri stöðum, nokkur möppustig niður. Finnur meira, en meira af því þarf vandlega skoðun. Hægari."
      },
      review: {
        services: "Þjónustur",
        tier: {
          certain: "Víst",
          likely: "Líklegt",
          possible: "Mögulegt",
          certainHint: "Inni í möppu forritsins sjálfs eða nefnt í eigin færslum þess.",
          likelyHint: "Heitir eftir forritinu.",
          possibleHint: "Pöruð aðeins við nafn útgefanda eða eitt orð úr nafni forritsins. Ekki hakað við; athugaðu hvert og eitt."
        },
        protectedNote: (n) => `Sleppt því þau tilheyra Windows eða öðrum uppsettum forritum: ${n}.`,
        truncatedNote: "Leitin stöðvaðist snemma til að vera hröð, svo það gæti verið meira."
      },
      tasks: {
        removed: (n) => `Áætluð verkefni fjarlægð: ${n}. Skilgreiningar þeirra eru vistaðar undir Afrit á skjánum Sóttkví, þar sem hægt er að endurheimta þau.`,
        failedHeading: (n) => `Áætluð verkefni sem ekki tókst að fjarlægja: ${n}`
      },
      forced: {
        button: "Þvinguð fjarlæging…",
        title: "Þvinguð fjarlæging",
        modalTitle: (n) => `Þvinguð fjarlæging á ${n}`,
        intro: "Fyrir hugbúnað sem er ekki á listanum eða þar sem fjarlægingarforritið er horfið. Settu inn nafnið, veldu möppuna sem hann var settur upp í, eða hvort tveggja, og Prune leitar rækilega að því sem eftir varð. Þú ferð yfir allt áður en nokkuð er fjarlægt.",
        nameLabel: "Heiti forrits",
        namePlaceholder: "Valfrjálst ef þú velur möppu",
        folderLabel: "Uppsetningarmappa",
        folderPlaceholder: "Valfrjálst ef þú slærð inn nafn",
        browse: "Vafra…",
        continue: "Halda áfram",
        needOne: "Sláðu inn nafn eða veldu möppu til að halda áfram.",
        pickFailed: (m) => `Ekki tókst að opna möppugluggann: ${m}`,
        scanIntro: "Prune leitar að skrám, skrárfærslum og áætluðum verkefnum sem passa við þetta nafn og þessa möppu. Engu er eytt fyrr en þú hefur farið yfir það.",
        folderLine: (f) => `Mappa: ${f}`
      }
    }
  },
  it: {
    uninstallerV3: {
      scanMode: {
        label: "Ricerca dei residui",
        safe: "Sicura",
        moderate: "Moderata",
        advanced: "Avanzata",
        safeHint: "Solo la cartella di installazione del programma e la sua chiave del registro.",
        moderateHint: "I posti consueti, individuati per nome. Consigliata.",
        advancedHint: "Cerca in molte più posizioni, a più livelli di cartelle. Trova di più, ma richiede più attenzione. Più lenta."
      },
      review: {
        services: "Servizi",
        tier: {
          certain: "Certo",
          likely: "Probabile",
          possible: "Possibile",
          certainHint: "Dentro la cartella del programma stesso, o indicato dalle sue voci.",
          likelyHint: "Porta il nome del programma.",
          possibleHint: "Trovato solo dal nome del produttore o da una parola del nome del programma. Non selezionato; controlla ogni voce."
        },
        protectedNote: (n) => `Esclusi perché appartengono a Windows o ad altri programmi installati: ${n}.`,
        truncatedNote: "La ricerca si è fermata prima per restare veloce, quindi potrebbe esserci altro."
      },
      tasks: {
        removed: (n) => `Attività pianificate rimosse: ${n}. Le loro definizioni sono salvate in Backup, nella schermata Quarantena, da cui si possono ripristinare.`,
        failedHeading: (n) => `Attività pianificate che non è stato possibile rimuovere: ${n}`
      },
      forced: {
        button: "Disinstallazione forzata…",
        title: "Disinstallazione forzata",
        modalTitle: (n) => `Disinstallazione forzata di ${n}`,
        intro: "Per il software che non è in elenco o il cui programma di disinstallazione non c'è più. Indica il nome, scegli la cartella in cui è stato installato, o entrambi, e Prune cerca a fondo ciò che ha lasciato. Controlli tutto prima che venga rimosso qualcosa.",
        nameLabel: "Nome del programma",
        namePlaceholder: "Facoltativo se scegli una cartella",
        folderLabel: "Cartella di installazione",
        folderPlaceholder: "Facoltativo se inserisci un nome",
        browse: "Sfoglia…",
        continue: "Continua",
        needOne: "Inserisci un nome o scegli una cartella per continuare.",
        pickFailed: (m) => `Impossibile aprire la finestra delle cartelle: ${m}`,
        scanIntro: "Prune cercherà file, voci del registro e attività pianificate corrispondenti a questo nome e a questa cartella. Non viene rimosso nulla finché non l'hai controllato.",
        folderLine: (f) => `Cartella: ${f}`
      }
    }
  },
  ja: {
    uninstallerV3: {
      scanMode: {
        label: "残留物のスキャン",
        safe: "安全",
        moderate: "標準",
        advanced: "詳細",
        safeHint: "プログラム自身のインストール フォルダーとレジストリ キーのみ。",
        moderateHint: "一般的な場所を名前の一致で検索します。推奨。",
        advancedHint: "はるかに多くの場所を、複数階層のフォルダーまで検索します。多く見つかりますが、慎重な確認が必要なものも増えます。時間がかかります。"
      },
      review: {
        services: "サービス",
        tier: {
          certain: "確実",
          likely: "可能性が高い",
          possible: "可能性あり",
          certainHint: "プログラム自身のフォルダー内にある、またはプログラム自身の登録項目で指定されています。",
          likelyHint: "プログラム名が付いています。",
          possibleHint: "発行元の名前、またはプログラム名の一語のみに一致しました。オフになっています。1 件ずつ確認してください。"
        },
        protectedNote: (n) => `Windows または他のインストール済みプログラムのものであるため除外した項目: ${n} 件。`,
        truncatedNote: "速度を保つために検索を途中で止めたため、ほかにも残っている可能性があります。"
      },
      tasks: {
        removed: (n) => `削除したタスク スケジューラのタスク: ${n} 件。定義は「隔離」画面の「バックアップ」に保存されており、復元できます。`,
        failedHeading: (n) => `削除できなかったタスク スケジューラのタスク: ${n} 件`
      },
      forced: {
        button: "強制アンインストール…",
        title: "強制アンインストール",
        modalTitle: (n) => `${n} の強制アンインストール`,
        intro: "一覧にないソフトウェアや、アンインストーラーが失われたソフトウェア向けです。名前、インストール先フォルダー、またはその両方を指定すると、Prune が残っているものを詳しく検索します。何かを削除する前に、すべて確認できます。",
        nameLabel: "プログラム名",
        namePlaceholder: "フォルダーを選ぶ場合は省略できます",
        folderLabel: "インストール フォルダー",
        folderPlaceholder: "名前を入力する場合は省略できます",
        browse: "参照…",
        continue: "続行",
        needOne: "続行するには、名前を入力するかフォルダーを選んでください。",
        pickFailed: (m) => `フォルダー選択ダイアログを開けませんでした: ${m}`,
        scanIntro: "この名前とフォルダーに一致するファイル、レジストリ エントリ、タスクを検索します。確認するまで何も削除されません。",
        folderLine: (f) => `フォルダー: ${f}`
      }
    }
  },
  ko: {
    uninstallerV3: {
      scanMode: {
        label: "남은 항목 검사",
        safe: "안전",
        moderate: "보통",
        advanced: "고급",
        safeHint: "프로그램 자체의 설치 폴더와 레지스트리 키만 검사합니다.",
        moderateHint: "일반적인 위치를 이름으로 일치시켜 검사합니다. 권장.",
        advancedHint: "훨씬 더 많은 위치를 여러 단계의 폴더까지 검색합니다. 더 많이 찾지만 신중한 확인이 필요한 항목도 늘어납니다. 더 느립니다."
      },
      review: {
        services: "서비스",
        tier: {
          certain: "확실",
          likely: "가능성 높음",
          possible: "가능성 있음",
          certainHint: "프로그램 자체 폴더 안에 있거나 프로그램 자신의 항목이 가리키는 항목입니다.",
          likelyHint: "프로그램 이름을 따른 항목입니다.",
          possibleHint: "게시자 이름 또는 프로그램 이름의 한 단어와만 일치합니다. 선택되지 않았으니 하나씩 확인하세요."
        },
        protectedNote: (n) => `Windows 또는 다른 설치된 프로그램에 속해 제외된 항목: ${n}개.`,
        truncatedNote: "속도를 유지하려고 검색을 일찍 멈췄으므로 더 있을 수 있습니다."
      },
      tasks: {
        removed: (n) => `제거된 예약 작업: ${n}개. 정의는 격리 화면의 백업에 저장되어 있으며 복원할 수 있습니다.`,
        failedHeading: (n) => `제거하지 못한 예약 작업: ${n}개`
      },
      forced: {
        button: "강제 제거…",
        title: "강제 제거",
        modalTitle: (n) => `${n} 강제 제거`,
        intro: "목록에 없거나 제거 프로그램이 사라진 소프트웨어용입니다. 이름, 설치된 폴더 또는 둘 다 지정하면 Prune이 남은 항목을 깊이 검색합니다. 무언가를 제거하기 전에 모든 항목을 직접 검토합니다.",
        nameLabel: "프로그램 이름",
        namePlaceholder: "폴더를 선택하면 생략할 수 있습니다",
        folderLabel: "설치 폴더",
        folderPlaceholder: "이름을 입력하면 생략할 수 있습니다",
        browse: "찾아보기…",
        continue: "계속",
        needOne: "계속하려면 이름을 입력하거나 폴더를 선택하세요.",
        pickFailed: (m) => `폴더 대화 상자를 열 수 없습니다: ${m}`,
        scanIntro: "이 이름과 폴더에 일치하는 파일, 레지스트리 항목, 예약 작업을 검색합니다. 검토하기 전에는 아무것도 제거되지 않습니다.",
        folderLine: (f) => `폴더: ${f}`
      }
    }
  },
  lt: {
    uninstallerV3: {
      scanMode: {
        label: "Liekanų paieška",
        safe: "Saugus",
        moderate: "Vidutinis",
        advanced: "Išplėstinis",
        safeHint: "Tik pačios programos diegimo aplankas ir registro raktas.",
        moderateHint: "Įprastos vietos, ieškoma pagal pavadinimą. Rekomenduojama.",
        advancedHint: "Ieško daug daugiau vietų, kelis aplankų lygius gilyn. Randa daugiau, bet daugiau ko reikia atidžiai peržiūrėti. Lėčiau."
      },
      review: {
        services: "Tarnybos",
        tier: {
          certain: "Tikri",
          likely: "Tikėtina",
          possible: "Galima",
          certainHint: "Pačios programos aplanke arba nurodyta jos pačios įrašų.",
          likelyHint: "Pavadinta pagal programą.",
          possibleHint: "Atitinka tik leidėjo pavadinimą arba vieną programos pavadinimo žodį. Nepažymėta; patikrinkite kiekvieną."
        },
        protectedNote: (n) => `Praleista, nes priklauso „Windows“ arba kitoms įdiegtoms programoms: ${n}.`,
        truncatedNote: "Paieška sustabdyta anksčiau, kad išliktų greita, todėl gali būti daugiau."
      },
      tasks: {
        removed: (n) => `Pašalintos suplanuotos užduotys: ${n}. Jų apibrėžtys išsaugotos skiltyje „Atsarginės kopijos“ ekrane „Karantinas“, iš kur jas galima atkurti.`,
        failedHeading: (n) => `Suplanuotos užduotys, kurių nepavyko pašalinti: ${n}`
      },
      forced: {
        button: "Priverstinis pašalinimas…",
        title: "Priverstinis pašalinimas",
        modalTitle: (n) => `Priverstinis ${n} pašalinimas`,
        intro: "Programinei įrangai, kurios nėra sąraše arba kurios šalinimo programos nebėra. Nurodykite pavadinimą, pasirinkite aplanką, kuriame ji įdiegta, arba abu – „Prune“ giliai ieškos, kas liko. Viską peržiūrite prieš ką nors pašalinant.",
        nameLabel: "Programos pavadinimas",
        namePlaceholder: "Neprivaloma, jei pasirinksite aplanką",
        folderLabel: "Diegimo aplankas",
        folderPlaceholder: "Neprivaloma, jei įvesite pavadinimą",
        browse: "Naršyti…",
        continue: "Tęsti",
        needOne: "Norėdami tęsti, įveskite pavadinimą arba pasirinkite aplanką.",
        pickFailed: (m) => `Nepavyko atidaryti aplanko dialogo: ${m}`,
        scanIntro: "„Prune“ ieškos failų, registro įrašų ir suplanuotų užduočių, atitinkančių šį pavadinimą ir aplanką. Niekas nepašalinama, kol jūs to neperžiūrėsite.",
        folderLine: (f) => `Aplankas: ${f}`
      }
    }
  },
  ms: {
    uninstallerV3: {
      scanMode: {
        label: "Imbasan baki",
        safe: "Selamat",
        moderate: "Sederhana",
        advanced: "Lanjutan",
        safeHint: "Hanya folder pemasangan dan kunci pendaftaran program itu sendiri.",
        moderateHint: "Lokasi biasa, dipadankan mengikut nama. Disyorkan.",
        advancedHint: "Mencari di lebih banyak lokasi, beberapa peringkat folder ke dalam. Menjumpai lebih banyak, tetapi lebih banyak yang perlu disemak dengan teliti. Lebih perlahan."
      },
      review: {
        services: "Perkhidmatan",
        tier: {
          certain: "Pasti",
          likely: "Berkemungkinan besar",
          possible: "Mungkin",
          certainHint: "Di dalam folder program itu sendiri, atau disebut oleh entrinya sendiri.",
          likelyHint: "Dinamakan sempena program.",
          possibleHint: "Hanya sepadan dengan nama penerbit atau satu perkataan nama program. Tidak ditanda; semak satu demi satu."
        },
        protectedNote: (n) => `Ditinggalkan kerana milik Windows atau program lain yang dipasang: ${n}.`,
        truncatedNote: "Carian dihentikan awal untuk kekal pantas, jadi mungkin ada lagi."
      },
      tasks: {
        removed: (n) => `Tugas berjadual dialihkan: ${n}. Takrifannya disimpan di bawah Sandaran pada skrin Kuarantin, tempat ia boleh dipulihkan.`,
        failedHeading: (n) => `Tugas berjadual yang tidak dapat dialihkan: ${n}`
      },
      forced: {
        button: "Nyahpasang paksa…",
        title: "Nyahpasang paksa",
        modalTitle: (n) => `Nyahpasang paksa ${n}`,
        intro: "Untuk perisian yang tidak disenaraikan atau pemasangnya telah hilang. Beri namanya, pilih folder tempat ia dipasang, atau kedua-duanya, dan Prune akan mencari sisanya dengan mendalam. Anda menyemak semuanya sebelum apa-apa dialihkan.",
        nameLabel: "Nama program",
        namePlaceholder: "Pilihan jika anda memilih folder",
        folderLabel: "Folder pemasangan",
        folderPlaceholder: "Pilihan jika anda memasukkan nama",
        browse: "Semak imbas…",
        continue: "Teruskan",
        needOne: "Masukkan nama atau pilih folder untuk meneruskan.",
        pickFailed: (m) => `Tidak dapat membuka dialog folder: ${m}`,
        scanIntro: "Prune akan mencari fail, entri pendaftaran dan tugas berjadual yang sepadan dengan nama dan folder ini. Tiada apa-apa dialihkan sehingga anda menyemaknya.",
        folderLine: (f) => `Folder: ${f}`
      }
    }
  },
  nb: {
    uninstallerV3: {
      scanMode: {
        label: "Søk etter rester",
        safe: "Trygg",
        moderate: "Moderat",
        advanced: "Avansert",
        safeHint: "Bare programmets egen installasjonsmappe og registernøkkel.",
        moderateHint: "De vanlige stedene, funnet etter navn. Anbefalt.",
        advancedHint: "Søker på mange flere steder, flere mappenivåer ned. Finner mer, men mer av det må sjekkes nøye. Tregere."
      },
      review: {
        services: "Tjenester",
        tier: {
          certain: "Helt sikker",
          likely: "Sannsynlig",
          possible: "Mulig",
          certainHint: "Inne i programmets egen mappe eller nevnt av dets egne oppføringer.",
          likelyHint: "Oppkalt etter programmet.",
          possibleHint: "Samsvarer bare med utgiverens navn eller ett ord i programnavnet. Ikke avmerket; sjekk hver enkelt."
        },
        protectedNote: (n) => `Utelatt fordi de tilhører Windows eller andre installerte programmer: ${n}.`,
        truncatedNote: "Søket stoppet tidlig for å holde tempoet, så det kan finnes mer."
      },
      tasks: {
        removed: (n) => `Fjernede planlagte oppgaver: ${n}. Definisjonene er lagret under Sikkerhetskopier på skjermen Karantene, hvor de kan gjenopprettes.`,
        failedHeading: (n) => `Planlagte oppgaver som ikke kunne fjernes: ${n}`
      },
      forced: {
        button: "Tvunget avinstallering…",
        title: "Tvunget avinstallering",
        modalTitle: (n) => `Tvunget avinstallering av ${n}`,
        intro: "For programvare som ikke står i listen, eller som mangler avinstalleringsprogram. Oppgi navnet, velg mappen den ble installert i, eller begge deler, så søker Prune grundig etter det som er igjen. Du ser gjennom alt før noe fjernes.",
        nameLabel: "Programnavn",
        namePlaceholder: "Valgfritt hvis du velger en mappe",
        folderLabel: "Installasjonsmappe",
        folderPlaceholder: "Valgfritt hvis du oppgir et navn",
        browse: "Bla gjennom…",
        continue: "Fortsett",
        needOne: "Oppgi et navn eller velg en mappe for å fortsette.",
        pickFailed: (m) => `Kunne ikke åpne mappedialogen: ${m}`,
        scanIntro: "Prune søker etter filer, registeroppføringer og planlagte oppgaver som samsvarer med dette navnet og denne mappen. Ingenting fjernes før du har sett gjennom det.",
        folderLine: (f) => `Mappe: ${f}`
      }
    }
  },
  nl: {
    uninstallerV3: {
      scanMode: {
        label: "Scan op restanten",
        safe: "Veilig",
        moderate: "Gematigd",
        advanced: "Geavanceerd",
        safeHint: "Alleen de eigen installatiemap van het programma en de registersleutel.",
        moderateHint: "De gebruikelijke plekken, gevonden op naam. Aanbevolen.",
        advancedHint: "Doorzoekt veel meer plekken, meerdere mapniveaus diep. Vindt meer, maar meer ervan moet zorgvuldig bekeken worden. Langzamer."
      },
      review: {
        services: "Services",
        tier: {
          certain: "Zeker",
          likely: "Waarschijnlijk",
          possible: "Mogelijk",
          certainHint: "In de eigen map van het programma, of genoemd door de eigen items.",
          likelyHint: "Genoemd naar het programma.",
          possibleHint: "Alleen gevonden op de naam van de uitgever of één woord van de programmanaam. Niet aangevinkt; controleer elk item."
        },
        protectedNote: (n) => `Weggelaten omdat ze bij Windows of andere geïnstalleerde programma's horen: ${n}.`,
        truncatedNote: "De zoekopdracht stopte eerder om snel te blijven, dus er kan meer zijn."
      },
      tasks: {
        removed: (n) => `Verwijderde geplande taken: ${n}. De definities zijn opgeslagen onder Back-ups op het scherm Quarantaine, waar ze kunnen worden hersteld.`,
        failedHeading: (n) => `Geplande taken die niet verwijderd konden worden: ${n}`
      },
      forced: {
        button: "Geforceerd verwijderen…",
        title: "Geforceerd verwijderen",
        modalTitle: (n) => `${n} geforceerd verwijderen`,
        intro: "Voor software die niet in de lijst staat of waarvan het verwijderprogramma weg is. Geef de naam op, kies de map waarin het is geïnstalleerd, of beide, en Prune zoekt grondig naar wat er is achtergebleven. U bekijkt alles voordat er iets wordt verwijderd.",
        nameLabel: "Programmanaam",
        namePlaceholder: "Optioneel als u een map kiest",
        folderLabel: "Installatiemap",
        folderPlaceholder: "Optioneel als u een naam invoert",
        browse: "Bladeren…",
        continue: "Doorgaan",
        needOne: "Voer een naam in of kies een map om door te gaan.",
        pickFailed: (m) => `Het mapdialoogvenster kon niet worden geopend: ${m}`,
        scanIntro: "Prune zoekt naar bestanden, registervermeldingen en geplande taken die bij deze naam en map passen. Er wordt niets verwijderd voordat u het hebt bekeken.",
        folderLine: (f) => `Map: ${f}`
      }
    }
  },
  pl: {
    uninstallerV3: {
      scanMode: {
        label: "Skanowanie pozostałości",
        safe: "Bezpieczny",
        moderate: "Umiarkowany",
        advanced: "Zaawansowany",
        safeHint: "Tylko własny folder instalacyjny programu i jego klucz rejestru.",
        moderateHint: "Zwykłe miejsca, dopasowanie po nazwie. Zalecane.",
        advancedHint: "Przeszukuje znacznie więcej miejsc, na kilka poziomów w głąb folderów. Znajduje więcej, ale więcej wymaga uważnego przejrzenia. Wolniej."
      },
      review: {
        services: "Usługi",
        tier: {
          certain: "Pewne",
          likely: "Prawdopodobne",
          possible: "Możliwe",
          certainHint: "Wewnątrz własnego folderu programu lub wskazane przez jego własne wpisy.",
          likelyHint: "Nazwane od programu.",
          possibleHint: "Dopasowane tylko do nazwy wydawcy lub jednego słowa z nazwy programu. Niezaznaczone; sprawdź każdy element."
        },
        protectedNote: (n) => `Pominięto, ponieważ należą do systemu Windows lub innych zainstalowanych programów: ${n}.`,
        truncatedNote: "Wyszukiwanie zatrzymano wcześniej, aby było szybkie, więc może być tego więcej."
      },
      tasks: {
        removed: (n) => `Usunięte zaplanowane zadania: ${n}. Ich definicje zapisano w sekcji Kopie zapasowe na ekranie Kwarantanna, skąd można je przywrócić.`,
        failedHeading: (n) => `Zaplanowane zadania, których nie udało się usunąć: ${n}`
      },
      forced: {
        button: "Wymuszone odinstalowanie…",
        title: "Wymuszone odinstalowanie",
        modalTitle: (n) => `Wymuszone odinstalowanie: ${n}`,
        intro: "Dla oprogramowania, którego nie ma na liście lub którego dezinstalator zniknął. Podaj nazwę, wybierz folder instalacji albo jedno i drugie, a Prune dokładnie przeszuka to, co zostało. Wszystko przeglądasz, zanim cokolwiek zostanie usunięte.",
        nameLabel: "Nazwa programu",
        namePlaceholder: "Opcjonalne, jeśli wybierzesz folder",
        folderLabel: "Folder instalacji",
        folderPlaceholder: "Opcjonalne, jeśli podasz nazwę",
        browse: "Przeglądaj…",
        continue: "Dalej",
        needOne: "Aby kontynuować, wpisz nazwę lub wybierz folder.",
        pickFailed: (m) => `Nie można otworzyć okna wyboru folderu: ${m}`,
        scanIntro: "Prune wyszuka pliki, wpisy rejestru i zaplanowane zadania pasujące do tej nazwy i folderu. Nic nie zostanie usunięte, dopóki tego nie przejrzysz.",
        folderLine: (f) => `Folder: ${f}`
      }
    }
  },
  ps: {
    uninstallerV3: {
      scanMode: {
        label: "د پاتې شونو سکین",
        safe: "خوندي",
        moderate: "منځنی",
        advanced: "پرمختللی",
        safeHint: "یوازې د برنامې خپل د نصبولو فولډر او د راجستر کیلي.",
        moderateHint: "عادي ځایونه، د نوم په اساس مطابقت. وړاندیز شوی.",
        advancedHint: "ډېر نور ځایونه په څو سطحو فولډرونو کې لټوي. ډېر پیدا کوي، خو ډېر یې ته دقیق کتنه په کار ده. ورو."
      },
      review: {
        services: "خدمتونه",
        tier: {
          certain: "ډاډمن",
          likely: "احتمالي",
          possible: "ممکن",
          certainHint: "د برنامې په خپل فولډر کې، یا د هغې په خپلو ننوتنو کې یاد شوی.",
          likelyHint: "د برنامې په نوم نومول شوی.",
          possibleHint: "یوازې د خپرونکي له نوم یا د برنامې د نوم له یوې کلمې سره سمون خوري. نښه شوی نه دی؛ هر یو وګورئ."
        },
        protectedNote: (n) => `پرېښودل شوي ځکه چې د Windows یا نورو نصب شویو برنامو دي: ${n}.`,
        truncatedNote: "لټون د چټکتیا لپاره مخکې ودرول شو، نو ښايي نور هم وي."
      },
      tasks: {
        removed: (n) => `لرې شوې مهالویش شوې دندې: ${n}. تعریفونه یې د قرنطین په پرده کې د بیک‌اپونه لاندې خوندي شوي، چې له هغه ځایه بیرته راګرځول کېدای شي.`,
        failedHeading: (n) => `مهالویش شوې دندې چې لرې نه شوې: ${n}`
      },
      forced: {
        button: "جبري لرې کول…",
        title: "جبري لرې کول",
        modalTitle: (n) => `د ${n} جبري لرې کول`,
        intro: "د هغو سافټویرونو لپاره چې په لیست کې نشته یا لرې کوونکی یې ورک دی. نوم ورکړئ، هغه فولډر وټاکئ چې پکې نصب شوی، یا دواړه، او Prune به پاتې شوني ژور ولټوي. مخکې له دې چې څه لرې شي، هر څه بیاکتل کېږي.",
        nameLabel: "د برنامې نوم",
        namePlaceholder: "اختیاري که فولډر وټاکئ",
        folderLabel: "د نصبولو فولډر",
        folderPlaceholder: "اختیاري که نوم ولیکئ",
        browse: "لټون…",
        continue: "دوام ورکړئ",
        needOne: "د دوام لپاره نوم ولیکئ یا فولډر وټاکئ.",
        pickFailed: (m) => `د فولډر ډیالوګ نه شو پرانیستل: ${m}`,
        scanIntro: "Prune به هغه دوتنې، د راجستر ننوتنې او مهالویش شوې دندې ولټوي چې له دې نوم او فولډر سره سمون لري. تر هغه چې تاسو یې بیاکتنه ونکړئ، هیڅ نه لرې کېږي.",
        folderLine: (f) => `فولډر: ${f}`
      }
    }
  },
  "pt-BR": {
    uninstallerV3: {
      scanMode: {
        label: "Verificação de resíduos",
        safe: "Seguro",
        moderate: "Moderado",
        advanced: "Avançado",
        safeHint: "Somente a pasta de instalação do próprio programa e a chave dele no registro.",
        moderateHint: "Os lugares de costume, localizados pelo nome. Recomendado.",
        advancedHint: "Procura em muitos outros lugares, vários níveis de pastas. Encontra mais, mas mais itens precisam de uma análise cuidadosa. Mais lento."
      },
      review: {
        services: "Serviços",
        tier: {
          certain: "Certo",
          likely: "Provável",
          possible: "Possível",
          certainHint: "Dentro da pasta do próprio programa, ou indicado pelas entradas dele.",
          likelyHint: "Tem o nome do programa.",
          possibleHint: "Encontrado só pelo nome do editor ou por uma palavra do nome do programa. Sem marcação; confira cada um."
        },
        protectedNote: (n) => `Deixados de fora porque pertencem ao Windows ou a outros programas instalados: ${n}.`,
        truncatedNote: "A busca parou antes para continuar rápida, então pode haver mais."
      },
      tasks: {
        removed: (n) => `Tarefas agendadas removidas: ${n}. As definições foram salvas em Backups, na tela Quarentena, onde podem ser restauradas.`,
        failedHeading: (n) => `Tarefas agendadas que não puderam ser removidas: ${n}`
      },
      forced: {
        button: "Desinstalação forçada…",
        title: "Desinstalação forçada",
        modalTitle: (n) => `Desinstalação forçada de ${n}`,
        intro: "Para software que não está na lista ou cujo desinstalador sumiu. Informe o nome, escolha a pasta onde foi instalado, ou os dois, e o Prune procura a fundo o que ficou para trás. Você confere tudo antes de qualquer coisa ser removida.",
        nameLabel: "Nome do programa",
        namePlaceholder: "Opcional se você escolher uma pasta",
        folderLabel: "Pasta de instalação",
        folderPlaceholder: "Opcional se você digitar um nome",
        browse: "Procurar…",
        continue: "Continuar",
        needOne: "Digite um nome ou escolha uma pasta para continuar.",
        pickFailed: (m) => `Não foi possível abrir a caixa de pastas: ${m}`,
        scanIntro: "O Prune vai procurar arquivos, entradas do registro e tarefas agendadas que correspondam a este nome e pasta. Nada é removido até você revisar.",
        folderLine: (f) => `Pasta: ${f}`
      }
    }
  },
  pt: {
    uninstallerV3: {
      scanMode: {
        label: "Análise de resíduos",
        safe: "Seguro",
        moderate: "Moderado",
        advanced: "Avançado",
        safeHint: "Apenas a pasta de instalação do próprio programa e a respetiva chave de registo.",
        moderateHint: "Os locais habituais, encontrados pelo nome. Recomendado.",
        advancedHint: "Procura em muitos mais locais, vários níveis de pastas. Encontra mais, mas há mais itens que exigem uma análise cuidadosa. Mais lento."
      },
      review: {
        services: "Serviços",
        tier: {
          certain: "Certo",
          likely: "Provável",
          possible: "Possível",
          certainHint: "Dentro da pasta do próprio programa, ou indicado pelas respetivas entradas.",
          likelyHint: "Tem o nome do programa.",
          possibleHint: "Encontrado apenas pelo nome do editor ou por uma palavra do nome do programa. Sem marca; verifique cada um."
        },
        protectedNote: (n) => `Deixados de fora porque pertencem ao Windows ou a outros programas instalados: ${n}.`,
        truncatedNote: "A pesquisa parou mais cedo para se manter rápida, por isso pode haver mais."
      },
      tasks: {
        removed: (n) => `Tarefas agendadas removidas: ${n}. As definições ficaram guardadas em Cópias de segurança, no ecrã Quarentena, onde podem ser restauradas.`,
        failedHeading: (n) => `Tarefas agendadas que não puderam ser removidas: ${n}`
      },
      forced: {
        button: "Desinstalação forçada…",
        title: "Desinstalação forçada",
        modalTitle: (n) => `Desinstalação forçada de ${n}`,
        intro: "Para software que não está na lista ou cujo desinstalador desapareceu. Indique o nome, escolha a pasta onde foi instalado, ou ambos, e o Prune procura a fundo o que ficou para trás. Verifica tudo antes de ser removido o que quer que seja.",
        nameLabel: "Nome do programa",
        namePlaceholder: "Opcional se escolher uma pasta",
        folderLabel: "Pasta de instalação",
        folderPlaceholder: "Opcional se introduzir um nome",
        browse: "Procurar…",
        continue: "Continuar",
        needOne: "Introduza um nome ou escolha uma pasta para continuar.",
        pickFailed: (m) => `Não foi possível abrir a caixa de diálogo de pastas: ${m}`,
        scanIntro: "O Prune vai procurar ficheiros, entradas do registo e tarefas agendadas que correspondam a este nome e pasta. Nada é removido até o verificar.",
        folderLine: (f) => `Pasta: ${f}`
      }
    }
  },
  ro: {
    uninstallerV3: {
      scanMode: {
        label: "Scanarea resturilor",
        safe: "Sigur",
        moderate: "Moderat",
        advanced: "Avansat",
        safeHint: "Doar folderul de instalare al programului și cheia lui de registru.",
        moderateHint: "Locurile obișnuite, potrivite după nume. Recomandat.",
        advancedHint: "Caută în mult mai multe locuri, pe mai multe niveluri de foldere. Găsește mai mult, dar mai multe elemente trebuie verificate cu atenție. Mai lent."
      },
      review: {
        services: "Servicii",
        tier: {
          certain: "Cert",
          likely: "Probabil",
          possible: "Posibil",
          certainHint: "În folderul programului însuși sau menționat de intrările lui.",
          likelyHint: "Poartă numele programului.",
          possibleHint: "Potrivit doar după numele editorului sau un cuvânt din numele programului. Nebifat; verifică fiecare element."
        },
        protectedNote: (n) => `Omise deoarece aparțin Windows sau altor programe instalate: ${n}.`,
        truncatedNote: "Căutarea s-a oprit mai devreme pentru a rămâne rapidă, deci pot exista mai multe."
      },
      tasks: {
        removed: (n) => `Sarcini programate eliminate: ${n}. Definițiile lor sunt salvate în Copii de rezervă, pe ecranul Carantină, de unde pot fi restaurate.`,
        failedHeading: (n) => `Sarcini programate care nu au putut fi eliminate: ${n}`
      },
      forced: {
        button: "Dezinstalare forțată…",
        title: "Dezinstalare forțată",
        modalTitle: (n) => `Dezinstalare forțată a ${n}`,
        intro: "Pentru programe care nu apar în listă sau al căror dezinstalator a dispărut. Introdu numele, alege folderul în care au fost instalate, sau ambele, iar Prune caută în profunzime ce a rămas. Verifici totul înainte de a se elimina ceva.",
        nameLabel: "Numele programului",
        namePlaceholder: "Opțional dacă alegi un folder",
        folderLabel: "Folder de instalare",
        folderPlaceholder: "Opțional dacă introduci un nume",
        browse: "Răsfoiește…",
        continue: "Continuă",
        needOne: "Introdu un nume sau alege un folder pentru a continua.",
        pickFailed: (m) => `Nu s-a putut deschide dialogul de foldere: ${m}`,
        scanIntro: "Prune va căuta fișiere, intrări de registru și sarcini programate care se potrivesc cu acest nume și folder. Nimic nu este eliminat până nu verifici.",
        folderLine: (f) => `Folder: ${f}`
      }
    }
  },
  ru: {
    uninstallerV3: {
      scanMode: {
        label: "Поиск остатков",
        safe: "Безопасный",
        moderate: "Умеренный",
        advanced: "Расширенный",
        safeHint: "Только собственная папка установки программы и её раздел реестра.",
        moderateHint: "Обычные места, поиск по названию. Рекомендуется.",
        advancedHint: "Ищет в гораздо большем числе мест, на несколько уровней вглубь папок. Находит больше, но больше результатов нужно проверять внимательно. Медленнее."
      },
      review: {
        services: "Службы",
        tier: {
          certain: "Точно",
          likely: "Вероятно",
          possible: "Возможно",
          certainHint: "Внутри собственной папки программы или указано в её собственных записях.",
          likelyHint: "Названо по имени программы.",
          possibleHint: "Совпало только с именем издателя или одним словом из названия программы. Не отмечено; проверьте каждый пункт."
        },
        protectedNote: (n) => `Пропущено, так как относится к Windows или другим установленным программам: ${n}.`,
        truncatedNote: "Поиск остановлен раньше, чтобы не затягиваться, поэтому результатов может быть больше."
      },
      tasks: {
        removed: (n) => `Удалено запланированных задач: ${n}. Их описания сохранены в разделе «Резервные копии» на экране «Карантин», откуда их можно восстановить.`,
        failedHeading: (n) => `Запланированные задачи, которые не удалось удалить: ${n}`
      },
      forced: {
        button: "Принудительное удаление…",
        title: "Принудительное удаление",
        modalTitle: (n) => `Принудительное удаление: ${n}`,
        intro: "Для программ, которых нет в списке или у которых пропал деинсталлятор. Укажите название, выберите папку установки или то и другое, и Prune тщательно поищет оставшееся. Всё проверяется вами до удаления.",
        nameLabel: "Название программы",
        namePlaceholder: "Необязательно, если выбрана папка",
        folderLabel: "Папка установки",
        folderPlaceholder: "Необязательно, если указано название",
        browse: "Обзор…",
        continue: "Продолжить",
        needOne: "Чтобы продолжить, укажите название или выберите папку.",
        pickFailed: (m) => `Не удалось открыть диалог выбора папки: ${m}`,
        scanIntro: "Prune найдёт файлы, записи реестра и запланированные задачи, соответствующие этому названию и папке. Ничего не удаляется, пока вы не проверите результаты.",
        folderLine: (f) => `Папка: ${f}`
      }
    }
  },
  sk: {
    uninstallerV3: {
      scanMode: {
        label: "Hľadanie zvyškov",
        safe: "Bezpečný",
        moderate: "Stredný",
        advanced: "Pokročilý",
        safeHint: "Iba vlastný inštalačný priečinok programu a jeho kľúč v registri.",
        moderateHint: "Obvyklé miesta, hľadanie podľa názvu. Odporúčané.",
        advancedHint: "Prehľadá oveľa viac miest do niekoľkých úrovní priečinkov. Nájde viac, ale viac z toho treba starostlivo skontrolovať. Pomalšie."
      },
      review: {
        services: "Služby",
        tier: {
          certain: "Isté",
          likely: "Pravdepodobné",
          possible: "Možné",
          certainHint: "Vo vlastnom priečinku programu alebo uvedené v jeho vlastných záznamoch.",
          likelyHint: "Pomenované podľa programu.",
          possibleHint: "Zhoda iba podľa mena vydavateľa alebo jedného slova z názvu programu. Nie je zaškrtnuté; skontrolujte každé zvlášť."
        },
        protectedNote: (n) => `Vynechané, pretože patria Windowsu alebo iným nainštalovaným programom: ${n}.`,
        truncatedNote: "Hľadanie sa predčasne zastavilo, aby zostalo rýchle, takže môže byť viac výsledkov."
      },
      tasks: {
        removed: (n) => `Odstránené naplánované úlohy: ${n}. Ich definície sú uložené v časti Zálohy na obrazovke Karanténa, odkiaľ sa dajú obnoviť.`,
        failedHeading: (n) => `Naplánované úlohy, ktoré sa nepodarilo odstrániť: ${n}`
      },
      forced: {
        button: "Vynútené odinštalovanie…",
        title: "Vynútené odinštalovanie",
        modalTitle: (n) => `Vynútené odinštalovanie: ${n}`,
        intro: "Pre softvér, ktorý nie je v zozname alebo ktorého odinštalátor zmizol. Zadajte názov, vyberte priečinok, do ktorého bol nainštalovaný, alebo oboje a Prune dôkladne vyhľadá, čo po ňom zostalo. Všetko skontrolujete, kým sa niečo odstráni.",
        nameLabel: "Názov programu",
        namePlaceholder: "Voliteľné, ak vyberiete priečinok",
        folderLabel: "Inštalačný priečinok",
        folderPlaceholder: "Voliteľné, ak zadáte názov",
        browse: "Prehľadávať…",
        continue: "Pokračovať",
        needOne: "Ak chcete pokračovať, zadajte názov alebo vyberte priečinok.",
        pickFailed: (m) => `Dialóg priečinka sa nepodarilo otvoriť: ${m}`,
        scanIntro: "Prune vyhľadá súbory, položky registra a naplánované úlohy zodpovedajúce tomuto názvu a priečinku. Nič sa neodstráni, kým to nepreveríte.",
        folderLine: (f) => `Priečinok: ${f}`
      }
    }
  },
  sq: {
    uninstallerV3: {
      scanMode: {
        label: "Skanimi i mbetjeve",
        safe: "I sigurt",
        moderate: "Mesatar",
        advanced: "I avancuar",
        safeHint: "Vetëm dosja e instalimit të vetë programit dhe çelësi i tij në regjistër.",
        moderateHint: "Vendet e zakonshme, të përputhura sipas emrit. E rekomanduar.",
        advancedHint: "Kërkon në shumë më tepër vende, disa nivele dosjesh në thellësi. Gjen më shumë, por më shumë prej tyre kërkojnë shqyrtim të kujdesshëm. Më ngadalë."
      },
      review: {
        services: "Shërbimet",
        tier: {
          certain: "E konfirmuar",
          likely: "Me gjasë",
          possible: "E mundur",
          certainHint: "Brenda dosjes së vetë programit, ose e përmendur nga shënimet e tij.",
          likelyHint: "Mban emrin e programit.",
          possibleHint: "U përputh vetëm me emrin e botuesit ose një fjalë të emrit të programit. Pa shenjë; kontrolloji një nga një."
        },
        protectedNote: (n) => `Lënë jashtë sepse i përkasin Windows ose programeve të tjera të instaluara: ${n}.`,
        truncatedNote: "Kërkimi u ndal herët për të mbetur i shpejtë, kështu që mund të ketë më shumë."
      },
      tasks: {
        removed: (n) => `Detyra të planifikuara të hequra: ${n}. Përkufizimet e tyre ruhen te Kopjet rezervë në ekranin Karantina, ku mund të rikthehen.`,
        failedHeading: (n) => `Detyra të planifikuara që nuk u hoqën: ${n}`
      },
      forced: {
        button: "Çinstalim i detyruar…",
        title: "Çinstalim i detyruar",
        modalTitle: (n) => `Çinstalim i detyruar i ${n}`,
        intro: "Për softuer që nuk është në listë ose që ka humbur çinstaluesin. Jepni emrin, zgjidhni dosjen ku është instaluar, ose të dyja, dhe Prune kërkon thellë çfarë ka lënë pas. Çdo gjë e shqyrtoni para se të hiqet diçka.",
        nameLabel: "Emri i programit",
        namePlaceholder: "Opsionale nëse zgjidhni një dosje",
        folderLabel: "Dosja e instalimit",
        folderPlaceholder: "Opsionale nëse jepni një emër",
        browse: "Shfleto…",
        continue: "Vazhdo",
        needOne: "Jepni një emër ose zgjidhni një dosje për të vazhduar.",
        pickFailed: (m) => `Nuk u hap dot dialogu i dosjes: ${m}`,
        scanIntro: "Prune do të kërkojë skedarë, shënime regjistri dhe detyra të planifikuara që përputhen me këtë emër dhe dosje. Asgjë nuk hiqet para se ta shqyrtoni.",
        folderLine: (f) => `Dosja: ${f}`
      }
    }
  },
  sr: {
    uninstallerV3: {
      scanMode: {
        label: "Претрага остатака",
        safe: "Безбедан",
        moderate: "Умерен",
        advanced: "Напредан",
        safeHint: "Само инсталациона фасцикла програма и његов кључ у регистру.",
        moderateHint: "Уобичајена места, претрага по називу. Препоручено.",
        advancedHint: "Претражује знатно више места, неколико нивоа фасцикли у дубину. Налази више, али више тога треба пажљиво прегледати. Спорије."
      },
      review: {
        services: "Услуге",
        tier: {
          certain: "Сигурно",
          likely: "Вероватно",
          possible: "Могуће",
          certainHint: "Унутар фасцикле самог програма или наведено у његовим уносима.",
          likelyHint: "Назван по програму.",
          possibleHint: "Поклапа се само са именом издавача или једном речју из назива програма. Није означено; проверите сваку ставку."
        },
        protectedNote: (n) => `Изостављено јер припада Windows-у или другим инсталираним програмима: ${n}.`,
        truncatedNote: "Претрага је стала раније да би остала брза, па може бити још резултата."
      },
      tasks: {
        removed: (n) => `Уклоњени заказани задаци: ${n}. Њихове дефиниције су сачуване у одељку Резервне копије на екрану Карантин, одакле се могу вратити.`,
        failedHeading: (n) => `Заказани задаци који нису могли да се уклоне: ${n}`
      },
      forced: {
        button: "Принудна деинсталација…",
        title: "Принудна деинсталација",
        modalTitle: (n) => `Принудна деинсталација: ${n}`,
        intro: "За софтвер којег нема на листи или коме је нестао програм за деинсталацију. Унесите назив, изаберите фасциклу у којој је инсталиран, или оба, а Prune ће темељно потражити шта је остало. Све прегледате пре него што се нешто уклони.",
        nameLabel: "Назив програма",
        namePlaceholder: "Необавезно ако изаберете фасциклу",
        folderLabel: "Инсталациона фасцикла",
        folderPlaceholder: "Необавезно ако унесете назив",
        browse: "Прегледај…",
        continue: "Настави",
        needOne: "Унесите назив или изаберите фасциклу да бисте наставили.",
        pickFailed: (m) => `Није могуће отворити дијалог фасцикле: ${m}`,
        scanIntro: "Prune ће потражити датотеке, уносе у регистру и заказане задатке који одговарају овом називу и фасцикли. Ништа се не уклања док то не прегледате.",
        folderLine: (f) => `Фасцикла: ${f}`
      }
    }
  },
  sv: {
    uninstallerV3: {
      scanMode: {
        label: "Sökning efter rester",
        safe: "Säker",
        moderate: "Måttlig",
        advanced: "Avancerad",
        safeHint: "Bara programmets egen installationsmapp och registernyckel.",
        moderateHint: "De vanliga platserna, matchade på namn. Rekommenderas.",
        advancedHint: "Söker på många fler platser, flera mappnivåer ner. Hittar mer, men mer av det behöver granskas noga. Långsammare."
      },
      review: {
        services: "Tjänster",
        tier: {
          certain: "Visst",
          likely: "Sannolikt",
          possible: "Möjligt",
          certainHint: "Inne i programmets egen mapp eller nämnt av dess egna poster.",
          likelyHint: "Uppkallat efter programmet.",
          possibleHint: "Matchar bara utgivarens namn eller ett ord i programnamnet. Inte ikryssat; kontrollera varje."
        },
        protectedNote: (n) => `Utelämnade eftersom de tillhör Windows eller andra installerade program: ${n}.`,
        truncatedNote: "Sökningen stoppades tidigt för att hålla farten, så det kan finnas mer."
      },
      tasks: {
        removed: (n) => `Borttagna schemalagda aktiviteter: ${n}. Deras definitioner är sparade under Säkerhetskopior på skärmen Karantän, där de kan återställas.`,
        failedHeading: (n) => `Schemalagda aktiviteter som inte kunde tas bort: ${n}`
      },
      forced: {
        button: "Påtvingad avinstallation…",
        title: "Påtvingad avinstallation",
        modalTitle: (n) => `Påtvingad avinstallation av ${n}`,
        intro: "För programvara som inte finns i listan eller vars avinstallationsprogram saknas. Ange namnet, välj mappen den installerades i, eller båda, så söker Prune grundligt efter det som blev kvar. Du granskar allt innan något tas bort.",
        nameLabel: "Programnamn",
        namePlaceholder: "Valfritt om du väljer en mapp",
        folderLabel: "Installationsmapp",
        folderPlaceholder: "Valfritt om du anger ett namn",
        browse: "Bläddra…",
        continue: "Fortsätt",
        needOne: "Ange ett namn eller välj en mapp för att fortsätta.",
        pickFailed: (m) => `Det gick inte att öppna mappdialogen: ${m}`,
        scanIntro: "Prune söker efter filer, registerposter och schemalagda aktiviteter som matchar detta namn och denna mapp. Inget tas bort innan du har granskat det.",
        folderLine: (f) => `Mapp: ${f}`
      }
    }
  },
  th: {
    uninstallerV3: {
      scanMode: {
        label: "การสแกนสิ่งตกค้าง",
        safe: "ปลอดภัย",
        moderate: "ปานกลาง",
        advanced: "ขั้นสูง",
        safeHint: "เฉพาะโฟลเดอร์ติดตั้งของโปรแกรมเองและคีย์รีจิสทรีของมัน",
        moderateHint: "ตำแหน่งที่พบบ่อย จับคู่ตามชื่อ แนะนำ",
        advancedHint: "ค้นหาในตำแหน่งอีกมากมาย ลึกหลายระดับโฟลเดอร์ พบมากขึ้น แต่ต้องตรวจสอบอย่างระมัดระวังมากขึ้น ช้ากว่า"
      },
      review: {
        services: "บริการ",
        tier: {
          certain: "แน่นอน",
          likely: "น่าจะใช่",
          possible: "อาจใช่",
          certainHint: "อยู่ในโฟลเดอร์ของโปรแกรมเอง หรือถูกระบุโดยรายการของโปรแกรมเอง",
          likelyHint: "ตั้งชื่อตามโปรแกรม",
          possibleHint: "ตรงกับชื่อผู้เผยแพร่หรือคำเดียวในชื่อโปรแกรมเท่านั้น ไม่ได้ติ๊กไว้ ตรวจสอบทีละรายการ"
        },
        protectedNote: (n) => `ข้ามไปเพราะเป็นของ Windows หรือโปรแกรมอื่นที่ติดตั้งไว้: ${n}`,
        truncatedNote: "การค้นหาหยุดก่อนเวลาเพื่อให้ยังเร็วอยู่ จึงอาจยังมีอีก"
      },
      tasks: {
        removed: (n) => `งานที่ตั้งเวลาไว้ที่นำออก: ${n} รายการ คำจำกัดความถูกบันทึกไว้ในการสำรองข้อมูล บนหน้ากักกัน ซึ่งสามารถกู้คืนได้`,
        failedHeading: (n) => `งานที่ตั้งเวลาไว้ที่นำออกไม่ได้: ${n} รายการ`
      },
      forced: {
        button: "บังคับถอนการติดตั้ง…",
        title: "บังคับถอนการติดตั้ง",
        modalTitle: (n) => `บังคับถอนการติดตั้ง ${n}`,
        intro: "สำหรับซอฟต์แวร์ที่ไม่อยู่ในรายการ หรือโปรแกรมถอนการติดตั้งหายไป ระบุชื่อ เลือกโฟลเดอร์ที่ติดตั้งไว้ หรือทั้งสองอย่าง แล้ว Prune จะค้นหาสิ่งที่ตกค้างอย่างละเอียด คุณตรวจสอบทุกอย่างก่อนที่จะมีสิ่งใดถูกนำออก",
        nameLabel: "ชื่อโปรแกรม",
        namePlaceholder: "ไม่บังคับหากเลือกโฟลเดอร์",
        folderLabel: "โฟลเดอร์ติดตั้ง",
        folderPlaceholder: "ไม่บังคับหากกรอกชื่อ",
        browse: "เรียกดู…",
        continue: "ดำเนินการต่อ",
        needOne: "กรอกชื่อหรือเลือกโฟลเดอร์เพื่อดำเนินการต่อ",
        pickFailed: (m) => `เปิดกล่องโต้ตอบโฟลเดอร์ไม่ได้: ${m}`,
        scanIntro: "Prune จะค้นหาไฟล์ รายการรีจิสทรี และงานที่ตั้งเวลาไว้ซึ่งตรงกับชื่อและโฟลเดอร์นี้ จะไม่มีสิ่งใดถูกนำออกจนกว่าคุณจะตรวจสอบ",
        folderLine: (f) => `โฟลเดอร์: ${f}`
      }
    }
  },
  tr: {
    uninstallerV3: {
      scanMode: {
        label: "Artık tarama",
        safe: "Güvenli",
        moderate: "Orta",
        advanced: "Gelişmiş",
        safeHint: "Yalnızca programın kendi kurulum klasörü ve kayıt defteri anahtarı.",
        moderateHint: "Olağan yerler, ada göre eşleştirilir. Önerilir.",
        advancedHint: "Çok daha fazla yerde, birkaç klasör derinliğinde arar. Daha çok şey bulur, ancak bunların daha fazlası dikkatle incelenmeli. Daha yavaş."
      },
      review: {
        services: "Hizmetler",
        tier: {
          certain: "Kesin",
          likely: "Muhtemel",
          possible: "Olası",
          certainHint: "Programın kendi klasörünün içinde veya kendi girdileriyle belirtilmiş.",
          likelyHint: "Programın adını taşıyor.",
          possibleHint: "Yalnızca yayıncı adıyla veya program adının tek bir sözcüğüyle eşleşti. İşaretli değil; her birini kontrol edin."
        },
        protectedNote: (n) => `Windows'a veya yüklü diğer programlara ait oldukları için dışarıda bırakıldı: ${n}.`,
        truncatedNote: "Arama hızlı kalması için erken durduruldu, bu yüzden daha fazlası olabilir."
      },
      tasks: {
        removed: (n) => `Kaldırılan zamanlanmış görevler: ${n}. Tanımları Karantina ekranındaki Yedekler bölümüne kaydedildi; oradan geri yüklenebilir.`,
        failedHeading: (n) => `Kaldırılamayan zamanlanmış görevler: ${n}`
      },
      forced: {
        button: "Zorla kaldır…",
        title: "Zorla kaldır",
        modalTitle: (n) => `${n} zorla kaldırılıyor`,
        intro: "Listede olmayan veya kaldırıcısı kaybolmuş yazılımlar için. Adını girin, kurulduğu klasörü seçin ya da ikisini birden yapın; Prune geride kalanları derinlemesine arar. Bir şey kaldırılmadan önce her şeyi siz gözden geçirirsiniz.",
        nameLabel: "Program adı",
        namePlaceholder: "Klasör seçerseniz isteğe bağlı",
        folderLabel: "Kurulum klasörü",
        folderPlaceholder: "Ad girerseniz isteğe bağlı",
        browse: "Gözat…",
        continue: "Devam",
        needOne: "Devam etmek için bir ad girin veya bir klasör seçin.",
        pickFailed: (m) => `Klasör iletişim kutusu açılamadı: ${m}`,
        scanIntro: "Prune bu ad ve klasörle eşleşen dosyaları, kayıt defteri girdilerini ve zamanlanmış görevleri arar. Siz gözden geçirmeden hiçbir şey kaldırılmaz.",
        folderLine: (f) => `Klasör: ${f}`
      }
    }
  },
  uk: {
    uninstallerV3: {
      scanMode: {
        label: "Пошук залишків",
        safe: "Безпечний",
        moderate: "Помірний",
        advanced: "Розширений",
        safeHint: "Лише власна папка встановлення програми та її розділ реєстру.",
        moderateHint: "Звичайні місця, пошук за назвою. Рекомендовано.",
        advancedHint: "Шукає в набагато більшій кількості місць, на кілька рівнів углиб папок. Знаходить більше, але більше результатів потрібно уважно перевіряти. Повільніше."
      },
      review: {
        services: "Служби",
        tier: {
          certain: "Точно",
          likely: "Імовірно",
          possible: "Можливо",
          certainHint: "Усередині власної папки програми або вказано у її власних записах.",
          likelyHint: "Названо за іменем програми.",
          possibleHint: "Збіг лише з іменем видавця або одним словом із назви програми. Не позначено; перевірте кожен пункт."
        },
        protectedNote: (n) => `Пропущено, бо належить Windows або іншим встановленим програмам: ${n}.`,
        truncatedNote: "Пошук зупинено раніше, щоб він лишався швидким, тож результатів може бути більше."
      },
      tasks: {
        removed: (n) => `Вилучено запланованих завдань: ${n}. Їхні описи збережено в розділі «Резервні копії» на екрані «Карантин», звідки їх можна відновити.`,
        failedHeading: (n) => `Запланованих завдань, які не вдалося вилучити: ${n}`
      },
      forced: {
        button: "Примусове видалення…",
        title: "Примусове видалення",
        modalTitle: (n) => `Примусове видалення: ${n}`,
        intro: "Для програм, яких немає у списку або в яких зник деінсталятор. Вкажіть назву, виберіть папку встановлення чи те й інше, і Prune ретельно пошукає залишки. Ви переглядаєте все до того, як щось буде видалено.",
        nameLabel: "Назва програми",
        namePlaceholder: "Необов’язково, якщо вибрано папку",
        folderLabel: "Папка встановлення",
        folderPlaceholder: "Необов’язково, якщо вказано назву",
        browse: "Огляд…",
        continue: "Продовжити",
        needOne: "Щоб продовжити, вкажіть назву або виберіть папку.",
        pickFailed: (m) => `Не вдалося відкрити діалог вибору папки: ${m}`,
        scanIntro: "Prune знайде файли, записи реєстру та заплановані завдання, що відповідають цій назві й папці. Нічого не видаляється, доки ви не перевірите результати.",
        folderLine: (f) => `Папка: ${f}`
      }
    }
  },
  vi: {
    uninstallerV3: {
      scanMode: {
        label: "Quét tệp sót lại",
        safe: "An toàn",
        moderate: "Vừa phải",
        advanced: "Nâng cao",
        safeHint: "Chỉ thư mục cài đặt và khóa registry của chính chương trình.",
        moderateHint: "Các vị trí thông thường, khớp theo tên. Khuyên dùng.",
        advancedHint: "Tìm ở nhiều vị trí hơn, sâu nhiều cấp thư mục. Tìm được nhiều hơn, nhưng cần xem xét cẩn thận hơn. Chậm hơn."
      },
      review: {
        services: "Dịch vụ",
        tier: {
          certain: "Chắc chắn",
          likely: "Nhiều khả năng",
          possible: "Có thể",
          certainHint: "Nằm trong thư mục của chính chương trình, hoặc được các mục của nó chỉ định.",
          likelyHint: "Được đặt tên theo chương trình.",
          possibleHint: "Chỉ khớp với tên nhà phát hành hoặc một từ trong tên chương trình. Chưa đánh dấu; hãy kiểm tra từng mục."
        },
        protectedNote: (n) => `Đã bỏ qua vì thuộc về Windows hoặc chương trình khác đã cài: ${n}.`,
        truncatedNote: "Việc tìm kiếm dừng sớm để giữ tốc độ, nên có thể còn nhiều hơn."
      },
      tasks: {
        removed: (n) => `Tác vụ đã lên lịch đã gỡ: ${n}. Định nghĩa của chúng được lưu trong Bản sao lưu trên màn hình Khu cách ly, nơi có thể khôi phục.`,
        failedHeading: (n) => `Tác vụ đã lên lịch không thể gỡ: ${n}`
      },
      forced: {
        button: "Gỡ cài đặt cưỡng bức…",
        title: "Gỡ cài đặt cưỡng bức",
        modalTitle: (n) => `Gỡ cài đặt cưỡng bức ${n}`,
        intro: "Dành cho phần mềm không có trong danh sách hoặc đã mất trình gỡ cài đặt. Nhập tên, chọn thư mục đã cài đặt, hoặc cả hai, và Prune sẽ tìm kỹ những gì còn sót lại. Bạn xem lại mọi thứ trước khi có gì bị xóa.",
        nameLabel: "Tên chương trình",
        namePlaceholder: "Tùy chọn nếu bạn chọn thư mục",
        folderLabel: "Thư mục cài đặt",
        folderPlaceholder: "Tùy chọn nếu bạn nhập tên",
        browse: "Duyệt…",
        continue: "Tiếp tục",
        needOne: "Nhập tên hoặc chọn thư mục để tiếp tục.",
        pickFailed: (m) => `Không mở được hộp thoại thư mục: ${m}`,
        scanIntro: "Prune sẽ tìm tệp, mục registry và tác vụ đã lên lịch khớp với tên và thư mục này. Không có gì bị xóa cho đến khi bạn xem lại.",
        folderLine: (f) => `Thư mục: ${f}`
      }
    }
  },
  "zh-CN": {
    uninstallerV3: {
      scanMode: {
        label: "残留项扫描",
        safe: "安全",
        moderate: "适中",
        advanced: "高级",
        safeHint: "仅限程序自身的安装文件夹及其注册表项。",
        moderateHint: "常见位置，按名称匹配。推荐。",
        advancedHint: "搜索更多位置，深入多层文件夹。能找到更多，但需要仔细核对的也更多。速度较慢。"
      },
      review: {
        services: "服务",
        tier: {
          certain: "确定",
          likely: "很可能",
          possible: "可能",
          certainHint: "位于程序自身的文件夹内，或由程序自己的条目指明。",
          likelyHint: "以该程序命名。",
          possibleHint: "仅与发布者名称或程序名称中的一个词匹配。未勾选，请逐项检查。"
        },
        protectedNote: (n) => `因属于 Windows 或其他已安装程序而排除：${n} 项。`,
        truncatedNote: "为保持速度，搜索提前停止，因此可能还有更多。"
      },
      tasks: {
        removed: (n) => `已移除的计划任务：${n} 个。其定义已保存到“隔离区”页面的“备份”中，可从那里还原。`,
        failedHeading: (n) => `无法移除的计划任务：${n} 个`
      },
      forced: {
        button: "强制卸载…",
        title: "强制卸载",
        modalTitle: (n) => `强制卸载 ${n}`,
        intro: "适用于未列出或卸载程序已丢失的软件。输入名称、选择其安装文件夹，或两者都提供，Prune 会深入搜索其留下的内容。在移除任何内容之前，你都可以先全部检查。",
        nameLabel: "程序名称",
        namePlaceholder: "选择文件夹时可不填",
        folderLabel: "安装文件夹",
        folderPlaceholder: "输入名称时可不填",
        browse: "浏览…",
        continue: "继续",
        needOne: "请输入名称或选择文件夹以继续。",
        pickFailed: (m) => `无法打开文件夹对话框：${m}`,
        scanIntro: "Prune 会搜索与此名称和文件夹匹配的文件、注册表项和计划任务。在你检查之前不会移除任何内容。",
        folderLine: (f) => `文件夹：${f}`
      }
    }
  },
  "zh-TW": {
    uninstallerV3: {
      scanMode: {
        label: "殘留項目掃描",
        safe: "安全",
        moderate: "適中",
        advanced: "進階",
        safeHint: "僅限程式本身的安裝資料夾與其登錄機碼。",
        moderateHint: "常見位置，依名稱比對。建議使用。",
        advancedHint: "搜尋更多位置，深入多層資料夾。能找到更多，但需要仔細確認的也更多。速度較慢。"
      },
      review: {
        services: "服務",
        tier: {
          certain: "確定",
          likely: "很可能",
          possible: "可能",
          certainHint: "位於程式本身的資料夾內，或由程式自己的項目指明。",
          likelyHint: "以該程式命名。",
          possibleHint: "僅與發行者名稱或程式名稱中的一個詞相符。未勾選，請逐項檢查。"
        },
        protectedNote: (n) => `因屬於 Windows 或其他已安裝程式而排除：${n} 項。`,
        truncatedNote: "為保持速度，搜尋提前停止，因此可能還有更多。"
      },
      tasks: {
        removed: (n) => `已移除的排程工作：${n} 個。其定義已儲存到「隔離區」頁面的「備份」中，可從那裡還原。`,
        failedHeading: (n) => `無法移除的排程工作：${n} 個`
      },
      forced: {
        button: "強制解除安裝…",
        title: "強制解除安裝",
        modalTitle: (n) => `強制解除安裝 ${n}`,
        intro: "適用於未列出或解除安裝程式已遺失的軟體。輸入名稱、選擇其安裝資料夾，或兩者都提供，Prune 會深入搜尋其留下的內容。在移除任何內容之前，你都可以先全部檢查。",
        nameLabel: "程式名稱",
        namePlaceholder: "選擇資料夾時可不填",
        folderLabel: "安裝資料夾",
        folderPlaceholder: "輸入名稱時可不填",
        browse: "瀏覽…",
        continue: "繼續",
        needOne: "請輸入名稱或選擇資料夾以繼續。",
        pickFailed: (m) => `無法開啟資料夾對話方塊：${m}`,
        scanIntro: "Prune 會搜尋與此名稱和資料夾相符的檔案、登錄項目和排程工作。在你檢查之前不會移除任何內容。",
        folderLine: (f) => `資料夾：${f}`
      }
    }
  }
};
