// The "What's new" notice shown once after an update (see lib/whatsNew.js), all 40 languages:
// { en: { whatsNewV3: { ... } }, af: { ... }, ... }. Merged into the catalog by ../catalog.js; every
// key lives under whatsNewV3. Generated by an out-of-tree script that writes every value with
// JSON.stringify (or as a template literal for the one title that takes the version), so quotes and
// non-ASCII text are safe. Names of screens and features (Disk Map, Deep Clean, Hunter, Forced
// uninstall, Backups, History, Quarantine, Dashboard, Settings) are each language's existing catalog
// terms. ui.title takes the major.minor version ("3.0").
export default {
  en: {
    whatsNewV3: {
      ui: {
        title: (a) => `What's new in Prune ${a}`,
        intro: "A few things worth knowing about, and where to find them.",
        gotIt: "Got it",
        showMe: "Show me",
        backgroundNote: "The background options in Settings are all off until you turn them on.",
        about: {
          title: "What's new",
          description: "See what changed in this version and where to find it.",
          button: "What's new in this version"
        }
      },
      cards: {
        rail: { title: "A sidebar that opens on hover", description: "Point at the icons on the left to see their names. It folds away again when you move off it." },
        diskMap: { title: "Disk Map", description: "Scan any drive, pick up where you left off, and search or export what you find." },
        deepClean: { title: "Deep Clean", description: "It scans once and remembers, shreds files, has a command line and takes your own locations." },
        uninstaller: { title: "Uninstaller", description: "Aim Hunter at a program, use Forced uninstall on stubborn ones, watch installs, and find Backups and History in Quarantine." },
        dashboard: { title: "Dashboard", description: "Clean recommended in one click, see what you've freed, get a low-disk warning, and Undo a clean." },
        settings: { title: "More in Settings", description: "Scheduled clean while Prune is closed, start with Windows, a right-click menu and always run as administrator." }
      }
    }
  },
  af: {
    whatsNewV3: {
      ui: {
        title: (a) => `Wat is nuut in Prune ${a}`,
        intro: "'n Paar dinge wat die moeite werd is om te ken, en waar om dit te vind.",
        gotIt: "Verstaan",
        showMe: "Wys my",
        backgroundNote: "Die agtergrondopsies in Instellings is almal af totdat jy hulle aanskakel.",
        about: {
          title: "Wat is nuut",
          description: "Kyk wat in hierdie weergawe verander het en waar om dit te vind.",
          button: "Wat is nuut in hierdie weergawe"
        }
      },
      cards: {
        rail: { title: "'n Sybalk wat oopgaan as jy daaroor beweeg", description: "Wys na die ikone links om hul name te sien. Dit vou weer toe as jy wegbeweeg." },
        diskMap: { title: "Skyfkaart", description: "Skandeer enige skyf, gaan voort waar jy opgehou het, en soek of voer uit wat jy vind." },
        deepClean: { title: "Diep Skoonmaak", description: "Dit skandeer een keer en onthou, versnipper lêers, het 'n opdragreël en neem jou eie plekke." },
        uninstaller: { title: "Deïnstalleer", description: "Rig die Jagter op 'n program, gebruik Gedwonge deïnstallering vir hardkoppiges, hou installasies dop, en vind Rugsteun en Geskiedenis in Karantyn." },
        dashboard: { title: "Kontroleskerm", description: "Maak aanbevole items skoon met een klik, sien wat jy vrygemaak het, kry 'n waarskuwing vir min skyfspasie, en maak 'n skoonmaak ongedaan." },
        settings: { title: "Meer in Instellings", description: "Geskeduleerde skoonmaak terwyl Prune toe is, begin saam met Windows, 'n regsklik-kieslys en voer altyd as administrateur uit." }
      }
    }
  },
  ar: {
    whatsNewV3: {
      ui: {
        title: (a) => `ما الجديد في Prune ${a}`,
        intro: "بعض الأمور التي تستحق المعرفة، وأين تجدها.",
        gotIt: "حسنًا",
        showMe: "أرني",
        backgroundNote: "جميع خيارات الخلفية في الإعدادات متوقفة حتى تشغّلها.",
        about: {
          title: "ما الجديد",
          description: "اطّلع على ما تغيّر في هذا الإصدار وأين تجده.",
          button: "ما الجديد في هذا الإصدار"
        }
      },
      cards: {
        rail: { title: "شريط جانبي يفتح عند تمرير المؤشر", description: "مرّر المؤشر فوق الأيقونات في الشريط الجانبي لرؤية أسمائها. يُطوى مجددًا عند إبعاد المؤشر." },
        diskMap: { title: "خريطة القرص", description: "افحص أي محرك، وتابع من حيث توقفت، وابحث فيما تجده أو صدّره." },
        deepClean: { title: "تنظيف عميق", description: "يفحص مرة واحدة ويتذكّر، ويمزّق الملفات، وله سطر أوامر، ويقبل مواقعك الخاصة." },
        uninstaller: { title: "إلغاء التثبيت", description: "وجّه الصيّاد إلى برنامج، واستخدم إلغاء تثبيت إجباري للبرامج العنيدة، وراقب التثبيتات، وستجد النسخ الاحتياطية والسجل في الحجر الصحي." },
        dashboard: { title: "لوحة المعلومات", description: "تنظيف الموصى به بنقرة واحدة، وشاهد ما حرّرته، وتنبيه عند انخفاض مساحة القرص، وتراجع عن التنظيف." },
        settings: { title: "المزيد في الإعدادات", description: "تنظيف مجدول أثناء إغلاق Prune، والبدء مع Windows، وقائمة بزر الماوس الأيمن، والتشغيل دائمًا كمسؤول." }
      }
    }
  },
  ca: {
    whatsNewV3: {
      ui: {
        title: (a) => `Novetats de Prune ${a}`,
        intro: "Algunes coses que val la pena conèixer i on trobar-les.",
        gotIt: "Entesos",
        showMe: "Mostra-m'ho",
        backgroundNote: "Les opcions en segon pla de la configuració estan desactivades fins que les activis.",
        about: {
          title: "Novetats",
          description: "Mira què ha canviat en aquesta versió i on trobar-ho.",
          button: "Novetats d'aquesta versió"
        }
      },
      cards: {
        rail: { title: "Una barra lateral que s'obre en passar-hi per sobre", description: "Posa el cursor sobre les icones de l'esquerra per veure'n els noms. Es plega quan te n'allunyes." },
        diskMap: { title: "Mapa del disc", description: "Escaneja qualsevol unitat, continua des d'on ho vas deixar i cerca o exporta el que trobis." },
        deepClean: { title: "Neteja profunda", description: "Escaneja una vegada i ho recorda, tritura fitxers, té línia d'ordres i accepta les teves ubicacions." },
        uninstaller: { title: "Desinstal·lació", description: "Apunta el Caçador a un programa, usa la desinstal·lació forçada amb els tossuts, vigila les instal·lacions i troba Còpies de seguretat i Historial a Quarantena." },
        dashboard: { title: "Tauler", description: "Neteja el recomanat amb un clic, mira què has alliberat, rep un avís d'espai baix i desfés una neteja." },
        settings: { title: "Més a Configuració", description: "Neteja programada amb Prune tancat, inici amb Windows, un menú contextual i executar sempre com a administrador." }
      }
    }
  },
  cs: {
    whatsNewV3: {
      ui: {
        title: (a) => `Co je nového v Prune ${a}`,
        intro: "Pár věcí, které stojí za zmínku, a kde je najdete.",
        gotIt: "Rozumím",
        showMe: "Ukázat",
        backgroundNote: "Možnosti na pozadí v Nastavení jsou všechny vypnuté, dokud je nezapnete.",
        about: {
          title: "Co je nového",
          description: "Podívejte se, co se v této verzi změnilo a kde to najdete.",
          button: "Co je nového v této verzi"
        }
      },
      cards: {
        rail: { title: "Postranní panel, který se otevře při najetí", description: "Najeďte na ikony vlevo a uvidíte jejich názvy. Po odjetí se panel znovu složí." },
        diskMap: { title: "Mapa disku", description: "Prohledejte libovolný disk, navažte tam, kde jste skončili, a výsledky vyhledávejte nebo exportujte." },
        deepClean: { title: "Důkladné čištění", description: "Skenuje jednou a pamatuje si výsledek, skartuje soubory, má příkazový řádek a přijímá vaše vlastní umístění." },
        uninstaller: { title: "Odinstalace", description: "Zaměřte Lovce na program, nepoddajné odstraňte Vynuceným odinstalováním, sledujte instalace a Zálohy a Historii najdete v Karanténě." },
        dashboard: { title: "Přehled", description: "Vyčistěte doporučené jedním kliknutím, uvidíte, kolik jste uvolnili, dostanete varování při nedostatku místa a čištění můžete vrátit zpět." },
        settings: { title: "Více v Nastavení", description: "Plánované čištění při zavřeném Prune, spuštění s Windows, nabídka po kliknutí pravým tlačítkem a vždy spouštět jako správce." }
      }
    }
  },
  cy: {
    whatsNewV3: {
      ui: {
        title: (a) => `Beth sy'n newydd yn Prune ${a}`,
        intro: "Ychydig o bethau gwerth eu gwybod, a lle i'w cael.",
        gotIt: "Iawn",
        showMe: "Dangoswch",
        backgroundNote: "Mae'r dewisiadau cefndir yn y Gosodiadau i gyd wedi'u diffodd nes i chi eu troi ymlaen.",
        about: {
          title: "Beth sy'n newydd",
          description: "Gweler beth sydd wedi newid yn y fersiwn hon a lle i'w gael.",
          button: "Beth sy'n newydd yn y fersiwn hon"
        }
      },
      cards: {
        rail: { title: "Bar ochr sy'n agor wrth hofran", description: "Pwyntiwch at yr eiconau ar y chwith i weld eu henwau. Mae'n plygu eto pan symudwch i ffwrdd." },
        diskMap: { title: "Map Disg", description: "Sganiwch unrhyw yriant, ailgydiwch lle roeddech, a chwiliwch neu allforiwch yr hyn a gewch." },
        deepClean: { title: "Glanhau Dwfn", description: "Mae'n sganio unwaith ac yn cofio, yn rhwygo ffeiliau, mae ganddo linell orchymyn ac yn derbyn eich lleoliadau eich hun." },
        uninstaller: { title: "Dadosod", description: "Anelwch yr Heliwr at raglen, defnyddiwch Ddadosod gorfodol ar rai ystyfnig, gwyliwch osodiadau, a chewch Gopïau wrth gefn a Hanes yn y Cwarantin." },
        dashboard: { title: "Dangosfwrdd", description: "Glanhewch yr hyn a argymhellir gydag un clic, gwelwch beth rydych wedi'i ryddhau, cewch rybudd disg lawn, a Dadwneud glanhad." },
        settings: { title: "Mwy yn y Gosodiadau", description: "Glanhau wedi'i drefnu pan fo Prune ar gau, dechrau gyda Windows, dewislen clic dde a rhedeg fel gweinyddwr bob amser." }
      }
    }
  },
  da: {
    whatsNewV3: {
      ui: {
        title: (a) => `Nyt i Prune ${a}`,
        intro: "Nogle ting, der er værd at kende, og hvor du finder dem.",
        gotIt: "Forstået",
        showMe: "Vis mig",
        backgroundNote: "Baggrundsindstillingerne i Indstillinger er alle slået fra, til du slår dem til.",
        about: {
          title: "Nyt",
          description: "Se, hvad der er ændret i denne version, og hvor du finder det.",
          button: "Nyt i denne version"
        }
      },
      cards: {
        rail: { title: "En sidebjælke, der åbner, når du peger på den", description: "Peg på ikonerne til venstre for at se deres navne. Den folder sig sammen igen, når du flytter musen væk." },
        diskMap: { title: "Diskkort", description: "Scan et vilkårligt drev, fortsæt, hvor du slap, og søg i eller eksportér det, du finder." },
        deepClean: { title: "Dybderensning", description: "Den scanner én gang og husker det, makulerer filer, har en kommandolinje og tager imod dine egne placeringer." },
        uninstaller: { title: "Afinstaller", description: "Ret Jæger mod et program, brug Gennemtvungen afinstallation til de genstridige, hold øje med installationer, og find Sikkerhedskopier og Historik i Karantæne." },
        dashboard: { title: "Oversigt", description: "Rens det anbefalede med ét klik, se hvad du har frigjort, få en advarsel ved lav diskplads, og fortryd en rensning." },
        settings: { title: "Mere i Indstillinger", description: "Planlagt rensning, mens Prune er lukket, start med Windows, en højrekliksmenu og kør altid som administrator." }
      }
    }
  },
  de: {
    whatsNewV3: {
      ui: {
        title: (a) => `Neu in Prune ${a}`,
        intro: "Einiges, was Sie wissen sollten, und wo Sie es finden.",
        gotIt: "Verstanden",
        showMe: "Zeig es mir",
        backgroundNote: "Die Hintergrundoptionen in den Einstellungen sind alle aus, bis Sie sie einschalten.",
        about: {
          title: "Neuheiten",
          description: "Sehen Sie, was sich in dieser Version geändert hat und wo Sie es finden.",
          button: "Neu in dieser Version"
        }
      },
      cards: {
        rail: { title: "Eine Seitenleiste, die sich beim Darüberfahren öffnet", description: "Zeigen Sie auf die Symbole links, um ihre Namen zu sehen. Sie klappt wieder zu, wenn Sie weggehen." },
        diskMap: { title: "Festplattenkarte", description: "Scannen Sie ein beliebiges Laufwerk, machen Sie dort weiter, wo Sie aufgehört haben, und durchsuchen oder exportieren Sie das Ergebnis." },
        deepClean: { title: "Gründliche Bereinigung", description: "Sie scannt einmal und merkt sich das Ergebnis, schreddert Dateien, hat eine Befehlszeile und nimmt eigene Orte auf." },
        uninstaller: { title: "Deinstallation", description: "Richten Sie den Jäger auf ein Programm, nutzen Sie die Erzwungene Deinstallation für Hartnäckige, beobachten Sie Installationen und finden Sie Sicherungen und Verlauf in der Quarantäne." },
        dashboard: { title: "Übersicht", description: "Empfohlenes mit einem Klick bereinigen, sehen, was Sie freigegeben haben, bei wenig Speicherplatz gewarnt werden und eine Bereinigung rückgängig machen." },
        settings: { title: "Mehr in den Einstellungen", description: "Geplante Bereinigung bei geschlossenem Prune, Start mit Windows, ein Kontextmenü und immer als Administrator ausführen." }
      }
    }
  },
  el: {
    whatsNewV3: {
      ui: {
        title: (a) => `Τι νέο υπάρχει στο Prune ${a}`,
        intro: "Μερικά πράγματα που αξίζει να γνωρίζετε και πού θα τα βρείτε.",
        gotIt: "Εντάξει",
        showMe: "Δείξε μου",
        backgroundNote: "Οι επιλογές παρασκηνίου στις Ρυθμίσεις είναι όλες απενεργοποιημένες μέχρι να τις ενεργοποιήσετε.",
        about: {
          title: "Τι νέο υπάρχει",
          description: "Δείτε τι άλλαξε σε αυτή την έκδοση και πού θα το βρείτε.",
          button: "Τι νέο υπάρχει σε αυτή την έκδοση"
        }
      },
      cards: {
        rail: { title: "Πλαϊνή γραμμή που ανοίγει όταν την επισημάνετε", description: "Τοποθετήστε τον δείκτη στα εικονίδια αριστερά για να δείτε τα ονόματά τους. Κλείνει ξανά όταν απομακρυνθείτε." },
        diskMap: { title: "Χάρτης δίσκου", description: "Σαρώστε οποιονδήποτε δίσκο, συνεχίστε από εκεί που μείνατε και κάντε αναζήτηση ή εξαγωγή των αποτελεσμάτων." },
        deepClean: { title: "Βαθύς καθαρισμός", description: "Σαρώνει μία φορά και θυμάται, καταστρέφει αρχεία, έχει γραμμή εντολών και δέχεται δικές σας τοποθεσίες." },
        uninstaller: { title: "Απεγκατάσταση", description: "Στρέψτε τον Κυνηγό σε ένα πρόγραμμα, χρησιμοποιήστε την Αναγκαστική απεγκατάσταση για τα πεισματάρικα, παρακολουθήστε τις εγκαταστάσεις και βρείτε Αντίγραφα ασφαλείας και Ιστορικό στην Καραντίνα." },
        dashboard: { title: "Πίνακας ελέγχου", description: "Καθαρισμός προτεινόμενων με ένα κλικ, δείτε τι ελευθερώσατε, λάβετε προειδοποίηση για λίγο χώρο και κάντε Αναίρεση ενός καθαρισμού." },
        settings: { title: "Περισσότερα στις Ρυθμίσεις", description: "Προγραμματισμένος καθαρισμός με κλειστό το Prune, εκκίνηση με τα Windows, μενού δεξιού κλικ και πάντα εκτέλεση ως διαχειριστής." }
      }
    }
  },
  es: {
    whatsNewV3: {
      ui: {
        title: (a) => `Novedades de Prune ${a}`,
        intro: "Algunas cosas que conviene conocer y dónde encontrarlas.",
        gotIt: "Entendido",
        showMe: "Muéstramelo",
        backgroundNote: "Las opciones en segundo plano de Configuración están todas desactivadas hasta que las actives.",
        about: {
          title: "Novedades",
          description: "Mira qué ha cambiado en esta versión y dónde encontrarlo.",
          button: "Novedades de esta versión"
        }
      },
      cards: {
        rail: { title: "Una barra lateral que se abre al pasar el cursor", description: "Pasa el cursor por los iconos de la izquierda para ver sus nombres. Se pliega de nuevo al apartarlo." },
        diskMap: { title: "Mapa del disco", description: "Analiza cualquier unidad, continúa donde lo dejaste y busca o exporta lo que encuentres." },
        deepClean: { title: "Limpieza profunda", description: "Analiza una vez y lo recuerda, tritura archivos, tiene línea de comandos y admite tus propias ubicaciones." },
        uninstaller: { title: "Desinstalar", description: "Apunta el Cazador a un programa, usa la desinstalación forzada con los rebeldes, vigila las instalaciones y encuentra Copias de seguridad e Historial en Cuarentena." },
        dashboard: { title: "Panel", description: "Limpia lo recomendado con un clic, mira cuánto has liberado, recibe un aviso de poco espacio y deshaz una limpieza." },
        settings: { title: "Más en Configuración", description: "Limpieza programada con Prune cerrado, inicio con Windows, un menú contextual y ejecutar siempre como administrador." }
      }
    }
  },
  et: {
    whatsNewV3: {
      ui: {
        title: (a) => `Mis on Prune ${a} uut`,
        intro: "Mõned asjad, mida tasub teada, ja kust neid leida.",
        gotIt: "Selge",
        showMe: "Näita",
        backgroundNote: "Seadete taustavalikud on kõik välja lülitatud, kuni sa need sisse lülitad.",
        about: {
          title: "Mis on uut",
          description: "Vaata, mis selles versioonis muutus ja kust seda leida.",
          button: "Mis on selles versioonis uut"
        }
      },
      cards: {
        rail: { title: "Külgriba, mis avaneb kursoriga osutades", description: "Osuta vasakul olevatele ikoonidele, et näha nende nimesid. Kui kursori ära viid, läheb riba uuesti kokku." },
        diskMap: { title: "Kettakaart", description: "Skanni mis tahes ketast, jätka sealt, kus pooleli jäid, ning otsi leitut või ekspordi see." },
        deepClean: { title: "Süvapuhastus", description: "See skannib ühe korra ja jätab meelde, purustab faile, sellel on käsurida ja see võtab vastu sinu enda asukohti." },
        uninstaller: { title: "Desinstallimine", description: "Suuna Jahimees programmile, kasuta kangekaelsete puhul Sundeemaldamist, jälgi installimisi ning leia Varukoopiad ja Ajalugu Karantiinist." },
        dashboard: { title: "Töölaud", description: "Puhasta soovitatud ühe klõpsuga, vaata, palju vabastasid, saa hoiatus vähese kettaruumi kohta ja võta puhastus tagasi." },
        settings: { title: "Veel Seadetes", description: "Ajastatud puhastus, kui Prune on suletud, käivitus koos Windowsiga, paremklõpsumenüü ja alati administraatorina käivitamine." }
      }
    }
  },
  fi: {
    whatsNewV3: {
      ui: {
        title: (a) => `Prunen ${a} uudet ominaisuudet`,
        intro: "Muutama hyvä tietää -asia ja mistä ne löytyvät.",
        gotIt: "Selvä",
        showMe: "Näytä",
        backgroundNote: "Asetusten taustavalinnat ovat kaikki pois päältä, kunnes otat ne käyttöön.",
        about: {
          title: "Uutta",
          description: "Katso, mikä tässä versiossa on muuttunut ja mistä sen löytää.",
          button: "Uutta tässä versiossa"
        }
      },
      cards: {
        rail: { title: "Sivupalkki, joka avautuu osoitettaessa", description: "Osoita vasemmalla olevia kuvakkeita nähdäksesi niiden nimet. Palkki sulkeutuu, kun siirrät osoittimen pois." },
        diskMap: { title: "Levykartta", description: "Skannaa mikä tahansa asema, jatka siitä mihin jäit ja hae tai vie löydetty." },
        deepClean: { title: "Syväpuhdistus", description: "Se skannaa kerran ja muistaa tuloksen, silppuaa tiedostoja, sillä on komentorivi ja se ottaa omat sijaintisi." },
        uninstaller: { title: "Poisto", description: "Osoita Metsästäjä ohjelmaan, käytä Pakotettua poistoa uppiniskaisiin, seuraa asennuksia ja löydä Varmuuskopiot ja Historia Karanteenista." },
        dashboard: { title: "Yhteenveto", description: "Puhdista suositellut yhdellä napsautuksella, katso paljonko vapautit, saa varoitus vähäisestä levytilasta ja kumoa puhdistus." },
        settings: { title: "Lisää Asetuksissa", description: "Ajastettu puhdistus Prunen ollessa suljettuna, käynnistys Windowsin mukana, hiiren kakkospainikkeen valikko ja suoritus aina järjestelmänvalvojana." }
      }
    }
  },
  fr: {
    whatsNewV3: {
      ui: {
        title: (a) => `Nouveautés de Prune ${a}`,
        intro: "Quelques points à connaître, et où les trouver.",
        gotIt: "Compris",
        showMe: "Montrez-moi",
        backgroundNote: "Les options d'arrière-plan des Paramètres sont toutes désactivées tant que vous ne les activez pas.",
        about: {
          title: "Nouveautés",
          description: "Voyez ce qui a changé dans cette version et où le trouver.",
          button: "Nouveautés de cette version"
        }
      },
      cards: {
        rail: { title: "Une barre latérale qui s'ouvre au survol", description: "Pointez les icônes à gauche pour voir leurs noms. Elle se replie quand vous vous éloignez." },
        diskMap: { title: "Carte du disque", description: "Analysez n'importe quel lecteur, reprenez où vous en étiez, puis recherchez ou exportez le résultat." },
        deepClean: { title: "Nettoyage approfondi", description: "Il analyse une fois et s'en souvient, détruit des fichiers, a une ligne de commande et accepte vos propres emplacements." },
        uninstaller: { title: "Désinstallation", description: "Visez un programme avec le Chasseur, utilisez la Désinstallation forcée pour les récalcitrants, surveillez les installations et retrouvez Sauvegardes et Historique dans la Quarantaine." },
        dashboard: { title: "Tableau de bord", description: "Nettoyez le recommandé en un clic, voyez ce que vous avez libéré, recevez une alerte d'espace faible et annulez un nettoyage." },
        settings: { title: "Plus dans les Paramètres", description: "Nettoyage planifié quand Prune est fermé, démarrage avec Windows, un menu contextuel et exécution toujours en tant qu'administrateur." }
      }
    }
  },
  he: {
    whatsNewV3: {
      ui: {
        title: (a) => `מה חדש ב-Prune ${a}`,
        intro: "כמה דברים ששווה להכיר, ואיפה למצוא אותם.",
        gotIt: "הבנתי",
        showMe: "הראה לי",
        backgroundNote: "כל אפשרויות הרקע בהגדרות כבויות עד שתפעילו אותן.",
        about: {
          title: "מה חדש",
          description: "ראו מה השתנה בגרסה הזו ואיפה למצוא את זה.",
          button: "מה חדש בגרסה הזו"
        }
      },
      cards: {
        rail: { title: "סרגל צד שנפתח במעבר עכבר", description: "הצביעו על הסמלים בסרגל כדי לראות את שמותיהם. הוא נסגר שוב כשמרחיקים את העכבר." },
        diskMap: { title: "מפת הדיסק", description: "סרקו כל כונן, המשיכו מהמקום שבו עצרתם, וחפשו או ייצאו את התוצאות." },
        deepClean: { title: "ניקוי מעמיק", description: "הוא סורק פעם אחת וזוכר, מגרסם קבצים, כולל שורת פקודה ומקבל מיקומים משלכם." },
        uninstaller: { title: "הסרה", description: "כוונו את הצייד אל תוכנה, השתמשו בהסרה כפויה בעקשניות, עקבו אחרי התקנות ומצאו גיבויים והיסטוריה בהסגר." },
        dashboard: { title: "לוח מחוונים", description: "נקו את המומלץ בלחיצה אחת, ראו כמה שחררתם, קבלו אזהרה על מקום פנוי נמוך ובטלו ניקוי." },
        settings: { title: "עוד בהגדרות", description: "ניקוי מתוזמן כש-Prune סגור, הפעלה עם Windows, תפריט לחיצה ימנית והפעלה תמיד כמנהל." }
      }
    }
  },
  hu: {
    whatsNewV3: {
      ui: {
        title: (a) => `Újdonságok a Prune ${a} verzióban`,
        intro: "Néhány tudnivaló, és hogy hol találod őket.",
        gotIt: "Értem",
        showMe: "Mutasd",
        backgroundNote: "A Beállítások háttérbeli lehetőségei mind ki vannak kapcsolva, amíg be nem kapcsolod őket.",
        about: {
          title: "Újdonságok",
          description: "Nézd meg, mi változott ebben a verzióban, és hol találod.",
          button: "Újdonságok ebben a verzióban"
        }
      },
      cards: {
        rail: { title: "Oldalsáv, amely rámutatásra kinyílik", description: "Mutass a bal oldali ikonokra a nevük megtekintéséhez. Ha elviszed az egeret, újra összecsukódik." },
        diskMap: { title: "Lemeztérkép", description: "Vizsgálj meg bármely meghajtót, folytasd ott, ahol abbahagytad, és keress az eredményben vagy exportáld." },
        deepClean: { title: "Mélytisztítás", description: "Egyszer vizsgál és megjegyzi, fájlokat zúz, van parancssora, és fogadja a saját helyeidet." },
        uninstaller: { title: "Eltávolítás", description: "Irányítsd a Vadászt egy programra, használd a Kényszerített eltávolítást a makacsoknál, figyeld a telepítéseket, és keresd a Biztonsági mentések és az Előzmények lapot a Karanténban." },
        dashboard: { title: "Áttekintés", description: "Az ajánlottak tisztítása egy kattintással, nézd meg, mennyit szabadítottál fel, kapj figyelmeztetést kevés lemezhelynél, és vonj vissza egy tisztítást." },
        settings: { title: "Több a Beállításokban", description: "Ütemezett tisztítás zárt Prune mellett, indítás a Windowsszal, jobb gombos menü és mindig futtatás rendszergazdaként." }
      }
    }
  },
  id: {
    whatsNewV3: {
      ui: {
        title: (a) => `Yang baru di Prune ${a}`,
        intro: "Beberapa hal yang perlu diketahui dan di mana menemukannya.",
        gotIt: "Mengerti",
        showMe: "Tunjukkan",
        backgroundNote: "Opsi latar belakang di Pengaturan semuanya nonaktif sampai Anda mengaktifkannya.",
        about: {
          title: "Yang baru",
          description: "Lihat apa yang berubah di versi ini dan di mana menemukannya.",
          button: "Yang baru di versi ini"
        }
      },
      cards: {
        rail: { title: "Bilah samping yang terbuka saat disorot", description: "Arahkan ke ikon di kiri untuk melihat namanya. Bilah ini menutup lagi saat Anda menjauh." },
        diskMap: { title: "Peta Disk", description: "Pindai drive mana pun, lanjutkan dari tempat Anda berhenti, lalu cari atau ekspor hasilnya." },
        deepClean: { title: "Pembersihan Mendalam", description: "Memindai sekali dan mengingatnya, mencabik file, punya baris perintah, dan menerima lokasi Anda sendiri." },
        uninstaller: { title: "Uninstal", description: "Arahkan Pemburu ke program, pakai Uninstal paksa untuk yang membandel, pantau instalasi, dan temukan Cadangan dan Riwayat di Karantina." },
        dashboard: { title: "Dasbor", description: "Bersihkan yang direkomendasikan dengan satu klik, lihat yang sudah dibebaskan, dapatkan peringatan disk hampir penuh, dan urungkan pembersihan." },
        settings: { title: "Lainnya di Pengaturan", description: "Pembersihan terjadwal saat Prune ditutup, mulai bersama Windows, menu klik kanan, dan selalu jalankan sebagai administrator." }
      }
    }
  },
  is: {
    whatsNewV3: {
      ui: {
        title: (a) => `Nýjungar í Prune ${a}`,
        intro: "Nokkur atriði sem gott er að vita um og hvar þau er að finna.",
        gotIt: "Skil",
        showMe: "Sýndu mér",
        backgroundNote: "Bakgrunnsvalkostirnir í Stillingum eru allir slökktir þar til þú kveikir á þeim.",
        about: {
          title: "Nýjungar",
          description: "Sjáðu hvað breyttist í þessari útgáfu og hvar það er að finna.",
          button: "Nýjungar í þessari útgáfu"
        }
      },
      cards: {
        rail: { title: "Hliðarstika sem opnast þegar bendillinn er yfir henni", description: "Bentu á táknin til vinstri til að sjá nöfn þeirra. Stikan lokast aftur þegar þú færir bendilinn burt." },
        diskMap: { title: "Diskakort", description: "Skannaðu hvaða drif sem er, haltu áfram þar sem frá var horfið og leitaðu í niðurstöðunum eða fluttu þær út." },
        deepClean: { title: "Djúphreinsun", description: "Hún skannar einu sinni og man það, tætir skrár, er með skipanalínu og tekur við þínum eigin stöðum." },
        uninstaller: { title: "Fjarlægja", description: "Beindu Veiðimanni að forriti, notaðu Þvingaða fjarlægingu á þrjóskum forritum, fylgstu með uppsetningum og finndu Afrit og Sögu í Sóttkví." },
        dashboard: { title: "Yfirlit", description: "Hreinsaðu það sem mælt er með í einum smelli, sjáðu hvað þú hefur losað, fáðu viðvörun um lítið diskpláss og afturkallaðu hreinsun." },
        settings: { title: "Meira í Stillingum", description: "Tímasett hreinsun þegar Prune er lokað, ræsing með Windows, hægrismellivalmynd og alltaf keyra sem stjórnandi." }
      }
    }
  },
  it: {
    whatsNewV3: {
      ui: {
        title: (a) => `Novità di Prune ${a}`,
        intro: "Alcune cose da conoscere e dove trovarle.",
        gotIt: "Ho capito",
        showMe: "Mostrami",
        backgroundNote: "Le opzioni in background nelle Impostazioni sono tutte disattivate finché non le attivi.",
        about: {
          title: "Novità",
          description: "Scopri cosa è cambiato in questa versione e dove trovarlo.",
          button: "Novità di questa versione"
        }
      },
      cards: {
        rail: { title: "Una barra laterale che si apre al passaggio del mouse", description: "Passa il puntatore sulle icone a sinistra per vederne i nomi. Si richiude quando ti allontani." },
        diskMap: { title: "Mappa del disco", description: "Analizza qualsiasi unità, riprendi da dove avevi lasciato e cerca o esporta ciò che trovi." },
        deepClean: { title: "Pulizia approfondita", description: "Analizza una volta e ricorda, distrugge i file, ha una riga di comando e accetta posizioni tue." },
        uninstaller: { title: "Disinstallazione", description: "Punta il Cacciatore su un programma, usa la Disinstallazione forzata per i più ostinati, tieni d'occhio le installazioni e trova Backup e Cronologia in Quarantena." },
        dashboard: { title: "Pannello", description: "Pulisci i consigliati con un clic, vedi quanto hai liberato, ricevi un avviso di poco spazio e annulla una pulizia." },
        settings: { title: "Altro nelle Impostazioni", description: "Pulizia pianificata a Prune chiuso, avvio con Windows, un menu contestuale ed esecuzione sempre come amministratore." }
      }
    }
  },
  ja: {
    whatsNewV3: {
      ui: {
        title: (a) => `Prune ${a} の新機能`,
        intro: "知っておきたい機能と、その場所をご紹介します。",
        gotIt: "了解",
        showMe: "見てみる",
        backgroundNote: "設定のバックグラウンド機能は、オンにするまですべてオフです。",
        about: {
          title: "新機能",
          description: "このバージョンでの変更点と、その場所を確認できます。",
          button: "このバージョンの新機能"
        }
      },
      cards: {
        rail: { title: "ポイントすると開くサイドバー", description: "左のアイコンにポイントすると名前が表示されます。離すとまた閉じます。" },
        diskMap: { title: "ディスクマップ", description: "任意のドライブをスキャンし、前回の続きから再開して、結果を検索またはエクスポートできます。" },
        deepClean: { title: "ディープクリーン", description: "一度スキャンした結果を記憶し、ファイルの完全削除、コマンドライン、独自の場所の追加に対応します。" },
        uninstaller: { title: "アンインストール", description: "ハンターをプログラムに向け、手ごわいものは強制アンインストールで削除し、インストールを監視し、バックアップと履歴は隔離で確認できます。" },
        dashboard: { title: "ダッシュボード", description: "推奨項目をワンクリックでクリーンし、解放した容量を確認し、空き容量の警告を受け取り、クリーンを元に戻せます。" },
        settings: { title: "設定のその他の機能", description: "Prune を閉じていても実行するスケジュールクリーン、Windows と同時の起動、右クリックメニュー、常に管理者として実行。" }
      }
    }
  },
  ko: {
    whatsNewV3: {
      ui: {
        title: (a) => `Prune ${a}의 새로운 기능`,
        intro: "알아 두면 좋은 기능과 그 위치를 소개합니다.",
        gotIt: "확인",
        showMe: "보여 주세요",
        backgroundNote: "설정의 백그라운드 옵션은 직접 켜기 전까지 모두 꺼져 있습니다.",
        about: {
          title: "새로운 기능",
          description: "이 버전에서 달라진 점과 그 위치를 확인하세요.",
          button: "이 버전의 새로운 기능"
        }
      },
      cards: {
        rail: { title: "마우스를 올리면 열리는 사이드바", description: "왼쪽 아이콘에 마우스를 올리면 이름이 보입니다. 마우스를 치우면 다시 접힙니다." },
        diskMap: { title: "디스크 맵", description: "원하는 드라이브를 검사하고, 중단한 곳에서 이어 가며, 결과를 검색하거나 내보낼 수 있습니다." },
        deepClean: { title: "딥 클린", description: "한 번 검사하고 기억하며, 파일을 완전히 지우고, 명령줄을 제공하며, 직접 지정한 위치도 받습니다." },
        uninstaller: { title: "제거", description: "헌터로 프로그램을 가리키고, 말썽인 프로그램은 강제 제거하며, 설치를 감시하고, 백업과 기록은 격리에서 찾을 수 있습니다." },
        dashboard: { title: "대시보드", description: "권장 항목 정리를 한 번에 실행하고, 확보한 공간을 확인하고, 공간 부족 경고를 받고, 정리를 실행 취소할 수 있습니다." },
        settings: { title: "설정의 더 많은 기능", description: "Prune이 닫혀 있어도 실행되는 예약 정리, Windows와 함께 시작, 오른쪽 클릭 메뉴, 항상 관리자 권한으로 실행." }
      }
    }
  },
  lt: {
    whatsNewV3: {
      ui: {
        title: (a) => `Kas naujo Prune ${a}`,
        intro: "Keletas dalykų, kuriuos verta žinoti, ir kur juos rasti.",
        gotIt: "Supratau",
        showMe: "Parodyk",
        backgroundNote: "Fono parinktys Nustatymuose yra išjungtos, kol jų neįjungsite.",
        about: {
          title: "Kas naujo",
          description: "Pažiūrėkite, kas pasikeitė šioje versijoje ir kur tai rasti.",
          button: "Kas naujo šioje versijoje"
        }
      },
      cards: {
        rail: { title: "Šoninė juosta, atsidaranti užvedus pelę", description: "Užveskite žymeklį ant piktogramų kairėje, kad pamatytumėte jų pavadinimus. Pasitraukus juosta vėl susitraukia." },
        diskMap: { title: "Disko žemėlapis", description: "Nuskaitykite bet kurį diską, tęskite nuo ten, kur baigėte, ir ieškokite rezultatų arba juos eksportuokite." },
        deepClean: { title: "Gilus valymas", description: "Nuskaito vieną kartą ir prisimena, naikina failus, turi komandų eilutę ir priima jūsų pačių vietas." },
        uninstaller: { title: "Šalinimas", description: "Nukreipkite Medžiotoją į programą, užsispyrusioms naudokite Priverstinį pašalinimą, stebėkite diegimus, o Atsargines kopijas ir Istoriją rasite Karantine." },
        dashboard: { title: "Valdymo skydas", description: "Išvalykite rekomenduojamus vienu spustelėjimu, pamatykite, kiek atlaisvinote, gaukite įspėjimą apie mažai vietos ir anuliuokite valymą." },
        settings: { title: "Daugiau Nustatymuose", description: "Suplanuotas valymas, kai Prune uždarytas, paleidimas su Windows, dešiniojo pelės mygtuko meniu ir visada vykdyti kaip administratorių." }
      }
    }
  },
  ms: {
    whatsNewV3: {
      ui: {
        title: (a) => `Yang baharu dalam Prune ${a}`,
        intro: "Beberapa perkara yang berguna untuk diketahui dan di mana mencarinya.",
        gotIt: "Faham",
        showMe: "Tunjukkan",
        backgroundNote: "Pilihan latar belakang dalam Tetapan semuanya dimatikan sehingga anda menghidupkannya.",
        about: {
          title: "Yang baharu",
          description: "Lihat apa yang berubah dalam versi ini dan di mana mencarinya.",
          button: "Yang baharu dalam versi ini"
        }
      },
      cards: {
        rail: { title: "Bar sisi yang terbuka apabila dilalui tetikus", description: "Halakan ke ikon di sebelah kiri untuk melihat namanya. Ia dilipat semula apabila anda beralih." },
        diskMap: { title: "Peta Cakera", description: "Imbas mana-mana pemacu, sambung dari tempat anda berhenti, dan cari atau eksport hasilnya." },
        deepClean: { title: "Pembersihan Mendalam", description: "Ia mengimbas sekali dan mengingatnya, mencarik fail, mempunyai baris arahan dan menerima lokasi anda sendiri." },
        uninstaller: { title: "Nyahpasang", description: "Halakan Pemburu ke program, guna Nyahpasang paksa untuk yang degil, pantau pemasangan, dan cari Sandaran dan Sejarah dalam Kuarantin." },
        dashboard: { title: "Papan Pemuka", description: "Bersihkan yang disyorkan dengan satu klik, lihat apa yang anda bebaskan, dapat amaran ruang rendah, dan buat asal pembersihan." },
        settings: { title: "Lagi dalam Tetapan", description: "Pembersihan berjadual semasa Prune ditutup, mula bersama Windows, menu klik kanan dan sentiasa jalankan sebagai pentadbir." }
      }
    }
  },
  nb: {
    whatsNewV3: {
      ui: {
        title: (a) => `Nytt i Prune ${a}`,
        intro: "Noen ting det er greit å vite om, og hvor du finner dem.",
        gotIt: "Greit",
        showMe: "Vis meg",
        backgroundNote: "Bakgrunnsvalgene i Innstillinger er alle av til du slår dem på.",
        about: {
          title: "Nytt",
          description: "Se hva som har endret seg i denne versjonen, og hvor du finner det.",
          button: "Nytt i denne versjonen"
        }
      },
      cards: {
        rail: { title: "En sidestolpe som åpner seg når du peker på den", description: "Pek på ikonene til venstre for å se navnene. Den lukker seg igjen når du flytter pekeren bort." },
        diskMap: { title: "Diskkart", description: "Skann en hvilken som helst stasjon, fortsett der du slapp, og søk i eller eksporter det du finner." },
        deepClean: { title: "Grundig opprydding", description: "Den skanner én gang og husker det, makulerer filer, har en kommandolinje og tar imot dine egne steder." },
        uninstaller: { title: "Avinstaller", description: "Rett Jeger mot et program, bruk Tvunget avinstallering på de sta, følg med på installasjoner, og finn Sikkerhetskopier og Logg i Karantene." },
        dashboard: { title: "Oversikt", description: "Rens det anbefalte med ett klikk, se hva du har frigjort, få advarsel om lite diskplass og angre en rensing." },
        settings: { title: "Mer i Innstillinger", description: "Planlagt rensing når Prune er lukket, start sammen med Windows, en høyreklikkmeny og kjør alltid som administrator." }
      }
    }
  },
  nl: {
    whatsNewV3: {
      ui: {
        title: (a) => `Nieuw in Prune ${a}`,
        intro: "Een paar dingen die het weten waard zijn, en waar je ze vindt.",
        gotIt: "Begrepen",
        showMe: "Laat zien",
        backgroundNote: "De achtergrondopties in Instellingen staan allemaal uit tot je ze aanzet.",
        about: {
          title: "Wat is er nieuw",
          description: "Bekijk wat er in deze versie is veranderd en waar je het vindt.",
          button: "Nieuw in deze versie"
        }
      },
      cards: {
        rail: { title: "Een zijbalk die opent als je erheen wijst", description: "Wijs naar de pictogrammen links om hun namen te zien. Hij klapt weer in als je wegbeweegt." },
        diskMap: { title: "Schijfkaart", description: "Scan elke schijf, ga verder waar je gebleven was en zoek in of exporteer wat je vindt." },
        deepClean: { title: "Grondige opschoning", description: "Scant één keer en onthoudt het, versnippert bestanden, heeft een opdrachtregel en neemt je eigen locaties aan." },
        uninstaller: { title: "Verwijderen", description: "Richt de Jager op een programma, gebruik Geforceerd verwijderen voor koppige gevallen, volg installaties en vind Back-ups en Geschiedenis in Quarantaine." },
        dashboard: { title: "Dashboard", description: "Aanbevolen opschonen met één klik, zie wat je hebt vrijgemaakt, krijg een waarschuwing bij weinig schijfruimte en maak een opschoning ongedaan." },
        settings: { title: "Meer in Instellingen", description: "Geplande opschoning terwijl Prune gesloten is, starten met Windows, een rechtsklikmenu en altijd als administrator uitvoeren." }
      }
    }
  },
  pl: {
    whatsNewV3: {
      ui: {
        title: (a) => `Nowości w Prune ${a}`,
        intro: "Kilka rzeczy wartych poznania i miejsca, gdzie je znaleźć.",
        gotIt: "Rozumiem",
        showMe: "Pokaż",
        backgroundNote: "Opcje działające w tle w Ustawieniach są wszystkie wyłączone, dopóki ich nie włączysz.",
        about: {
          title: "Nowości",
          description: "Zobacz, co zmieniło się w tej wersji i gdzie to znaleźć.",
          button: "Nowości w tej wersji"
        }
      },
      cards: {
        rail: { title: "Pasek boczny, który otwiera się po najechaniu", description: "Najedź na ikony po lewej, aby zobaczyć ich nazwy. Po odsunięciu kursora pasek znów się zwija." },
        diskMap: { title: "Mapa dysku", description: "Skanuj dowolny dysk, kontynuuj od miejsca, w którym skończono poprzednio, i przeszukuj lub eksportuj wyniki." },
        deepClean: { title: "Głębokie czyszczenie", description: "Skanuje raz i zapamiętuje wynik, niszczy pliki, ma wiersz poleceń i przyjmuje własne lokalizacje." },
        uninstaller: { title: "Odinstalowywanie", description: "Wskaż program za pomocą Łowcy, użyj Wymuszonego odinstalowania dla opornych, śledź instalacje, a Kopie zapasowe i Historię znajdziesz w Kwarantannie." },
        dashboard: { title: "Panel", description: "Wyczyść zalecane jednym kliknięciem, zobacz, ile zwolniono, otrzymaj ostrzeżenie o małej ilości miejsca i cofnij czyszczenie." },
        settings: { title: "Więcej w Ustawieniach", description: "Zaplanowane czyszczenie przy zamkniętym Prune, uruchamianie z Windows, menu prawego przycisku i zawsze uruchamianie jako administrator." }
      }
    }
  },
  ps: {
    whatsNewV3: {
      ui: {
        title: (a) => `په Prune ${a} کې نوي څه دي`,
        intro: "څو شیان چې پوهېدل یې ګټور دي، او چېرته یې موندلی شئ.",
        gotIt: "پوه شوم",
        showMe: "ما ته وښيه",
        backgroundNote: "په تنظیماتو کې د شاليد ټول اختیارونه تر هغه بند دي چې تاسو یې فعال نه کړئ.",
        about: {
          title: "نوي څه دي",
          description: "وګورئ چې په دې نسخه کې څه بدل شوي او چېرته یې موندلی شئ.",
          button: "په دې نسخه کې نوي څه دي"
        }
      },
      cards: {
        rail: { title: "یو اړخیز بار چې په اشارې سره پرانیستل کیږي", description: "کیڼ لوري ته په آیکونونو اشاره وکړئ ترڅو نومونه یې وګورئ. کله چې لرې شئ بیا تړل کیږي." },
        diskMap: { title: "د ډیسک نقشه", description: "هر ډرایو سکین کړئ، له هغه ځایه دوام ورکړئ چې پرېښی مو و، او پایلې ولټوئ یا صادرې کړئ." },
        deepClean: { title: "ژور پاکول", description: "یو ځل سکین کوي او یادوي یې، فایلونه ټوټه ټوټه کوي، د قومانډ لاین لري او ستاسو خپل ځایونه مني." },
        uninstaller: { title: "لرې کول", description: "ښکاري پر یوه پروګرام وکاروئ، سرغړو لپاره جبري لرې کول وکاروئ، نصبونه وڅارئ، او بیک‌اپونه او تاریخچه په قرنطین کې ومومئ." },
        dashboard: { title: "ډشبورډ", description: "سپارښتل شوي په یوه کلیک پاک کړئ، وګورئ څومره مو خالي کړي، د ټیټې ډیسک ځای خبرداری ترلاسه کړئ، او پاکول بیرته کړئ." },
        settings: { title: "په تنظیماتو کې نور", description: "کله چې Prune بند وي مهال‌ویش شوی پاکول، له Windows سره پیل، د ښي کلیک مېنو، او تل د مدیر په توګه چلول." }
      }
    }
  },
  "pt-BR": {
    whatsNewV3: {
      ui: {
        title: (a) => `Novidades do Prune ${a}`,
        intro: "Algumas coisas que vale conhecer e onde encontrá-las.",
        gotIt: "Entendi",
        showMe: "Mostre-me",
        backgroundNote: "As opções em segundo plano em Configurações ficam todas desativadas até você ativá-las.",
        about: {
          title: "Novidades",
          description: "Veja o que mudou nesta versão e onde encontrar.",
          button: "Novidades desta versão"
        }
      },
      cards: {
        rail: { title: "Uma barra lateral que se abre ao passar o mouse", description: "Passe o mouse sobre os ícones à esquerda para ver os nomes. Ela se recolhe de novo quando você se afasta." },
        diskMap: { title: "Mapa do disco", description: "Analise qualquer unidade, continue de onde parou e pesquise ou exporte o que encontrar." },
        deepClean: { title: "Limpeza profunda", description: "Analisa uma vez e lembra, tritura arquivos, tem linha de comando e aceita seus próprios locais." },
        uninstaller: { title: "Desinstalação", description: "Aponte o Caçador para um programa, use a Desinstalação forçada nos teimosos, acompanhe instalações e encontre Backups e Histórico na Quarentena." },
        dashboard: { title: "Painel", description: "Limpe o recomendado com um clique, veja o que liberou, receba um aviso de pouco espaço e desfaça uma limpeza." },
        settings: { title: "Mais em Configurações", description: "Limpeza agendada com o Prune fechado, iniciar com o Windows, um menu de contexto e sempre executar como administrador." }
      }
    }
  },
  pt: {
    whatsNewV3: {
      ui: {
        title: (a) => `Novidades do Prune ${a}`,
        intro: "Algumas coisas que vale a pena conhecer e onde as encontrar.",
        gotIt: "Percebi",
        showMe: "Mostrar",
        backgroundNote: "As opções em segundo plano nas Definições estão todas desativadas até as ativar.",
        about: {
          title: "Novidades",
          description: "Veja o que mudou nesta versão e onde o encontrar.",
          button: "Novidades desta versão"
        }
      },
      cards: {
        rail: { title: "Uma barra lateral que abre ao passar o rato", description: "Passe o rato sobre os ícones à esquerda para ver os nomes. Recolhe de novo quando se afasta." },
        diskMap: { title: "Mapa do disco", description: "Analise qualquer unidade, continue de onde ficou e pesquise ou exporte o que encontrar." },
        deepClean: { title: "Limpeza profunda", description: "Analisa uma vez e fica a lembrar-se, tritura ficheiros, tem linha de comandos e aceita as suas próprias localizações." },
        uninstaller: { title: "Desinstalação", description: "Aponte o Caçador a um programa, use a Desinstalação forçada nos teimosos, acompanhe instalações e encontre Cópias de segurança e Histórico na Quarentena." },
        dashboard: { title: "Painel", description: "Limpe o recomendado com um clique, veja o que libertou, receba um aviso de pouco espaço e anule uma limpeza." },
        settings: { title: "Mais nas Definições", description: "Limpeza agendada com o Prune fechado, iniciar com o Windows, um menu de contexto e executar sempre como administrador." }
      }
    }
  },
  ro: {
    whatsNewV3: {
      ui: {
        title: (a) => `Noutăți în Prune ${a}`,
        intro: "Câteva lucruri bune de știut și unde le găsești.",
        gotIt: "Am înțeles",
        showMe: "Arată-mi",
        backgroundNote: "Opțiunile din fundal din Setări sunt toate dezactivate până le activezi.",
        about: {
          title: "Noutăți",
          description: "Vezi ce s-a schimbat în această versiune și unde găsești.",
          button: "Noutăți în această versiune"
        }
      },
      cards: {
        rail: { title: "O bară laterală care se deschide la trecerea cursorului", description: "Treci cu cursorul peste pictogramele din stânga ca să le vezi numele. Se închide la loc când te îndepărtezi." },
        diskMap: { title: "Harta discului", description: "Scanează orice unitate, reia de unde ai rămas și caută sau exportă ce găsești." },
        deepClean: { title: "Curățare profundă", description: "Scanează o dată și ține minte, distruge fișiere, are linie de comandă și acceptă locațiile tale." },
        uninstaller: { title: "Dezinstalare", description: "Îndreaptă Vânătorul spre un program, folosește Dezinstalarea forțată pentru cele încăpățânate, urmărește instalările și găsește Copii de rezervă și Istoric în Carantină." },
        dashboard: { title: "Panou", description: "Curăță ce este recomandat dintr-un clic, vezi cât ai eliberat, primește avertisment de spațiu redus și anulează o curățare." },
        settings: { title: "Mai multe în Setări", description: "Curățare programată când Prune este închis, pornire cu Windows, meniu clic dreapta și rulare întotdeauna ca administrator." }
      }
    }
  },
  ru: {
    whatsNewV3: {
      ui: {
        title: (a) => `Что нового в Prune ${a}`,
        intro: "Несколько полезных возможностей и где их найти.",
        gotIt: "Понятно",
        showMe: "Показать",
        backgroundNote: "Фоновые параметры в Настройках выключены, пока вы их не включите.",
        about: {
          title: "Что нового",
          description: "Узнайте, что изменилось в этой версии и где это найти.",
          button: "Что нового в этой версии"
        }
      },
      cards: {
        rail: { title: "Боковая панель, которая раскрывается при наведении", description: "Наведите курсор на значки слева, чтобы увидеть их названия. Когда курсор уходит, панель сворачивается." },
        diskMap: { title: "Карта диска", description: "Сканируйте любой диск, продолжайте с того места, где остановились, ищите по результатам и экспортируйте их." },
        deepClean: { title: "Глубокая очистка", description: "Сканирует один раз и запоминает, уничтожает файлы, имеет командную строку и принимает ваши собственные расположения." },
        uninstaller: { title: "Удаление", description: "Наведите Охотника на программу, используйте Принудительное удаление для упрямых, следите за установками, а Резервные копии и История находятся в Карантине." },
        dashboard: { title: "Панель", description: "Очищайте рекомендованное одним щелчком, смотрите, сколько освободили, получайте предупреждение о нехватке места и отменяйте очистку." },
        settings: { title: "Ещё в Настройках", description: "Очистка по расписанию при закрытом Prune, запуск вместе с Windows, контекстное меню и постоянный запуск от имени администратора." }
      }
    }
  },
  sk: {
    whatsNewV3: {
      ui: {
        title: (a) => `Čo je nové v Prune ${a}`,
        intro: "Niekoľko vecí, ktoré stoja za zmienku, a kde ich nájdete.",
        gotIt: "Rozumiem",
        showMe: "Ukázať",
        backgroundNote: "Možnosti na pozadí v Nastaveniach sú všetky vypnuté, kým ich nezapnete.",
        about: {
          title: "Čo je nové",
          description: "Pozrite si, čo sa v tejto verzii zmenilo a kde to nájdete.",
          button: "Čo je nové v tejto verzii"
        }
      },
      cards: {
        rail: { title: "Bočný panel, ktorý sa otvorí po nabehnutí myšou", description: "Nabehnite na ikony vľavo a uvidíte ich názvy. Po odídení myšou sa znova zloží." },
        diskMap: { title: "Mapa disku", description: "Skenujte ľubovoľný disk, pokračujte tam, kde ste skončili, a výsledky vyhľadávajte alebo exportujte." },
        deepClean: { title: "Hĺbkové čistenie", description: "Skenuje raz a zapamätá si výsledok, skartuje súbory, má príkazový riadok a prijíma vaše vlastné umiestnenia." },
        uninstaller: { title: "Odinštalovanie", description: "Namierte Lovca na program, tvrdohlavé odstráňte Vynúteným odinštalovaním, sledujte inštalácie a Zálohy a Históriu nájdete v Karanténe." },
        dashboard: { title: "Prehľad", description: "Vyčistite odporúčané jedným kliknutím, pozrite si, koľko ste uvoľnili, dostanete upozornenie na nedostatok miesta a čistenie môžete vrátiť späť." },
        settings: { title: "Viac v Nastaveniach", description: "Plánované čistenie pri zavretom Prune, spustenie s Windows, ponuka pravého tlačidla a vždy spúšťať ako správca." }
      }
    }
  },
  sq: {
    whatsNewV3: {
      ui: {
        title: (a) => `Çfarë ka të re në Prune ${a}`,
        intro: "Disa gjëra që vlen t'i dini dhe ku t'i gjeni.",
        gotIt: "E kuptova",
        showMe: "Më trego",
        backgroundNote: "Opsionet e sfondit te Cilësimet janë të gjitha të fikura derisa t'i ndizni.",
        about: {
          title: "Çfarë ka të re",
          description: "Shihni çfarë ndryshoi në këtë version dhe ku ta gjeni.",
          button: "Çfarë ka të re në këtë version"
        }
      },
      cards: {
        rail: { title: "Një shirit anësor që hapet kur e kaloni kursorin sipër", description: "Drejtojeni kursorin te ikonat në të majtë për të parë emrat. Mbyllet përsëri kur e largoni." },
        diskMap: { title: "Harta e Diskut", description: "Skanoni çdo disk, vazhdoni aty ku e latë dhe kërkoni ose eksportoni çka gjeni." },
        deepClean: { title: "Pastrim i thellë", description: "Skanon një herë dhe e mban mend, shqyen skedarë, ka linjë komande dhe pranon vendet tuaja." },
        uninstaller: { title: "Çinstalim", description: "Drejtojeni Gjahtarin te një program, përdorni Çinstalimin e detyruar për kokëfortët, ndiqni instalimet dhe gjeni Kopjet rezervë dhe Historikun te Karantina." },
        dashboard: { title: "Paneli", description: "Pastroni të rekomanduarat me një klikim, shihni sa liruat, merrni paralajmërim për pak hapësirë dhe zhbëni një pastrim." },
        settings: { title: "Më shumë te Cilësimet", description: "Pastrim i planifikuar kur Prune është mbyllur, nisja me Windows, një meny me klik të djathtë dhe ekzekutim gjithmonë si administrator." }
      }
    }
  },
  sr: {
    whatsNewV3: {
      ui: {
        title: (a) => `Шта је ново у Prune ${a}`,
        intro: "Неколико ствари које вреди знати и где их наћи.",
        gotIt: "Разумем",
        showMe: "Покажи ми",
        backgroundNote: "Опције у позадини у Подешавањима су све искључене док их не укључите.",
        about: {
          title: "Шта је ново",
          description: "Погледајте шта се променило у овој верзији и где то наћи.",
          button: "Шта је ново у овој верзији"
        }
      },
      cards: {
        rail: { title: "Бочна трака која се отвара при преласку мишем", description: "Пређите мишем преко иконица лево да видите њихове називе. Затвара се поново кад одмакнете миша." },
        diskMap: { title: "Мапа диска", description: "Скенирајте било који диск, наставите где сте стали и претражите или извезите резултате." },
        deepClean: { title: "Дубоко чишћење", description: "Скенира једном и памти, уништава датотеке, има командну линију и прихвата ваше локације." },
        uninstaller: { title: "Деинсталација", description: "Усмерите Ловца на програм, користите Принудну деинсталацију за тврдоглаве, пратите инсталације, а Резервне копије и Историју налазите у Карантину." },
        dashboard: { title: "Контролна табла", description: "Очистите препоручено једним кликом, погледајте колико сте ослободили, добијте упозорење о малом простору и опозовите чишћење." },
        settings: { title: "Више у Подешавањима", description: "Заказано чишћење док је Prune затворен, покретање са Windows-ом, мени десног клика и увек покретање као администратор." }
      }
    }
  },
  sv: {
    whatsNewV3: {
      ui: {
        title: (a) => `Nytt i Prune ${a}`,
        intro: "Några saker som är bra att känna till, och var du hittar dem.",
        gotIt: "Uppfattat",
        showMe: "Visa mig",
        backgroundNote: "Bakgrundsalternativen i Inställningar är alla avstängda tills du slår på dem.",
        about: {
          title: "Nyheter",
          description: "Se vad som har ändrats i den här versionen och var du hittar det.",
          button: "Nytt i den här versionen"
        }
      },
      cards: {
        rail: { title: "Ett sidofält som öppnas när du pekar på det", description: "Peka på ikonerna till vänster för att se deras namn. Det fälls ihop igen när du flyttar bort pekaren." },
        diskMap: { title: "Diskkarta", description: "Skanna valfri enhet, fortsätt där du slutade och sök i eller exportera det du hittar." },
        deepClean: { title: "Grundlig rensning", description: "Den skannar en gång och minns det, makulerar filer, har en kommandorad och tar emot dina egna platser." },
        uninstaller: { title: "Avinstallation", description: "Rikta Jägare mot ett program, använd Påtvingad avinstallation på de envisa, håll koll på installationer och hitta Säkerhetskopior och Historik i Karantän." },
        dashboard: { title: "Översikt", description: "Rensa det rekommenderade med ett klick, se hur mycket du har frigjort, få en varning vid lite diskutrymme och ångra en rensning." },
        settings: { title: "Mer i Inställningar", description: "Schemalagd rensning medan Prune är stängt, start med Windows, en högerklicksmeny och kör alltid som administratör." }
      }
    }
  },
  th: {
    whatsNewV3: {
      ui: {
        title: (a) => `มีอะไรใหม่ใน Prune ${a}`,
        intro: "ไม่กี่อย่างที่ควรรู้ และจะหาได้ที่ไหน",
        gotIt: "เข้าใจแล้ว",
        showMe: "แสดงให้ดู",
        backgroundNote: "ตัวเลือกเบื้องหลังในการตั้งค่าปิดอยู่ทั้งหมดจนกว่าคุณจะเปิดเอง",
        about: {
          title: "มีอะไรใหม่",
          description: "ดูว่าเวอร์ชันนี้เปลี่ยนอะไรไปและหาได้ที่ไหน",
          button: "มีอะไรใหม่ในเวอร์ชันนี้"
        }
      },
      cards: {
        rail: { title: "แถบด้านข้างที่เปิดเมื่อวางเมาส์", description: "วางเมาส์บนไอคอนทางซ้ายเพื่อดูชื่อ แถบจะพับกลับเมื่อคุณย้ายเมาส์ออก" },
        diskMap: { title: "แผนที่ดิสก์", description: "สแกนไดรฟ์ใดก็ได้ ทำต่อจากที่ค้างไว้ แล้วค้นหาหรือส่งออกสิ่งที่พบ" },
        deepClean: { title: "ทำความสะอาดเชิงลึก", description: "สแกนครั้งเดียวและจดจำไว้ ทำลายไฟล์ มีบรรทัดคำสั่ง และรับตำแหน่งที่คุณกำหนดเอง" },
        uninstaller: { title: "ถอนการติดตั้ง", description: "ชี้ฮันเตอร์ไปที่โปรแกรม ใช้บังคับถอนการติดตั้งกับตัวที่ดื้อ เฝ้าดูการติดตั้ง และหาการสำรองข้อมูลกับประวัติได้ในกักกัน" },
        dashboard: { title: "แดชบอร์ด", description: "ล้างรายการที่แนะนำได้ในคลิกเดียว ดูพื้นที่ที่คืนมา รับคำเตือนเมื่อพื้นที่ใกล้เต็ม และเลิกทำการล้างได้" },
        settings: { title: "เพิ่มเติมในการตั้งค่า", description: "ล้างตามกำหนดเวลาแม้ปิด Prune อยู่ เริ่มพร้อม Windows เมนูคลิกขวา และเรียกใช้ในฐานะผู้ดูแลระบบเสมอ" }
      }
    }
  },
  tr: {
    whatsNewV3: {
      ui: {
        title: (a) => `Prune ${a} sürümünde yenilikler`,
        intro: "Bilmeye değer birkaç şey ve bunları nerede bulacağınız.",
        gotIt: "Anladım",
        showMe: "Göster",
        backgroundNote: "Ayarlar'daki arka plan seçeneklerinin hepsi, siz açana kadar kapalıdır.",
        about: {
          title: "Yenilikler",
          description: "Bu sürümde nelerin değiştiğini ve nerede bulacağınızı görün.",
          button: "Bu sürümdeki yenilikler"
        }
      },
      cards: {
        rail: { title: "Üzerine gelince açılan bir kenar çubuğu", description: "Adlarını görmek için soldaki simgelerin üzerine gelin. İmleci çekince yeniden kapanır." },
        diskMap: { title: "Disk Haritası", description: "Herhangi bir sürücüyü tarayın, kaldığınız yerden devam edin, sonuçlarda arama yapın veya dışa aktarın." },
        deepClean: { title: "Derin Temizlik", description: "Bir kez tarar ve hatırlar, dosyaları parçalar, komut satırı vardır ve kendi konumlarınızı kabul eder." },
        uninstaller: { title: "Kaldırma", description: "Avcı'yı bir programa doğrultun, inatçılar için Zorla kaldır'ı kullanın, kurulumları izleyin; Yedekler ve Geçmiş Karantina'dadır." },
        dashboard: { title: "Panel", description: "Önerilenleri tek tıkla temizleyin, ne kadar yer açtığınızı görün, düşük disk uyarısı alın ve bir temizliği geri alın." },
        settings: { title: "Ayarlar'da daha fazlası", description: "Prune kapalıyken zamanlanmış temizlik, Windows ile başlatma, sağ tık menüsü ve her zaman yönetici olarak çalıştırma." }
      }
    }
  },
  uk: {
    whatsNewV3: {
      ui: {
        title: (a) => `Що нового в Prune ${a}`,
        intro: "Кілька речей, які варто знати, і де їх знайти.",
        gotIt: "Зрозуміло",
        showMe: "Показати",
        backgroundNote: "Фонові параметри в Налаштуваннях вимкнені, доки ви їх не ввімкнете.",
        about: {
          title: "Що нового",
          description: "Дізнайтеся, що змінилося в цій версії та де це знайти.",
          button: "Що нового в цій версії"
        }
      },
      cards: {
        rail: { title: "Бічна панель, що розгортається при наведенні", description: "Наведіть курсор на значки ліворуч, щоб побачити їхні назви. Коли курсор іде, панель згортається." },
        diskMap: { title: "Карта диска", description: "Скануйте будь-який диск, продовжуйте з місця, де зупинилися, шукайте в результатах і експортуйте їх." },
        deepClean: { title: "Глибоке очищення", description: "Сканує один раз і запам'ятовує, знищує файли, має командний рядок і приймає ваші власні розташування." },
        uninstaller: { title: "Видалення", description: "Наведіть Мисливця на програму, для впертих використовуйте Примусове видалення, стежте за встановленнями, а Резервні копії та Історія — у Карантині." },
        dashboard: { title: "Панель", description: "Очищайте рекомендоване одним клацанням, дивіться, скільки звільнено, отримуйте попередження про брак місця й скасовуйте очищення." },
        settings: { title: "Ще в Налаштуваннях", description: "Очищення за розкладом, коли Prune закрито, запуск разом із Windows, контекстне меню та постійний запуск від імені адміністратора." }
      }
    }
  },
  vi: {
    whatsNewV3: {
      ui: {
        title: (a) => `Có gì mới trong Prune ${a}`,
        intro: "Một vài điều đáng biết và nơi tìm chúng.",
        gotIt: "Đã hiểu",
        showMe: "Chỉ cho tôi",
        backgroundNote: "Các tùy chọn nền trong Cài đặt đều tắt cho đến khi bạn bật chúng.",
        about: {
          title: "Có gì mới",
          description: "Xem điều gì đã thay đổi trong phiên bản này và tìm ở đâu.",
          button: "Có gì mới trong phiên bản này"
        }
      },
      cards: {
        rail: { title: "Thanh bên mở ra khi rê chuột", description: "Rê chuột vào các biểu tượng bên trái để xem tên. Thanh sẽ thu lại khi bạn rời chuột đi." },
        diskMap: { title: "Bản đồ ổ đĩa", description: "Quét bất kỳ ổ nào, tiếp tục từ chỗ bạn dừng và tìm kiếm hoặc xuất kết quả." },
        deepClean: { title: "Dọn dẹp sâu", description: "Quét một lần và ghi nhớ, hủy tệp, có dòng lệnh và nhận vị trí riêng của bạn." },
        uninstaller: { title: "Gỡ cài đặt", description: "Chĩa Thợ săn vào một chương trình, dùng Gỡ cài đặt cưỡng bức cho chương trình cứng đầu, theo dõi cài đặt, và tìm Bản sao lưu và Lịch sử trong Khu cách ly." },
        dashboard: { title: "Tổng quan", description: "Dọn dẹp mục khuyến nghị chỉ với một lần nhấp, xem bạn đã giải phóng bao nhiêu, nhận cảnh báo ổ đĩa sắp đầy và hoàn tác một lần dọn dẹp." },
        settings: { title: "Thêm trong Cài đặt", description: "Dọn dẹp theo lịch khi Prune đã đóng, khởi động cùng Windows, menu chuột phải và luôn chạy với quyền quản trị viên." }
      }
    }
  },
  "zh-CN": {
    whatsNewV3: {
      ui: {
        title: (a) => `Prune ${a} 新功能`,
        intro: "几项值得了解的功能，以及在哪里找到它们。",
        gotIt: "知道了",
        showMe: "带我去看",
        backgroundNote: "设置中的后台选项默认全部关闭，需要时由你自己开启。",
        about: {
          title: "新功能",
          description: "了解这个版本有哪些变化，以及在哪里找到它们。",
          button: "此版本的新功能"
        }
      },
      cards: {
        rail: { title: "鼠标指向时展开的侧边栏", description: "将鼠标移到左侧图标上即可查看名称，移开后会再次收起。" },
        diskMap: { title: "磁盘地图", description: "扫描任意驱动器，从上次的位置继续，并搜索或导出结果。" },
        deepClean: { title: "深度清理", description: "扫描一次并记住结果，可粉碎文件，提供命令行，还支持你自己的位置。" },
        uninstaller: { title: "卸载", description: "用猎手瞄准程序，对顽固程序使用强制卸载，监控安装，并在隔离区找到备份和历史记录。" },
        dashboard: { title: "仪表盘", description: "一键清理推荐项，查看已释放的空间，收到磁盘空间不足的警告，并可撤销清理。" },
        settings: { title: "设置中的更多功能", description: "Prune 关闭时的计划清理、随 Windows 启动、右键菜单，以及始终以管理员身份运行。" }
      }
    }
  },
  "zh-TW": {
    whatsNewV3: {
      ui: {
        title: (a) => `Prune ${a} 新功能`,
        intro: "幾項值得了解的功能，以及在哪裡找到它們。",
        gotIt: "知道了",
        showMe: "帶我去看",
        backgroundNote: "設定中的背景選項預設全部關閉，需要時由你自行開啟。",
        about: {
          title: "新功能",
          description: "了解這個版本有哪些變化，以及在哪裡找到它們。",
          button: "此版本的新功能"
        }
      },
      cards: {
        rail: { title: "滑鼠指向時展開的側邊欄", description: "將滑鼠移到左側圖示上即可查看名稱，移開後會再次收合。" },
        diskMap: { title: "磁碟地圖", description: "掃描任何磁碟機，從上次的位置繼續，並搜尋或匯出結果。" },
        deepClean: { title: "深度清理", description: "掃描一次並記住結果，可粉碎檔案，提供命令列，也支援你自己的位置。" },
        uninstaller: { title: "解除安裝", description: "用獵手瞄準程式，對頑固程式使用強制解除安裝，監控安裝，並在隔離區找到備份和歷程記錄。" },
        dashboard: { title: "儀表板", description: "一鍵清理建議項目，查看已釋放的空間，收到磁碟空間不足的警告，並可復原清理。" },
        settings: { title: "設定中的更多功能", description: "Prune 關閉時的排程清理、隨 Windows 啟動、右鍵選單，以及一律以系統管理員身分執行。" }
      }
    }
  }
};
